! obcomm.f90

MODULE obcomm_parm
  USE commpi
  USE plcomm_parm
  IMPLICIT NONE
  PUBLIC

  INTEGER,PARAMETER:: NOBTM=100

! --- input parameters ---

  INTEGER:: NOBTMAX,NSTPMAX,NRSMAX,NRRMAX,LMAXNW
  INTEGER:: MDLOBI,MDLOBG,MDLOBP,MDLOBQ,MDLOBW
  REAL(rkind) SMAX,DELS,UUMIN,EPSOBT,DELOBT,DELDER,DELKR,EPSNW
  REAL(rkind) RF,RPI,ZPI,PHII,RNZI,RNPHII,RKR0,UUI,RKRI,RKPHII,RKZI
  REAL(rkind) RCURVA,RCURVB,RBRADA,RBRADB,NRADMX
  INTEGER:: MODEW

  REAL(rkind),DIMENSION(NOBTM):: &
       RFIN,RPIN,ZPIN,PHIIN,RKRIN,RNZIN,RNPHIIN,ANGZIN,ANGPHIN,UUIN, &
       RCURVAIN,RCURVBIN,RBRADAIN,RBRADBIN
  INTEGER,DIMENSION(NOBTM):: &
       MODEWIN

CONTAINS

  SUBROUTINE open_obcomm_parm
    RETURN
  END SUBROUTINE open_obcomm_parm

END MODULE obcomm_parm

MODULE obcomm
  USE obcomm_parm
  USE plcomm
  USE commpi
  IMPLICIT NONE

  INTEGER,PARAMETER:: NEQ=8
  INTEGER,PARAMETER:: NBEQ=19
  INTEGER,PARAMETER:: NBVAR=53

  INTEGER,DIMENSION(:),ALLOCATABLE:: &
       NSTPMAX_NOBT
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       OBTIN
  REAL(rkind),DIMENSION(:,:,:),ALLOCATABLE:: &
       OBTS
  COMPLEX(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       CEXS,CEYS,CEZS
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       RKXS,RKYS,RKZS,RXS,RYS,RZS,BNXS,BNYS,BNZS,BABSS
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       OBTB,OBTRB1,OBTRB2
  COMPLEX(rkind),DIMENSION(:),ALLOCATABLE:: &
       CEXB,CEYB,CEZB
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       RK1B,RP1B
  REAL(rkind),DIMENSION(:,:,:),ALLOCATABLE:: &
       RK2B,RP2B
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       RAMPB
  REAL(rkind),ALLOCATABLE:: &
       pos_nrs(:),pwr_nrs(:),pwr_nrs_nobt(:,:)
  REAL(rkind),ALLOCATABLE:: &
       pos_nrr(:),pwr_nrr(:),pwr_nrr_nobt(:,:)
  REAL(rkind),ALLOCATABLE:: &
       rs_nstp_nobt(:,:),rr_nstp_nobt(:,:)
  REAL(rkind),ALLOCATABLE:: &
       pos_pwrmax_rs_nobt(:),pwrmax_rs_nobt(:)
  REAL(rkind):: pos_pwrmax_rs,pwrmax_rs
  REAL(rkind),ALLOCATABLE:: &
       pos_pwrmax_rr_nobt(:),pwrmax_rr_nobt(:)
  REAL(rkind):: pos_pwrmax_rr,pwrmax_rr
CONTAINS

  SUBROUTINE ob_allocate
    IMPLICIT NONE
    INTEGER,SAVE:: INIT=0
    INTEGER,SAVE:: NOBTMAX_SAVE=0
    INTEGER,SAVE:: NSTPMAX_SAVE=0

    IF(INIT.EQ.0) THEN
       INIT=1
    ELSE
       IF((NOBTMAX.EQ.NOBTMAX_SAVE).AND. &
          (NSTPMAX.EQ.NSTPMAX_SAVE)) RETURN
       CALL ob_deallocate
    END IF

    ALLOCATE(OBTIN(NEQ,NOBTMAX))
    ALLOCATE(NSTPMAX_NOBT(NOBTMAX))
    ALLOCATE(OBTS(0:NEQ,0:NSTPMAX,NOBTMAX))

    ALLOCATE(CEXS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(CEYS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(CEZS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RKXS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RKYS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RKZS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RXS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RYS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(RZS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(BNXS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(BNYS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(BNZS(0:NSTPMAX,NOBTMAX))
    ALLOCATE(BABSS(0:NSTPMAX,NOBTMAX))

    ALLOCATE(OBTB(0:NBVAR,0:NSTPMAX))
    ALLOCATE(OBTRB1(0:NSTPMAX,NOBTMAX))
    ALLOCATE(OBTRB2(0:NSTPMAX,NOBTMAX))
    ALLOCATE(CEXB(0:NSTPMAX),CEYB(0:NSTPMAX),CEZB(0:NSTPMAX))
    ALLOCATE(RK1B(3,0:NSTPMAX),RP1B(3,0:NSTPMAX))
    ALLOCATE(RK2B(3,3,0:NSTPMAX),RP2B(3,3,0:NSTPMAX))
    ALLOCATE(RAMPB(0:NSTPMAX))
  END SUBROUTINE ob_allocate

  SUBROUTINE ob_deallocate
    IMPLICIT NONE

    DEALLOCATE(NSTPMAX_NOBT)
    DEALLOCATE(OBTIN)
    DEALLOCATE(OBTS)
    DEALLOCATE(CEXS,CEYS,CEZS)
    DEALLOCATE(RKXS,RKYS,RKZS,RXS,RYS,RZS,BNXS,BNYS,BNZS,BABSS)
    DEALLOCATE(OBTB,OBTRB1,OBTRB2)
    DEALLOCATE(CEXB,CEYB,CEZB)
    DEALLOCATE(RK1B,RP1B)
    DEALLOCATE(RK2B,RP2B,RAMPB)
  END SUBROUTINE ob_deallocate
END MODULE obcomm
