!     $Id$

MODULE w1comm

  USE bpsd_kinds
  USE bpsd_constants

! --- Input parameters ---
  INTEGER,PARAMETER:: NXPM=1000
  INTEGER,PARAMETER:: NXVM=50
  INTEGER,PARAMETER:: NZLM=7
  INTEGER,PARAMETER:: NSM=5
  INTEGER,PARAMETER:: NAM=8
  INTEGER,PARAMETER:: NHARMM=30
  INTEGER,PARAMETER:: MATLM=70
  INTEGER,PARAMETER:: NCLM=140*NXPM
  INTEGER,PARAMETER:: NDM=101
  INTEGER,PARAMETER:: NZPM=2**NZLM
  INTEGER,PARAMETER:: NXTM=NXPM+2*NXVM
  INTEGER,PARAMETER:: NXM=NXPM*6+10
  INTEGER,PARAMETER:: NXQ=NXPM+1
  INTEGER,PARAMETER:: NHM=2*NHARMM+1
  INTEGER,PARAMETER:: NHM1=NHARMM+1
  INTEGER,PARAMETER:: NCLW=2*MATLM+1

! --- Input parameters ---

  INTEGER:: NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NALPHA
  REAL(rkind):: DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP
  INTEGER:: NDMAX
  REAL(rkind):: XDMAX
  INTEGER:: NMODEL,NSYS,NDISP,NXABS
  REAL(rkind):: ZEFF,WVYSIZ
  INTEGER:: NCDTYP

  INTEGER:: NXP,NXV,NXT
  REAL(rkind):: RR,RB,BB,RA,WALLR,EPSH

  REAL(rkind):: RF,RD,RKZ
  INTEGER:: NAMAX
  REAL(rkind),DIMENSION(NAM):: AJYL,AJYH,AJZL,AJZH,ALYL,ALYH,APYL,APYH

  INTEGER:: NSMAX
  REAL(rkind),DIMENSION(NSM):: PA,PZ,PN,PTPP,PTPR,PNS,PTS,PU,PZCL
  INTEGER,DIMENSION(NSM):: IHARM,IELEC


! --- Global variables ---

  COMPLEX(rkind),DIMENSION(NXTM,3):: CEF,CBF
  COMPLEX(rkind),DIMENSION(NXTM,4):: CAF
  REAL(rkind),DIMENSION(NXTM,7):: RHL
  COMPLEX(rkind),DIMENSION(NXPM,NSM,7):: CJF
  REAL(rkind),DIMENSION(NXPM,NSM,2):: FHL
  REAL(rkind),DIMENSION(NSM,4):: AHLT
  REAL(rkind),DIMENSION(NXPM,NSM,4):: AHL
  COMPLEX(rkind),DIMENSION(NXTM,3):: CED
  COMPLEX(rkind),DIMENSION(NXPM,NSM,4):: CJD
  COMPLEX(rkind):: CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
  COMPLEX(rkind):: CA(NXM)
  REAL(rkind):: AJCDX(NXPM),AJCDK(NZPM),AJCDT
  COMPLEX(rkind):: CE2DA(NZPM,NXTM,3)
  COMPLEX(rkind):: CSKX(NXPM*3),CSPX(NXPM*3),CSPZ(NXPM*3)
  COMPLEX(rkind):: CD0(4,NXPM),CD1(2,NXPM),CD2(4,NXPM)
  COMPLEX(rkind):: CM0(4,NXPM,NSM),CM1(2,NXPM,NSM),CM2(4,NXPM,NSM)
  COMPLEX(rkind):: CF(6*MATLM+5,NXM)

  REAL(rkind),DIMENSION(NXPM):: PROFB
  REAL(rkind),DIMENSION(NXPM,NSM):: PROFPN,PROFPU,PROFTR,PROFTP
  REAL(rkind),DIMENSION(NXPM,NSM):: PABS,PABSX
  REAL(rkind),DIMENSION(NXTM):: FLUX,FLUXX
  REAL(rkind):: PABSXZ(NSM),PABSTT
  REAL(rkind),DIMENSION(NAM):: RANT1,RANT2,XANT1,XANT2
  REAL(rkind):: PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,PIBW1,PIBW2,PIBW,PERR
  REAL(rkind):: PAKT(NZPM,3),PANTK(NZPM),PAK(NZPM,NSM)
  COMPLEX(rkind):: CL(3,3,4,NCLM)
  INTEGER:: NCL(NCLW,NXPM,NSM)

  REAL(rkind):: SF(NDM,NHM1,3),SG(NDM,NHM1,3),AF(NDM,NHM1,2),AG(NDM,NHM1,2)

  INTEGER:: NFLR,NZP
  REAL(rkind):: RZ,DZ
  REAL(rkind):: DXD
  INTEGER:: NHARM,MATL

  REAL(rkind),DIMENSION(NXPM):: XM,YX,YK
  COMPLEX(rkind),DIMENSION(NXPM):: CS0,CS1,CS2,CS3
  REAL(rkind):: TEMP(NXTM,NZPM)
  INTEGER:: NXPRNT(NXTM)
  REAL(rkind):: XA(NXQ),XAM(NXTM)
  COMPLEX(rkind),DIMENSION(NZPM):: CJ1,CJ2,CJ3,CJ4,CFJ2
  REAL(rkind),DIMENSION(NZPM):: ZA(NZPM),AKZ(NZPM)
  INTEGER,DIMENSION(NAM):: NZANT1,NZANT2
  INTEGER:: NANT
  COMPLEX(rkind),DIMENSION(NXPM,NHM):: CZ,CDZ,CDDZ,GZ

! --- FFT ---
  COMPLEX(rkind):: CT(NZPM),CFFT(NZPM*NZLM)
  INTEGER:: LNST(NZPM),LFFT(NZPM*NZLM)

CONTAINS

  SUBROUTINE w1comm_init
    RETURN
  END SUBROUTINE w1comm_init

END MODULE w1comm

MODULE w1comm_alf1
  USE bpsd_kinds
  REAL(rkind):: FY1,FY2,FY3
  INTEGER:: NY1,NY2
CONTAINS

  SUBROUTINE w1comm_alf1_init
    RETURN
  END SUBROUTINE w1comm_alf1_init

END MODULE w1comm_alf1

MODULE w1comm_dec
  USE bpsd_kinds
  REAL(rkind):: G1
  INTEGER:: NF,NN,NM
CONTAINS

  SUBROUTINE w1comm_dec_init
    RETURN
  END SUBROUTINE w1comm_dec_init

END MODULE w1comm_dec

MODULE w1comm_gdat
  USE w1comm,ONLY: NXTM,NZPM
  INTEGER,PARAMETER:: NZPMP1=NZPM+1
  REAL(4):: GDATA1(NXTM),GDATA2(NXTM),GDATA3(NXTM)
  REAL(4):: GX(NXTM),GXM(NXTM),GGZ(NZPMP1),GDATAZ(NZPMP1)
CONTAINS

  SUBROUTINE w1comm_gdat_init
    RETURN
  END SUBROUTINE w1comm_gdat_init

END MODULE w1comm_gdat

