MODULE w1comm

  USE bpsd_kinds
  USE bpsd_constants
  
  INTEGER,PARAMETER:: NSM=100  ! maximum number of particle species
  INTEGER,PARAMETER:: NAM=20   ! maximum number of antenna

!  PARAMETER (NXPM=5000,NXVM=200,NZLM=5,ISM=5,IAM=8)
!  PARAMETER (NHARMM=30,MATLM=70,NCLM=140*NXPM,NDM=101)

!      PARAMETER (NZPM=2**NZLM)
!      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
!      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)

  INTEGER:: NXPMAX,NXVMAX,NZPMAX,NSMAX,NAMAX
  REAL(rkind):: BB,RR,RA,RD,RB,WALLR,APRFPN,APRFTR,APRFTP
  REAL(rkind):: RF,RKZ,DRF,DRKZ,DXFACT,DXWDTH
  REAL(rkind),DIMENSION(NSM):: PA,PZ,PN,PTPP,PTPR,PU,PNS,PTS,PZCL
  INTEGER,DIMENSION(NSM):: IELEC
  REAL(rkind),DIMENSION(NSM):: AJYL,AJYH,AJZL,AJZH,ALYL,ALYH,APYL,APYH
  REAL(rkind):: RZ,DZ,EPSH,XDMAX,ZEFF,WVYSIZ
  INTEGER:: NPRINT,NFILE,NGRAPH,NLOOP,NSYM
  INtEGEr:: NMODEL,NALPHA,NDMAX,NHARM,NSYS,NDISP,NCDTYP,NXABS
  
!  INTEGER:: NXM,NDM,NHM,NHM1,MATLM,NCLM
  INTEGER:: NXTMAX,MATLM,NCLM,NDM,NHARMM
  COMPLEX(rkind):: CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
  COMPLEX(rkind),DIMENSION(:,:,:),ALLOCATABLE:: CE2DA
  COMPLEX(rkind),DIMENSION(:),ALLOCATABLE:: CJ1,CJ2,CJ3,CJ4
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: ZA,AKZ
  INTEGER,DIMENSION(:),ALLOCATABLE:: NZANT1,NZANT2
  INTEGER:: NANT
  INTEGER,DIMENSION(:),ALLOCATABLE:: IHARM
  INTEGER:: MATL
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: XA,XAM
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: AJCDX,AJCDK
  REAL(rkind):: AJCDT

  INTEGER,SAVE:: nxpmax_save = 0
  INTEGER,SAVE:: nxvmax_save = 0
  INTEGER,SAVE:: nzpmax_save = 0
  INTEGER,SAVE:: nsmax_save = 0
  INTEGER,SAVE:: namax_save = 0

CONTAINS

  SUBROUTINE w1_allocate

    IF(nxpmax == nxpmax_save .AND. &
       nxvmax == nxvmax_save .AND. &
       nzpmax == nzpmax_save .AND. &
       nsmax  == nsmax_save  .AND. &
       namax  == namax_save) RETURN

    CALL w1_deallocate

    NXTMAX=NXPMAX+2*NXVMAX

    ALLOCATE(CE2DA(NZPMAX,NXTMAX,3))
    ALLOCATE(CJ1(NZPMAX),CJ2(NZPMAX),CJ3(NZPMAX),CJ4(NZPMAX))
    ALLOCATE(ZA(NZPMAX),AKZ(NZPMAX))
    ALLOCATE(NZANT1(NAMAX),NZANT2(NAMAX))
    ALLOCATE(XA(NXPMAX+1),XAM(NXTMAX))
    ALLOCATE(AJCDX(NXPMAX),AJCDK(NZPMAX))

    nxpmax_save = nxpmax
    nxvmax_save = nxvmax
    nzpmax_save = nzpmax
    nsmax_save = nsmax
    namax_save = namax

  END SUBROUTINE w1_allocate

  SUBROUTINE w1_deallocate
    
    DEALLOCATE(CE2DA)
    DEALLOCATE(CJ1,CJ2,CJ3,CJ4)
    DEALLOCATE(ZA,AKZ)
    DEALLOCATE(NZANT1,NZANT2)
    DEALLOCATE(XA,XAM)
    DEALLOCATE(AJCDX,AJCDK)
    
    nxpmax_save = 0
    nxvmax_save = 0
    nzpmax_save = 0
    nsmax_save = 0
    namax_save = 0

  END SUBROUTINE w1_deallocate

END MODULE w1comm

