MODULE w1gdsp

  PRIVATE
  PUBLIC w1_gdsp

CONTAINS

!     ****** DRAW DISPERSION RELATION ******

  SUBROUTINE W1_GDSP
    USE w1comm
    USE w1prof,ONLY: w1_prof
    USE w1disp,ONLY: w1dspa
    USE w1mlm,ONLY: w1wkxb,w1wkxd
    USE w1intg,ONLY: w1dspq
    IMPLICIT NONE
    INTEGER:: NXP,NX,NZ,NS
    REAL(rkind):: XMIN,XMAX,PKXMIN,PKXMAX

    PKXMIN=-1000.D0
    PKXMAX= 1000.D0
    XMIN=-RA
    XMAX= RA
    NXP=NXPMAX

100 CONTINUE

    WRITE(6,*) '## INPUT : NXP,XMIN,XMAX,PKXMIN,PKXMAX ?'
    WRITE(6,'(I5,1P4E12.4)') NXP,XMIN,XMAX,PKXMIN,PKXMAX
    READ(5,*,ERR=100,END=9000) NXP,XMIN,XMAX,PKXMIN,PKXMAX
    IF(NXP.EQ.0) GOTO 9000

    DO NX=1,NXP
       XAM(NX)=XMIN+(XMAX-XMIN)*(NX-0.5D0)/NXP
    END DO
    CALL W1_PROF
    NZ=1
    write(6,*) 'point 1'

    IF(MOD(NXVMAX,2).NE.0) NXVMAX=NXVMAX+1
    IF(ABS(RZ).LE.1.D-8) RZ=2.D0*PI*RR
    NHMAX=0
    DO NS=1,NSMAX
       IF(ABS(IHARM(NS)).GT.NHMAX)  NHMAX=IHARM(NS)
    END DO
    NCMAX=2*NHMAX+1 


    CALL W1DSPA
    write(6,*) 'point 2'
    IF(NMODEL.LE.3) THEN
       CALL W1WKXB
    ELSE
       CALL W1WKXD
    ENDIF
    write(6,*) 'point 3'
    CALL W1GDSPA(PKXMIN,PKXMAX)
    GOTO 100

9000 CONTINUE
    RETURN
  END SUBROUTINE W1_GDSP

!     ****** DRAW DISPERSION RELATION ******

  FUNCTION SQK2R(CK)
    USE w1comm,ONLY: rkind
    IMPLICIT NONE
    COMPLEX(rkind),INTENT(IN):: CK
    REAL(rkind):: R,A,S,SQK2R
    R=REAL(CK)
    A=IMAG(CK)
    S=R*R-A*A
    IF(S.GE.0.) THEN
       SQK2R=SQRT(S)
    ELSE
       SQK2R=-SQRT(-S)
    ENDIF
    RETURN
  END FUNCTION SQK2R

  FUNCTION SQK2I(CK)
    USE w1comm,ONLY: rkind
    IMPLICIT NONE
    COMPLEX(rkind),INTENT(IN):: CK
    REAL(rkind):: R,A,S,SQK2I
    S=2.*REAL(CK)*IMAG(CK)
    IF(S.GE.0.) THEN
       SQK2I=SQRT(S)
    ELSE
       SQK2I=-SQRT(-S)
    ENDIF
    RETURN
  END FUNCTION SQK2I

  SUBROUTINE W1GDSPA(PKXMIN,PKXMAX)
    USE w1comm
    USE w1grf1,ONLY: w1gprm
    IMPLICIT NONE
    REAL(rkind),INTENT(IN):: PKXMIN,PKXMAX
    REAL(4),DIMENSION(:),ALLOCATABLE:: SX,SKR1,SKR2,SKR3,SKI1,SKI2,SKI3
    REAL(4):: S1,S2,SXMIN,SXMAX,SKMIN,SKMAX
    REAL(4):: SCALX,SCALV,SCALK,SXORG,SKORG
    INTEGER:: NX,KK,NGULEN

    ALLOCATE(SX(NXPMAX),SKR1(NXPMAX),SKR2(NXPMAX),SKR3(NXPMAX))
    ALLOCATE(SKI1(NXPMAX),SKI2(NXPMAX),SKI3(NXPMAX))

    IF(2.0*XAM(1)-XAM(2).LE.-RA.AND. &
       2.0*XAM(NXPMAX)-XAM(NXPMAX-1).GE.RA) THEN
       SXMIN=-RB
       SXMAX= RB
       SXORG=0.0
       SCALX=0.1
       SCALV= RA
    ELSE
       SXMIN= 1.5*XAM(1)     -0.5*XAM(2)
       SXMAX= 1.5*XAM(NXPMAX)-0.5*XAM(NXPMAX-1)
       CALL GQSCAL(SXMIN,SXMAX,S1,S2,SCALX)
       SXORG=SXMIN
       IF(SXMIN*SXMAX.LE.0.0) SXORG=0.0
       SCALV= 2.*SCALX
    ENDIF
    SKMIN= PKXMIN
    SKMAX= PKXMAX

    DO NX=1,NXPMAX
       IF(NMODEL.LE.3) THEN
          KK=(NX-1)*2
       ELSE
          KK=(NX-1)*3
       ENDIF
       SX(NX)=XAM(NX)
       SKR1(NX)=SQK2R(CSKX(KK+1))
       SKI1(NX)=SQK2I(CSKX(KK+1))
       SKR2(NX)=SQK2R(CSKX(KK+2))
       SKI2(NX)=SQK2I(CSKX(KK+2))
       IF(NMODEL.GT.3) THEN
          SKR3(NX)=SQK2R(CSKX(KK+3))
          SKI3(NX)=SQK2I(CSKX(KK+3))
       ENDIF
    END DO

    CALL PAGES
    CALL SETLIN(0,0,4)
    CALL SETCHS(0.3,0.)
    CALL SETMKS(0,0.1)
    CALL GQSCAL(SKMIN,SKMAX,S1,S2,SCALK)
    SKORG=SKMIN
    IF(SKMIN*SKMAX.LE.0.0) SKORG=0.0
    CALL GDEFIN(2.5,12.5,1.,17.5,SXMIN,SXMAX,SKMIN,SKMAX)
    CALL GFRAME
    CALL GSCALE(SXORG,SCALX,SKORG,SCALK,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,1)
    CALL GSCALE(-REAL(RA),2.*REAL(RA),0.,13.*SCALK,0.1,0)
    CALL GVALUE(SXORG,SCALV,0.,0.,2)
    CALL GVALUE(0.,0.,SKORG,2*SCALK,NGULEN(2*SCALK))
    CALL SETLIN(0,0,6)
    CALL GPLOTP(SX,SKR1,1,NXPMAX,1,7,1,0)
    CALL SETLIN(0,0,5)
    CALL GPLOTP(SX,SKI1,1,NXPMAX,1,6,1,0)
    CALL SETLIN(0,0,6)
    CALL GPLOTP(SX,SKR2,1,NXPMAX,1,8,1,0)
    CALL SETLIN(0,0,5)
    CALL GPLOTP(SX,SKI2,1,NXPMAX,1,3,1,0)
    IF(NMODEL.GT.3) THEN
       CALL SETLIN(0,0,6)
       CALL GPLOTP(SX,SKR3,1,NXPMAX,1,4,1,0)
       CALL SETLIN(0,0,5)
       CALL GPLOTP(SX,SKI3,1,NXPMAX,1,2,1,0)
    ENDIF

    CALL W1GPRM(0)

    CALL PAGEE

    DEALLOCATE(SX,SKR1,SKR2,SKR3)
    DEALLOCATE(SKI1,SKI2,SKI3)

    RETURN
  END SUBROUTINE W1GDSPA
!         
END MODULE w1gdsp
