MODULE w1gout

CONTAINS

  SUBROUTINE w1_gout
    USE w1comm
    IMPLICIT NONE

    IF(NGRAPH.GT.0) THEN
       IF(NZPMAX.EQ.1) THEN
          CALL W1GR1D(MOD(NGRAPH,   4))
          CALL W1GR1B(MOD(NGRAPH/4, 2))
          CALL W1GR1F(MOD(NGRAPH/8, 2))
          CALL W1GR1H(MOD(NGRAPH/16,2))
          CALL W1GRUD(MOD(NGRAPH/32,2))
          CALL W1GRUF(MOD(NGRAPH/64,2))
       ELSE
          CALL W1GR2D(MOD(NGRAPH,   4))
          CALL W1GR1D(MOD(NGRAPH,   4))
       ENDIF
    ENDIF
  END SUBROUTINE w1_gout
END MODULE w1gout
