MODULE w1grf1

CONTAINS

!     ****** 1-D GRAPHIC ROUTINE ******

  SUBROUTINE W1GRUD
    USE w1comm
    IMPLICIT NONE
    INTEGER:: NZ,NX,NN,NS,NGULEN
    REAL(rkind):: RNORM,RNORM2
    REAL(4):: GA,GB,GAMIN,GAMAX,GMIN,GMAX,SCAL
    REAL(4):: GAMIN1,GAMIN2,GAMIN3,GAMAX1,GAMAX2,GAMAX3

    IF(NGRAPH.EQ.0) RETURN

    RNORM=1.D0/SQRT(PANT)
    RNORM2=RNORM*RNORM

1   CONTINUE
    IF(NZPMAX.EQ.1) THEN
       NZ=1
    ELSE
100    CONTINUE
       WRITE(6,*) '## GRAPH INPUT : NZ  (0 : QUIT GRAPHIC)'
       READ(5,*,END=9990) NZ
       IF(NZ.GT.NZPMAX) GOTO 100
       IF(NZ.LE.0) RETURN
    ENDIF

    CALL PAGES
    CALL SETMKS(0,0.1)
    CALL SETCHS(0.3,0.)
    CALL SETLIN(0,2,4)
    CALL MOVE( 2.5,17.7)
    CALL TEXT('EX,EY,EZ,PABS',13)

    GA=RA
    GB=RB
    DO NX=1,NXTMAX
       NN        =NXPRNT(NX)
       GX    (NX)=XAM(NN)
       GXM   (NX)=XAM(NX)
       GDATA1(NX)= ABS(CE2DA(NZ,NN,1))*RNORM
       GDATA2(NX)=REAL(CE2DA(NZ,NN,1))*RNORM
       GDATA3(NX)=IMAG(CE2DA(NZ,NN,1))*RNORM
    END DO
    CALL GMNMX1(GDATA1,1,NXTMAX,1,GAMIN,GAMAX)
    CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
    CALL GDEFIN(2.5,12.5,13.5,17.5,-GB,GB,-GMAX,GMAX)
    CALL GFRAME
    CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*SCAL,NGULEN(4*SCAL))
    CALL SETLIN(0,1,7)
    CALL GPLOTP(GX, GDATA1,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,6)
    CALL GPLOTP(GX, GDATA2,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,5)
    CALL GPLOTP(GX, GDATA3,1,NXTMAX,1, 0, 0,2)
    CALL SETLIN(0,2,4)

    DO NX=1,NXTMAX
       NN        =NXPRNT(NX)
       GDATA1(NX)= ABS(CE2DA(NZ,NN,2))*RNORM
       GDATA2(NX)=REAL(CE2DA(NZ,NN,2))*RNORM
       GDATA3(NX)=IMAG(CE2DA(NZ,NN,2))*RNORM
    END DO
    CALL GMNMX1(GDATA1,1,NXTMAX,1,GAMIN,GAMAX)
    CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
    CALL GDEFIN(2.5,12.5,9.5,13.5,-GB,GB,-GMAX,GMAX)
    CALL GFRAME
    CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*SCAL,NGULEN(4*SCAL))
    CALL SETLIN(0,1,7)
    CALL GPLOTP(GX, GDATA1,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,6)
    CALL GPLOTP(GX, GDATA2,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,5)
    CALL GPLOTP(GX, GDATA3,1,NXTMAX,1, 0, 0,2)
    CALL SETLIN(0,2,4)

    DO NX=1,NXTMAX
       NN        =NXPRNT(NX)
       GDATA1(NX)= ABS(CE2DA(NZ,NN,3))*RNORM
       GDATA2(NX)=REAL(CE2DA(NZ,NN,3))*RNORM
       GDATA3(NX)=IMAG(CE2DA(NZ,NN,3))*RNORM
    END DO
    CALL GMNMX1(GDATA1,1,NXTMAX,1,GAMIN,GAMAX)
    CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
    CALL GDEFIN(2.5,12.5,5.5,9.5,-GB,GB,-GMAX,GMAX)
    CALL GFRAME
    CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*SCAL,NGULEN(4*SCAL))
    CALL SETLIN(0,1,7)
    CALL GPLOTP(GX, GDATA1,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,6)
    CALL GPLOTP(GX, GDATA2,1,NXTMAX,1, 0, 0,0)
    CALL SETLIN(0,2,5)
    CALL GPLOTP(GX, GDATA3,1,NXTMAX,1, 0, 0,2)
    CALL SETLIN(0,2,4)

    GMIN=0.0
    GMAX=0.0
    DO NS=1,NSMAX
       DO NX=1,NXPMAX
          GDATA1(NX)=PABSX(NX,NS)*RNORM2
       END DO
       CALL GMNMX1(GDATA1,2,NXPMAX-1,1,GAMIN,GAMAX)
       GMIN=MIN(GMIN,GAMIN)
       GMAX=MAX(GMAX,GAMAX)
    END DO
    GAMAX=MAX(ABS(GMAX),ABS(GMIN))
    CALL GQSCAL(0.,GAMAX,GMIN,GMAX,SCAL)

    CALL GDEFIN(2.5,12.5,1.5,5.5,-GB,GB,-0.1*GMAX,GMAX)
    CALL GFRAME
    CALL GSCALE(0.,0.2,0.,0.,0.1,9)
    CALL GSCALE(0.,0.,0.,SCAL,0.1,1)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,20.*SCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*SCAL,NGULEN(4*SCAL))
    CALL GVALUE(0.,REAL(RA),0.,0.,2)
    DO NS=1,NSMAX
       CALL SETLIN(0,2,7-NS)
       DO NX=1,NXPMAX
          GDATA1(NX)=PABSX(NX,NS)*RNORM2
       END DO
       CALL GPLOTP(GXM,GDATA1,1,NXPMAX,1,-NS,10,0)
    END DO
    CALL SETLIN(0,2,4)

    IF(NMODEL.EQ.5.OR.NMODEL.EQ.3.OR.NMODEL.EQ.1) THEN
       DO NX=1,NXTMAX
          NN        =NXPRNT(NX)
          GDATA1(NX)=FLUXX(NN)*RNORM2
       END DO
       CALL GMNMX1(GDATA1,1,NXTMAX,1,GAMIN,GAMAX)
       IF(ABS(GAMIN).GE.ABS(GAMAX)) THEN
          DO NX=1,NXTMAX
             GDATA1(NX)=-GDATA1(NX)
          END DO
          GAMAX=-GAMIN
       ENDIF
       CALL GQSCAL(0.,GAMAX*1.02,GMIN,GMAX,SCAL)
       CALL GDEFIN(2.5,12.5,1.5,5.5,-GB,GB,-0.1*GMAX,GMAX)
       CALL GSCALE(0.,0.,0.,SCAL,0.1,5)
       CALL SETLIN(0,2,7)
       CALL GPLOTP(GX, GDATA1,1,NXTMAX,1,  0, 0,0)
    END IF

    CALL W1GPRM(NZ)
    CALL W1GPRX

    DO NX=1,NXPMAX
       GDATA1(NX)=(AHL(NX,1,3)+AHL(NX,1,4))*RNORM2
       GDATA2(NX)=AHL(NX,1,3)*RNORM2
       GDATA3(NX)=AHL(NX,1,4)*RNORM2
    END DO
    CALL GMNMX1(GDATA1,1,NXPMAX,1,GAMIN1,GAMAX1)
    CALL GMNMX1(GDATA2,1,NXPMAX,1,GAMIN2,GAMAX2)
    CALL GMNMX1(GDATA3,1,NXPMAX,1,GAMIN3,GAMAX3)
    GAMIN=MIN(GAMIN1,GAMIN2,GAMIN3)
    GAMAX=MAX(GAMAX1,GAMAX2,GAMAX3)
    CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
    CALL GDEFIN(15.0,25.0,1.5,5.5,-GB,GB,GMIN,GMAX)
    CALL GFRAME
    CALL GSCALE(0.,0.2,0.,2*SCAL,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*SCAL,NGULEN(4*SCAL))
    CALL GVALUE(0.,REAL(RA),0.,0.,2)
    CALL SETLIN(0,2,7)
!     CALL GPLOTP(GXM,GDATA1,1,NXPMAX,1, 0, 0,0)
    CALL SETLIN(0,2,6)
    CALL GPLOTP(GXM,GDATA2,1,NXPMAX,1,-7,10,0)
    CALL SETLIN(0,2,5)
    CALL GPLOTP(GXM,GDATA3,1,NXPMAX,1, 0, 0,0)
    CALL SETLIN(0,2,4)

    CALL PAGEE
    IF(NZPMAX.GT.1) GOTO 1
    RETURN

9990 CONTINUE
    RETURN
  END SUBROUTINE W1GRUD

!     ****** 1-D GRAPHIC PARAMETER ******

  SUBROUTINE W1GPRM(NZ)
    USE w1comm
    IMPLICIT NONE
    INTEGER,INTENT(IN):: NZ
    INTEGER:: NS
    REAL(rkind):: RNORM2

    IF(ABS(PANT).LE.1.D-30) THEN
       RNORM2=0.D0
    ELSE
       RNORM2=1.D0/PANT
    ENDIF

    CALL SETLIN(0,0,7)
    CALL MOVE(14.,17.5)
    CALL TEXT('FREQ =',6)
    CALL NUMBD(RF,'(F9.4)',9)
    IF(NZPMAX.EQ.1) THEN
       CALL TEXT('   K-PR =',9)
       CALL NUMBD(RKZ,'(F9.4)',9)
    ELSE
       CALL TEXT('   Z-POS=',9)
       CALL NUMBD(ZA(NZ),'(F9.4)',9)
    ENDIF
    CALL MOVE(14.,17.0)
    CALL TEXT('B    =',6)
    CALL NUMBD(BB,'(F9.4)',9)
    CALL TEXT('   WALLR=',9)
    CALL NUMBD(WALLR,'(1PE9.1)',9)

    CALL MOVE(14.,16.4)
    CALL TEXT('J-HI =',6)
    CALL NUMBD(AJYH(1),'(F9.4)',9)
    CALL TEXT('/',1)
    CALL NUMBD(RANT1,'(F8.4)',8)
    CALL NUMBD(XANT1,'(F9.4)',9)
    CALL MOVE(14.,15.9)
    CALL TEXT('J-LO =',6)
    CALL NUMBD(AJYL(1),'(F9.4)',9)
    CALL TEXT('/',1)
    CALL NUMBD(RANT2,'(F8.4)',8)
    CALL NUMBD(XANT2,'(F9.4)',9)

    CALL MOVE(14.,15.3)
    CALL TEXT('      ',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL TEXT('     NS',7)
       CALL NUMBI(NS,'(I1)',1)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14.,14.8)
    CALL TEXT('N-20 =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PN(NS),'(F8.3)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14.,14.3)
    CALL TEXT('T-PP =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PTPP(NS),'(F8.3)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14.,13.8)
    CALL TEXT('T-PR =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PTPR(NS),'(F8.3)',8)
    END DO

    IF(NZPMAX.EQ.1.AND.NZ.EQ.0) RETURN

    CALL SETLIN(0,0,7)
    CALL MOVE(14.,13.3)
    CALL TEXT('P/TOT=',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PABSXZ(NS)*RNORM2,'(F8.3)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(14.,12.7)
    CALL TEXT('PTOT =',6)
    CALL NUMBD(PABSTT*RNORM2,'(F9.4)',9)
    CALL TEXT('   JTOT =',9)
    CALL NUMBD(AJCDT*RNORM2,'(F9.4)',9)

    RETURN
  END SUBROUTINE W1GPRM

!     ****** 2-D GRAPHIC ROUTINE ******

  SUBROUTINE W1GR2DW
    USE w1comm,ONLY: rkind,XAM,NXTMAX,NZPMAX,NXPRNT,CE2DA,PANT,RB
    USE libgrf
    IMPLICIT NONE
    INTEGER:: NX,NZ,NXN,NZN
    REAL(rkind):: RNORM
    REAL(rkind),DIMENSION(:),ALLOCATABLE:: GX,GZ
    REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: GFR,GFI

    RNORM=1.D0/SQRT(PANT)
    ALLOCATE(GX(NXTMAX),GZ(NZPMAX))
    ALLOCATE(GFR(NXTMAX,NZPMAX),GFI(NXTMAX,NZPMAX))

    DO NX=1,NXTMAX
       NXN=NXPRNT(NX)
       GX(NX)=XAM(NXN)
    END DO

    DO NZ=1,NZPMAX
       GZ(NZ)=DBLE(NZ)-DBLE(NZPMAX/2)
    END DO

    CALL PAGES

    DO NX=1,NXTMAX
       NXN=NXPRNT(NX)
       DO NZ=1,NZPMAX
          NZN=NZ+NZPMAX/2+1
          IF(NZN.GT.NZPMAX) NZN=NZN-NZPMAX
          GFR(NX,NZ)=DBLE(CE2DA(NZN,NXN,1))*RNORM
          GFI(NX,NZ)=IMAG(CE2DA(NZN,NXN,1))*RNORM
       END DO
    END DO

    CALL GRD2D(1,GX,GZ,GFR,NXTMAX,NXTMAX,NZPMAX,'@Re(Ex)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=2.D0,GPXMAX=12.D0,GPYMIN=2.D0,GPYMAX=17.D0)
    CALL GRD2D(2,GX,GZ,GFI,NXTMAX,NXTMAX,NZPMAX,'@Im(Ex)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=14.D0,GPXMAX=24.D0,GPYMIN=2.D0,GPYMAX=17.D0)

    CALL PAGEE

    CALL PAGES

    DO NX=1,NXTMAX
       NXN=NXPRNT(NX)
       DO NZ=1,NZPMAX
          NZN=NZ+NZPMAX/2+1
          IF(NZN.GT.NZPMAX) NZN=NZN-NZPMAX
          GFR(NX,NZ)=DBLE(CE2DA(NZN,NXN,2))*RNORM
          GFI(NX,NZ)=IMAG(CE2DA(NZN,NXN,2))*RNORM
       END DO
    END DO

    CALL GRD2D(3,GX,GZ,GFR,NXTMAX,NXTMAX,NZPMAX,'@Re(Ey)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=2.D0,GPXMAX=12.D0,GPYMIN=2.D0,GPYMAX=17.D0)
    CALL GRD2D(4,GX,GZ,GFI,NXTMAX,NXTMAX,NZPMAX,'@Im(Ey)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=14.D0,GPXMAX=24.D0,GPYMIN=2.D0,GPYMAX=17.D0)

    CALL PAGEE

    CALL PAGES

    DO NX=1,NXTMAX
       NXN=NXPRNT(NX)
       DO NZ=1,NZPMAX
          NZN=NZ+NZPMAX/2+1
          IF(NZN.GT.NZPMAX) NZN=NZN-NZPMAX
          GFR(NX,NZ)=DBLE(CE2DA(NZN,NXN,3))*RNORM
          GFI(NX,NZ)=IMAG(CE2DA(NZN,NXN,3))*RNORM
       END DO
    END DO

    CALL GRD2D(1,GX,GZ,GFR,NXTMAX,NXTMAX,NZPMAX,'@Re(Ez)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=2.D0,GPXMAX=12.D0,GPYMIN=2.D0,GPYMAX=17.D0)
    CALL GRD2D(2,GX,GZ,GFI,NXTMAX,NXTMAX,NZPMAX,'@Im(Ez)@', &
               XMIN=-RB,XMAX=RB,YMIN=DBLE(-NZPMAX/2),YMAX=DBLE(NZPMAX/2), &
               GPXMIN=14.D0,GPXMAX=24.D0,GPYMIN=2.D0,GPYMAX=17.D0)

    CALL PAGEE

    DEALLOCATE(GX,GZ,GFR,GFI)
    RETURN
  END SUBROUTINE W1GR2DW

  SUBROUTINE W1GR2DR
    USE w1comm
    IMPLICIT NONE
    INTEGER:: NS,NX,NZ,NZZ,NN,NGULEN
    REAL(rkind):: RNORM2,PGAMIN,PGAMAX
    REAL(4):: GA,GB,GZMIN,GZMAX,GZSCL,GAMIN,GAMAX,GMIN,GMAX,GSCAL
    REAL(4):: PGMIN,PGMAX,PSCAL,SGAMAX

    GA=RA
    GB=RB
    CALL PAGES
    CALL SETCHS(0.3,0.)
    CALL SETLIN(0,0,7)

    CALL MOVE(1.1,17.0)
    CALL TEXT(' FREQ=',6)
    CALL NUMBD(RF,'(F8.3)',8)
    CALL TEXT('     BB=',8)
    CALL NUMBD(BB,'(F8.3)',8)
    CALL TEXT('     RR=',8)
    CALL NUMBD(RR,'(F8.3)',8)
    CALL TEXT('     RZ=',8)
    CALL NUMBD(RZ,'(F8.3)',8)
    CALL TEXT('  WALLR=',8)
    CALL NUMBD(WALLR,'(1PE8.1)',8)

    CALL MOVE(1.1,16.5)
    CALL TEXT('  NXP=',6)
    CALL NUMBI(NXPMAX,'(I8)',8)
    CALL TEXT('    NZP=',8)
    CALL NUMBI(NZPMAX,'(I8)',8)
    CALL TEXT('     RA=',8)
    CALL NUMBD(RA,'(F8.3)',8)
    CALL TEXT('     RD=',8)
    CALL NUMBD(RD,'(F8.3)',8)
    CALL TEXT('     RB=',8)
    CALL NUMBD(RB,'(F8.3)',8)

    CALL MOVE(1.1,16.0)
    CALL TEXT('              ',14)
    CALL TEXT('                ',16)
    CALL TEXT('        ',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL TEXT('    NS-',7)
       CALL NUMBI(NS,'(I1)',1)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,15.5)
    CALL TEXT('  J-H=',6)
    CALL NUMBD(AJYH(1),'(F8.3)',8)
    CALL TEXT('    J-L=',8)
    CALL NUMBD(AJYL(1),'(F8.3)',8)
    CALL TEXT('  N-20 :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PN(NS),'(F8.3)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,15.0)
    CALL TEXT('  R-H=',6)
    CALL NUMBD(RANT1,'(F8.3)',8)
    CALL TEXT('    R-L=',8)
    CALL NUMBD(RANT2,'(F8.3)',8)
    CALL TEXT('  T-PR :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PTPR(NS),'(F8.3)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,14.5)
    CALL TEXT('  X-H=',6)
    CALL NUMBD(XANT1,'(F8.3)',8)
    CALL TEXT('    X-L=',8)
    CALL NUMBD(XANT2,'(F8.3)',8)
    CALL TEXT('  T-PP :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PTPP(NS),'(F8.3)',8)
    END DO

    RNORM2=1.D0/PANT

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,14.0)
    CALL TEXT('PANTH=',6)
    CALL NUMBD(PANT1*RNORM2,'(F8.3)',8)
    CALL TEXT('  PANTL=',8)
    CALL NUMBD(PANT2*RNORM2,'(F8.3)',8)
    CALL TEXT('  N-S  :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PNS(NS),'(F8.3)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,13.5)
    CALL TEXT('PWALH=',6)
    CALL NUMBD(PWALL1*RNORM2,'(F8.3)',8)
    CALL TEXT('  PWALL=',8)
    CALL NUMBD(PWALL2*RNORM2,'(F8.3)',8)
    CALL TEXT('  T-S  :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PTS(NS),'(F8.3)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,13.0)
    CALL TEXT('PABST=',6)
    CALL NUMBD(PABSTT*RNORM2,'(F8.3)',8)
    CALL TEXT('  AJCDT=',8)
    CALL NUMBD(AJCDT*RNORM2,'(F8.3)',8)
    CALL TEXT('  PABS :',8)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(PABSXZ(NS)*RNORM2,'(F8.3)',8)
    END DO

    DO NZ=1,NZPMAX+1
       IF(NZ.LE.NZPMAX/2) THEN
          NZZ = NZ + NZPMAX/2
       ELSE
          NZZ = NZ - NZPMAX/2
       ENDIF
       GZ(NZ)=AKZ(NZZ)
    END DO
    GZ(1    )=-AKZ(NZPMAX/2+1)
    CALL GQSCAL(GZ(1),GZ(NZPMAX+1),GZMIN,GZMAX,GZSCL)

    DO NZ=1,NZPMAX
       GDATAZ(NZ)=PANTK(NZ)*RNORM2
    END DO
    CALL GMNMX1(GDATAZ,1,NZPMAX,1,GAMIN,GAMAX)
    CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,GSCAL)

    CALL SETLIN(0,0,4)
    IF(NGRAPH.EQ.3) THEN
       CALL GDEFIN(2.5,12.5,1.0,12.0,GZ(1),GZ(NZPMAX+1),-0.1*GMAX,GMAX)
    ELSE
       CALL GDEFIN(2.5,12.5,1.0,6.5,GZ(1),GZ(NZPMAX+1),-0.1*GMAX,GMAX)
    ENDIF
    CALL GFRAME
    CALL GSCALE(0.,GZSCL,0.,   GSCAL,0.1,9)
    CALL GSCALE(0.,0.,0.,2.*GMAX,0.0,0)
    CALL GVALUE(0.,0.,0.,4*GSCAL,NGULEN(4*GSCAL))
    CALL GVALUE(0.,2*GZSCL,0.,0.,     0)
    CALL SETLIN(0,0,7)
    DO NZ=1,NZPMAX+1
       IF(NZ.LE.NZPMAX/2) THEN
          NZZ = NZ + NZPMAX/2
       ELSE
          NZZ = NZ - NZPMAX/2
       ENDIF
       GDATAZ(NZ)=PANTK(NZZ)*RNORM2
    END DO
    CALL GPLOTP(GZ,GDATAZ,1,NZPMAX+1,1,0,0,0)
    DO NZ=1,NZPMAX+1
       GDATAZ(NZ)=0.0
    END DO
    DO NS=1,NSMAX
       DO NZ=1,NZPMAX+1
          IF(NZ.LE.NZPMAX/2) THEN
             NZZ = NZ + NZPMAX/2
          ELSE
             NZZ = NZ - NZPMAX/2
          ENDIF
          GDATAZ(NZ)=GDATAZ(NZ)+PAK(NZZ,NS)*RNORM2
       END DO
       CALL SETLIN(0,0,7-NS)
       CALL GPLOTP(GZ,GDATAZ,1,NZPMAX+1,1,-NS,10,0)
    END DO

    IF(NGRAPH.NE.2.AND.NGRAPH.NE.3) THEN
       DO NZ=1,NZPMAX+1
          IF(NZ.LE.NZPMAX/2) THEN
             NZZ = NZ + NZPMAX/2
          ELSE
             NZZ = NZ - NZPMAX/2
          ENDIF
          GDATAZ(NZ)=AJCDK(NZZ)*RNORM2
       END DO
       CALL GMNMX1(GDATAZ,1,NZPMAX,1,GAMIN,GAMAX)
       CALL SETLIN(0,0,4)
       CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,GSCAL)
       CALL GDEFIN(2.5,12.5,6.5,12.0,GZ(1),GZ(NZPMAX+1),GMIN,GMAX)
       CALL GFRAME
       CALL GSCALE(0.,  GZSCL,0.,  GSCAL,0.1,9)
       CALL GSCALE(0.,2*GZSCL,0.,2*GSCAL,0.2,9)
       CALL GSCALE(0.,0.,0.,2.*MAX(ABS(GMAX),ABS(GMIN)),0.0,0)
       CALL GVALUE(0.,0.,0.,4*GSCAL,NGULEN(4*GSCAL))
       CALL SETLIN(0,0,7)
       CALL GPLOTP(GZ,GDATAZ,1,NZPMAX+1,1,0,0,0)
    ENDIF

    DO NX=1,NXTMAX
       NN=NXPRNT(NX)
       GX(NX)=XAM(NN)
       GXM(NX)=XAM(NX)
    END DO

    PGAMIN=0.0
    PGAMAX=0.0
    DO NS=1,NSMAX
       DO NX=1,NXPMAX
          GDATA1(NX)=PABSX(NX,NS)*RNORM2
       END DO
       CALL GMNMX1(GDATA1,1,NXPMAX,1,GAMIN,GAMAX)
       PGAMIN=MIN(PGAMIN,GAMIN)
       PGAMAX=MAX(PGAMAX,GAMAX)
    END DO
    PGAMAX=MAX(ABS(PGAMAX),ABS(PGAMIN))
    CALL GQSCAL(0.,PGAMAX,PGMIN,PGMAX,PSCAL)

    IF(NGRAPH.NE.2.AND.NGRAPH.NE.3) THEN
       DO NX=1,NXPMAX
          GDATA1(NX)=AJCDX(NX)*RNORM2
       END DO
       CALL GMNMX1(GDATA1,1,NXPMAX,1,GAMIN,GAMAX)
       IF(ABS(GAMAX).GE.ABS(GAMIN)) THEN
          SGAMAX=GAMAX
       ELSE
          SGAMAX=GAMIN
       ENDIF

       CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,GSCAL)
       CALL GDEFIN(15.0,25.0,6.5,12.0,-GB,GB,GMIN,GMAX)
       CALL SETLIN(0,0,4)
       CALL GFRAME
       CALL GSCALE(0.,0.1,0.,0.,0.1,9)
       CALL GSCALE(0.,0.,0.,GSCAL,0.1,9)
       CALL GSCALE(0.,100.,0.,0.,0.2,9)
       CALL GSCALE(-GA,2.*GA,0.,20.*GSCAL,0.1,0)
       CALL GVALUE(0.,0.,0.,4*GSCAL,NGULEN(4*GSCAL))
       CALL SETLIN(0,0,7)
       CALL GPLOTP(GXM,GDATA1,1,NXPMAX,1,0,0,0)
    ENDIF
    CALL SETLIN(0,0,4)

    IF(NGRAPH.EQ.3) THEN
       CALL GDEFIN(15.0,25.0,1.0,12.0,-GB,GB,-0.1*PGMAX,PGMAX)
    ELSE
       CALL GDEFIN(15.0,25.0,1.0,6.5,-GB,GB,-0.1*PGMAX,PGMAX)
    ENDIF
    CALL GFRAME
    CALL GSCALE(0.,0.1,0.,0.,0.1,9)
    CALL GSCALE(0.,0.,0.,PSCAL,0.1,9)
    CALL GSCALE(0.,100.,0.,0.,0.2,9)
    CALL GSCALE(-GA,2.*GA,0.,20.*PSCAL,0.1,0)
    CALL GVALUE(0.,0.,0.,4*PSCAL,NGULEN(4*PSCAL))
    CALL GVALUE(0.,REAL(RA),0.,0.,2)
    DO NS=1,NSMAX
       CALL SETLIN(0,0,7-NS)
       DO NX=1,NXPMAX
          GDATA1(NX)=PABSX(NX,NS)*RNORM2
       END DO
       CALL GPLOTP(GXM,GDATA1,1,NXPMAX,1,-NS,10,0)
    END DO

    IF(NMODEL.EQ.5.OR.NMODEL.EQ.3.OR.NMODEL.EQ.1) THEN
       DO NX=1,NXTMAX
          NN        =NXPRNT(NX)
          GDATA1(NX)=FLUXX(NN)*RNORM2
       END DO
       CALL GMNMX1(GDATA1,1,NXTMAX,1,GAMIN,GAMAX)
       IF(ABS(GAMIN).GE.ABS(GAMAX)) THEN
          DO NX=1,NXTMAX
             GDATA1(NX)=-GDATA1(NX)
          END DO
          GAMAX=-GAMIN
       ENDIF
       CALL GQSCAL(0.,GAMAX*1.02,GMIN,GMAX,GSCAL)
       IF(NGRAPH.EQ.3) THEN
          CALL GDEFIN(15.0,25.0,1.0,12.0,-GB,GB,-0.1*GMAX,GMAX)
       ELSE
          CALL GDEFIN(15.0,25.0,1.0,6.5,-GB,GB,-0.1*GMAX,GMAX)
       ENDIF
       CALL SETLIN(0,0,7)
       CALL GPLOTP(GX,GDATA1,1,NXTMAX,1,0,0,0)
    ENDIF

    CALL SETLIN(0,0,7)
    CALL MOVE(1.1,12.5)
    CALL TEXT('PGAMAX=',6)
    CALL NUMBR(PGAMAX,'(F8.3)',8)
    CALL TEXT('  SGAMAX=',8)
    CALL NUMBR(SGAMAX,'(F8.3)',8)

    CALL PAGEE
    RETURN
  END SUBROUTINE W1GR2DR

  SUBROUTINE W1GPRX
    USE w1comm
    IMPLICIT NONE
    INTEGER:: NS
    REAL(rkind):: RNORM2

    RNORM2=1.D0/PANT

    CALL SETLIN(0,0,7)
    CALL MOVE(14.,12.0)
    CALL TEXT('IR   =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(AHLT(NS,1)*RNORM2,'(F8.5)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14.,11.5)
    CALL TEXT('INR  =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(AHLT(NS,2)*RNORM2,'(F8.5)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14.,11.0)
    CALL TEXT('ITOT =',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD((AHLT(NS,1)+AHLT(NS,2))*RNORM2,'(F8.5)',8)
    END DO

    CALL SETLIN(0,0,7)
    CALL MOVE(14.,10.3)
    CALL TEXT('IR  T=',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(AHLT(NS,3)*RNORM2,'(F8.5)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14., 9.8)
    CALL TEXT('INR T=',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD(AHLT(NS,4)*RNORM2,'(F8.5)',8)
    END DO
    CALL SETLIN(0,0,7)
    CALL MOVE(14., 9.3)
    CALL TEXT('ITOTT=',6)
    DO NS=1,MIN(NSMAX,4)
       CALL SETLIN(0,0,7-NS)
       CALL NUMBD((AHLT(NS,3)+AHLT(NS,4))*RNORM2,'(F8.5)',8)
    END DO
    CALL SETLIN(0,2,4)

    RETURN
  END SUBROUTINE W1GPRX

END MODULE w1grf1
