C
C     ****** TASK/W1 (SUBROUTINE LIBRARY 1) ******
C
C     ******* OUTPUT TO LINE PRINTER *******
C
      SUBROUTINE W1PRNT(NPRINT)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1PWR2/ PAKT(NZPM,3),PANTK(NZPM),PAK(NZPM,ISM)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1FFTW/ CT(NZPM),CFFT(NZPM*NZLM),LFFT(NZPM*NZLM)
      COMMON /W1WORK/ TEMP(NXTM,NZPM),NXPRNT(NXTM)
      COMMON /W1PRF1/ PROFB(NXPM),PROFPN(NXPM,ISM),PROFPU(NXPM,ISM),
     &                PROFTR(NXPM,ISM),PROFTP(NXPM,ISM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,ICDTYP
      COMMON /W1BAH3/ AHLT(ISM,4),AHL(NXPM,ISM,4)
C
      CHARACTER INDEX*8
C
      RNORM=1.D0/PANT
      IF(NPRINT.LE.-1) THEN
         WRITE(6,611) (PROFPN(NX,4),NX=1,NXP)
  611    FORMAT(1H ,'*** ALPHA PARTICLE DENSITY PROFILE ***'/
     &         (1H ,1P10D12.4))
      ENDIF
C
      WRITE(6,620) PANT*RNORM,PANT1*RNORM,PANT2*RNORM
      WRITE(6,661) PWALL*RNORM,PWALL1*RNORM,PWALL2*RNORM,
     &             PABSTT*RNORM,AJCDT*RNORM,PERR*RNORM
      WRITE(6,664)
      WRITE(6,663) (IS,PABSXZ(IS)*RNORM,
     &              AHLT(IS,1)*RNORM,AHLT(IS,2)*RNORM,
     &             (AHLT(IS,1)+AHLT(IS,2))*RNORM,
     &              AHLT(IS,3)*RNORM,AHLT(IS,4)*RNORM,
     &             (AHLT(IS,3)+AHLT(IS,4))*RNORM,IS=1,ISMAX)
      WRITE(6,662)
      DO 200 IA = 1 , IAMAX
  200 WRITE(6,621) IA,RANT1(IA),XANT1(IA),RANT2(IA),XANT2(IA)
C
      DO 2000 NX=1,NXT
         IF(NX.LE.NXV) THEN
            NXPRNT(NX)=NXP+NXV+NX
         ELSE
            NXPRNT(NX)=NX-NXV
         ENDIF
 2000 CONTINUE
C
      IF(NPRINT.LE.0) RETURN
C
      NXANT1=NXP+NXV+NXV/2+1
      NXANT2=NXP    +NXV/2
      WRITE(6,633)
      WRITE(6,601)
      DO 3100 NZ=1,NZP
         WRITE(6,634) ZA(NZ),CJ1(NZ),CE2DA(NZ,NXANT1,2),
     &                       CJ2(NZ),CE2DA(NZ,NXANT2,2)
 3100 CONTINUE
C
      CALL W1FFTL(CJ1,NZP,0)
      CALL FFT2L(CJ2,CFJ2,CT,LIST,NZP/2,IFFT,1,LP)
      WRITE(6,635) (IS,IS=1,ISMAX)
      WRITE(6,601)
      DO 3200 NZ=1,NZP
         PJK=ABS(CJ1(NZ))**2+ABS(CJ2(NZ))**2
         WRITE(6,636) AKZ(NZ),PJK*RNORM,PANTK(NZ)*RNORM,
     &                (PAKT(NZ,I)*RNORM,I=1,3),
     &                (PAK(NZ,IS)*RNORM,IS=1,ISMAX)
 3200 CONTINUE
      CALL W1FFTL(CJ1,NZP,1)
      CALL FFT2L(CFJ2,CJ2,CT,LIST,NZP/2,IFFT,2,LP)
C
      IF(NPRINT.LE.1) RETURN
C
      WRITE(6,630) (IS,IS=1,ISMAX)
      WRITE(6,601)
      DO 3000 NX=1,NXP
         WRITE(6,631) XAM(NX),FLUXX(NX),
     &                (PABSX(NX,IS),IS=1,ISMAX)
 3000 CONTINUE
      WRITE(6,632) PABSTT,(PABSXZ(IS),IS=1,ISMAX)
      WRITE(6,6321)       (PABSXZ(IS)/PABSTT,IS=1,ISMAX)
C
      IF(NPRINT.LE.2) RETURN
C
      DO 4200 IC=1,3
C
         DO 4110 NX=1,NXT
         DO 4110 NZ=1,NZP
            TEMP(NX,NZ)=ABS(CE2DA(NZ,NX,IC))
 4110    CONTINUE
         IF(IC.EQ.1) INDEX='ABS(EX) '
         IF(IC.EQ.2) INDEX='ABS(EY) '
         IF(IC.EQ.3) INDEX='ABS(EZ) '
         CALL W1PRTS(NXT,NZP,1,INDEX)
C
         IF(NPRINT.LE.3) RETURN
C
         DO 4120 NX=1,NXT
         DO 4120 NZ=1,NZP
            TEMP(NX,NZ)=REAL(CE2DA(NZ,NX,IC))
 4120    CONTINUE
         IF(IC.EQ.1) INDEX='REAL(EX)'
         IF(IC.EQ.2) INDEX='REAL(EY)'
         IF(IC.EQ.3) INDEX='REAL(EZ)'
         CALL W1PRTS(NXT,NZP,1,INDEX)
C
         DO 4130 NX=1,NXT
         DO 4130 NZ=1,NZP
            TEMP(NX,NZ)=IMAG(CE2DA(NZ,NX,IC))
 4130    CONTINUE
         IF(IC.EQ.1) INDEX='IMAG(EX)'
         IF(IC.EQ.2) INDEX='IMAG(EY)'
         IF(IC.EQ.3) INDEX='IMAG(EZ)'
         CALL W1PRTS(NXT,NZP,1,INDEX)
C
 4200 CONTINUE
      RETURN
C
  601 FORMAT(1H )
  620 FORMAT(1H0,'*** POWER PARTITION *** (UNIT = MW/M)'/
     &       1H ,4X,'PANT   =',1PE12.4,8X,
     &              'PANT1  =',  E12.4,4X,'PANT2  =',E12.4)
  661 FORMAT(1H ,4X,'PWALL  =',1PE12.4,8X,
     &              'PWALL1 =',  E12.4,4X,'PWALL2 =',E12.4/
     &       1H ,4X,'PABST  =',1PE12.4,8X,'AJCDT  =',E12.4,
     &           4X,'PERR   =',1PE12.4)
  663 FORMAT(1H ,I5,1P7E10.2)
  662 FORMAT(1H ,'*** ANTENNA LOADING *** (UNIT = OHM/M)'/
     &       1H ,'IA  ',7X,'RANTH',10X,'XANTH',15X,'RANTL',10X,'XANTL')
  664 FORMAT(1H ,'   IS   PABS       I R      I NR      I TOT',
     &                        '      I RT     I NRT     I TOTT')
  621 FORMAT(1H ,1X,I3,2X,2(3X,1PE12.4),5X,2(3X,E12.4))
  630 FORMAT(1H0,5X,'X',10X,'FLUXX(X)',1X,
     &           2X,5(6X,'P-IS',I1,'(X)':))
  631 FORMAT(1H ,F10.5,1PE14.4,2X,5(E14.4))
  632 FORMAT(1H0,3X,'TOTAL',18X,1PE14.4,2X,5(E14.4))
 6321 FORMAT(1H ,42X,5(F14.5))
  633 FORMAT(1H0,5X,'Z',20X,'CJ1',23X,'EY1',25X,'CJ2',23X,'EY2')
  634 FORMAT(1H ,F10.5,2(4X,1P2E12.4,2X,2E12.4))
  635 FORMAT(1H0,3X,'KZ',6X,'J**2(KZ)',4X,'P-ANT(KZ)',3X,'P-TOT(KZ)',
     &           3X,'P-IBW(KZ)',3X,'P-ABS(KZ)',
     &           2X,5(3X,'P-IS',I1,'(KZ)':))
  636 FORMAT(1H ,F8.4,1PE12.4,E12.4,E12.4,E12.4,E12.4,2X,5(E12.4))
      END
C
C     ====== OUTPUT OF 2-D DATA TO LINE PRINTER ======
C
      SUBROUTINE W1PRTS(NX,NZ,IND,INDEX)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1WORK/ TEMP(NXTM,NZPM),NXPRNT(NXTM)
      CHARACTER INDEX*8
C
      DO 10 IZ=1,NZ,9
         IEND=IZ+8
         IF(IEND.GT.NZ) IEND=NZ
         WRITE(6,601) INDEX
         WRITE(6,602) (ZA(I),I=IZ,IEND)
         WRITE(6,603)
      DO 10 KX=1,NX
         K=KX
         IF(IND.EQ.1) K=NXPRNT(KX)
         WRITE(6,604) XAM(K),(TEMP(K,I),I=IZ,IEND)
   10 CONTINUE
      RETURN
  601 FORMAT(1H0,A8)
  602 FORMAT(1H ,'        Z=',9(F8.4,4X))
  603 FORMAT(1H ,'   X')
  604 FORMAT(1H ,F8.4,2X,9(1PE12.4))
      END
C
C     ******* OUTPUT TO FILE 21 *******
C
      SUBROUTINE W1FILE(NFILE)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1PWR2/ PAKT(NZPM,3),PANTK(NZPM),PAK(NZPM,ISM)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1WORK/ TEMP(NXTM,NZPM),NXPRNT(NXTM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
C
      CHARACTER INDEX*8
C
      IF(NFILE.LE.0) RETURN
C
      AZ=0.D0
      WRITE(21) REAL(RF),REAL(BB),REAL(AJYH(1)),REAL(AJYL(1)),
     &          REAL(RR),REAL(RA),REAL(RD),REAL(RB),REAL(RZ),
     &          REAL(AZ),REAL(WALLR),REAL(RKZ)
      WRITE(21) NXP,NXV,NZP,ISMAX
      WRITE(21) (REAL(PA(IS)),REAL(PZ(IS)),REAL(PN(IS)),
     &           REAL(PTPP(IS)),REAL(PTPR(IS)),REAL(PU(IS)),
     &           REAL(PNS(IS)),REAL(PTS(IS)),REAL(PZCL(IS)),
     &           IS=1,ISMAX)
      WRITE(21) (REAL(XAM(NX)),NXPRNT(NX),NX=1,NXT)
C
      WRITE(21) PANT,PANT1,PANT2,PWALL,PWALL1,PWALL2,PIBW,PIBW1,PIBW2,
     &          PABSTT,(PABSXZ(IS),IS=1,ISMAX),PERR,
     &          RANT1,RANT2,XANT1,XANT2
      WRITE(21) (FLUXX(NX),NX=1,NXT)
      WRITE(21) ((PABSX(NX,IS),NX=1,NXP),IS=1,ISMAX)
C
      WRITE(21) (REAL(ZA(NZ)),NZ=1,NZP)
      WRITE(21) (REAL(AKZ(NZ)),NZ=1,NZP)
      WRITE(21) (PANTK(NZ),(PAKT(NZ,I),I=1,3),
     &          (PAK(NZ,IS),IS=1,ISMAX),NZ=1,NZP)
C
      IF(NFILE.LE.1) GOTO 9000
C
      DO 8100 IC=1,3
         IF(IC.EQ.1) INDEX='EFIELD-X'
         IF(IC.EQ.2) INDEX='EFIELD-Y'
         IF(IC.EQ.3) INDEX='EFIELD-Z'
         WRITE(21) INDEX
C        WRITE(21) ((CE2DA(NZ,NX,IC),NX=1,NXT),NZ=1,NZP)
         WRITE(21) ((REAL(CE2DA(NZ,NX,IC)),
     &               IMAG(CE2DA(NZ,NX,IC)),NX=1,NXT),NZ=1,NZP)
 8100 CONTINUE
C
C
 9000 INDEX='END-DATA'
      WRITE(21) INDEX
      WRITE(6,680)
      RETURN
  680 FORMAT(1H0,'***** DATA SAVED IN FILE 21 *****'/)
      END
