! wrgout.f90

MODULE WRGOUT

  INTERFACE
     FUNCTION GUCLIP(X)
       REAL(8):: X
       REAL(4):: GUCLIP
     END FUNCTION GUCLIP
     FUNCTION NGULEN(Y)
       REAL(4):: Y
       INTEGER:: NGULEN
     END FUNCTION NGULEN
  END INTERFACE

CONTAINS

!*********************** GRAPHIC DATA OUTPUT ************************

  SUBROUTINE WR_GOUT(NSTAT)

    USE wrcomm
    IMPLICIT NONE
    INTEGER,INTENT(IN):: NSTAT
    CHARACTER(LEN=1)::  KID

      IF(MODELG.EQ.11) THEN
         CALL WRGRF11A
         RETURN
      END IF

    1 WRITE(6,*)'INPUT GRAPH TYPE : 1,2,3,4,5,6  X'
      READ(5,'(A1)',ERR=1,END=9000) KID
      CALL GUCPTL(KID)

      IF(KID.EQ.'1'.AND.NSTAT.GE.1) CALL WRGRFA
      IF(KID.EQ.'2'.AND.NSTAT.GE.1) CALL WRGRFB
      IF(KID.EQ.'3'.AND.NSTAT.GE.1) CALL WRGRFC
      IF(KID.EQ.'4'.AND.NSTAT.GE.2) CALL WRGRFD
      IF(KID.EQ.'5'.AND.NSTAT.GE.2) CALL WRGRFE
      IF(KID.EQ.'6'.AND.NSTAT.GE.2) CALL WRGRFF
      IF(KID.EQ.'7'.AND.NSTAT.GE.2) CALL WRGRFG
      IF(KID.EQ.'X') GOTO 9000

      GOTO 1

 9000 RETURN
  END SUBROUTINE WR_GOUT

!     ***** POLOIDAL TRAJECTORY AND POWER *****

  SUBROUTINE WRGRFA

    USE wrcomm
    USE plprof,ONLY:PL_RZSU,PL_MAG_OLD
    IMPLICIT NONE
    INTEGER,PARAMETER:: NSUM=501
    INTEGER,PARAMETER:: NGXL=101
    INTEGER,PARAMETER:: NGYL=101
    REAL(rkind):: RSU(NSUM),ZSU(NSUM)
    REAL(4):: GRS(NSUM+1),GZS(NSUM+1)
    REAL(4):: GX(NSTPMAX+1),GY(NSTPMAX+1)
    REAL(4):: GUX(NSTPMAX+1),GUY(NSTPMAX+1)
    REAL(4):: GPX(NSTPMAX+1),GPY(NSTPMAX+1,NRAYMAX)
    REAL(4):: GPRY(NSTPMAX+1,NRAYMAX)
    REAL(4):: GCF(NGXL,NGYL),GCX(NGXL),GCY(NGYL)
    INTEGER:: KA(2,NGXL,NGYL)
    INTEGER:: NSU,NSUMAX,NGX,NGY,NRAY,NSTP,NRDIV,NRS1,NRS2,NDR,NR
    REAL(4):: GRSMIN,GRSMAX,GRMIN,GRMAX,GRSTEP,GRORG,GRLEN
    REAL(4):: GZSMIN,GZSMAX,GZMIN,GZMAX,GZSTEP,GZORG,GZLEN
    REAL(4):: GRMID,GZMID,GXOR
    REAL(4):: GYSMIN,GYSMAX1,GYSCAL1,GYSMAX2,GYSCAL2,GYSMAX,GYSCAL
    REAL(4):: GXMIN,GXMAX,GXSTEP,GYMIN,GYMAX,GXORG
    REAL(rkind):: DGX,DGY,ZL,RL,RHON,XL,YL,DRHO,RHON1,RHON2,SDR,DELPWR
    REAL(rkind):: FACTA,FACTB

!     ----- PLASMA BOUNDARY -----

      CALL PL_RZSU(RSU,ZSU,NSUM,NSUMAX)
      DO NSU=1,NSUMAX
         GRS(NSU)=GUCLIP(RSU(NSU))
         GZS(NSU)=GUCLIP(ZSU(NSU))
      ENDDO
      GRS(NSUMAX+1)=GRS(1)
      GZS(NSUMAX+1)=GZS(1)

      CALL GMNMX1(GRS,1,NSUMAX,1,GRSMIN,GRSMAX)
      CALL GMNMX1(GZS,1,NSUMAX,1,GZSMIN,GZSMAX)
      CALL GQSCAL(GRSMIN,GRSMAX,GRMIN,GRMAX,GRSTEP)
      CALL GQSCAL(GZSMIN,GZSMAX,GZMIN,GZMAX,GZSTEP)

      GRORG=(INT(GRMIN/(2*GRSTEP))+1)*2*GRSTEP

      GRLEN=GRMAX-GRMIN
      GZLEN=GZMAX-GZMIN
      IF(1.5*GRLEN.GT.GZLEN) THEN
         GZMID=0.5*(GZMIN+GZMAX)
         GZMIN=GZMID-0.75*GRLEN
         GZMAX=GZMID+0.75*GRLEN
!         CALL GDEFIN(1.5,11.5,1.0,16.0,
!     &               GRMIN,GRMAX,GZMID-0.75*GRLEN,GZMID+0.75*GRLEN)
         
      ELSE
         GRMID=0.5*(GRMIN+GRMAX)
         GRMIN=GRMID-0.333*GZLEN
         GRMAX=GRMID+0.333*GZLEN
!         CALL GDEFIN(1.5,11.5,1.0,16.0,
!     &               GRMID-0.333*GZLEN,GRMID+0.333*GZLEN,GZMIN,GZMAX)
      ENDIF
         CALL GDEFIN(1.5,11.5,1.0,16.0,GRMIN,GRMAX,GZMIN,GZMAX)

      CALL PAGES
      CALL SETCHS(0.25,0.)
      CALL SETFNT(32)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      CALL GSCALE(GRORG,  GRSTEP,0.0,  GZSTEP,0.1,9)
      CALL GVALUE(GRORG,2*GRSTEP,0.0,0.0,NGULEN(2*GRSTEP))
      CALL GVALUE(0.0,0.0,0.0,2*GZSTEP,NGULEN(2*GZSTEP))
      CALL SETLIN(0,2,4)
      CALL GPLOTP(GRS,GZS,1,NSUMAX+1,1,0,0,0)

      IF(MODELG.EQ.3.OR.MODELG.EQ.5.OR.MODELG.EQ.8) THEN
         DGX=DBLE(GRMAX-GRMIN)/(NGXL-1)
         DO NGX=1,NGXL
            GCX(NGX)=GRMIN+(NGX-1)*GUCLIP(DGX)
         ENDDO
         DGY=DBLE(GZMAX-GZMIN)/(NGYL-1)
         DO NGY=1,NGYL
            GCY(NGY)=GZMIN+(NGY-1)*GUCLIP(DGY)
         ENDDO
         DO NGY=1,NGYL
            ZL=DBLE(GCY(NGY))
            DO NGX=1,NGXL
               RL=DBLE(GCX(NGX))
               CALL PL_MAG_OLD(RL,0.D0,ZL,RHON)
               GCF(NGX,NGY)=GUCLIP(RHON)
            ENDDO
         ENDDO
         CALL CONTP2(GCF,GCX,GCY,NGXL,NGXL,NGYL,0.1,0.1,9,0,1,KA)
      ENDIF

!     ----- RAY TRAJECTORY -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            RL=SQRT(RAYS(1,NSTP,NRAY)**2+RAYS(2,NSTP,NRAY)**2)
            GX(NSTP+1)=GUCLIP(RL)
            GY(NSTP+1)=GUCLIP(RAYS(3,NSTP,NRAY))
         ENDDO
         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

!     ----- CALCULATE RADIAL DEPOSNSTPION PROFILE -----

      DRHO=1.D0/NRDIVMAX
      DO NRDIV=1,NRDIVMAX
         GPX(NRDIV)=GUCLIP(NRDIV*DRHO)
      ENDDO
      DO NRAY=1,NRAYMAX
         DO NRDIV=1,NRDIVMAX
             GPY(NRDIV,NRAY)=0.0
             GPRY(NRDIV,NRAY)=0.0
         ENDDO
      ENDDO

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)-1
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON1)
	    NRS1=INT(RHON1/DRHO)+1
            XL=RAYS(1,NSTP+1,NRAY)
            YL=RAYS(2,NSTP+1,NRAY)
            ZL=RAYS(3,NSTP+1,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON2)
            NRS2=INT(RHON2/DRHO)+1
            NDR=ABS(NRS2-NRS1)
            IF(NDR.EQ.0) THEN
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)+GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE IF(NRS1.LT.NRS2) THEN
               SDR=(RHON2-RHON1)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                    +GUCLIP((DBLE(NRS1)-RHON1/DRHO)*DELPWR)
               DO NR=NRS1+1,NRS2-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                             +GUCLIP((RHON2/DRHO-DBLE(NRS2-1))*DELPWR)
            ELSE
               SDR=(RHON1-RHON2)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                             +GUCLIP((DBLE(NRS2)-RHON2/DRHO)*DELPWR)
               DO NR=NRS2+1,NRS1-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                             +GUCLIP((RHON1/DRHO-DBLE(NRS1-1))*DELPWR)
            ENDIF
!            WRITE(6,'(3I5,1P5E12.4))') 
!     &           NSTP,NRS1,NRS2,RHON1,RHON2,SDR,DELPWR,RAYS(8,NSTP+1,NRAY)
         ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO

      DO NRAY=1,NRAYMAX
      DO NRDIV=1,NRDIVMAX
         GPY(NRDIV,NRAY)=GPY(NRDIV,NRAY) &
                      /GUCLIP(2*PI*(DBLE(NRDIV)-0.5D0)*DRHO*DRHO)
       ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO

!     ----- weight of power for each ray-------

      IF(NRAYMAX.EQ.1) THEN
         FACTA=0.D0
      ELSE
         FACTA=EXP(-1.D0)/(1.D0+EXP(-1.D0)*(NRAYMAX/2))
      ENDIF
      FACTB=1.D0-FACTA*(NRAYMAX/2)
      DO NRDIV=1,NRDIVMAX
         DO NRAY=2,NRAYMAX
            GPRY(NRDIV,1)=GPRY(NRDIV,1)+GPY(NRDIV,NRAY)*FACTA
         ENDDO
            GPRY(NRDIV,1)=GPRY(NRDIV,1)+GPY(NRDIV,1)*FACTB
      ENDDO

!     ----- draw deposition profile -----

      CALL GQSCAL(GUCLIP(RHOGMN),GUCLIP(RHOGMX),GXMIN,GXMAX,GXSTEP)

      CALL GMNMX2(GPY,NSTPMAX+1,1,NRDIVMAX,1,1,NRAYMAX,1,GYMIN,GYMAX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMIN,GYSMAX1,GYSCAL1)
      GYSMIN=0.0
      GYSMAX2=0.1 
      GYSCAL2=2.E-2
      GYSMAX=MAX(GYSMAX1,GYSMAX2)
      GYSCAL=MAX(GYSCAL1,GYSCAL2)

      CALL MOVE(13.5,16.1)
      CALL TEXT('ABS POWER',10)
      IF(MOD(MDLWRG/2,2).EQ.0) THEN
         CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,0.0,GYSMAX)
         CALL SETLIN(0,2,7)
         CALL GFRAME
         CALL GSCALE(0.0,  GXSTEP,0.0,  GYSCAL,0.1,9)
         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,GYSCAL,NGULEN(GYSCAL))
      ELSE
         CALL GDEFIN(13.5,23.5,9.0,16.0,GXMIN,GXMAX,0.0,GYSMAX)
         CALL SETLIN(0,2,7)
         CALL GFRAME
         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
         CALL GSCALE(GXORG,  GXSTEP,0.0,  GYSCAL,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,GYSCAL,NGULEN(GYSCAL))
      ENDIF
!      CALL SETLIN(0,0,4)
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GPX,GPY(1,NRAY),1,NRDIVMAX,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)


!     ----- draw weight power ----

      CALL GMNMX1(GPRY(1,1),1,NRDIVMAX,1,GYMIN,GYMAX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMIN,GYSMAX1,GYSCAL1)
      GYSMIN=0.0
      GYSMAX2=0.1 
      GYSCAL2=2.E-2
      GYSMAX=MAX(GYSMAX1,GYSMAX2)
      GYSCAL=MAX(GYSCAL1,GYSCAL2)

      CALL MOVE(13.5,8.1)
      CALL TEXT('ABS WEIGHT POWER',20)
      IF(MOD(MDLWRG/2,2).EQ.0) THEN
         CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,0.0,GYSMAX)
         CALL SETLIN(0,2,7)
         CALL GFRAME
         CALL GSCALE(0.0,  GXSTEP,0.0,  GYSCAL,0.1,9)
         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,GYSCAL,NGULEN(GYSCAL))
      ELSE
         CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,0.0,GYSMAX)
         CALL SETLIN(0,2,7)
         CALL GFRAME
         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
         CALL GSCALE(GXORG,  GXSTEP,0.0,  GYSCAL,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,GYSCAL,NGULEN(GYSCAL))
      ENDIF
!      CALL SETLIN(0,0,4)
!      DO NRAY=1,NRAYMAX
!         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GPX,GPRY(1,1),1,NRDIVMAX,1,0,0,0)
!      ENDDO

!     ----- DRAW POWER FLUX -----
!      
!      GZSMIN=0.0
!      GZSMAX=1.1
!      GZSCAL=0.2

!      CALL MOVE(13.5,8.1)
!      CALL TEXT('POWER FLUX',10)
!      IF(MOD(MDLWRG/2,2).EQ.0) THEN
!         CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,0.0,GZSMAX)
!         CALL SETLIN(0,2,7)
!         CALL GFRAME
!         CALL GSCALE(0.0,  GXSTEP,0.0,  GZSCAL,0.1,9)
!         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
!         CALL GVALUE(0.0,0.0,0.0,GZSCAL,1)
!      ELSE
!         CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,0.0,GXSMAX)
!         CALL SETLIN(0,2,7)
!         CALL GFRAME
!         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
!         CALL GSCALE(GXORG,  GXSTEP,0.0,  GZSCAL,0.1,9)
!         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
!         CALL GVALUE(0.0,0.0,0.0,GZSCAL,1)
!      ENDIF
!      DO NRAY=1,NRAYMAX
!         DO NSTP=0,NSTPMAX_NRAY(NRAY)
!            XL=RAYS(1,NSTP,NRAY)
!            YL=RAYS(2,NSTP,NRAY)
!            ZL=RAYS(3,NSTP,NRAY)
!            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
!	    GUX(NSTP+1)=GUCLIP(RHON)
!            GUY(NSTP+1)=GUCLIP(RAYS(7,NSTP,NRAY))
!         ENDDO
!         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
!         CALL GPLOTP(GUX,GUY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)      
!      ENDDO

      CALL WRGPRM
      CALL PAGEE
      RETURN
  END SUBROUTINE WRGRFA

!     ***** RADIAL DEPENDENCE 1 *****

  SUBROUTINE WRGRFB

    USE wrcomm
    USE plprof,ONLY: PL_MAG_OLD
    USE wrcalc,ONLY: wrcalk
    IMPLICIT NONE
    INTEGER,PARAMETER:: NSRM=101
    REAL(4):: GX(NSTPMAX+1),GY(NSTPMAX+1)
    REAL(4):: GKX(NSTPMAX+1,NRAYMAX)
    REAL(4):: GKY1(NSTPMAX+1,NRAYMAX),GKY2(NSTPMAX+1,NRAYMAX)
    REAL(4):: GLCX(NSRM),GLCY(NSRM),GSCX(NSRM),GSCY(NSRM)
    INTEGER:: NSRMAX,NSU,NRAY,NSTP
    REAL(4):: GRRMAX,GXMIN,GXMAX,GXSTEP,GYMIN,GYMAX,GYSTEP,GXORG
    REAL(4):: GYMIN1,GYMIN2,GYMAX1,GYMAX2,GYORG
    REAL(rkind):: RMAXL,RMINL,DTH,TH,XL,YL,ZL,RHON,RKPARA,RKPERP

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETLIN(0,2,7)

!     ----- TOROIDAL CROSS SECTION -----

      NSRMAX=101
      RMAXL=RR+RA
      RMINL=RR-RA
      DTH=2*PI/(NSRMAX-1)
      DO NSU=1,NSRMAX
         TH=DTH*(NSU-1)
         GLCX(NSU)=GUCLIP(RMAXL*COS(TH))
         GLCY(NSU)=GUCLIP(RMAXL*SIN(TH))
         GSCX(NSU)=GUCLIP(RMINL*COS(TH))
         GSCY(NSU)=GUCLIP(RMINL*SIN(TH))
      ENDDO
      IF(MOD(MDLWRG,2).EQ.0) THEN
         GRRMAX=GUCLIP(RMAXL)
         CALL GQSCAL(-GRRMAX,GRRMAX,GXMIN,GXMAX,GXSTEP)
         CALL GQSCAL(-GRRMAX,GRRMAX,GYMIN,GYMAX,GYSTEP)
      ELSE
         CALL GQSCAL(GUCLIP(RR-RA),GUCLIP(RR+RA),GXMIN,GXMAX,GXSTEP)
         CALL GQSCAL(GUCLIP(  -RA),GUCLIP(   RA),GYMIN,GYMAX,GYSTEP)
         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
      ENDIF

      CALL GDEFIN(1.7,11.7,1.0,11.0,GXMIN,GXMAX,GYMIN,GYMAX)

      CALL SETLIN(0,2,7)
      CALL GFRAME
      IF(MOD(MDLWRG,2).EQ.0) THEN
         CALL GSCALE(0.0,GXSTEP,0.0,GYSTEP,0.1,9)
         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALE(GXORG,GXSTEP,0.0,GYSTEP,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,2*GYSTEP,NGULEN(2*GYSTEP))
      ENDIF

      CALL SETLIN(0,2,4)
      CALL GPLOTP(GLCX,GLCY,1,NSRMAX,1,0,0,0)
      CALL GPLOTP(GSCX,GSCY,1,NSRMAX,1,0,0,0)

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GX(NSTP+1)=GUCLIP(RAYS(1,NSTP,NRAY))
            GY(NSTP+1)=GUCLIP(RAYS(2,NSTP,NRAY))
         ENDDO
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

!     ----- WAVE NUMBER -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            CALL WRCALK(NSTP,NRAY,RKPARA,RKPERP)
            GKX( NSTP+1,NRAY)=GUCLIP(RHON)
            GKY1(NSTP+1,NRAY)=GUCLIP(RKPARA*VC &
                                   /(2*PI*RAYIN(1,NRAY)*1.D6))
            GKY2(NSTP+1,NRAY)=GUCLIP(RKPERP*VC &
                                   /(2*PI*RAYIN(1,NRAY)*1.D6))
         ENDDO
      ENDDO

      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
      NRAY=1
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN2,GYMAX2)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN2=MIN(GYMIN2,GYMIN)
         GYMAX2=MAX(GYMAX2,GYMAX)
      ENDDO

      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,16.1)
      CALL TEXT('n-para',6)
      CALL GDEFIN(13.7,23.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

      CALL GQSCAL(GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,8.1)
      CALL TEXT('n-perp',6)
      CALL GDEFIN(13.7,23.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

      CALL WRGPRM
      CALL PAGEE

      RETURN
  END SUBROUTINE WRGRFB

!     ***** RADIAL DEPENDENCE 2 *****

  SUBROUTINE WRGRFC

    USE wrcomm
    USE plprof,ONLY:PL_MAG_OLD
    IMPLICIT NONE

    REAL(4):: GKX(NSTPMAX+1,NRAYMAX)
    REAL(4):: GKY(NSTPMAX+1,NRAYMAX)
    INTEGER:: NRAY,NSTP,NRS1,NRS2,NDR,NR,NRDIV
    REAL(4):: GXMIN,GXMAX,GXSTEP
    REAL(4):: GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP,GYORG
    REAL(rkind):: XL,YL,ZL,RHON,RL,RKR,RKZ,RKPHI,RNPHI
    REAL(rkind):: DRHO,SDR,DELPWR,DRAD,RLA,RLAD,ZLA,ZLAD,DRL,DZL
    REAL(rkind):: DRLS,DZLS,DABSS,DRLSN,DZLSN

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETLIN(0,2,7)

!     ----- X AXIS -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            GKX( NSTP+1,NRAY)=GUCLIP(RHON)
         ENDDO
      ENDDO
      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)

!     ----- Fig.1 -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            RL=SQRT(RAYS(1,NSTP,NRAY)**2+RAYS(2,NSTP,NRAY)**2)
            RKR  =( RAYS(4,NSTP,NRAY)*RAYS(1,NSTP,NRAY) &
                   +RAYS(5,NSTP,NRAY)*RAYS(2,NSTP,NRAY))/RL
            GKY( NSTP+1,NRAY)=GUCLIP(RKR)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)

      CALL MOVE(1.7,16.1)
      CALL TEXT('k-R',3)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

!     ----- Fig.2 -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            RKZ  =  RAYS(6,NSTP,NRAY)
            GKY( NSTP+1,NRAY)=GUCLIP(RKZ)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)

      CALL MOVE(13.7,16.1)
      CALL TEXT('k-Z',3)
      CALL GDEFIN(13.7,23.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

!     ----- Fig.3 -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            RL=SQRT(RAYS(1,NSTP,NRAY)**2+RAYS(2,NSTP,NRAY)**2)
            RKPHI=(-RAYS(4,NSTP,NRAY)*RAYS(2,NSTP,NRAY) &
                   +RAYS(5,NSTP,NRAY)*RAYS(1,NSTP,NRAY))/RL
            GKY( NSTP+1,NRAY)=GUCLIP(RKPHI)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)

      CALL MOVE(1.7,8.1)
      CALL TEXT('k-phi',5)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

!     ----- Fig.4 -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            RNPHI=(-RAYS(4,NSTP,NRAY)*RAYS(2,NSTP,NRAY) &
                   +RAYS(5,NSTP,NRAY)*RAYS(1,NSTP,NRAY))
            GKY( NSTP+1,NRAY)=GUCLIP(RNPHI)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)

      CALL MOVE(13.7,8.1)
      CALL TEXT('R*k-phi',7)
      CALL GDEFIN(13.7,23.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

      CALL WRGPRM
      CALL PAGEE
      RETURN
  END SUBROUTINE WRGRFC

!     ***** BEAM AND POWER *****

  SUBROUTINE WRGRFD

    USE wrcomm
    USE libspf,ONLY: erf0
    USE plprof,ONLY: PL_MAG_OLD
    IMPLICIT NONE
    REAL(4):: GPX(NSTPMAX+1),GPY(NSTPMAX+1,NRAYMAX)
    REAL(4):: GKX(NSTPMAX+1,NRAYMAX)
    REAL(4):: GKY(NSTPMAX+1,NRAYMAX)
    REAL(rkind):: FRLRO1(0:NRDIVMAX+1),FZLRO1(0:NRDIVMAX+1)
    REAL(rkind):: FRLRO2(0:NRDIVMAX+1),FZLRO2(0:NRDIVMAX+1)
    REAL(4):: GPAY(NSTPMAX+1,NRAYMAX)
    REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
         RLMA1,ZLMA1,FASSX1,FASSZ1,DELP1, &
         RLMA2,ZLMA2,FASSX2,FASSZ2,DELP2
    INTEGER:: NRAY,NSTP,NRDIV,NRS1,NDR,NR,NRS2
    REAL(4):: GXMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP
    REAL(4):: GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP
    REAL(4):: GYMINA,GYMAXA,GYMINB,GYMAXB,GYSMIN,GYSMAX1,GYSCAL1
    REAL(4):: GYSMAX2,GYSMAX,GYSCAL,GYSCAL2
    REAL(rkind):: XL,YL,ZL,RHON,DRHO,RHON1,RHON2,SDR,DELPWR
    REAL(rkind):: DRAD,RLA,RLAD,ZLA,ZLAD,DRL,DZL,DRLS,DZLS,DABSS
    REAL(rkind):: RLDMAX1,ZLDMAX1,PHIL,BR,BZ,BPHI
    REAL(rkind):: RHOMIN1,RHOMAX1,RL1,ZL1,RLD1,ZLD1,SLD1,RHOD1,DRLSN,DZNLS
    REAL(rkind):: SIGMA,DRLT,DZLT,DABST,DRLTN,DZLTN,RLDMAX2,ZLDMAX2
    REAL(rkind):: RHOMAX2,RHOMIN2,RL2,ZL2,RLD2,ZLD2,RHOD2,DZLSN
    INTEGER:: NRSMIN1,NRSMAX1,NDBRD1,NABSM1,NRSA1,NCS,NRSMAX2,NRSMIN2
    INTEGER:: NDBRD2,NABSM2,NRSA2,NRSDA1,NRSDA2,NCS2

      ALLOCATE(RLMA1(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(RLMA2(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(ZLMA1(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(ZLMA2(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(FASSX1(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(FASSX2(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(FASSZ1(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(FASSZ2(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(DELP1(0:NSTPMAX+1,0:NRDIVMAX))
      ALLOCATE(DELP2(0:NSTPMAX+1,0:NRDIVMAX))

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!     ----- X AXIS -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            GKX( NSTP+1,NRAY)=GUCLIP(RHON)
         ENDDO
      ENDDO

      CALL GMNMX1(GKX,1,NSTPMAX_NRAY(1),1,GXMIN1,GXMAX1)
      CALL GQSCAL(0.0,GXMAX1,GXMIN,GXMAX,GXSTEP)

!     ----- Fig.1  R-CURV-----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY( NSTP+1,1)=GUCLIP(RAYB(21,NSTP))
            GKY( NSTP+1,2)=GUCLIP(RAYB(22,NSTP))
         ENDDO
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
!     CALL SETLNW(0.035)
      CALL SETLIN(0,2,7)
      CALL MOVE(1.7,16.1)
      CALL TEXT('R-curv',6)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-6.0,6.0)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,2.0,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2.0,1)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)

!     ----- Fig.2   R-BEAM-----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY( NSTP+1,1)=GUCLIP(RAYB(23,NSTP))
            GKY( NSTP+1,2)=GUCLIP(RAYB(24,NSTP))
         ENDDO
      ENDDO

      CALL MOVE(1.7,8.1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL TEXT('R-beam',6)
      CALL GMNMX1(GKY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
      CALL GMNMX1(GKY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)
      GYMIN1=MIN(GYMINA,GYMINB)
      GYMAX1=MAX(GYMAXA,GYMAXB)     
      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
!      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,0.0,0.10)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.01,0.1,9)
!      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
!      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,2)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)

!      CALL MOVE(9.0,16.4)
!      CALL TEXT ('X1= ',3)
!      CALL NUMBR(GKX(K,1),'(F5.3)',5)
!      CALL MOVE(5.0,16.4)
!      CALL TEXT ('dMIN1= ',6)
!      CALL NUMBR(GKY(K,1),'(F9.7)',9)

!      CALL MOVE(9.0,16.0)
!      CALL TEXT ('X2= ',3)
!      CALL NUMBR(GKX(K,1),'(F5.3)',5)
!      CALL MOVE(5.0,16.0)
!      CALL TEXT ('dMIN2= ',6)
!      CALL NUMBR(GKY(K,2),'(F9.7)',9)

      CALL MOVE(1.0,16.4)
      CALL TEXT ('SMAX= ',6)
      CALL NUMBD(smax,'(F5.2)',5)
      CALL MOVE(11.0,16.0)
      CALL TEXT ('RCURV= ',6)
      CALL NUMBD(RCURVA,'(F5.2)',5)
      CALL MOVE(11.0,16.4)
      CALL TEXT ('RBRAD= ',6)
      CALL NUMBD(RBRADA,'(F5.2)',5)

!     ----- Fig.3  Beam-Rot -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY(NSTP+1,1)=GUCLIP(RAYB(25,NSTP))
            GKY(NSTP+1,2)=GUCLIP(RAYB(26,NSTP))
         ENDDO
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLIN(0,2,7)
      CALL MOVE(13.5,16.1)
      CALL TEXT('Beam-rot',8) 
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,0.0,180.0)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.0,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,1)
      CALL GSCALE(0.0,0.0,0.0,30.0,0.1,9)
      CALL GVALUE(0.0,0.0,0.0,30.0,0)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)

!     -------------------------------------------------------------------
!     ----- CALCULATE RADIAL DEPOSITION PROFILE (without beam radial)----
!     -------------------------------------------------------------------
      DRHO=1.D0/NRDIVMAX
      DO NRDIV=1,NRDIVMAX
         GPX(NRDIV)=GUCLIP(NRDIV*DRHO)
      ENDDO
      DO NRAY=1,NRAYMAX
         DO NRDIV=1,NRDIVMAX
            GPY(NRDIV,NRAY)=0.0
         ENDDO
      ENDDO

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)-1
            CALL pl_mag_old(RAYS(1,NSTP,NRAY),RAYS(2,NSTP,NRAY)**2, &
                            RAYS(3,NSTP,NRAY),RHON1)
	    NRS1=INT(RHON1/DRHO)+1
            CALL pl_mag_old(RAYS(1,NSTP+1,NRAY),RAYS(2,NSTP+1,NRAY)**2, &
                            RAYS(3,NSTP+1,NRAY),RHON2)
            NRS2=INT(RHON2/DRHO)+1
            NDR=ABS(NRS2-NRS1)

            IF(NDR.EQ.0) THEN
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)+GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE IF(NRS1.LT.NRS2) THEN
               SDR=(RHON2-RHON1)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                             +GUCLIP((REAL(NRS1)-RHON1/DRHO)*DELPWR)
               DO NR=NRS1+1,NRS2-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                             +GUCLIP((RHON2/DRHO-DBLE(NRS2-1))*DELPWR)
            ELSE
               SDR=(RHON1-RHON2)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                             +GUCLIP((REAL(NRS2)-RHON2/DRHO)*DELPWR)
               DO NR=NRS2+1,NRS1-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                            +GUCLIP((RHON1/DRHO-DBLE(NRS1-1))*DELPWR)
            ENDIF
         ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO

      DO NRAY=1,NRAYMAX
      DO NRDIV=1,NRDIVMAX
         GPY(NRDIV,NRAY)=GPY(NRDIV,NRAY) &
                        /GUCLIP(2*PI*(DBLE(NRDIV)-0.5D0)*DRHO*DRHO)
      ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO

!     -------------------------------------------------------------------
!     ----- CALCULATE RADIAL DEPOSITION PROFILE (with beam radial)-------
!     -------------------------------------------------------------------

      IF (MODELG.EQ.3.OR.MODELG.EQ.5.OR.MODELG.EQ.8) THEN
         DRHO=1.D0/NRDIVMAX  
         DO NRAY=1,NRAYMAX
            DO NRDIV=1,NRDIVMAX
               GPX (NRDIV)=GUCLIP(NRDIV*DRHO)
               GPAY(NRDIV,NRAY)=0.0
            ENDDO
         ENDDO

         DO NRAY=1,NRAYMAX
            DO NSTP=0,NSTPMAX_NRAY(NRAY)-1
               DRAD=1.D0/DBLE(NRDIVMAX)

!     ----- CALC SLOPE OF RAY TRAJECTORY-----------------------

               RLA =SQRT(RAYS(1,NSTP,NRAY)**2+RAYS(2,NSTP,NRAY)**2)
               RLAD=SQRT(RAYS(1,NSTP+1,NRAY)**2+RAYS(2,NSTP+1,NRAY)**2)
               ZLA =RAYS(3,NSTP ,NRAY)
               ZLAD=RAYS(3,NSTP+1,NRAY)
               DRL=RLAD-RLA
               DZL=ZLAD-ZLA
!        ---------------------------------------------------------

!        -----(i)ROTATE DRL and DZL (90 Degree)-------------------
               DRLS=-DZL
               DZLS= DRL
               DABSS=SQRT(DRLS**2+DZLS**2)
               DRLSN=DRLS/DABSS
               DZLSN=DZLS/DABSS
!        ---------------------------------------------------------

!        ----- JUDGE MAGNETIC SURFACE-----------------------------
               DO NRDIV=0,NRDIVMAX
                  FRLRO1(NRDIV)=RLA+NRDIV*DRAD*DRLSN*RAYB(23,NSTP)
                  FZLRO1(NRDIV)=ZLA+NRDIV*DRAD*DZLSN*RAYB(23,NSTP)
               ENDDO

!            ------ BEAM RADIAL DIRECTION ----------------

               RLDMAX1=FRLRO1(NRDIVMAX)
               ZLDMAX1=FZLRO1(NRDIVMAX)
               CALL GETRZ(RLDMAX1,ZLDMAX1,PHIL,BR,BZ,BPHI,RHOMAX1)
               NRSMAX1=INT(RHOMAX1/DRHO)+1
               CALL GETRZ(RLA,ZLA,PHIL,BR,BZ,BPHI,RHOMIN1)
               NRSMIN1=INT(RHOMIN1/DRHO)+1
               NDBRD1=(NRSMAX1-NRSMIN1)
               NABSM1=ABS(NDBRD1)

               
           DO NRDIV=0,NRDIVMAX-1
               RL1=FRLRO1(NRDIV)
               ZL1=FZLRO1(NRDIV)
               CALL GETRZ(RL1,ZL1,PHIL,BR,BZ,BPHI,RHON1)
!               WRITE(6,'(A,1P3E12.4)') 'RL1: ',RL1,ZL1,RHON1
               NRSA1=INT(RHON1/DRHO)+1

               RLD1=FRLRO1(NRDIV+1)
               ZLD1=FZLRO1(NRDIV+1)
               CALL GETRZ(RLD1,ZLD1,PHIL,BR,BZ,BPHI,RHOD1)
!               WRITE(6,'(A,1P3E12.4)') 'RLD1: ',RLD1,ZLD1,RHOD1
               NRSDA1=INT(RHOD1/DRHO)+1

                IF (NRSDA1.NE.NRSA1) THEN
                   RLMA1(NSTP,ABS(NRSDA1-NRSMIN1))=RL1
                   ZLMA1(NSTP,ABS(NRSDA1-NRSMIN1))=ZL1
                ENDIF
            ENDDO
!           
            IF (NDBRD1.EQ.0) THEN
               GPAY(NRSMIN1,NRAY)=GPAY(NRSMIN1,NRAY) &
                                 +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE IF (NDBRD1.LT.0) THEN 
               RLMA1(NSTP,0)=RLA
               ZLMA1(NSTP,0)=ZLA
               DO NCS=1,NABSM1
               SIGMA=RAYB(23,NSTP)/3.D0
!               SIGMA=5.D0*RAYB(23,NSTP)
               FASSX1(NSTP,NCS)=SQRT((RLMA1(NSTP,NCS)-RLA)**2 &
                               +(ZLMA1(NSTP,NCS)-ZLA)**2)
!               FASSZ1(NSTP,NCS)=FASSX1(NSTP,NCS)/RAYB(23,NSTP)
               FASSZ1(NSTP,NCS)=FASSX1(NSTP,NCS)/SIGMA
               DELP1(NSTP,NCS)=ERF0(FASSZ1(NSTP,NCS)) &
                              -ERF0(FASSZ1(NSTP,NCS-1))
!               WRITE(6,*) DELP1(NSTP,NCS)
               GPAY(NRSMIN1-NCS+1,NRAY)=GPAY(NRSMIN1-NCS+1,NRAY) &
                    +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY)*DELP1(NSTP,NCS))
               ENDDO
               GPAY(NRSMAX1,NRAY)=GPAY(NRSMAX1,NRAY) &
                    +GUCLIP(0.5D0-0.5D0*ERF0(FASSZ1(NSTP,NABSM1))) &
                    *GUCLIP(RAYS(8,NSTP+1,NRAY))
!             
            ELSE 
               RLMA1(NSTP,0)=RLA
               ZLMA1(NSTP,0)=ZLA
               DO NCS=1,NABSM1
               SIGMA=RAYB(23,NSTP)/3.D0
               FASSX1(NSTP,NCS)=SQRT((RLMA1(NSTP,NCS)-RLA)**2 &
                               +(ZLMA1(NSTP,NCS)-ZLA)**2)
!               FASSZ1(NSTP,NCS)=FASSX1(NSTP,NCS)/RAYB(23,NSTP)
               FASSZ1(NSTP,NCS)=FASSX1(NSTP,NCS)/SIGMA
               DELP1(NSTP,NCS)=ERF0(FASSZ1(NSTP,NCS)) &
                              -ERF0(FASSZ1(NSTP,NCS-1))
!               WRITE(6,*) DELP1(NSTP,NCS)
               GPAY(NRSMIN1+NCS-1,NRAY)=GPAY(NRSMIN1+NCS-1,NRAY) &
                    +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY)*DELP1(NSTP,NCS))
               ENDDO
               GPAY(NRSMAX1,NRAY)=GPAY(NRSMAX1,NRAY) &
                    +0.5*GUCLIP(1.0D0-ERF0(FASSZ1(NSTP,NABSM1))) &
                    *GUCLIP(RAYS(8,NSTP+1,NRAY))
            ENDIF
            
!      ------------------------------------------------------

!      -----(ii)ROTATE DRLS and DZLS (-90 Degree)
            DRLT= DZL
            DZLT=-DRL
            DABST=SQRT(DRLT**2+DZLT**2)
            DRLTN=DRLT/DABST
            DZLTN=DZLT/DABST
!      ------------------------------------------------------

!      ------ JUDGE MAGNETIC SURFACE ------------------------
            DO NRDIV=0,NRDIVMAX
               FRLRO2(NRDIV)=RLA+NRDIV*DRAD*DRLTN*RAYB(23,NSTP)
               FZLRO2(NRDIV)=ZLA+NRDIV*DRAD*DZLTN*RAYB(23,NSTP)
            ENDDO

               RLDMAX2=FRLRO2(NRDIVMAX)
               ZLDMAX2=FZLRO2(NRDIVMAX)
               CALL GETRZ(RLDMAX2,ZLDMAX2,PHIL,BR,BZ,BPHI,RHOMAX2)
!               WRITE(6,'(A,1P3E12.4)') 'RLD: ',RLDMAX2,ZLDMAX2,RHOMAX2
               NRSMAX2=INT(RHOMAX2/DRHO)+1
               CALL GETRZ(RLA,ZLA,PHIL,BR,BZ,BPHI,RHOMIN2)
!               WRITE(6,'(A,1P3E12.4)') 'RLA: ',RLA,ZLA,RHOMIN2
               NRSMIN2=INT(RHOMIN2/DRHO)+1
               NDBRD2=(NRSMAX2-NRSMIN2)
               NABSM2=ABS(NDBRD2)

            DO NRDIV=0,NRDIVMAX-1
               RL2=FRLRO2(NRDIV)
               ZL2=FZLRO2(NRDIV)
               CALL GETRZ(RL2,ZL2,PHIL,BR,BZ,BPHI,RHON2)
!              WRITE(6,'(A,1P3E12.4)') 'RL2: ',RL2,ZL2,RHON2
               NRSA2=INT(RHON2/DRHO)+1

               RLD2=FRLRO2(NRDIV+1)
               ZLD2=FZLRO2(NRDIV+1)
               CALL GETRZ(RLD2,ZLD2,PHIL,BR,BZ,BPHI,RHOD2)
!               WRITE(6,'(A,1P3E12.4)') 'RL2D:',RLD2,ZLD2,RHOD2
               NRSDA2=INT(RHOD2/DRHO)+1
!            
               IF (NRSDA2.NE.NRSA2) THEN
                     RLMA2(NSTP,ABS(NRSDA2-NRSMIN2))=RL2
                     ZLMA2(NSTP,ABS(NRSDA2-NRSMIN2))=ZL2
               ENDIF
            ENDDO
! 
            IF (NDBRD2.EQ.0) THEN
               GPAY(NRSMIN2,NRAY)=GPAY(NRSMIN2,NRAY) &
                                 +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE IF (NDBRD2.LT.0) THEN
               RLMA2(NSTP,0)=RLA
               ZLMA2(NSTP,0)=ZLA
               DO NCS2=1,NABSM2
               SIGMA=RAYB(23,NSTP)/3.D0
!               SIGMA=5.D0*RAYB(23,NSTP)
               FASSX2(NSTP,NCS2)=SQRT((RLMA2(NSTP,NCS2)-RLA)**2 &
                                +(ZLMA2(NSTP,NCS2)-ZLA)**2)
!               FASSZ2(NSTP,NCS2)=FASSX2(NSTP,NCS2)/RAYB(23,NSTP)
               FASSZ2(NSTP,NCS2)=FASSX2(NSTP,NCS2)/SIGMA
               DELP2(NSTP,NCS2)=ERF0(FASSZ2(NSTP,NCS2)) &
                               -ERF0(FASSZ2(NSTP,NCS2-1))
               GPAY(NRSMIN2-NCS2+1,NRAY)=GPAY(NRSMIN2-NCS2+1,NRAY) &
                    +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY)*DELP2(NSTP,NCS2))
               ENDDO
               GPAY(NRSMAX2,NRAY)=GPAY(NRSMAX2,NRAY) &
                    +(0.5-0.5*GUCLIP(ERF0(FASSZ2(NSTP,NABSM2)))) &
                    *GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE
               RLMA2(NSTP,0)=RLA
               ZLMA2(NSTP,0)=ZLA
               DO NCS2=1,NABSM2
               SIGMA=RAYB(23,NSTP)/3.D0
!                SIGMA=5.D0*RAYB(23,NSTP)
               FASSX2(NSTP,NCS2)=SQRT((RLMA2(NSTP,NCS2)-RLA)**2 &
                                +(ZLMA2(NSTP,NCS2)-ZLA)**2)
!               FASSZ2(NSTP,NCS2)=FASSX2(NSTP,NCS2)/RAYB(23,NSTP)
                FASSZ2(NSTP,NCS2)=FASSX2(NSTP,NCS2)/SIGMA
               DELP2(NSTP,NCS2)=ERF0(FASSZ2(NSTP,NCS2)) &
                               -ERF0(FASSZ2(NSTP,NCS2-1))
               GPAY(NRSMIN2+NCS2-1,NRAY)=GPAY(NRSMIN2+NCS2-1,NRAY) &
                    +0.5*GUCLIP(RAYS(8,NSTP+1,NRAY)*DELP2(NSTP,ncs2))
               ENDDO
               GPAY(NRSMAX2,NRAY)=GPAY(NRSMAX2,NRAY) &
                    +(0.5-0.5*GUCLIP(ERF0(FASSZ2(NSTP,NABSM2)))) &
                    *GUCLIP(RAYS(8,NSTP+1,NRAY))
            ENDIF
         ENDDO
      ENDDO


      DO NRAY=1,NRAYMAX
         DO NRDIV=1,NRDIVMAX
            GPAY(NRDIV,NRAY)=GPAY(NRDIV,NRAY) &
                            /GUCLIP(2*PI*(DBLE(NRDIV)-0.5D0)*DRHO*DRHO)
         ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPAY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO
      ENDIF
!     -----Fig.4 draw deposition profile -----

      IF(MOD(MDLWRG/2,2).EQ.0) THEN
         CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
      ELSE
         CALL GQSCAL(GUCLIP(RHOGMN),GUCLIP(RHOGMX),GXMIN,GXMAX,GXSTEP)
      ENDIF
!
      CALL GMNMX2(GPY,NSTPMAX+1,1,NRDIVMAX,1,1,NRAYMAX,1,GYMIN,GYMAX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMIN,GYSMAX1,GYSCAL1)
      GYSMIN=0.0
      GYSMAX2=0.1 
      GYSCAL2=2.E-2
      GYSMAX=MAX(GYSMAX1,GYSMAX2)
      GYSCAL=MAX(GYSCAL1,GYSCAL2)

      CALL MOVE(13.5,8.1)
      CALL TEXT('ABS POWER',10)
!      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,GYSMIN,GYSMAX)
      CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,GYSMIN,GYSMAX)
      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME
      CALL GSCALE(GXMIN,GXSTEP,GYSMIN,GYSCAL,0.1,9)      
      CALL GVALUE(GXMIN,2*GXSTEP,GYSMIN,GYSCAL,2)
!      CALL SETLIN(0,0,4)
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GPX,GPY(1,NRAY),1,NRDIVMAX,1,0,0,0)
         CALL SETRGB(0.0,0.0,0.0)
      ENDDO

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,2,7-MOD(NRAY,5))
         CALL GPLOTP(GPX,GPAY(1,NRAY),1,NRDIVMAX,1,0,0,0)
         CALL SETRGB(1.0,0.0,0.0)
      ENDDO     
      DEALLOCATE(RLMA1)
      DEALLOCATE(RLMA2)
      DEALLOCATE(ZLMA1)
      DEALLOCATE(ZLMA2)
      DEALLOCATE(FASSX1)
      DEALLOCATE(FASSX2)
      DEALLOCATE(FASSZ1)
      DEALLOCATE(FASSZ2)
      DEALLOCATE(DELP1)
      DEALLOCATE(DELP2)

      CALL WRGPRM
      CALL PAGEE
      RETURN
    END SUBROUTINE WRGRFD

!     ***** Rays ***********
      SUBROUTINE WRGRFE

      USE wrcomm
      USE plprof,ONLY:PL_MAG_OLD
      IMPLICIT NONE
      REAL(4):: GSX (NSTPMAX+1,NRAYM),GRX (NSTPMAX+1,NRAYM)
      REAL(4):: GKY1(NSTPMAX+1,NRAYM),GKY2(NSTPMAX+1,NRAYM)
      INTEGER:: NRAY,NSTP
      REAL(4):: GXMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP
      REAL(4):: GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP,GYMIN2,GYMAX2
      REAL(rkind):: XL,YL,ZL,RHON

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!    ------- X Axis (direction along ray reference)-------

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GSX(NSTP+1,NRAY)=GUCLIP(RAYS(0,NSTP,NRAY))
         ENDDO
         CALL GMNMX1(GSX(1,1),1,NSTPMAX_NRAY(1),1,GXMIN1,GXMAX1)
         CALL GMNMX1(GSX(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GXMIN,GXMAX)
         GXMAX1=MAX(GXMAX1,GXMAX)
      ENDDO

      CALL GQSCAL(0.0,GXMAX1,GXMIN,GXMAX,GXSTEP)

!      ------ NRAY BEAM WIDTH 1 -------
      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY1(NSTP+1,NRAY)=GUCLIP(RAYRB1(NSTP,NRAY))
         ENDDO
         CALL GMNMX1(GKY1(1,1),1,NSTPMAX_NRAY(1),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMAX1=MAX(GYMAX1,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
      ENDDO

      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(1.7,16.1)
      CALL TEXT('S-Beam1',7)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,0.0,GYMAX)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2*GYSTEP,2)


      DO NRAY=1,NRAYM
      CALL SETLIN(0,2,7-MOD(NRAY-1,5))
      CALL GPLOTP(GSX(1,NRAY),GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

!            ------ NRAY BEAM WIDTH 2 -------
      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY2(NSTP+1,NRAY)=GUCLIP(RAYRB2(NSTP,NRAY))
         ENDDO
         CALL GMNMX1(GKY2(1,1),1,NSTPMAX_NRAY(1),1,GYMIN2,GYMAX2)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMAX2=MAX(GYMAX2,GYMAX)
         GYMIN2=MIN(GYMIN2,GYMIN)
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
      CALL GQSCAL(GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.5,16.1)
      CALL TEXT('S-Beam2',7)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,0.0,GYMAX)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2*GYSTEP,2)

      DO NRAY=1,NRAYM
      CALL SETLIN(0,2,7-MOD(NRAY-1,5))
      CALL GPLOTP(GSX(1,NRAY),GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
!   
!    ------- X Axis (radial direction)-------

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            GRX(NSTP+1,NRAY)=GUCLIP(RHON)
         ENDDO
         CALL GMNMX1(GRX(1,1),1,NSTPMAX_NRAY(1),1,GXMIN1,GXMAX1)
         CALL GMNMX1(GRX(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GXMIN,GXMAX)
         GXMAX1=MAX(GXMAX1,GXMAX)
      ENDDO

      CALL GQSCAL(0.0,GXMAX1,GXMIN,GXMAX,GXSTEP)
      

!     ------ NRAY BEAM WIDTH1 ----------------

      CALL SETRGB(0.0,0.0,0.0)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(1.7,8.1)
      CALL TEXT('R-Beam1',7)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,0.0,GYMAX)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2*GYSTEP,2)

      DO NRAY=1,NRAYM
      CALL SETLIN(0,2,7-MOD(NRAY-1,5))
      CALL GPLOTP(GRX(1,NRAY),GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

!     ------ NRAY BEAM WIDTH2 ----------------

      CALL SETRGB(0.0,0.0,0.0)
      CALL GQSCAL(GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.5,8.1)
      CALL TEXT('R-Beam2',7)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,0.0,GYMAX)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2*GYSTEP,2)

      DO NRAY=1,NRAYM
      CALL SETLIN(0,2,7-MOD(NRAY-1,5))
      CALL GPLOTP(GRX(1,NRAY),GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO

      CALL PAGEE
      RETURN
    END SUBROUTINE WRGRFE

!     ***** ANGLE AND WS(I,J) *****

      SUBROUTINE WRGRFF

      USE wrcomm
      USE plprof,ONLY:PL_MAG_OLD
      IMPLICIT NONE
      REAL(4):: GKX(NSTPMAX+1,1),GKY(NSTPMAX+1,2)
      REAL(4):: GKSY(NSTPMAX+1,6),GKPY(NSTPMAX+1,6)
      REAL(4):: GTHY(NSTPMAX+1,1)
      INTEGER:: NRAY,NSTP,N
      REAL(rkind):: Xl,YL,ZL,RHON
      REAL(4):: GXMIN,GXMAX,GXSTEP
      REAL(4):: GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!     ----- X AXIS -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            GKX( NSTP+1,NRAY)=GUCLIP(RHON)
         ENDDO
      ENDDO

!      CALL GMNMX1(GKX,1,NSTPMAX_NRAY(1),1,GXMIN1,GXMAX1)
!      CALL GQSCAL(GKMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP) 
!      CALL GQSCAL(3.0,4.0,GXMIN,GXMAX,GXSTEP)
       CALL GQSCAL(0.0,4.0,GXMIN,GXMAX,GXSTEP)

!     ----- Fig.1  WS-----

      DO NRAY=1,NRAYMAX         
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            DO N=1,6
            GKSY(NSTP+1,N)=GUCLIP(RAYB(25+N,NSTP))
            ENDDO
         ENDDO
      ENDDO

      CALL GMNMX1(GKSY(1,1),1,NSTPMAX_NRAY(1),1,GYMIN1,GYMAX1)

      DO N=2,6
       CALL GMNMX1(GKSY(1,N),1,NSTPMAX_NRAY(1),1,GYMIN,GYMAX)
       GYMIN1=MIN(GYMIN1,GYMIN)
       GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(1.7,16.1)
      CALL TEXT('X-WS',6)
!      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-40.0,40.0)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL GFRAME
!      CALL GSCALE(0.0,GXSTEP,0.0,5.0,0.1,9)
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
      CALL SETRGB(0.0,0.0,1.0)

      DO N=1,6
      CALL GPLOTP(GKX,GKSY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETLIN(0,0,N)
      ENDDO
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!    
!     
!     
!      


!     ------Fig2  WP-------
!   
!    
      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            DO N=1,6
            GKPY( NSTP+1,N)=GUCLIP(RAYB(31+N,NSTP))
            ENDDO
         ENDDO
      ENDDO

      CALL GMNMX1(GKPY(1,1),1,NSTPMAX_NRAY(1),1,GYMIN1,GYMAX1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

      DO N=2,6
       CALL GMNMX1(GKPY(1,N),1,NSTPMAX_NRAY(1),1,GYMIN,GYMAX)
       GYMIN1=MIN(GYMIN1,GYMIN)
       GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO

      CALL MOVE(1.7,8.1)
      CALL TEXT('X-WP',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
!       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
!      
      DO N=1,6
      CALL GPLOTP(GKX,GKPY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETLIN(0,0,N)
      ENDDO

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!     ----- Fig.3   Angle-----

      DO NRAY=1,NRAYMAX         
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GTHY( NSTP+1,1)=GUCLIP(RAYB(25,NSTP))
         ENDDO
      ENDDO

!      CALL GMNMX1(GTHY(1,1),1,NSTPMAX_NRAY(1),1,GYMIN1,GYMAX1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
!      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.5,16.1)
      CALL TEXT('Angle',6)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,-40.0,40.0)
!      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,GYMIN1,GYMAX1)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,5.0,0.1,9)
!      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
!      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
       CALL GVALUE(0.0,2*GXSTEP,0.0,10.0,1)
      CALL SETRGB(0.0,0.0,1.0)

      CALL GPLOTP(GKX,GTHY(1,1),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!    
!     
!     
!      



!     -------fig4  LAMDA------------------------

            DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
!            GKY( NSTP+1,1)=GUCLIP(RAYB(47,NSTP))
!            GKY( NSTP+1,2)=GUCLIP(RAYB(48,NSTP))
            GKY( NSTP+1,1)=GUCLIP(RAYB(20,NSTP))
         ENDDO
      ENDDO

      CALL GMNMX1(GKY(1,1),1,NSTPMAX_NRAY(1),1,GYMIN1,GYMAX1)
!      CALL GMNMX1(GKY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
!      CALL GMNMX1(GKY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)

!      GYMIN1=MIN(GYMINA,GYMINB)
!      GYMAX1=MAX(GYMAXA,GYMAXB)
      CALL MOVE(13.5,8.1)
!      CALL TEXT('LAMDA',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
!      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
!      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
      CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,GYMIN,GYMAX)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(GXMIN,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(GXMIN,2*GXSTEP,GYMIN,GYSTEP,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
!      
      CALL GPLOTP(GKX,GKY(1,1),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL GPLOTP(GKX,GKY(1,2),1,NSTPMAX_NRAY(1)+1,1,0,0,0)
      CALL SETLIN(0,0,7)

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
      CALL WRGPRM
      CALL PAGEE
      RETURN
    END SUBROUTINE WRGRFF

!     ***** K,(K*B),K*(K*B),VG *****

      SUBROUTINE WRGRFG

      USE wrcomm
      IMPLICIT NONE
      REAL(4):: GKX(NSTPMAX+1,1)
      REAL(4):: GKY(NSTPMAX+1,3),GKBY(NSTPMAX+1,3),GKKBY(NSTPMAX+1,3)
      REAL(4):: GVGY(NSTPMAX+1,3)
      INTEGER:: NRAY,NSTP,N
      REAL(4):: GXMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP
!      REAL(4):: GYMNINA,GYMAXA,GYMINB,GYMAXB,GYMINC,GYMAXC
!      REAL(4):: GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!     ----- X AXIS -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKX( NSTP+1,NRAY)=GUCLIP(RAYB(0,NSTP))
         ENDDO
      ENDDO

      CALL GMNMX1(GKX,1,NSTPMAX_NRAY(1),1,GXMIN1,GXMAX1)
      CALL GQSCAL(GXMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP) 

!     ------fig 1  K----------

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKY( NSTP+1,1)=GUCLIP(RAYB(38,NSTP))
            GKY( NSTP+1,2)=GUCLIP(RAYB(39,NSTP))
            GKY( NSTP+1,3)=GUCLIP(RAYB(40,NSTP))
         ENDDO
      ENDDO
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!      CALL GMNMX1(GKY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
!      CALL GMNMX1(GKY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)
!      CALL GMNMX1(GKY(1,3),1,NSTPMAX_NRAY(1),1,GYMINC,GYMAXC)

!      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
!      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(1.7,16.1)
      CALL TEXT('K',6)
!      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-1.2,1.2)
!       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.1,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.2,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)

      DO N=1,3
        CALL GPLOTP(GKX,GKY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!     ------fig 2 K*B---------

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKBY( NSTP+1,1)=GUCLIP(RAYB(41,NSTP))
            GKBY( NSTP+1,2)=GUCLIP(RAYB(42,NSTP))
            GKBY( NSTP+1,3)=GUCLIP(RAYB(43,NSTP))
         ENDDO
      ENDDO
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!      CALL GMNMX1(GKBY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
!      CALL GMNMX1(GKBY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)
!      CALL GMNMX1(GKBY(1,3),1,NSTPMAX_NRAY(1),1,GYMINC,GYMAXC)

!      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
!      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(1.7,8.1)
      CALL TEXT('K*B',6)
!      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-1.2,1.2)
!       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.1,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.2,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)

      DO N=1,3
        CALL GPLOTP(GKX,GKBY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!     ------fig 3 K*(K*B)-----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GKKBY( NSTP+1,1)=GUCLIP(RAYB(44,NSTP))
            GKKBY( NSTP+1,2)=GUCLIP(RAYB(45,NSTP))
            GKKBY( NSTP+1,3)=GUCLIP(RAYB(46,NSTP))
         ENDDO
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)

!      CALL GMNMX1(GKKBY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
!      CALL GMNMX1(GKKBY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)
!      CALL GMNMX1(GKKBY(1,3),1,NSTPMAX_NRAY(1),1,GYMINC,GYMAXC)

!      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
!      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(13.5,16.1)
      CALL TEXT('K*(K*B)',6)
!      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,-1.2,1.2)
!       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.1,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.2,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)

      DO N=1,3
        CALL GPLOTP(GKX,GKKBY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)

!     ------fig 4 VG ---------

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GVGY( NSTP+1,1)=GUCLIP(RAYB(49,NSTP))
            GVGY( NSTP+1,2)=GUCLIP(RAYB(50,NSTP))
            GVGY( NSTP+1,3)=GUCLIP(RAYB(51,NSTP))
         ENDDO
      ENDDO

      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
!      CALL GMNMX1(GVGY(1,1),1,NSTPMAX_NRAY(1),1,GYMINA,GYMAXA)
!      CALL GMNMX1(GVGY(1,2),1,NSTPMAX_NRAY(1),1,GYMINB,GYMAXB)
!      CALL GMNMX1(GVGY(1,3),1,NSTPMAX_NRAY(1),1,GYMINC,GYMAXC)

!      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
!      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(13.5,8.1)
      CALL TEXT('VG',6)
!      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,-1.2,1.2)
!       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
!      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.1,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.2,1)
!      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)

      DO N=1,3
        CALL GPLOTP(GKX,GVGY(1,N),1,NSTPMAX_NRAY(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  

      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
      CALL WRGPRM
      CALL PAGEE 
      RETURN
    END SUBROUTINE WRGRFG

!     ***** DRAW PARAMETERS *****

    SUBROUTINE WRGPRM

      USE wrcomm
      IMPLICIT NONE

!     ----- DRAW PARAMETERS -----

      CALL SETLIN(0,0,7)
      CALL WRPRMT(1.0,18.0, 'BB   =',6, BB  ,'(F8.3)',8)
      CALL WRPRMT(1.0,17.6, 'RR   =',6, RR  ,'(F8.3)',8)
      CALL WRPRMT(1.0,17.2, 'RA   =',6, RA  ,'(F8.3)',8)
      CALL WRPRMT(1.0,16.8, 'RKAP =',6, RKAP,'(F8.3)',8)
      CALL WRPRMT(5.0,18.0, 'Q0   =',6, Q0  ,'(F8.3)',8)
      CALL WRPRMT(5.0,17.6, 'QA   =',6, QA  ,'(F8.3)',8)
      CALL WRPRMT(5.0,17.2, 'RF =',  4, RF  ,'(1PE10.3)',10)
      CALL WRPRMT(5.0,16.8, 'NPHII=',6,RNPHII,'(F8.4)',8)
      CALL WRPRMT(9.0,18.0, 'PA(1)  =',8,PA(1),'(F8.4)',8)
      CALL WRPRMT(9.0,17.6, 'PZ(1)  =',8,PZ(1),'(F8.4)',8)
      CALL WRPRMT(9.0,17.2, 'PN(1)  =',8,PN(1),'(F8.4)',8)
      CALL WRPRMT(9.0,16.8, 'PNS(1) =',8,PNS(1),'(F8.4)',8)
      CALL WRPRMT(13.0,18.0,'PTPR(1)=',8,PTPR(1),'(F8.4)',8)
      CALL WRPRMT(13.0,17.6,'PTPP(1)=',8,PTPP(1),'(F8.4)',8)
      CALL WRPRMT(13.0,17.2,'PTS(1) =',8,PTS(1),'(F8.4)',8)
      CALL WRPRMT(13.0,16.8,'MODELP1=',8,DBLE(MODELP(1)),'(F4.0)',4)
      CALL WRPRMT(17.0,18.0,'PA(2)  =',8,PA(2),'(F8.4)',8)
      CALL WRPRMT(17.0,17.6,'PZ(2)  =',8,PZ(2),'(F8.4)',8)
      CALL WRPRMT(17.0,17.2,'PN(2)  =',8,PN(2),'(F8.4)',8)
      CALL WRPRMT(17.0,16.8,'PNS(2)= ',8,PNS(2),'(F8.4)',8)
      CALL WRPRMT(21.0,18.0,'PTPR(2)=',8,PTPR(2),'(F8.4)',8)
      CALL WRPRMT(21.0,17.6,'PTPP(2)=',8,PTPP(2),'(F8.4)',8)
      CALL WRPRMT(21.0,17.2,'PTS(2) =',8,PTS(2),'(F8.4)',8)
      CALL WRPRMT(21.0,16.8,'MODELP2=',8,DBLE(MODELP(2)),'(F4.0)',4)
      CALL PAGEE
      RETURN
    END SUBROUTINE WRGPRM

!***********************************************************************

    SUBROUTINE WRPRMT(X,Y,KTEXT,ITEXT,D,KFORM,IFORM)

      REAL(4),INTENT(IN):: X,Y
      INTEGER,INTENT(IN):: ITEXT,IFORM
      CHARACTER(LEN=*),INTENT(IN):: KTEXT,KFORM
      REAL(8),INTENT(IN):: D

      CALL MOVE(X,Y)
      CALL TEXT(KTEXT,ITEXT)
      CALL NUMBD(D,KFORM,IFORM)
      RETURN
    END SUBROUTINE WRPRMT


!     ***** POLOIDAL TRAJECTORY AND POWER *****

    SUBROUTINE WRGRF11A

      USE wrcomm
      USE plprof,ONLY: PL_RZSU,PL_MAG_OLD
      USE wrcalc,ONLY: wrcalk
      IMPLICIT NONE
      INTEGER,PARAMETER:: NSUM=501
      INTEGER,PARAMETER:: NGXL=101
      INTEGER,PARAMETER:: NGYL=101
      REAL(4):: GX(NSTPMAX+1),GY(NSTPMAX+1)
      REAL(4):: GUX(NSTPMAX+1),GUY(NSTPMAX+1)
      REAL(4):: GPX(NSTPMAX+1),GPY(NSTPMAX+1,NRAYM)
      REAL(4):: GPRY(NSTPMAX+1,NRAYM)
      REAL(4):: GCF(NGXL,NGYL),GCX(NGXL),GCY(NGYL)
      INTEGER:: KA(2,NGXL,NGYL)
      REAL(4):: GKX(NSTPMAX+1,NRAYM)
      REAL(4):: GKY1(NSTPMAX+1,NRAYM),GKY2(NSTPMAX+1,NRAYM)
      REAL(4):: GRSMIN,GRSMAX,GZSMIN,GZSMAX
      REAL(4):: GRMIN,GRMAX,GRSTEP,GZMIN,GZMAX,GZSTEP
      REAL(4):: GRORG,GZORG,GYMAXT,GYORG
      REAL(4):: GXMIN,GXMAX,GXSTEP
      REAL(4):: GYMIN1,GYMAX1,GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP
      INTEGER:: NRAY,NSTP,NRDIV,NRS1,NRS2,NDR,NR
      REAL(rkind):: DRHO,RHO0,XL1,XL2,SDR,DELPWR,XL,YL,ZL,RHON,RKPARA,RKPERP

      GRSMIN=GUCLIP(r_corner(1))
      GRSMAX=GUCLIP(r_corner(2))
      GZSMIN=GUCLIP(z_corner(1))
      GZSMAX=GUCLIP(z_corner(3))
      CALL GQSCAL(GRSMIN,GRSMAX,GRMIN,GRMAX,GRSTEP)
      CALL GQSCAL(GZSMIN,GZSMAX,GZMIN,GZMAX,GZSTEP)
      IF(GRMIN*GRMAX.LT.0.D0) THEN
         GRORG=0.0
      ELSE
         GRORG=(INT(GRMIN/(2*GRSTEP))+1)*2*GRSTEP
      END IF
      IF(GZMIN*GZMAX.LT.0.D0) THEN
         GZORG=0.0
      ELSE
         GZORG=(INT(GZMIN/(2*GZSTEP))+1)*2*GZSTEP
      END IF


      CALL PAGES
      CALL SETCHS(0.25,0.)
      CALL SETFNT(32)
      CALL SETLIN(0,2,7)
      CALL GDEFIN(1.5,11.5,1.0,16.0,GRMIN,GRMAX,GZMIN,GZMAX)
      CALL GFRAME
      CALL GSCALE(GRORG,  GRSTEP,0.0,  GZSTEP,0.1,9)
      CALL GVALUE(GRORG,2*GRSTEP,0.0,0.0,NGULEN(2*GRSTEP))
      CALL GVALUE(0.0,0.0,0.0,2*GZSTEP,NGULEN(2*GZSTEP))

!     ----- RAY TRAJECTORY -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GX(NSTP+1)=GUCLIP(RAYS(1,NSTP,NRAY))
            GY(NSTP+1)=GUCLIP(RAYS(3,NSTP,NRAY))
!            WRNSTPE(6,'(A,I5,1P2E12.4)') 
!     &           'NNSTP,GX,GY=',NSTP+1,GX(NSTP+1),GY(NSTP+1)
         ENDDO
         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

!     ----- CALCULATE RADIAL DEPOSITION PROFILE -----

      DRHO=(r_corner(2)-r_corner(1))/NRDIVMAX
      RHO0=r_corner(1)
      DO NRDIV=1,NRDIVMAX
         GPX(NRDIV)=GUCLIP(RHO0+(NRDIV-0.5D0)*DRHO)
      ENDDO
      DO NRAY=1,NRAYMAX
         DO NRDIV=1,NRDIVMAX
             GPY(NRDIV,NRAY)=0.0
             GPRY(NRDIV,NRAY)=0.0
         ENDDO
      ENDDO

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)-1
            XL1=RAYS(1,NSTP,NRAY)
            NRS1=INT((XL1-RHO0)/DRHO)+1
            XL2=RAYS(1,NSTP+1,NRAY)
            NRS2=INT((XL2-RHO0)/DRHO)+1
            NDR=ABS(NRS2-NRS1)
            IF(MIN(NRS1,NRS2).GE.1.AND.MAX(NRS1,NRS2).LE.NRDIVMAX) THEN
            IF(NDR.EQ.0) THEN
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)+GUCLIP(RAYS(8,NSTP+1,NRAY))
            ELSE IF(NRS1.LT.NRS2) THEN
               SDR=(XL2-XL1)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                    +GUCLIP((DBLE(NRS1)-XL1/DRHO)*DELPWR)
               DO NR=NRS1+1,NRS2-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                    +GUCLIP((XL2/DRHO-DBLE(NRS2-1))*DELPWR)
            ELSE
               SDR=(XL1-XL2)/DRHO
               DELPWR=RAYS(8,NSTP+1,NRAY)/SDR
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY) &
                    +GUCLIP((DBLE(NRS2)-XL2/DRHO)*DELPWR)
               DO NR=NRS2+1,NRS1-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELPWR)
               ENDDO
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY) &
                    +GUCLIP((XL1/DRHO-DBLE(NRS1-1))*DELPWR)
            ENDIF
            ENDIF
!            WRITE(6,'(3I5,1P5E12.4))') &
!                NSTP,NRS1,NRS2,RHON1,RHON2,SDR,DELPWR,RAYS(8,NSTP+1,NRAY)
         ENDDO
!         WRITE(6,'(5(I3,1PE12.4))') (NRDIV,GPY(NRDIV,NRAY),NRDIV=1,NRDIVMAX)
      ENDDO

!     ----- draw deposition profile -----

      CALL GQSCAL(GRSMIN,GRSMAX,GXMIN,GXMAX,GXSTEP)

      GYMAXT=0.0
      DO NRAY=1,NRAYMAX
         CALL GMNMX1(GPY(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN1,GYMAX1)
         GYMAXT=MAX(GYMAXT,GYMAX1)
      END DO
      CALL GQSCAL(0.0,GYMAXT,GYMIN,GYMAX,GYSTEP)
      GYMIN=0.0

      CALL MOVE(13.5,8.1)
      CALL TEXT('ABS POWER',10)
      IF(MOD(MDLWRG/2,2).EQ.0) THEN
         CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,GYMIN,GYMAX)
         CALL SETLIN(0,2,7)
         CALL GFRAME
         CALL GSCALE(0.0,  GXSTEP,0.0,  GYSTEP,0.1,9)
         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GYSTEP))
         CALL GVALUE(0.0,0.0,0.0,GYSTEP,NGULEN(GYSTEP))
      ENDIF
!      CALL SETLIN(0,0,4)
      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,2,7-MOD(NRAY-1,5))
         CALL GPLOTP(GPX,GPY(1,NRAY),1,NRDIVMAX,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

!     ----- DRAW POWER FLUX -----
!      
!      GZSMIN=0.0
!      GZSMAX=1.1
!      GZSCAL=0.2

!      CALL MOVE(13.5,8.1)
!      CALL TEXT('POWER FLUX',10)
!      IF(MOD(MDLWRG/2,2).EQ.0) THEN
!         CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,0.0,GZSMAX)
!         CALL SETLIN(0,2,7)
!         CALL GFRAME
!         CALL GSCALE(0.0,  GXSTEP,0.0,  GZSCAL,0.1,9)
!         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
!         CALL GVALUE(0.0,0.0,0.0,GZSCAL,1)
!      ELSE
!         CALL GDEFIN(13.5,23.5,1.0,8.0,GXMIN,GXMAX,0.0,GXSMAX)
!         CALL SETLIN(0,2,7)
!         CALL GFRAME
!         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
!         CALL GSCALE(GXORG,  GXSTEP,0.0,  GZSCAL,0.1,9)
!         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
!         CALL GVALUE(0.0,0.0,0.0,GZSCAL,1)
!      ENDIF
!      DO NRAY=1,NRAYMAX
!         DO NSTP=0,NSTPMAX_NRAY(NRAY)
!            XL=RAYS(1,NSTP,NRAY)
!            YL=RAYS(2,NSTP,NRAY)
!            ZL=RAYS(3,NSTP,NRAY)
!            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
!	    GUX(NSTP+1)=GUCLIP(RHON)
!            GUY(NSTP+1)=GUCLIP(RAYS(7,NSTP,NRAY))
!         ENDDO
!         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
!         CALL GPLOTP(GUX,GUY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)      
!      ENDDO


!     ----- WAVE NUMBER -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            CALL WRCALK(NSTP,NRAY,RKPARA,RKPERP)
            GKX( NSTP+1,NRAY)=GUCLIP(XL)
            GKY1(NSTP+1,NRAY)=GUCLIP(RKPARA)
            GKY2(NSTP+1,NRAY)=GUCLIP(RKPERP)
         ENDDO
      ENDDO

      NRAY=1
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN2,GYMAX2)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN2=MIN(GYMIN2,GYMIN)
         GYMAX2=MAX(GYMAX2,GYMAX)
      ENDDO

      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,16.1)
      CALL TEXT('k-para',6)
      CALL GDEFIN(13.7,23.7,9.0,16.0,GXMIN,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

      CALL WRGPRM
      CALL PAGEE
      RETURN
    END SUBROUTINE WRGRF11A


!     ***** RADIAL DEPENDENCE 1 *****

    SUBROUTINE WRGRF11B

      USE wrcomm
      USE plprof,ONLY: PL_MAG_OLD
      USE wrcalc,ONLY: wrcalk
      IMPLICIT NONE
      INTEGER,PARAMETER:: NSRM=101
      REAL(4):: GX(NSTPMAX+1),GY(NSTPMAX+1)
      REAL(4):: GKX(NSTPMAX+1,NRAYM)
      REAL(4):: GKY1(NSTPMAX+1,NRAYM),GKY2(NSTPMAX+1,NRAYM)
      REAL(4):: GLCX(NSRM),GLCY(NSRM),GSCX(NSRM),GSCY(NSRM)
      INTEGER:: NSRMAX,NSU,NRAY,NSTP
      REAL(rkind):: RMAXL,RMINL,DTH,TH,XL,YL,ZL,RHON,RKPARA,RKPERP
      REAL(4):: GRRMAX,GXMIN,GXMAX,GXSTEP,GYMIN,GYMAX,GYSTEP,GXORG
      REAL(4):: GYMIN1,GYMIN2,GYMAX1,GYMAX2,GYORG

      CALL PAGES
      CALL SETFNT(32)
      CALL SETCHS(0.25,0.)
      CALL SETLIN(0,2,7)

!     ----- TOROIDAL CROSS SECTION -----

      NSRMAX=101
      RMAXL=RR+RA
      RMINL=RR-RA
      DTH=2*PI/(NSRMAX-1)
      DO NSU=1,NSRMAX
         TH=DTH*(NSU-1)
         GLCX(NSU)=GUCLIP(RMAXL*COS(TH))
         GLCY(NSU)=GUCLIP(RMAXL*SIN(TH))
         GSCX(NSU)=GUCLIP(RMINL*COS(TH))
         GSCY(NSU)=GUCLIP(RMINL*SIN(TH))
      ENDDO
      IF(MOD(MDLWRG,2).EQ.0) THEN
         GRRMAX=GUCLIP(RMAX)
         CALL GQSCAL(-GRRMAX,GRRMAX,GXMIN,GXMAX,GXSTEP)
         CALL GQSCAL(-GRRMAX,GRRMAX,GYMIN,GYMAX,GYSTEP)
      ELSE
         CALL GQSCAL(GUCLIP(RR-RA),GUCLIP(RR+RA),GXMIN,GXMAX,GXSTEP)
         CALL GQSCAL(GUCLIP(  -RA),GUCLIP(   RA),GYMIN,GYMAX,GYSTEP)
         GXORG=(INT(GXMIN/(2*GXSTEP))+1)*2*GXSTEP
      ENDIF

      CALL GDEFIN(1.7,11.7,1.0,11.0,GXMIN,GXMAX,GYMIN,GYMAX)

      CALL SETLIN(0,2,7)
      CALL GFRAME
      IF(MOD(MDLWRG,2).EQ.0) THEN
         CALL GSCALE(0.0,GXSTEP,0.0,GYSTEP,0.1,9)
         CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALE(GXORG,GXSTEP,0.0,GYSTEP,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
         CALL GVALUE(0.0,0.0,0.0,2*GYSTEP,NGULEN(2*GYSTEP))
      ENDIF

      CALL SETLIN(0,2,4)
      CALL GPLOTP(GLCX,GLCY,1,NSRMAX,1,0,0,0)
      CALL GPLOTP(GSCX,GSCY,1,NSRMAX,1,0,0,0)

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            GX(NSTP+1)=GUCLIP(RAYS(1,NSTP,NRAY))
            GY(NSTP+1)=GUCLIP(RAYS(2,NSTP,NRAY))
         ENDDO
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

!     ----- WAVE NUMBER -----

      DO NRAY=1,NRAYMAX
         DO NSTP=0,NSTPMAX_NRAY(NRAY)
            XL=RAYS(1,NSTP,NRAY)
            YL=RAYS(2,NSTP,NRAY)
            ZL=RAYS(3,NSTP,NRAY)
            CALL PL_MAG_OLD(XL,YL,ZL,RHON)
            CALL WRCALK(NSTP,NRAY,RKPARA,RKPERP)
            GKX( NSTP+1,NRAY)=GUCLIP(RHON)
            GKY1(NSTP+1,NRAY)=GUCLIP(RKPARA*VC &
                                  /(2*PI*RAYIN(1,NRAY)*1.D6))
            GKY2(NSTP+1,NRAY)=GUCLIP(RKPERP)
         ENDDO
      ENDDO

      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
      NRAY=1
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN2,GYMAX2)
      DO NRAY=2,NRAYMAX
         CALL GMNMX1(GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
         CALL GMNMX1(GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY),1,GYMIN,GYMAX)
         GYMIN2=MIN(GYMIN2,GYMIN)
         GYMAX2=MAX(GYMAX2,GYMAX)
      ENDDO

      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,16.1)
      CALL TEXT('n-para',6)
      CALL GDEFIN(13.7,23.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY1(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

      CALL GQSCAL(GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,8.1)
      CALL TEXT('k-perp',6)
      CALL GDEFIN(13.7,23.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,2,7)
      CALL GFRAME
      GYORG=(INT(GYMIN/(2*GYSTEP))+1)*2*GYSTEP
      CALL GSCALE(0.0,GXSTEP,GYORG,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))

      DO NRAY=1,NRAYMAX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX(1,NRAY),GKY2(1,NRAY),1,NSTPMAX_NRAY(NRAY)+1,1,0,0,0)
      ENDDO
      CALL SETLIN(0,2,7)

      CALL WRGPRM
      CALL PAGEE

      RETURN
    END SUBROUTINE WRGRF11B
END MODULE WRGOUT
