! dpcomm.f90

MODULE dpcomm_parm

  USE plcomm_parm
  USE commpi
  IMPLICIT NONE

  PUBLIC

! --- input paramters ---

  INTEGER:: MODELP(NSM),MODELV(NSM),NCMIN(NSM),NCMAX(NSM)
  REAL(rkind):: RF0,RFI0,RKX0,RKY0,RKZ0,RX0,RY0,RZ0,RK0,RKANG0
  REAL(rkind):: EPSRT
  INTEGER:: LMAXRT

  INTEGER:: NS_NSA(NSM)
  REAL(rkind):: PMAX(NSM),EMAX(NSM),RHON_MIN(NSM),RHON_MAX(NSM)
  INTEGER:: NPMAX,NTHMAX,NRMAX,NSAMAX

END MODULE dpcomm_parm

MODULE dpcomm_parm_local     ! only for DP program, not for DP library

  USE dpcomm_parm
  IMPLICIT NONE

  REAL(rkind):: RF1,RFI1,RKX1,RKY1,RKZ1,RX1,RY1,RZ1,RK1
  REAL(rkind):: RF2,RFI2,RKX2,RKY2,RKZ2,RX2,RY2,RZ2,RK2
  INTEGER:: NGXMAX,NGYMAX,NGPMAX
  REAL(rkind):: EPSDP,EPSRF
  INTEGER:: NORMF,NORMK
  INTEGER:: NFLOUT

END MODULE dpcomm_parm_local

MODULE dpcomm
  USE dpcomm_parm
  IMPLICIT NONE

  PUBLIC

  COMPLEX(rkind):: CRF0,CKX0,CKY0,CKZ0
  REAL(rkind):: XPOS0,YPOS0,ZPOS0
  INTEGER:: ILIST

  INTEGER:: NSDP(NSM)

  REAL(rkind):: DELTH,DELR
  REAL(rkind):: FPDATA(2)
  INTEGER:: NFPDATA(3)

  REAL(rkind),ALLOCATABLE:: FP(:,:,:) ! FP(NTHMAX,NPMAX,NRMAX)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       FM,DFP,DFT ! (NPMAX,NTHMAX)

  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       AEFP,AMFP,RNFP0,RTFP0,DELP ! (NSAMAX)
  REAL(rkind),DIMENSION(:,:,:,:),ALLOCATABLE:: &
       FNS ! (NTHMAX,NPMAX,NRMAX,NSAMAX)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       THM,THG,TSNM,TSNG,TCSM,TCSG,TTNM,TTNG ! (NTHMAX)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       PM,PG ! (NPMAX,NSAMAX)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       RGMM,RGMG ! (NPMAX)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       RM ! (NRMAX)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       DGP1,DGP2,DGT1,DGT2 ! (NPM,NTHM)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       RFP ! (NRM+2)
  REAL(rkind),DIMENSION(:,:,:,:),ALLOCATABLE:: &
       URFP ! (4,NRM+2,NPM,NTHM)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       FPDATAS ! (NSAM)
!  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
!       CHI,CCHI,SCHI ! (NCHMAX)

CONTAINS

  SUBROUTINE dp_allocate
    RETURN
  END SUBROUTINE dp_allocate

  SUBROUTINE dp_deallocate
    RETURN
  END SUBROUTINE dp_deallocate

  SUBROUTINE dpfp_allocate
    IMPLICIT NONE
    INTEGER,SAVE:: init=0
    INTEGER,SAVE:: NTHMAX_SAVE=0
    INTEGER,SAVE:: NPMAX_SAVE=0
    INTEGER,SAVE:: NRMAX_SAVE=0
    INTEGER,SAVE:: NSAMAX_SAVE=0

    IF(init.EQ.0) THEN
       init=1
    ELSE
       IF((NTHMAX.EQ.NTHMAX_SAVE).AND. &
          (NPMAX.EQ.NPMAX_SAVE).AND. &
          (NRMAX.EQ.NRMAX_SAVE).AND. &
          (NSAMAX.EQ.NSAMAX_SAVE)) RETURN
       CALL dpfp_deallocate
    ENDIF

    ALLOCATE(AEFP(NSAMAX),AMFP(NSAMAX),RNFP0(NSAMAX),RTFP0(NSAMAX))
    ALLOCATE(DELP(NSMAX))
    ALLOCATE(FNS(NTHMAX,NPMAX,NRMAX,NSAMAX))
    ALLOCATE(FP(NTHMAX,NPMAX,NRMAX))
    ALLOCATE(FM(NPMAX,NTHMAX),DFP(NPMAX,NTHMAX),DFT(NPMAX,NTHMAX))
    ALLOCATE(THM(NTHMAX),THG(NTHMAX),TSNM(NTHMAX),TSNG(NTHMAX), &
             TCSM(NTHMAX),TCSG(NTHMAX),TTNM(NTHMAX),TTNG(NTHMAX))
    ALLOCATE(PM(NPMAX,NSAMAX),PG(NPMAX,NSAMAX))
    ALLOCATE(RGMM(NPMAX,NSAMAX),RGMG(NPMAX,NSAMAX))
    ALLOCATE(RM(NRMAX))
    ALLOCATE(DGP1(NPMAX,NTHMAX),DGP2(NPMAX,NTHMAX), &
             DGT1(NPMAX,NTHMAX),DGT2(NPMAX,NTHMAX))
    ALLOCATE(RFP(NRMAX+2),URFP(4,NRMAX+2,NPMAX,NTHMAX))
    ALLOCATE(FPDATAS(NSAMAX))
!    ALLOCATE(CHI(NCHMAX),CCHI(NCHMAX),SCHI(NCHMAX))
    RETURN
  END SUBROUTINE dpfp_allocate

  SUBROUTINE dpfp_deallocate
    DEALLOCATE(AEFP,AMFP,RNFP0,RTFP0,DELP)
    DEALLOCATE(FNS)
    DEALLOCATE(FP)
    DEALLOCATE(FM,DFP,DFT)
    DEALLOCATE(THM,THG,TSNM,TSNG,TCSM,TCSG,TTNM,TTNG)
    DEALLOCATE(PM,PG)
    DEALLOCATE(RGMM,RGMG)
    DEALLOCATE(RM)
    DEALLOCATE(DGP1,DGP2,DGT1,DGT2)
    DEALLOCATE(RFP,URFP,FPDATAS)
!    DEALLOCATE(CHI,CCHI,SCHI)
    RETURN
  END SUBROUTINE dpfp_deallocate

END MODULE dpcomm

MODULE dpcomm_local

  USE dpcomm
  USE dpcomm_parm_local

END MODULE dpcomm_local

