MODULE dpmenu

PRIVATE

PUBLIC dp_menu

CONTAINS

!     ***** TASK/DP MENU *****

  SUBROUTINE dp_menu

    USE dpcomm
    USE pllocal
    USE plprof,ONLY:pl_mag_old,pl_prof_old
    USE plinit
    USE dpinit
    USE dpparm
    USE dproot
    USE dpcont
    USE dptnsr1
    IMPLICIT NONE
      
    REAL(4),ALLOCATABLE:: GX(:),GY(:,:)
    COMPLEX(rkind):: CDTNS(3,3)
    CHARACTER(LEN=1):: KID
    CHARACTER(LEN=80):: LINE
    INtEGER:: MODE,IERR,NID
    COMPLEX(rkind):: CD4(6),CD5(6),CD6(6)
    REAL(rkind):: RF0_SAVE,RKZ0_SAVE,RKX0_SAVE,RL,RHON,RKPR0
    COMPLEX(rkind):: CW,CKPR,CKPP,CZ,CFZ

1   CONTINUE
    WRITE(6,*) '## DP MENU: P,V/PARM  ', &
               'D1,D2,D3/DISP  F/ROOT  T,S,K/TEST  Q/QUIT'

    CALL TASK_KLIN(LINE,KID,MODE,DP_PARM)
    IF(MODE.NE.1) GOTO 1

    IF(KID.EQ.'P') THEN
       CALL DP_PARM(0,'DP',IERR)
    ELSEIF(KID.EQ.'V') THEN
       CALL PL_VIEW
       CALL DP_VIEW
    ELSEIF(KID.EQ.'D') THEN
       READ(LINE(2:),*,ERR=1,END=1) NID
       IF(NID.EQ.1) THEN
          CALL DPGRP1
       ELSEIF(NID.EQ.2) THEN
          CALL DP_CONT
       ELSEIF(NID.EQ.3) THEN
          CALL DPCONTX
       ELSE
          WRITE(6,*) 'XX DPMENU: unknown NID'
       ENDIF
    ELSEIF(KID.EQ.'F') THEN
       CALL DP_ROOT
    ELSEIF(KID.EQ.'T') THEN
       MODELP_SAVE=MODELP(1)
       RF0_SAVE=RF0
       RKZ0_SAVE=RKZ0
       RKX0_SAVE=RKX0
       RL=RR
1001   WRITE(6,*) '# INPUT: RL,RF0,RKZ0,RKX0 ='
       READ(5,*,ERR=1001,END=1002) RL,RF0,RKZ0,RKX0
       IF(RF0.LE.0.D0) GOTO 1002
       CW=2.D0*PI*CMPLX(RF0,RFI0)*1.D6
       CKPR=MAX(RKZ0,1.D-4)
       CKPP=RKX0
       CALL PL_MAG_OLD(RL,0.D0,0.D0,RHON)
       CALL PL_PROF_OLD(RHON)
       MODELP(1)=1
       CALL DP_TENS(CW,CKPR,CKPP,1,CD4)
       MODELP(1)=4
       CALL DP_TENS(CW,CKPR,CKPP,1,CD5)
       MODELP(1)=5
       CALL DP_TENS(CW,CKPR,CKPP,1,CD6)
       WRITE(6,602) 
602    FORMAT(8X,'MODELP=1',16X,'MODELP=4',16X,'MODELP=5')
       WRITE(6,603) (I,CD4(I),CD5(I),CD6(I),I=1,6)
603    FORMAT(I5,1P6E12.4)
       GOTO 1001

1002   MODELP(1)=MODELP_SAVE
       RF0=RF0_SAVE
       RKZ0=RKZ0_SAVE
       RKX0=RKX0_SAVE
       GOTO 1
    ELSEIF(KID.EQ.'S') THEN
       XMIN=-50.D0
       XMAX= 50.D0
       NXGMAX=101
       Q=2.5D0
2001   WRITE(6,*) '# XMIN,XMAX,NXGMAX,Q='
       READ(5,*,ERR=2001,END=1) XMIN,XMAX,NXGMAX,Q
       DX=(XMAX-XMIN)/(NXGMAX-1)
       ALLOCATE(GX(NXGMAX),GY(NXGMAX,4))
       DO NX=1,NXGMAX
          X=XMIN+DX*(NX-1)
          GX(NX)=GUCLIP(X)
          CZ=X
          CFZ=CFQZ(Q,CZ)
          GY(NX,1)=GUCLIP(DBLE(CFZ))
          GY(NX,2)=GUCLIP(DIMAG(CFZ))
          CFZ=CFQZ_Z(Q,CZ)
          GY(NX,3)=GUCLIP(DBLE(CFZ))
          GY(NX,4)=GUCLIP(DIMAG(CFZ))
          WRITE(6,'(1P5E12.4)') GX(NX),GY(NX,1),GY(NX,2),GY(NX,3),GY(NX,4)
       ENDDO
       CALL DPGTMP(GX,GY,NXGMAX,NXGMAX,4)
       DEALLOCATE(GX,GY)
       GOTO 2001
    ELSEIF(KID.EQ.'Q') THEN
       GOTO 9000
    ENDIF
    GOTO 1

9000 RETURN
  END SUBROUTINE dp_menu

!     ###############################################################

!            SUBROUTINE DPGTMP

!     ###############################################################

  SUBROUTINE DPGTMP(GX,GY,NXM,NXMAX,NGMAX)

    IMPLICIT NONE
    INTEGER,INTENT(IN):: NXM,NXMAX,NGMAX
    REAL(4),INTENT(IN):: GX(NXMAX),GY(NXM,NGMAX)
    REAL(4):: GXMIN,GXMAX,GXSMN,GXSMX,GSCALX,GXORG
    REAL(4):: GYMIN,GYMAX,GYSMN,GYSMX,GSCALY,GYORG,GYMIN1,GYMAX1
    INtEGEr:: NG

    CALL PAGES
    CALL SETLIN(0,0,7)
    CALL SETCHS(0.3,0.)
    CALL GMNMX1(GX,1,NXMAX,1,GXMIN,GXMAX)
    CALL GMNMX1(GY(1,1),1,NXMAX,1,GYMIN,GYMAX)
    DO NG=2,NGMAX
       CALL GMNMX1(GY(1,NG),1,NXMAX,1,GYMIN1,GYMAX1)
       GYMIN=MIN(GYMIN,GYMIN1)
       GYMAX=MAX(GYMAX,GYMAX1)
    ENDDO
    CALL GQSCAL(GXMIN,GXMAX,GXSMN,GXSMX,GSCALX)
    CALL SETLIN(0,0,5)
    CALL GQSCAL(GYMIN,GYMAX,GYSMN,GYSMX,GSCALY)
    IF(GXMIN*GXMAX.LT.0.0) THEN
       GXORG=0.0
    ELSE
       GXORG=GXSMN
    ENDIF
    IF(GYMIN*GYMAX.LT.0.0) THEN
       GYORG=0.0
    ELSE
       GYORG=GYSMN
    ENDIF
    CALL GDEFIN(4.,17.,2.,17.,GXSMN,GXSMX,GYSMN,GYSMX)
    CALL SETLIN(0,0,7)
    CALL GFRAME
    CALL GSCALE(GXORG,GSCALX,0.0,0.0,0.2,9)
    CALL GSCALE(0.0,0.0,GYORG,GSCALY,0.2,9)
    CALL GVALUE(GXORG,2*GSCALX,0.0,0.0,2)
    CALL GVALUE(0.0,0.0,GYORG,2*GSCALY,-2)
    DO NG=1,NGMAX
       CALL SETLIN(0,0,7-MOD(NG-1,5))
       CALL GPLOTP(GX,GY(1,NG),1,NXMAX,1,0,0,MOD(NG-1,5)+1)
    ENDDO
    CALL PAGEE
    RETURN
  END SUBROUTINE DPGTMP
END MODULE dpmenu
