C     $Id$
C
      COMMON /FPSPL2/ PSIX(0:NITM,NRAYM),SI(0:NITM,NRAYM)
      COMMON /FPSPL3/ CU1(4,0:NITM,NRAYM),CU2(4,0:NITM,NRAYM)
      COMMON /FPSPL4/ CU3(4,0:NITM,NRAYM),U4(4,0:NITM,NRAYM)
      COMMON /FPSPL5/ U5(4,0:NITM,NRAYM),U6(4,0:NITM,NRAYM)
      COMMON /FPSPL6/ U7(4,0:NITM,NRAYM),U8(4,0:NITM,NRAYM)
      COMMON /FPSPL7/ U9(4,0:NITM,NRAYM),U0(4,0:NITM,NRAYM)
      COMMON /FPDPC1/ NCRMAX(NRM,NRAYM)
      COMMON /FPDPC2/ CECR(3,NCRM,NRM,NRAYM)
      COMMON /FPDPC3/ RKCR(3,NCRM,NRM,NRAYM)
      COMMON /FPDPC4/ RCR(3,NCRM,NRM,NRAYM)
      COMMON /FPDPC5/ RRMIN(NRM),RRMAX(NRM)
