C     $Id$
C
      IMPLICIT COMPLEX*16(C),REAL*8(A,B,D-F,H,O-Z)
      CHARACTER*80 KNAMEQ
C
      NRMAX=50
      NTHMAX=16
      NSUMAX=41
C
      CALL GSOPEN
      KNAMEQ='eqdata'
C
      CALL AKEQIN(KNAMEQ,NRMAX,NTHMAX,NSUMAX,
     &            ALPMAX,RAXIS,ZAXIS,IERR)
      IF(IERR.NE.0) GOTO 9000
      WRITE(6,'(A,1PE12.4)') 'ALPMAX=',ALPMAX
      WRITE(6,'(A,1PE12.4)') 'RAXIS =',RAXIS
      WRITE(6,'(A,1PE12.4)') 'ZAXIS =',ZAXIS
C
      CALL EQGETB(BB,RR,RIP,RA,RKAP,RDEL,RB)
      WRITE(6,'(A,1PE12.4)') 'BB    =',BB
      WRITE(6,'(A,1PE12.4)') 'RR    =',RR
      WRITE(6,'(A,1PE12.4)') 'RIP   =',RIP
      WRITE(6,'(A,1PE12.4)') 'RA    =',RA
      WRITE(6,'(A,1PE12.4)') 'RKAP  =',RKAP
      WRITE(6,'(A,1PE12.4)') 'RDEL  =',RDEL
C
    1 WRITE(6,*) '# INPUT R,Z'
      READ(5,*,ERR=1,END=9000) R,Z
C
      CALL RZTOAB(R,Z,ALPHA,BETA)
      WRITE(6,'(A,1P2E12.4)') 'ALPHA,BETA=',ALPHA,BETA
      DR=1.D-4
      DZ=1.D-4
      CALL RZTOAB(R+DR,Z,ALPHA1,BETA1)
      CALL RZTOAB(R,Z+DZ,ALPHA2,BETA2)
      DADR=(ALPHA1-ALPHA)/DR
      DADZ=(ALPHA2-ALPHA)/DZ
      DBDR=(BETA1-BETA)/DR
      DBDZ=(BETA2-BETA)/DZ
      BTAB=DADR*DBDZ-DADZ*DBDR
      CALL ABTORZ(ALPHA,BETA,R1,Z1,IERR)
      WRITE(6,'(A,1P2E12.4,I5)') 'R1,Z1,IERR=',R1,Z1,IERR
      ER=R1-R
      EZ=Z1-Z
      ET=SQRT(ER**2+EZ**2)/RAXIS
      WRITE(6,'(A,1P3E12.4,I5)') 'ERRORS=',ER,EZ,ET
C
C      CALL SUBQPA(ALPHA,Q,DQDA)
C      WRITE(6,'(A,1P2E12.4)') 'Q,DQ/DA=',Q,DQDA
C      CALL SUBBMX(ALPHA,BMX,DBMXDA)
C      WRITE(6,'(A,1P2E12.4)') 'BMAX,DBMAX/DA=',BMX,DBMXDA
C      CALL SUBBMN(ALPHA,BMN,DBMNDA)
C      WRITE(6,'(A,1P2E12.4)') 'BMIN,DBMIN/DA=',BMN,DBMNDA
      CALL SUBMAG(ALPHA,BETA,BR,BZ,BT,BTOT)
      WRITE(6,'(A,1P5E12.4)') 'BR,BZ,BT,BTOT=',BR,BZ,BT,BTOT,BTAB
      GOTO 1
C
 9000 CALL GSCLOS
      STOP
      END
