C
      PARAMETER (NTRM=201)
C
      COMMON /TREQL1/ PSITR(NTRM),RHOTR(NTRM)
C
      COMMON /TREQG1/ UPPSI(4,NTRM),UJPSI(4,NTRM),UJPSI0(NTRM)
      COMMON /TREQG2/ UVTPSI(4,NTRM),UTPSI(4,NTRM)
C
      COMMON /TREQP1/ NTRMAX
