C
      PARAMETER (NRM=201)
      PARAMETER (NPSM=101)
C
      COMMON /TREQL1/ PSILL(NPSM),PSIT(NPSM)
C
      COMMON /TREQG1/ UHJP(4,NRM),UPP(4,NRM),UOMGTP(4,NRM),UTP(4,NRM)
      COMMON /TREQG2/ UPSIT(4,NRM),UHJTOT(4,NRM)
C
      COMMON /TREQP1/ NTRMAX
