C     $Id$
C
C     ****** DRAW SPLINED EQ3D GRAPH ******
C
      SUBROUTINE EQGS3D
C
      INCLUDE 'eqcomq.inc'
C
      REAL,DIMENSION(:),ALLOCATABLE:: GRG,GZG
      REAL,DIMENSION(:,:),ALLOCATABLE:: GPSIRZ
      INTEGER,DIMENSION(:,:,:),ALLOCATABLE:: KA
      CHARACTER KTITL*80
      EXTERNAL R2W2B,W2G2B,R2Y2W,WRGBW
C
      ALLOCATE(GPSIRZ(NRGM,NZGM),GRG(NRGM),GZG(NZGM),KA(8,NRGM,NZGM))

      DO NR=1,NRGMAX
         GRG(NR)=GUCLIP(RG(NR))
      ENDDO
      DO NZ=1,NZGMAX
         GZG(NZ)=GUCLIP(ZG(NZ))
      ENDDO
      DO NZ=1,NZGMAX
         DO NR=1,NRGMAX
            GPSIRZ(NR,NZ)=-GUCLIP(PSIRZ(NR,NZ))
         ENDDO
      ENDDO
C
      CALL GMNMX1(GRG,1,NRGMAX,1,GRMIN,GRMAX)
      CALL GMNMX1(GZG,1,NZGMAX,1,GZMIN,GZMAX)
      CALL GMNMX2(GPSIRZ,NRGM,1,NRGMAX,1,1,NZGMAX,1,GPMIN,GPMAX)
C
      IF(GPMIN*GPMAX.LT.0.0) THEN
         GPMAX=MAX(ABS(GPMIN),ABS(GPMAX))
         GPMIN=-GPMAX
      ENDIF
C
      NPSTEP=20
      GPORG=GPMIN
      GPSTEP=(GPMAX-GPMIN)/NPSTEP
C
      GRLEN=GRMAX-GRMIN
      GZLEN=GZMAX-GZMIN
      IF(GRLEN.GT.GZLEN) THEN
         GPR=15.0
         GPZ=15.0*GZLEN/GRLEN
      ELSE
         GPR=15.0*GRLEN/GZLEN
         GPZ=15.0
      ENDIF
C
      CALL PAGES
C
      CALL MOVE(2.0,2.0+GPZ)
      CALL TEXT('-PSI',4)
C
      CALL GQSCAL(GRMIN,GRMAX,GGRMIN,GGRMAX,GGRSTP)
      CALL GQSCAL(GZMIN,GZMAX,GGZMIN,GGZMAX,GGZSTP)
      CALL GQSCAL(GPMIN,GPMAX,GGPMIN,GGPMAX,GGPSTP)
C
      CALL SETLIN(0,2,7)

      GYL=15.0
      GXL=(GRMAX-GRMIN)/(GZMAX-GZMIN)*GYL
      GZL=10.0
      CALL GDEFIN3D(2.0,2.0+GPR,2.0,2.0+GPZ,GXL,GYL,GZL)
      GPHI=-90.0
      GTHETA=30.0
      GRADIUS=100.0
C      GPHI    =-90.0
C      GTHETA  =  0.0
C      GRADIUS =  5.0
C
      GOX=0.5*(GGRMIN+GGRMAX)+GGRSTP
      GOY=0.5*(GGZMIN+GGZMAX)
      GOZ=0.5*(GGPMIN+GGPMAX)

      CALL GVIEW3D(GPHI,GTHETA,GRADIUS,1.0,1,GOX,GOY,GOZ)
      CALL GDATA3D1(GPSIRZ,NRGM,NRGMAX,NZGMAX,
     &     GGRMIN,GGRMAX,GGZMIN,GGZMAX,GGPMIN,GGPMAX)
      CALL GUFLSH

      CALL SETCHS(0.2,0.0)
      CALL SETLIN(0,0,7)
C
      CALL GSCALE3DX(GGRMIN,GGRSTP,0.3,0)
      CALL GSCALE3DY(GGZMIN,GGZSTP,0.3,0)
      CALL GSCALE3DZ(GGPMIN,GGPSTP,0.3,0)
      CALL GVALUE3DX(GGRMIN,GGRSTP,1,NGULEN(GGRSTP))
      CALL GVALUE3DY(GGZMIN,GGZSTP,1,NGULEN(GGZSTP))
      CALL GVALUE3DZ(GGPMIN,GGPSTP,2,NGULEN(GGPSTP)+1)

      IF(GGPMIN*GGPMAX.LT.0.0) THEN
         CALL CPLOT3D1(4,R2W2B)
      ELSEIF(GGPMIN.LT.0.0) THEN
         CALL CPLOT3D1(4,W2G2B)
      ELSE
         CALL CPLOT3D1(4,R2Y2W)
      ENDIF
      CALL PERSE3D(0,11)

      CALL SETLIN(0,0,7)
C
      CALL EQGPRM
      CALL PAGEE
C
      DEALLOCATE(GPSIRZ,GRG,GZG,KA)
      RETURN
      END
