C     $Id$
C
C     ****** DRAW PSI CONTOUR ******
C
      SUBROUTINE SHOWPS
C
      INCLUDE 'eqcomq.h'
C
      DIMENSION GR(NTHMP),GZ(NTHMP)
      DIMENSION GX(NRM),GY(NRM,2)
      CHARACTER*80 KTITL
C
      GRMIN=GCLIP(RGMIN)
      GRMAX=GCLIP(RGMAX)
      GZMIN=GCLIP(ZGMIN)
      GZMAX=GCLIP(ZGMAX)
      GRLEN=GRMAX-GRMIN
      GZLEN=GZMAX-GZMIN
      IF(GRLEN.GT.GZLEN) THEN
         GPR=15.0
         GPZ=15.0*GZLEN/GRLEN
      ELSE
         GPR=15.0*GRLEN/GZLEN
         GPZ=15.0
      ENDIF
C
      CALL PAGES
      CALL MOVE(2.0,17.5)
      KTITL='/PSI in R-Z/'
      CALL TEXTX(KTITL)
C
      CALL GDEFIN(2.0,2.0+GPR,2.0,2.0+GPZ,
     &            GRMIN,GRMAX,GZMIN,GZMAX)
      CALL GFRAME
C
      DO 1000 NR=1,NRMAX
         DO 800 NTH=1,NTHMAX
            GR(NTH)=GCLIP(RPS(NTH,NR))
            GZ(NTH)=GCLIP(ZPS(NTH,NR))
C            WRITE(6,*) NR,NTH,GR(NTH),GZ(NTH)
  800    CONTINUE
         GR(NTHMAX+1)=GR(1)
         GZ(NTHMAX+1)=GZ(1)
         CALL GPLOTP(GR,GZ,1,NTHMAX+1,1,0,0,0)
 1000 CONTINUE
      CALL EQGPRM
      CALL PAGEE
C
      CALL PAGES
      CALL SETCHS(0.35,0.0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(PPS(NR)*1.D-6)
      ENDDO
      CALL EQGR1D( 3.0,13.0,10.0,16.0,GX,GY,NRM,NRMAX,1,'@PPS@',0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(TTS(NR))
      ENDDO
      CALL EQGR1D(15.0,25.0,10.0,16.0,GX,GY,NRM,NRMAX,1,'@TTS@',1)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(RLEN(NR))
      ENDDO
      CALL EQGR1D( 3.0,13.0, 2.0, 8.0,GX,GY,NRM,NRMAX,1,'@RLEN@',0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(QPS(NR))
      ENDDO
      CALL EQGR1D(15.0,25.0, 2.0, 8.0,GX,GY,NRM,NRMAX,1,'@QPS@',0)
C
      CALL PAGEE
C
      CALL PAGES
      CALL SETCHS(0.35,0.0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(VPS(NR))
      ENDDO
      CALL EQGR1D( 3.0,13.0,10.0,16.0,GX,GY,NRM,NRMAX,1,'@VPS@',0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(SPS(NR))
      ENDDO
      CALL EQGR1D(15.0,25.0,10.0,16.0,GX,GY,NRM,NRMAX,1,'@SPS@',0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(RRMIN(NR))
         GY(NR,2)=GCLIP(RRMAX(NR))
      ENDDO
      CALL EQGR1D( 3.0,13.0, 2.0, 8.0,GX,GY,NRM,NRMAX,2,'@RRMIN/MAX@',0)
C
      DO NR=1,NRMAX
         GX(NR)=GCLIP(PSS(NR)-SAXIS)
         GY(NR,1)=GCLIP(BBMIN(NR))
         GY(NR,2)=GCLIP(BBMAX(NR))
      ENDDO
      CALL EQGR1D(15.0,25.0, 2.0, 8.0,GX,GY,NRM,NRMAX,2,'@BBMIN/MAX@',0)
C
      CALL PAGEE
C
      RETURN
      END
C
      SUBROUTINE EQDRAW(IND)
C
      INCLUDE 'eqcomq.h'
C
      DIMENSION GF(NRM,NTHM),GR(NRM,NTHM),GZ(NRM,NTHM)
      DIMENSION GRSU(NSUM),GZSU(NSUM)
      DIMENSION GRSW(NSUM),GZSW(NSUM)
      DIMENSION KA(4,NRM,NTHM)
      CHARACTER*80 KTITL
C
      DO 1000 NR=1,NRMAX
      DO 1000 NTH=1,NTHMAX
         GR(NR,NTH)=GCLIP(RPS(NTH,NR))
         GZ(NR,NTH)=GCLIP(ZPS(NTH,NR))
 1000 CONTINUE
C
      IF(IND.EQ.1) THEN
         DO 1001 NR=1,NRMAX
         DO 1001 NTH=1,NTHMAX
            R2=(RPS(NTH,NR)-RAXIS)**2+(ZPS(NTH,NR)-ZAXIS)**2
            GF(NR,NTH)=GCLIP(DRPSI(NTH,NR)*R2)
 1001    CONTINUE
         KTITL='/DRPSI*r^2/'
      ELSEIF(IND.EQ.2) THEN
         DO 1002 NR=1,NRMAX
         DO 1002 NTH=1,NTHMAX
            R2=(RPS(NTH,NR)-RAXIS)**2+(ZPS(NTH,NR)-ZAXIS)**2
            GF(NR,NTH)=GCLIP(DZPSI(NTH,NR)*R2)
 1002    CONTINUE
         KTITL='/DZPSI*r^2/'
      ELSEIF(IND.EQ.3) THEN
         DO 1003 NR=1,NRMAX
         DO 1003 NTH=1,NTHMAX
            GF(NR,NTH)=GCLIP(DRCHI(NTH,NR))
 1003    CONTINUE
         KTITL='/DRCHI/'
      ELSEIF(IND.EQ.4) THEN
         DO 1004 NR=1,NRMAX
         DO 1004 NTH=1,NTHMAX
            GF(NR,NTH)=GCLIP(DZCHI(NTH,NR))
 1004    CONTINUE
         KTITL='/DZCHI/'
      ENDIF
C
      GSUM=0.0
      DO NTH=1,NTHMAX
         GSUM=GSUM+GF(1,NTH)
      ENDDO
      GSUM=GSUM/NTHMAX
      DO NTH=1,NTHMAX
         GF(1,NTH)=GSUM
      ENDDO
C
      CALL GMNMX2(GF,NRM,1,NRMAX,1,1,NTHMAX,1,GFMIN,GFMAX)
      CALL GQSCAL(GFMIN,GFMAX,GGFMIN,GGFMAX,GGFSTP)
      GGFSTP=0.5*GGFSTP
      NSTEP=INT((GGFMAX-GGFMIN)/GGFSTP)+1
      DO 1030 NSU=1,NSUMAX
         GRSU(NSU)=GCLIP(RSU(NSU))
         GZSU(NSU)=GCLIP(ZSU(NSU))
         GRSW(NSU)=GCLIP(RSW(NSU))
         GZSW(NSU)=GCLIP(ZSW(NSU))
 1030 CONTINUE
C
      GRLEN=GCLIP(RGMAX-RGMIN)
      GZLEN=GCLIP(ZGMAX-ZGMIN)
      IF(GRLEN.GT.GZLEN) THEN
         GPR=15.0
         GPZ=15.0*GZLEN/GRLEN
      ELSE
         GPR=15.0*GRLEN/GZLEN
         GPZ=15.0
      ENDIF
C
      CALL PAGES
      CALL MOVE(2.0,17.5)
      CALL TEXTX(KTITL)
C
      CALL GDEFIN(2.0,2.0+GPR,2.0,2.0+GPZ,
     &            REAL(RGMIN),REAL(RGMAX),
     &            REAL(ZGMIN),REAL(ZGMAX))
      CALL GFRAME
C
      IF(GFMIN*GFMAX.GT.0.) THEN
         CALL CONTP5(GF,GR,GZ,NRM,NRMAX,NTHMAX,
     &               GGFMIN,GGFSTP,NSTEP,2,0,KA)
      ELSE
         CALL CONTP5(GF,GR,GZ,NRM,NRMAX,NTHMAX,
     &                0.5*GGFSTP, GGFSTP,NSTEP,2,0,KA)
         CALL CONTP5(GF,GR,GZ,NRM,NRMAX,NTHMAX,
     &               -0.5*GGFSTP,-GGFSTP,NSTEP,2,2,KA)
      ENDIF
      CALL SETLIN(-1,-1,6)
      CALL GPLOTP(GRSU,GZSU,1,NSUMAX,1,0,0,0)
      CALL SETLIN(-1,-1,5)
      CALL GPLOTP(GRSW,GZSW,1,NSUMAX,1,0,0,0)
C
      CALL SETLIN(0,0,7)
      CALL MOVE(16.5,17.0)
      CALL TEXT('MAX :',5)
      CALL NUMBR(GFMAX,'(1PE12.4)',12)
      CALL MOVE(16.5,16.5)
      CALL TEXT('MIN :',5)
      CALL NUMBR(GFMIN,'(1PE12.4)',12)
      CALL MOVE(16.5,16.0)
      CALL TEXT('STEP:',5)
      CALL NUMBR(GGFSTP,'(1PE12.4)',12)
C
      CALL PAGEE
C
      RETURN
      END
