C     $Id$
C
      IMPLICIT COMPLEX*16(C),REAL*8(A,B,D-F,H,O-Z)
      CHARACTER*72 KNAMEQ
C
      CALL GSOPEN
    1 WRITE(6,*) '#EQ> INPUT 1:TASK/EQ  2:JFT2M'
      READ(5,*,ERR=1,END=9000) MODELG
      IF(MODELG.EQ.1) THEN
         KNAMEQ='eqdata'
      ELSE
         KNAMEQ='data1'
      ENDIF
      CALL EQLOAD(MODELG,KNAMEQ,IERR)
      IF(IERR.EQ.1) GOTO 1
      CALL EQSETP
      NRMAX1=NRMAX
      NTHMAX1=NTHMAX
      NSUMAX1=NSUMAX
      CALL EQPSIC(NRMAX1,NTHMAX1,NSUMAX1,IERR)
C
    2 WRITE(6,*) '#EQ> INPUT PSIN'
      READ(5,*,ERR=2,END=9000) PSIN
      IF(PSIN.LT.0.D0) GOTO 9000
      CALL GETPP(PSIN,PP)
      CALL GETQP(PSIN,QP)
      CALL GETRMN(PSIN,RRMINL)
      CALL GETRMX(PSIN,RRMAXL)
      WRITE(6,'(A,1P4E12.4)') 'PP,QP,RRMIN,RRMAX =',PP,QP,RRMINL,RRMAXL
      GOTO 2
C
 9000 CALL GSCLOS
      STOP
      END
