C     $Id$
C
C     ***** GET PARAMETERS *****
C
      SUBROUTINE EQGETP(RHOT1,PSIP1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION RHOT1(NRMAX1),PSIP1(NRMAX1)
C
      DO NR=1,NRMAX1
         RHOT1(NR)=RHOT(NR)
         PSIP1(NR)=PSIP(NR)
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETR(RPS1,DRPSI1,DRCHI1,NTHM1,NTHMAX1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION RPS1(NTHM1,NRMAX1)
      DIMENSION DRPSI1(NTHM1,NRMAX1),DRCHI1(NTHM1,NRMAX1)
C
      DO NR=1,NRMAX1
      DO NTH=1,NTHMAX1
         RPS1  (NTH,NR)=RPS  (NTH,NR)
         DRPSI1(NTH,NR)=DRPSI(NTH,NR)
         DRCHI1(NTH,NR)=DRCHI(NTH,NR)
C         IF(NR.LE.3) THEN
C            WRITE(6,'(2I5,1P3E12.4)') 
C     &           NR,NTH,RPS(NTH,NR),DRPSI(NTH,NR),DRCHI(NTH,NR)
C         ENDIF
      ENDDO
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETZ(ZPS1,DZPSI1,DZCHI1,NTHM1,NTHMAX1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION ZPS1(NTHM1,NRMAX1)
      DIMENSION DZPSI1(NTHM1,NRMAX1),DZCHI1(NTHM1,NRMAX1)
C
      DO NR=1,NRMAX1
      DO NTH=1,NTHMAX1
         ZPS1  (NTH,NR)=ZPS  (NTH,NR)
         DZPSI1(NTH,NR)=DZPSI(NTH,NR)
         DZCHI1(NTH,NR)=DZCHI(NTH,NR)
      ENDDO
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETQ(PPS1,QPS1,RBPS1,VPS1,RLEN1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION PPS1(NRMAX1),QPS1(NRMAX1),RBPS1(NRMAX1)
      DIMENSION VPS1(NRMAX1),RLEN1(NRMAX1)
C
      DO NR=1,NRMAX1
         PPS1(NR) =PPS(NR)
         QPS1(NR) =QPS(NR)
         RBPS1(NR)=TTS(NR)
         VPS1(NR) =VPS(NR)
         RLEN1(NR)=RLEN(NR)
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETU(RSU1,ZSU1,RSW1,ZSW1,NSUMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION RSU1(NSUMAX1),ZSU1(NSUMAX1)
      DIMENSION RSW1(NSUMAX1),ZSW1(NSUMAX1)
C
      DO NSU=1,NSUMAX1
         RSU1(NSU)=RSU(NSU)
         ZSU1(NSU)=ZSU(NSU)
         RSW1(NSU)=RSW(NSU)
         ZSW1(NSU)=ZSW(NSU)
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETF(RGMIN1,RGMAX1,ZGMIN1,ZGMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
C
      RGMIN1=RGMIN
      RGMAX1=RGMAX
      ZGMIN1=ZGMIN
      ZGMAX1=ZGMAX
      RETURN
      END
C
      SUBROUTINE EQGETA(RAXIS1,ZAXIS1,PSIPA1,PSITA1,Q01,QA1)
C
      INCLUDE '../eq/eqcomq.inc'
C
      RAXIS1=RAXIS
      ZAXIS1=ZAXIS
      PSIPA1=PSIPA
      PSITA1=PSITA
      Q01   =QAXIS
      QA1   =QSURF
      RETURN
      END
C
      SUBROUTINE EQGETG(RPS1,ZPS1,NTHM1,NTHMAX1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION RPS1(NTHM1,NRMAX1)
      DIMENSION ZPS1(NTHM1,NRMAX1)
C
      DO NR=1,NRMAX1
      DO NTH=1,NTHMAX1
         RPS1  (NTH,NR)=RPS  (NTH,NR)
         ZPS1  (NTH,NR)=ZPS  (NTH,NR)
      ENDDO
      ENDDO
      RETURN
      END
C
      SUBROUTINE EQGETBB(BPR1,BPZ1,BPT1,BTP1,NTHM1,NTHMAX1,NRMAX1)
C
      INCLUDE '../eq/eqcomq.inc'
      DIMENSION BPR1(NTHM1,NRMAX1)
      DIMENSION BPZ1(NTHM1,NRMAX1)
      DIMENSION BPT1(NTHM1,NRMAX1)
      DIMENSION BTP1(NTHM1,NRMAX1)
C
      DO NR=1,NRMAX1
      DO NTH=1,NTHMAX1
         BPR1(NTH,NR)=BPR(NTH,NR)
         BPZ1(NTH,NR)=BPZ(NTH,NR)
         BPT1(NTH,NR)=BPT(NTH,NR)
         BTP1(NTH,NR)=BTP(NTH,NR)
      ENDDO
      ENDDO
      RETURN
      END
