MODULE grf2dpexec

  PRIVATE
  PUBLIC grf2dp_exec

CONTAINS

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DP_EXEC(GX,GY,GF,NFMAX,A,WLM,LINE_RGB_SUB,MARK_RGB_SUB)

    USE grftype, ONLY: grf_attr_type
    USE grfutils, ONLY: grf_title, grf_frame2d, grf_frame3d ,grf_info, setrgba
    IMPLICIT NONE

    TYPE(grf_attr_type),INTENT(IN):: A
    REAL(4),INTENT(IN):: GX(NFMAX),GY(NFMAX),GF(NFMAX)
    INTEGER,INTENT(IN):: NFMAX
    REAL(4),INTENT(IN):: WLM(A%NPMAX)
    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE MARK_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE MARK_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,MARK_RGB_SUB

    REAL(4):: FSTEP
    INTEGER(4):: NL
    INTERFACE
       SUBROUTINE R2W2B(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE R2W2B
       SUBROUTINE W2G2B(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE W2G2B
       SUBROUTINE R2Y2W(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE R2Y2W
    END INTERFACE

       CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                   A%XMIN,A%XMAX,A%YMIN,A%YMAX)

       SELECT CASE(A%MODE_XY)
       CASE(0)
          CALL PLOTG2(GF,GX,GY,A%NXMIN,NFMAX,A%NXSTEP, &
               A%LINE_VALUE,A%LINE_RGB,A%LINE_PAT,A%LINE_THICKNESS,A%NLMAX, &
               A%PAINT_VALUE,A%PAINT_RGB,A%LINE_MARK,A%LINE_MARK_STEP, &
               A%LINE_MARK_SIZE,WLM,A%NPMAX,A%MODE_PRD)
       CASE(1)
          CALL PLOTG3(GF,GX,GY,A%NXMIN,NFMAX,A%NXSTEP, &
               A%LINE_VALUE,A%LINE_RGB,A%LINE_PAT,A%LINE_THICKNESS,A%NLMAX, &
               A%PAINT_VALUE,A%PAINT_RGB,A%LINE_MARK,A%LINE_MARK_STEP, &
               A%LINE_MARK_SIZE,WLM,A%NPMAX,A%MODE_PRD)
       CASE(2)
          CALL PLOTG4(GF,GX,GY,A%NXMIN,NFMAX,A%NXSTEP, &
               A%LINE_VALUE,A%LINE_RGB,A%LINE_PAT,A%LINE_THICKNESS,A%NLMAX, &
               A%PAINT_VALUE,A%PAINT_RGB,A%LINE_MARK,A%LINE_MARK_STEP, &
               A%LINE_MARK_SIZE,WLM,A%NPMAX,A%MODE_PRD)
       END SELECT

       IF(A%NOFRAME.EQ.0) CALL GRF_FRAME2D(A)
       IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)
       IF(A%NOINFO.EQ.0)  CALL GRF_INFO(A)

    CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2DP_EXEC

END MODULE grf2dpexec
