C     $Id$
C
C     ******* OUTPUT ELEMENT DATA *******
C
      SUBROUTINE WFWELM
C
      INCLUDE 'wfcomm.inc'
      CHARACTER KNAME*32
      LOGICAL LEX
C
    1 WRITE(6,*) '## ENTER ELEMENT FILE NAME: ',KFNAME
      READ(5,'(A32)',ERR=1,END=9000) KNAME
      IF(KNAME(1:2).NE.'/ ') KFNAME=KNAME
      INQUIRE(FILE=KFNAME,EXIST=LEX)
      IF(LEX) THEN
         OPEN(25,FILE=KFNAME,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## OLD FILE (',KFNAME,') IS ASSIGNED FOR OUTPUT.'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ELSE
         OPEN(25,FILE=KFNAME,IOSTAT=IST,STATUS='NEW',ERR=20,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## NEW FILE (',KFNAME,') IS CREATED FOR OUTPUT.'
         GOTO 30
   20    WRITE(6,*) 'XX NEW FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ENDIF
C
   30 WRITE(25) BXMIN,BXMAX,BYMIN,BYMAX,RB,BKAP,BDEL
      WRITE(25) NNOD,NELM
      WRITE(25) (XD(I),YD(I),I=1,NNOD)
      WRITE(25) ((IELM(J,I),J=1,3),I=1,NELM)
      CLOSE(25)
C
      WRITE(6,*) '## ELEMENT DATA SAVED IN FILE: ',KFNAME
 9000 RETURN
      END
C
C     ******* INPUT ELEMENT DATA *******
C
      SUBROUTINE WFRELM
C
      INCLUDE 'wfcomm.inc'
      LOGICAL LEX
C
      INQUIRE(FILE=KFNAME,EXIST=LEX)
      IF(LEX) THEN
         OPEN(25,FILE=KFNAME,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## FILE (',KFNAME,') IS ASSIGNED FOR ELM INPUT'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 9000
      ELSE
         WRITE(6,*) 'XX FILE (',KFNAME,') IS NOT FOUND'
         GOTO 9000
      ENDIF
C
   30 READ(25,ERR=9100,END=9200) BXMIN,BXMAX,BYMIN,BYMAX,RB,BKAP,BDEL
      READ(25,ERR=9100,END=9200) NNOD,NELM
C
      IF(NNOD.GT.NNODM.OR.
     &   NELM.GT.NELMM) THEN
         WRITE(6,800) NNOD,NNODM,NELM,NELMM
  800    FORMAT(1H ,'XX ELEMENT DATA EXCEEDS ARAAY DIMENSION :'/
     &          1H ,'  NNOD NNODM  NELM NELMM'/1H ,4I6)
         GOTO 9000
      ENDIF
C
      READ(25,ERR=9100,END=9200) (XD(I),YD(I),I=1,NNOD)
      READ(25,ERR=9100,END=9200) ((IELM(J,I),J=1,3),I=1,NELM)
      CLOSE(25)
C
      CALL WFGINI
      NDMAX=0
      NBWMAX=0
      NBPMAX=0
      NMMAX=1
      NVWMAX=0
      NVPMAX=0
C
 9000 RETURN
C
 9100 WRITE(6,*) 'XX ERROR IN READING FILE: ',KFNAME
      GOTO 9000
C
 9200 WRITE(6,*) 'XX UNEXPECTED END OF FILE: ',KFNAME
      GOTO 9000
      END
C
C     ******* OUTPUT ZONE DATA *******
C
      SUBROUTINE WFWZON
C
      INCLUDE 'wfcomm.inc'
      CHARACTER KNAME*32
      LOGICAL LEX
C
    1 WRITE(6,*) '## ENTER ZONE FILE NAME: ',KFNAMZ
      READ(5,'(A32)',ERR=1,END=9000) KNAME
      IF(KNAME(1:2).NE.'/ ') KFNAMZ=KNAME
      INQUIRE(FILE=KFNAMZ,EXIST=LEX)
      IF(LEX) THEN
         OPEN(25,FILE=KFNAMZ,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## OLD FILE (',KFNAMZ,') IS ASSIGNED FOR OUTPUT.'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ELSE
         OPEN(25,FILE=KFNAMZ,IOSTAT=IST,STATUS='NEW',ERR=20,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## NEW FILE (',KFNAMZ,') IS CREATED FOR OUTPUT.'
         GOTO 30
   20    WRITE(6,*) 'XX NEW FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ENDIF
C
   30 WRITE(25) NDMAX
      WRITE(25) (IDZONE(ND),(XYZONE(I,ND),I=1,4),ND=1,NDMAX)
      WRITE(25) NBWMAX
      WRITE(25) (IDBDYW(NBW),(XYBDYW(I,NBW),I=1,4),NBW=1,NBWMAX)
      WRITE(25) NBPMAX
      WRITE(25) (IDBDYP(NBP),(XYBDYP(I,NBP),I=1,4),NBP=1,NBPMAX)
      WRITE(25) NMMAX
      WRITE(25) (EPSDM(NM),RMUDM(NM),SIGDM(NM),NM=1,NMMAX)
      WRITE(25) NVWMAX
      WRITE(25) ((XYVARW(I,NVW),I=1,4),NVW=1,NVWMAX)
      WRITE(25) NVPMAX
      WRITE(25) ((XYVARP(I,NVP),I=1,4),NVP=1,NVPMAX)
      CLOSE(25)
C
      WRITE(6,*) '## ZONE DATA SAVED IN FILE: ',KFNAMZ
 9000 RETURN
      END
C
C     ******* INPUT ZONE DATA *******
C
      SUBROUTINE WFRZON
C
      INCLUDE 'wfcomm.inc'
      LOGICAL LEX
C
      NDMAX=0
      NBWMAX=0
      NBPMAX=0
      NMMAX=1
      NVWMAX=0
      NVPMAX=0
C
      INQUIRE(FILE=KFNAMZ,EXIST=LEX)
      IF(LEX) THEN
         OPEN(25,FILE=KFNAMZ,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## FILE (',KFNAMZ,') IS ASSIGNED FOR ZONE INPUT'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 9000
      ELSE
         WRITE(6,*) 'XX FILE (',KFNAMZ,') IS NOT FOUND'
         GOTO 9000
      ENDIF
C
   30 READ(25,ERR=9100,END=9200) NDMAX
      READ(25,ERR=9100,END=9200) 
     &     (IDZONE(ND),(XYZONE(I,ND),I=1,4),ND=1,NDMAX)
      READ(25,ERR=9100,END=9200) NBWMAX
      READ(25,ERR=9100,END=9200) 
     &     (IDBDYW(NBW),(XYBDYW(I,NBW),I=1,4),NBW=1,NBWMAX)
      READ(25,ERR=9100,END=9200) NBPMAX
      READ(25,ERR=9100,END=9200) 
     &     (IDBDYP(NBP),(XYBDYP(I,NBP),I=1,4),NBP=1,NBPMAX)
      READ(25,ERR=9100,END=9200) NMMAX
      READ(25,ERR=9100,END=9200) 
     &     (EPSDM(NM),RMUDM(NM),SIGDM(NM),NM=1,NMMAX)
      READ(25,ERR=9100,END=9200) NVWMAX
      READ(25,ERR=9100,END=9200) 
     &     ((XYVARW(I,NVW),I=1,4),NVW=1,NVWMAX)
      READ(25,ERR=9100,END=9200) NVPMAX
      READ(25,ERR=9100,END=9200) 
     &     ((XYVARP(I,NVP),I=1,4),NVP=1,NVPMAX)
      CLOSE(25)
C
      CALL WFSETZ
C
 9000 RETURN
C
 9100 WRITE(6,*) 'XX ERROR IN READING FILE: ',KFNAMZ
      GOTO 9000
C
 9200 WRITE(6,*) 'XX UNEXPECTED END OF FILE: ',KFNAMZ
      GOTO 9000
      END
C
C     ******* OUTPUT ANTENNA DATA *******
C
      SUBROUTINE WFWANT
C
      INCLUDE 'wfcomm.inc'
      CHARACTER KNAME*32
      LOGICAL LEX
C
    1 WRITE(6,*) '## ENTER ANTENNA FILE NAME: ',KFNAMA
      READ(5,'(A32)',ERR=1,END=9000) KNAME
      IF(KNAME(1:2).NE.'/ ') KFNAMA=KNAME
      INQUIRE(FILE=KFNAMA,EXIST=LEX)
      IF(LEX) THEN
         OPEN(24,FILE=KFNAMA,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='FORMATTED')
         WRITE(6,*) '## OLD FILE (',KFNAMA,') IS ASSIGNED FOR OUTPUT.'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ELSE
         OPEN(24,FILE=KFNAMA,IOSTAT=IST,STATUS='NEW',ERR=20,
     &        FORM='FORMATTED')
         WRITE(6,*) '## NEW FILE (',KFNAMA,') IS CREATED FOR OUTPUT.'
         GOTO 30
   20    WRITE(6,*) 'XX NEW FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ENDIF
C
   30 WRITE(24,200) NAMAX
  200 FORMAT(I6)
      DO 400 NA=1,NAMAX
         WRITE(24,250) NA,JNUM0(NA),NTYPJ0(NA)
  250    FORMAT(3I6)
         WRITE(24,255) RTJ0(1,NA),RTJ0(2,NA),THJ0(1,NA),THJ0(2,NA)
  255    FORMAT(4E15.7)
         WRITE(24,300) (XJ0(I,NA),YJ0(I,NA),I=1,JNUM0(NA))
  300    FORMAT(2E15.7)
  400 CONTINUE
      CLOSE(24)
C
      WRITE(6,*) '## ANTENNA DATA SAVED IN FILE: ',KFNAMA
 9000 RETURN
      END
C
C     ******* INPUT ANTENNA DATA FROM FILE 24 *******
C
      SUBROUTINE WFRANT
C
      INCLUDE 'wfcomm.inc'
      LOGICAL LEX
C
      INQUIRE(FILE=KFNAMA,EXIST=LEX)
      IF(LEX) THEN
         OPEN(24,FILE=KFNAMA,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='FORMATTED')
         WRITE(6,*) '## FILE (',KFNAMA,') IS ASSIGNED FOR ANT INPUT'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 9000
      ELSE
         WRITE(6,*) 'XX FILE (',KFNAMA,') IS NOT FOUND'
         GOTO 9000
      ENDIF
C
   30 READ(24,150,ERR=9100,END=9200) NAMAX
  150 FORMAT(I6)
      IF(NAMAX.LT.1.OR.NAMAX.GT.NAM) THEN
         WRITE(6,*) 'XX INVALID ANTENNA DATA: NAMAX,NAM = ',NAMAX,NAM
         GOTO 9000
      ENDIF
C
      DO 20 NA=1,NAMAX
         READ(24,250,ERR=9100,END=9200) NA_in,JNUM0(NA),NTYPJ0(NA)
  250    FORMAT(3I6)
         IF(JNUM0(NA).GT.JNUMM.OR.JNUM0(NA).LT.1) THEN
            WRITE(6,*) 'XX INVALID ANTENNA DATA: NA,JNUM0,JNUMM =',
     &                 NA,JNUM0(NA),JNUMM
            GOTO 9000
         ENDIF
         READ(24,255,ERR=9100,END=9200) 
     &        RTJ0(1,NA),RTJ0(2,NA),THJ0(1,NA),THJ0(2,NA)
  255    FORMAT(4E15.7)
         READ(24,300,ERR=9100,END=9200) 
     &        (XJ0(I,NA),YJ0(I,NA),I=1,JNUM0(NA))
  300    FORMAT(2E15.7)
   20 CONTINUE
      CLOSE(24)
C
      CALL MODANT(IERR)
C
 9000 RETURN
C
 9100 WRITE(6,*) 'XX ERROR IN READING FILE: ',KFNAMA
      GOTO 9000
C
 9200 WRITE(6,*) 'XX UNEXPECTED END OF FILE: ',KFNAMA
      GOTO 9000
      END
C
C     ******* OUTPUT FIELD DATA *******
C
      SUBROUTINE WFWFLD
C
      INCLUDE 'wfcomm.inc'
      CHARACTER KNAME*32
      LOGICAL LEX
C
      IF(NFOPEN.EQ.0) THEN
C
    1 WRITE(6,*) '## ENTER FIELD FILE NAME: ',KFNAMF
      READ(5,'(A32)',ERR=1,END=9000) KNAME
      IF(KNAME(1:2).NE.'/ ') KFNAME=KNAME
      INQUIRE(FILE=KFNAMF,EXIST=LEX)
      IF(LEX) THEN
         OPEN(26,FILE=KFNAMF,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## OLD FILE (',KFNAMF,') IS ASSIGNED FOR OUTPUT.'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ELSE
         OPEN(26,FILE=KFNAMF,IOSTAT=IST,STATUS='NEW',ERR=20,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## NEW FILE (',KFNAMF,') IS CREATED FOR OUTPUT.'
         GOTO 30
   20    WRITE(6,*) 'XX NEW FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 1
      ENDIF
   30 NFOPEN=1
C
      ENDIF
C
      WRITE(26) MODELS,MODELB,MODELD,MODELP,MODELW,MODELT
      WRITE(26) NNOD,NELM
      WRITE(26) NSMAX,NAMAX,NRMAX,NZMAX
      WRITE(26) BB,RA
         WRITE(26) RR,QA,Q0,RKAP,RDEL
         WRITE(26) RMIR,ZBB,RR
         WRITE(26) H1,H2,RRC,RKAP
      WRITE(26) RF,RKZ,RZ,NPHI
      WRITE(26) (PA(NS),PZ(NS),PN(NS),PNS(NS),PZCL(NS),NS=1,NSMAX)
      WRITE(26) (PTPR(NS),PTPP(NS),PTS(NS),NS=1,NSMAX)
      WRITE(26) (AJ(NA),APH(NA),APOS(NA),AWD(NA),NA=1,NAMAX)
C
      WRITE(26) ((CEF(I,IN),I=1,3),IN=1,NNOD)
      WRITE(26) CTIMP,(CIMP(NA),NA=1,NAMAX)
      WRITE(26) PWR,(PWRN(IN),IN=1,NNOD)
      WRITE(26) (PWRS(NS),(PWRNS(IN,NS),IN=1,NNOD),NS=1,NSMAX)
      WRITE(26) (PWRR(NR),NR=1,NRMAX)
      WRITE(26) ((PWRRS(NR,NS),NR=1,NRMAX),NS=1,NSMAX)
      IF(NZMAX.GT.1) THEN
         WRITE(26) (RKZF(NZ),PWRF(NZ),NZ=1,NZMAX)
         WRITE(26) ((CAJF(NZ,NA),NZ=1,NZMAX),NA=1,NAMAX)
         WRITE(26) ((PWRFS(NZ,NS),NZ=1,NZMAX),NS=1,NSMAX)
      ENDIF
C
      WRITE(6,*) '## FIELD DATA SAVED IN FILE: ',KFNAMF
 9000 RETURN
      END
C
C     ****** INPUT FIELD DATA ******
C
      SUBROUTINE WFRFLD
C
      INCLUDE 'wfcomm.inc'
      LOGICAL LEX
C
      IF(NFOPEN.EQ.0) THEN
C
      INQUIRE(FILE=KFNAMF,EXIST=LEX)
      IF(LEX) THEN
         OPEN(26,FILE=KFNAMF,IOSTAT=IST,STATUS='OLD',ERR=10,
     &        FORM='UNFORMATTED')
         WRITE(6,*) '## FILE (',KFNAMF,') IS ASSIGNED FOR FLD INPUT'
         GOTO 30
   10    WRITE(6,*) 'XX OLD FILE OPEN ERROR : IOSTAT = ',IST
         GOTO 9000
      ELSE
         WRITE(6,*) 'XX FILE (',KFNAMF,') IS NOT FOUND'
         GOTO 9000
      ENDIF
   30 NFOPEN=1
C
      ENDIF
C
      READ(26,ERR=9100,END=9200) 
     &     MODELS,MODELB,MODELD,MODELP,MODELW,MODELT
C
      READ(26,ERR=9100,END=9200) NNOD,NELM
      READ(26,ERR=9100,END=9200) NSMAX,NAMAX,NRMAX,NZMAX
      READ(26,ERR=9100,END=9200) BB,RA
         READ(26,ERR=9100,END=9200) RR,QA,Q0,RKAP,RDEL
         READ(26,ERR=9100,END=9200) RMIR,ZBB,RR
         READ(26,ERR=9100,END=9200) H1,H2,RRC,RKAP
      READ(26,ERR=9100,END=9200) RF,RKZ,RZ,NPHI
      READ(26,ERR=9100,END=9200) 
     &     (PA(NS),PZ(NS),PN(NS),PNS(NS),PZCL(NS),NS=1,NSMAX)
      READ(26,ERR=9100,END=9200) 
     &     (PTPR(NS),PTPP(NS),PTS(NS),NS=1,NSMAX)
      READ(26,ERR=9100,END=9200) 
     &     (AJ(NA),APH(NA),APOS(NA),AWD(NA),NA=1,NAMAX)
C
      READ(26,ERR=9100,END=9200) 
     &     ((CEF(I,IN),I=1,3),IN=1,NNOD)
      READ(26,ERR=9100,END=9200) 
     &     CTIMP,(CIMP(NA),NA=1,NAMAX)
      READ(26,ERR=9100,END=9200) 
     &     PWR,(PWRN(IN),IN=1,NNOD)
      READ(26,ERR=9100,END=9200) 
     &     (PWRS(NS),(PWRNS(IN,NS),IN=1,NNOD),NS=1,NSMAX)
      READ(26,ERR=9100,END=9200) 
     &     (PWRR(NR),NR=1,NRMAX)
      READ(26,ERR=9100,END=9200) 
     &     ((PWRRS(NR,NS),NR=1,NRMAX),NS=1,NSMAX)
      IF(NZMAX.GT.1) THEN
         READ(26,ERR=9100,END=9200) 
     &        (RKZF(NZ),PWRF(NZ),NZ=1,NZMAX)
         READ(26,ERR=9100,END=9200) 
     &        ((CAJF(NZ,NA),NZ=1,NZMAX),NA=1,NAMAX)
         READ(26,ERR=9100,END=9200) 
     &        ((PWRFS(NZ,NS),NZ=1,NZMAX),NS=1,NSMAX)
      ENDIF
C
 9000 RETURN
C
 9100 WRITE(6,*) 'XX ERROR IN READING FILE: ',KFNAMF
      GOTO 9000
C
 9200 WRITE(6,*) 'XX UNEXPECTED END OF FILE: ',KFNAMF
      GOTO 9000
      END
