C
C     ======( PHYSICAL CONSTANTS )======
C
C        PI    : Pi
C        AEE   : Elementaty charge
C        AME   : Electron mass
C        AMP   : Proton mass
C        VC    : Speed of light in vacuum
C        RMU0  : Permeability of free space
C        EPS0  : Permittivity of free space
C        CI    : Imaginary unit
C
      PI    = 2.D0*ACOS(0.D0)
      AEE   = 1.6021892  D-19
      AME   = 9.109534   D-31
      AMP   = 1.6726485  D-27
      VC    = 2.99792458 D  8
      RMU0  = 4.D0*PI*1.D-7
      EPS0  = 1.D0/(VC*VC*RMU0)
      CI    = (0.D0,1.D0)
