MODULE PLCOM3
  IMPLICIT NONE
  INTEGER(4), PARAMETER :: NRM   = 201
  INTEGER(4), PARAMETER :: NWRM  = 4
  INTEGER(4), PARAMETER :: NWMM  = 4
  INTEGER(4), PARAMETER :: NRMPP = NRM+2
END MODULE

MODULE PLDAT0
  IMPLICIT NONE
  INTEGER(4) :: NRMAXPL, NSMAXPL, NWRMAX, NWMMAX, NSPL
END MODULE

MODULE PLDAT1
  USE PLCOM3, ONLY : NRM
  IMPLICIT NONE
  REAL(8), DIMENSION(NRM) :: RGPL, RMPL
END MODULE

MODULE PLDAT2
  USE PLCOM0
  USE PLCOM3, ONLY : NRM
  IMPLICIT NONE
  REAL(8), DIMENSION(NRM,NSM) :: RNPL, RTPL, RUPL
END MODULE

MODULE PLDAT3
  USE PLCOM0
  USE PLCOM3, ONLY : NRM, NWRM
  IMPLICIT NONE
  REAL(8), DIMENSION(NRM,NSM,NWRM) :: PWRPL
  REAL(8), DIMENSION(NRM,NWRM)     :: AJWRPL
END MODULE

MODULE PLDAT4
  USE PLCOM0
  USE PLCOM3, ONLY : NRM, NWMM
  IMPLICIT NONE
  REAL(8), DIMENSION(NRM,NSM,NWMM) :: PWMPL
  REAL(8), DIMENSION(NRM,NWMM)     :: AJWMPL
END MODULE

MODULE PLDAT5
  USE PLCOM3, ONLY : NWRM, NWMM
  IMPLICIT NONE
  CHARACTER(LEN=80),DIMENSION(NWRM) :: KIDWR
  CHARACTER(LEN=80),DIMENSION(NWMM) :: KIDWM
END MODULE

MODULE PLDAT6
  USE PLCOM0
  USE PLCOM3, ONLY : NRMPP
  IMPLICIT NONE
  REAL(8), DIMENSION(4,NRMPP,NSM) :: URNPL, URTPL
END MODULE

MODULE PLDAT7
  USE PLCOM0
  USE PLCOM3, ONLY : NRMPP
  IMPLICIT NONE
  REAL(8), DIMENSION(4,NRMPP,NSM) :: URUPL
  REAL(8), DIMENSION(NRMPP)       :: URPL
END MODULE
