MODULE PLPRM1
  IMPLICIT NONE
  REAL(8) :: RR, RA, RB, RKAP, RDLT
END MODULE

MODULE PLPRM2
  IMPLICIT NONE
  REAL(8) :: BB, Q0, QA, RIP, PROFJ
END MODULE

MODULE PLPRM3
  IMPLICIT NONE
  INTEGER(4) :: NSMAX
END MODULE

MODULE PLPRM4
  USE PLCOM0
  IMPLICIT NONE
  REAL(8), DIMENSION(NSM) :: PA, PZ, PN, PNS, PZCL
END MODULE

MODULE PLPRM5
  USE PLCOM0
  IMPLICIT NONE
  REAL(8), DIMENSION(NSM) :: PTPR, PTPP, PTS, PU, PUS
END MODULE

MODULE PLPRM6
  IMPLICIT NONE
  REAL(8) :: PROFN1, PROFN2, PROFT1, PROFT2, PROFU1, PROFU2
END MODULE

MODULE PLPRM7
  IMPLICIT NONE
  REAL(8) :: RHOMIN, QMIN, RHOEDG
END MODULE

MODULE PLPRM8
  USE PLCOM0
  IMPLICIT NONE
  REAL(8), DIMENSION(NSM) :: PNITB, PTITB, PUITB
  REAL(8)                 :: RHOITB
END MODULE

MODULE PLPRM9
  IMPLICIT NONE
  INTEGER(4) :: MODELG, MODELN, MODELQ
END MODULE

MODULE PLPRG1
  IMPLICIT NONE
  REAL(8) :: RHOGMN, RHOGMX
END MODULE

MODULE PLDBG1
  IMPLICIT NONE
  INTEGER(4) :: IDEBUG
END MODULE

MODULE PLNAM1
  IMPLICIT NONE
  CHARACTER(LEN=80) :: KNAMEQ, KNAMWR, KNAMFP, KNAMWM, KNAMPF, KNAMFO
END MODULE

MODULE PLNAM2
  IMPLICIT NONE
  CHARACTER(LEN=80) :: KNAMTR
END MODULE
