MODULE TRCOM2
  IMPLICIT NONE

  CHARACTER(LEN=80) :: KXNDEV,KXNDCG,KXNID
  CHARACTER(LEN=80) :: KDIRW1,KDIRW2

  CONTAINS

  SUBROUTINE TRCOM2_INIT
    RETURN
  END SUBROUTINE TRCOM2_INIT

END MODULE TRCOM2
