MODULE TRCOM3
  IMPLICIT NONE

  INTEGER(4),PARAMETER        :: NSTMAX2 = 16
  REAL(8), DIMENSION(NSTMAX2) :: PA,PZ,PN,PNS,PT,PTS,PELPAT

  CONTAINS

  SUBROUTINE TRCOM3_INIT
    RETURN
  END SUBROUTINE TRCOM3_INIT

END MODULE TRCOM3
