C     $Id$
C
C     ***********************************************************
C
C           LOAD TRANSPORT DATA
C
C     ***********************************************************
C
      SUBROUTINE WMTRLOAD(KNAMTR1,IERR)
C
      USE libfio
      INCLUDE '../tr/trcomm.inc'
      DIMENSION RNPL(NRM,6),RTPL(NRM,6),RUPL(NRM,6)
      CHARACTER KNAMTR1*80
C
      CALL FROPEN(21,KNAMTR1,0,0,'TR',IERR)
      IF(IERR.NE.0) RETURN
C
      READ(21) MDLEQB,MDLEQN,MDLEQT,MDLEQU,MDLEQZ,MDLEQ0,MDLEQE,MDLEOI
      READ(21) NSS,NSV,NNS,NST,NEQMAX
      READ(21) NRMAX,NRAMAX,NROMAX,DT,NGPST,TSST
      READ(21) NTMAX,NTSTEP,NGTSTP,NGRSTP
      READ(21) RR,RA,RKAP,RDLT,BB,RIPS,RIPSS,RIPE,RHOA,PHIA
      READ(21) PA,PZ,PN,PNS,PT,PTS,NSMAX,NSZMAX,NSNMAX
      READ(21) PNC,PNFE,PNNU,PNNUS
      READ(21) PROFN1,PROFN2,PROFT1,PROFT2,PROFU1,PROFU2,PROFJ1,PROFJ2,
     &         ALP,AD0,AV0,CNP,CNH,CDP,CDH,CDW,CWEB,CALF,CNB
      READ(21) MDLKAI,MDLETA,MDLAD,MDLAVK,MDLJBS,MDLKNC,MDLTPF
      READ(21) TPRST,MDLST,MDLNF,IZERO
      READ(21) MODELG,NTEQIT
      READ(21) MDLXP,MDLUF,MDNCLS,MDLWLD,MDDIAG,MDDW,MDLFLX
      READ(21) KUFDEV,KUFDCG,TIME_INT,MODEP,MDNI,MDLJQ,MDTC,MDLPCK
      READ(21) PNBTOT,PNBR0,PNBRW,PNBENG,PNBRTG,MDLNB
      READ(21) PECTOT,PECR0,PECRW,PECTOE,PECNPR,MDLEC
      READ(21) PLHTOT,PLHR0,PLHRW,PLHTOE,PLHNPR,MDLLH
      READ(21) PICTOT,PICR0,PICRW,PICTOE,PICNPR,MDLIC
      READ(21) PNBCD,PECCD,PLHCD,PICCD,PBSCD,MDLCD
      READ(21) PELTOT,PELR0,PELRW,PELRAD,PELVEL,PELTIM,PELPAT,MDLPEL
      READ(21) DR,PNSS,T,TST,VSEC,WPPRE,TPRE,KFNLOG,NTMAX_SAVE
      READ(21) RG,RM,RN,RT,RU,RW,BP,RDP,RPSI,RNF,RTF,ANC,ANFE,ANNU
      READ(21) VTOR,VPOL,AJOH,ETA,AMZ
      READ(21) EPSLTR,LMAXTR,CHP,CK0,CK1,CKALFA,CKBETA,CKGUMA,CNB,CALF
      READ(21) DVRHO,TTRHO,ABRHO,ARRHO,AR1RHO,AR2RHO,RMJRHO,RMNRHO,
     &         RKPRHO,RJCB,EPSRHO
      READ(21) DVRHOG,TTRHOG,ABRHOG,ARRHOG,AR1RHOG,AR2RHOG,
     &         RMJRHOG,RMNRHOG,ABB2RHOG,AIB2RHOG,ARHBRHOG,RKPRHOG
      CLOSE(21)
C
      WRITE(6,*) '# DATA WAS SUCCESSFULLY LOADED FROM THE FILE.'
      IREAD=1
C
      CALL PLDATA_SETN(NRMAX,6)
      CALL PLDATA_SETR(RG,RM)
C
      DO NS=1,4
         DO NR=1,NRMAX
            RNPL(NR,NS)=RN(NR,NS)
            RTPL(NR,NS)=RT(NR,NS)
            RUPL(NR,NS)=RU(NR,NS)
         ENDDO
      ENDDO
C
      DO NS=5,6
         DO NR=1,NRMAX
            RNPL(NR,NS)=RNF(NR,NS-4)
            RTPL(NR,NS)=RTF(NR,NS-4)
            RUPL(NR,NS)=0.D0
         ENDDO
      ENDDO
C
      CALL PLDATA_SETP(NRM,RNPL,RTPL,RUPL)
C
  900 RETURN
      END
