all:
	(cd ../lib; make)
	(cd ../pl; make)
	(cd ../eq; make)
#	(cd ../equ; make)
	(cd trcore; make trcomm.o trlib.o)
	(cd trufile; make)
	(cd trmodels; make)
	(cd trsources; make)
	(cd trgraphics; make)
	(cd trcore; make)

clean:
	(cd trcore; make clean)
	(cd trufile; make clean)
	(cd trmodels; make clean)
	(cd trsources; make clean)
	(cd trgraphics; make clean)

veryclean:
	(cd trcore; make veryclean)
	(cd trufile; make veryclean)
	(cd trmodels; make veryclean)
	(cd trsources; make veryclean)
	(cd trgraphics; make veryclean)
