all:
	(cd ../lib; make)
	(cd ../plx; make)
	(cd ../pl; make)
	(cd ../eq; make)
	(cd trcore; make trcomm.o)
	(cd trmodels; make)
	(cd trcore; make)

clean:
	(cd trcore; make clean)
	(cd trmodels; make clean)
