C
C     ***** Draw Dispersion Relation *****
C
      SUBROUTINE w1gdsp

      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PRM6/ IELEC(ISM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1BND1/ CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1PRM5/ EPSH
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,NCDTYP
      SAVE PKXMIN,PKXMAX,XMIN,XMAX,RASAVE
      DATA INIT/0/
C
      IF(INIT.EQ.0) THEN
         PKXMIN=-1000.D0
         PKXMAX= 1000.D0
         XMIN=-RA
         XMAX= RA
         INIT=1
         RASAVE=RA
      ELSE IF(RA.NE.RASAVE) THEN
         XMIN=-RA
         XMAX= RA
         INIT=1
         RASAVE=RA
      END IF

  100    WRITE(6,*) '## INPUT : XMIN,XMAX,KXMIN,KXMAX,NXP ?'
         WRITE(6,'(1P4E12.4,I5)') XMIN,XMAX,PKXMIN,PKXMAX,NXP
         NXP1=NXP
         READ(5,*,ERR=100,END=9000) XMIN,XMAX,PKXMIN,PKXMAX,NXP1
         IF(ABS(XMAX-XMIN).LE.1.D-32) GOTO 9000
         IF(NXP1.EQ.0) GO TO 9000
         NXP=NXP1
         DO 110 NX=1,NXP
            XAM(NX)=XMIN+(XMAX-XMIN)*(NX-0.5)/NXP
  110    CONTINUE
         CALL W1PROF
         NZ=1
         CALL W1DSPA(NALPHA)
         IF(NMODEL.LE.3) THEN
            CALL W1WKXB
         ELSE
            CALL W1WKXD
         ENDIF
         CALL W1GDSP1(PKXMIN,PKXMAX)
         GOTO 100
C
 9000    CONTINUE
         RETURN
      END
