C
C   ***** TASK/W1 W1GOUT Graphic output *****
C
      SUBROUTINE W1GOUT
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PRM6/ IELEC(ISM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1BND1/ CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1PRM5/ EPSH
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,NCDTYP

      IF(NZP.EQ.1) THEN
         WRITE(6,'(A)') 
     &     '## W1 GRAPH MENU: IF(NZP.EQ.1) THEN
               CALL W1GR1D(MOD(NGRAPH,   4))
               CALL W1GR1B(MOD(NGRAPH/4, 2))
               CALL W1GR1F(MOD(NGRAPH/8, 2))
               CALL W1GR1H(MOD(NGRAPH/16,2))
               CALL W1GRUD(MOD(NGRAPH/32,2))
               CALL W1GRUF(MOD(NGRAPH/64,2))
            ELSE
               CALL W1GR2D(MOD(NGRAPH,   4))
               CALL W1GR1D(MOD(NGRAPH,   4))
            ENDIF
         ENDIF
         IF(NLOOP.NE.1) THEN
            RF   = RF   + DRF
            RKZ  = RKZ  + DRKZ
         ENDIF
 2000 CONTINUE
C
      RF =RFSAVE
      RKZ=RKSAVE
      CALL FCLOCK(TT2)
      WRITE(6,699) (TT2-TT1)
  699 FORMAT(1H ,'## CPU TIME = ',F15.3,' SEC')
      RETURN
  616 FORMAT('## INTEGRO-DIFF EQ. : ',
     &           'MATL    MATLM    ICL     NCLM    NDMAX   XDMAX'/
     &       22X,5I8,1P1D12.4)
  630 FORMAT(1H /
     &       1H ,'** RF = ',1PD12.4,' (MHZ) , RKZ = ',1PD12.4,
     &           ' (/M) **')
      END
