!     ****** FUNCTION FOR ALPHA PARTICLE ABSORPTION ******

MODULE w1alfa
  USE w1comm,ONLY: rkind
  REAL(rkind):: FY1,FY2,FY3
  INTEGER:: NY1,NY2

  PRIVATE
  PUBLIC W1FALF

CONTAINS

!     ****** SLAVE FUNCTION FOR DE INTEGRATEION ******

  FUNCTION W1FNA1(X,XP,XM)
    USE w1comm,ONLY: rkind
    USE libbes
    IMPLICIT NONE
    REAL(rkind),INTENT(IN):: X,XP,XM
    REAL(rkind):: W1FNA1
    INTEGER:: NN,ID
    REAL(rkind):: Y1,Y2,A,XX,DUMMY,ARG,BES,Y

    Y1=FY1
    Y2=FY2
    A =FY3
    NN=NY1
    ID=NY2
    XX=SINH(0.5D0*A*XP)/SINH(0.5D0*A)
    DUMMY=X
    DUMMY=XM
    ARG=Y1*XX
    IF(ID.EQ.1) THEN
       BES=NN*NN*XX*BESJNX(NN,ARG)**2/(Y1*Y1)
    ELSEIF(ID.EQ.2) THEN
       BES=NN*XX*XX*BESJNX(NN,ARG) &
                   *(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))*0.5D0/Y1
    ELSEIF(ID.EQ.3) THEN
       BES=NN*Y2*XX*BESJNX(NN,ARG)**2/Y1
    ELSEIF(ID.EQ.4) THEN
       BES=0.25D0*XX*XX*XX*(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))**2
    ELSEIF(ID.EQ.5) THEN
       BES=Y2*XX*XX*BESJNX(NN,ARG) &
                  *(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))*0.5D0
    ELSEIF(ID.EQ.6) THEN
       BES=Y2*Y2*XX*BESJNX(NN,ARG)**2
    END IF
    Y=SQRT(XX*XX+Y2*Y2)
    W1FNA1=COSH(0.5D0*A*XP)*Y*BES/(1.D0+Y**3)**2
    RETURN
  END FUNCTION W1FNA1

!     ****** SLAVE FUNCTION FOR DE INTEGRATEION ******

  FUNCTION W1FNA2(X,XP,XM)
    USE w1comm,ONLY: rkind
    USE libbes
    IMPLICIT NONE
    REAL(rkind),INTENT(IN):: X,XP,XM
    REAL(rkind):: W1FNA2
    INTEGER:: NN,ID
    REAL(rkind):: Y1,Y2,Y3,XX,DUMMY,ARG,BES,Y

    Y1=FY1
    Y2=FY2
    Y3=FY3
    NN=NY1
    ID=NY2
    XX=0.5D0*Y3*XP
    DUMMY=X
    DUMMY=XM
    ARG=Y1*XX
    IF(ID.EQ.1) THEN
       BES=NN*NN*XX*BESJNX(NN,ARG)**2/(Y1*Y1)
    ELSEIF(ID.EQ.2) THEN
       BES=NN*XX*XX*BESJNX(NN,ARG) &
                   *(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))*0.5D0/Y1
    ELSEIF(ID.EQ.3) THEN
       BES=NN*Y2*XX*BESJNX(NN,ARG)**2/Y1
    ELSEIF(ID.EQ.4) THEN
       BES=0.25D0*XX*XX*XX*(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))**2
    ELSEIF(ID.EQ.5) THEN
       BES=Y2*XX*XX*BESJNX(NN,ARG) &
                   *(BESJNX(NN-1,ARG)-BESJNX(NN+1,ARG))*0.5D0
    ELSEIF(ID.EQ.6) THEN
       BES=Y2*Y2*XX*BESJNX(NN,ARG)**2
    END IF
    Y=SQRT(XX*XX+Y2*Y2)
    W1FNA2=Y*BES/(1.D0+Y**3)**2
    RETURN
  END FUNCTION W1FNA2

  FUNCTION W1FALF(Y1,Y2,Y3,NN,ID)
    USE libde
    IMPLICIT NONE
    REAL(rkind),INTENT(IN):: Y1,Y2,Y3
    INTEGER,INTENT(IN):: NN,ID
    INTEGER:: NY1,NY2,ILST
    REAL(rkind):: A,FY1,FY2,FY3,W1FALF
    REAL(rkind):: H0,EPS,CS,ES

    IF(Y3.GT.2.D0) THEN
       A=2.D0*ACOSH(0.5D0*Y3)
       FY1=Y1
       FY2=Y2
       FY3=A
       NY1=NN
       NY2=ID
       H0=0.5D0
       EPS=1.D-6
       ILST=0
       CALL DEFT(CS,ES,H0,EPS,ILST,W1FNA1,'W1FNA1')
       W1FALF=0.5D0*A*CS/SINH(0.5D0*A)
    ELSE
       FY1=Y1
       FY2=Y2
       FY3=Y3
       NY1=NN
       NY2=ID
       H0=0.5D0
       EPS=1.D-6
       ILST=0
       CALL DEFT(CS,ES,H0,EPS,ILST,W1FNA2,'W1FNA2')
       W1FALF=0.5D0*Y3*CS
    END IF
    RETURN
  END FUNCTION W1FALF

END MODULE w1alfa
