C
C     ****** TASK/W1 (SUBROUTINE LIBRARY 1) ******
C
C
C     ****** 1-D GRAPHIC ROUTINE ******
C
      SUBROUTINE W1GRUD(NGRAPH)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      PARAMETER (NZPMP1=NZPM+1)
      REAL*4 GDATA1,GDATA2,GDATA3,GX,GXM,GZ,GDATAZ
      COMMON /W1GDAT/ GDATA1(NXTM),GDATA2(NXTM),GDATA3(NXTM),
     &                GX(NXTM),GXM(NXTM),GZ(NZPMP1),GDATAZ(NZPMP1)
      COMMON /W1WORK/ TEMP(NXTM,NZPM),NXPRNT(NXTM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,ICDTYP
      COMMON /W1BAH3/ AHLT(ISM,4),AHL(NXPM,ISM,4)
C
      REAL*4 GA,GB,GAMIN,GAMAX,GMIN,GMAX,SCAL
      REAL*4 GAMIN1,GAMIN2,GAMIN3,GAMAX1,GAMAX2,GAMAX3
C
      IF(NGRAPH.EQ.0) RETURN
C
      RNORM=1.D0/SQRT(PANT)
      RNORM2=RNORM*RNORM
C
    1 IF(NZP.EQ.1) THEN
         NZ=1
      ELSE
  100    CONTINUE
         WRITE(6,*) '## GRAPH INPUT : NZ  (0 : QUIT GRAPHIC)'
         READ(5,*,END=9990) NZ
         IF(NZ.GT.NZP) GOTO 100
         IF(NZ.LE.0) RETURN
      ENDIF
C
      CALL PAGES
      CALL SETMKS(0,0.1)
      CALL SETCHS(0.3,0.)
      CALL SETLIN(0,2,4)
      CALL MOVE( 2.5,17.7)
      CALL TEXT('EX,EY,EZ,PABS',13)
C
      GA=RA
      GB=RB
      DO 1010 NX=1,NXT
      NN        =NXPRNT(NX)
      GX    (NX)=XAM(NN)
      GXM   (NX)=XAM(NX)
      GDATA1(NX)= ABS(CE2DA(NZ,NN,1))*RNORM
      GDATA2(NX)=REAL(CE2DA(NZ,NN,1))*RNORM
      GDATA3(NX)=IMAG(CE2DA(NZ,NN,1))*RNORM
 1010 CONTINUE
      CALL GMNMX1(GDATA1,1,NXT,1,GAMIN,GAMAX)
      CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
      CALL GDEFIN(2.5,12.5,13.5,17.5,-GB,GB,-GMAX,GMAX)
      CALL GFRAME
      CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
      CALL SETLIN(0,1,7)
      CALL GPLOTP(GX, GDATA1,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,6)
      CALL GPLOTP(GX, GDATA2,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,5)
      CALL GPLOTP(GX, GDATA3,1,NXT,1, 0, 0,2)
      CALL SETLIN(0,2,4)
C
      DO 1020 NX=1,NXT
      NN        =NXPRNT(NX)
      GDATA1(NX)= ABS(CE2DA(NZ,NN,2))*RNORM
      GDATA2(NX)=REAL(CE2DA(NZ,NN,2))*RNORM
      GDATA3(NX)=IMAG(CE2DA(NZ,NN,2))*RNORM
 1020 CONTINUE
      CALL GMNMX1(GDATA1,1,NXT,1,GAMIN,GAMAX)
      CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
      CALL GDEFIN(2.5,12.5,9.5,13.5,-GB,GB,-GMAX,GMAX)
      CALL GFRAME
      CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
      CALL SETLIN(0,1,7)
      CALL GPLOTP(GX, GDATA1,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,6)
      CALL GPLOTP(GX, GDATA2,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,5)
      CALL GPLOTP(GX, GDATA3,1,NXT,1, 0, 0,2)
      CALL SETLIN(0,2,4)
C
      DO 1025 NX=1,NXT
      NN        =NXPRNT(NX)
      GDATA1(NX)= ABS(CE2DA(NZ,NN,3))*RNORM
      GDATA2(NX)=REAL(CE2DA(NZ,NN,3))*RNORM
      GDATA3(NX)=IMAG(CE2DA(NZ,NN,3))*RNORM
 1025 CONTINUE
      CALL GMNMX1(GDATA1,1,NXT,1,GAMIN,GAMAX)
      CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
      CALL GDEFIN(2.5,12.5,5.5,9.5,-GB,GB,-GMAX,GMAX)
      CALL GFRAME
      CALL GSCALE(0.,0.2,0.,2.*SCAL,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
C     CALL GVALUE(0.,REAL(RA),0.,0.,2)
      CALL SETLIN(0,1,7)
      CALL GPLOTP(GX, GDATA1,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,6)
      CALL GPLOTP(GX, GDATA2,1,NXT,1, 0, 0,0)
      CALL SETLIN(0,2,5)
      CALL GPLOTP(GX, GDATA3,1,NXT,1, 0, 0,2)
      CALL SETLIN(0,2,4)
C
      GMIN=0.0
      GMAX=0.0
      DO 1029 IS=1,ISMAX
         DO 1028 NX=1,NXP
            GDATA1(NX)=PABSX(NX,IS)*RNORM2
 1028    CONTINUE
         CALL GMNMX1(GDATA1,2,NXP-1,1,GAMIN,GAMAX)
         GMIN=MIN(GMIN,GAMIN)
         GMAX=MAX(GMAX,GAMAX)
 1029 CONTINUE
      GAMAX=MAX(ABS(GMAX),ABS(GMIN))
      CALL GQSCAL(0.,GAMAX,GMIN,GMAX,SCAL)
C
      CALL GDEFIN(2.5,12.5,1.5,5.5,-GB,GB,-0.1*GMAX,GMAX)
      CALL GFRAME
      CALL GSCALE(0.,0.2,0.,0.,0.1,9)
      CALL GSCALE(0.,0.,0.,SCAL,0.1,1)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,20.*SCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
      CALL GVALUE(0.,REAL(RA),0.,0.,2)
      DO 1040 IS=1,ISMAX
         CALL SETLIN(0,2,7-IS)
         DO 1039 NX=1,NXP
            GDATA1(NX)=PABSX(NX,IS)*RNORM2
 1039    CONTINUE
         CALL GPLOTP(GXM,GDATA1,1,NXP,1,-IS,10,0)
 1040 CONTINUE
      CALL SETLIN(0,2,4)
C
      IF(NMODEL.EQ.5.OR.NMODEL.EQ.3.OR.NMODEL.EQ.1) THEN
         DO 1130 NX=1,NXT
            NN        =NXPRNT(NX)
            GDATA1(NX)=FLUXX(NN)*RNORM2
 1130    CONTINUE
         CALL GMNMX1(GDATA1,1,NXT,1,GAMIN,GAMAX)
         IF(ABS(GAMIN).GE.ABS(GAMAX)) THEN
            DO 1131 NX=1,NXT
               GDATA1(NX)=-GDATA1(NX)
 1131       CONTINUE
         GAMAX=-GAMIN
         ENDIF
         CALL GQSCAL(0.,GAMAX*1.02,GMIN,GMAX,SCAL)
      CALL GDEFIN(2.5,12.5,1.5,5.5,-GB,GB,-0.1*GMAX,GMAX)
         CALL GSCALE(0.,0.,0.,SCAL,0.1,5)
         CALL SETLIN(0,2,7)
         CALL GPLOTP(GX, GDATA1,1,NXT,1,  0, 0,0)
      ENDIF
C
      CALL W1GPRM(NZ,NZP)
      CALL W1GPRX
C
      DO 4010 NX=1,NXP
         GDATA1(NX)=(AHL(NX,1,3)+AHL(NX,1,4))*RNORM2
         GDATA2(NX)=AHL(NX,1,3)*RNORM2
         GDATA3(NX)=AHL(NX,1,4)*RNORM2
 4010 CONTINUE
      CALL GMNMX1(GDATA1,1,NXP,1,GAMIN1,GAMAX1)
      CALL GMNMX1(GDATA2,1,NXP,1,GAMIN2,GAMAX2)
      CALL GMNMX1(GDATA3,1,NXP,1,GAMIN3,GAMAX3)
      GAMIN=MIN(GAMIN1,GAMIN2,GAMIN3)
      GAMAX=MAX(GAMAX1,GAMAX2,GAMAX3)
      CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
      CALL GDEFIN(15.0,25.0,1.5,5.5,-GB,GB,GMIN,GMAX)
      CALL GFRAME
      CALL GSCALE(0.,0.2,0.,2*SCAL,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,13.*SCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
      CALL GVALUE(0.,REAL(RA),0.,0.,2)
      CALL SETLIN(0,2,7)
C     CALL GPLOTP(GXM,GDATA1,1,NXP,1, 0, 0,0)
      CALL SETLIN(0,2,6)
      CALL GPLOTP(GXM,GDATA2,1,NXP,1,-7,10,0)
      CALL SETLIN(0,2,5)
      CALL GPLOTP(GXM,GDATA3,1,NXP,1, 0, 0,0)
      CALL SETLIN(0,2,4)
C
      CALL PAGEE
      IF(NZP.GT.1) GOTO 1
      RETURN
C
 9990 CONTINUE
      RETURN
      END
C
C     ****** 1-D GRAPHIC PARAMETER ******
C
      SUBROUTINE W1GPRM(NZ,NZP)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,ICDTYP
C
      IF(ABS(PANT).LE.1.D-30) THEN
         RNORM2=0.D0
      ELSE
         RNORM2=1.D0/PANT
      ENDIF
C
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,17.5)
      CALL TEXT('FREQ =',6)
      CALL NUMBD(RF,'(F9.4)',9)
      IF(NZP.EQ.1) THEN
         CALL TEXT('   K-PR =',9)
         CALL NUMBD(RKZ,'(F9.4)',9)
      ELSE
         CALL TEXT('   Z-POS=',9)
         CALL NUMBD(ZA(NZ),'(F9.4)',9)
      ENDIF
      CALL MOVE(14.,17.0)
      CALL TEXT('B    =',6)
      CALL NUMBD(BB,'(F9.4)',9)
      CALL TEXT('   WALLR=',9)
      CALL NUMBD(WALLR,'(1PE9.1)',9)
C
      CALL MOVE(14.,16.4)
      CALL TEXT('J-HI =',6)
      CALL NUMBD(AJYH(1),'(F9.4)',9)
      CALL TEXT('/',1)
      CALL NUMBD(RANT1,'(F8.4)',8)
      CALL NUMBD(XANT1,'(F9.4)',9)
      CALL MOVE(14.,15.9)
      CALL TEXT('J-LO =',6)
      CALL NUMBD(AJYL(1),'(F9.4)',9)
      CALL TEXT('/',1)
      CALL NUMBD(RANT2,'(F8.4)',8)
      CALL NUMBD(XANT2,'(F9.4)',9)
C
      CALL MOVE(14.,15.3)
      CALL TEXT('      ',6)
      DO 1200 ISDO=1,MIN(ISMAX,4)
         IS=ISDO
         CALL SETLIN(0,0,7-IS)
         CALL TEXT('     IS',7)
         CALL NUMBI(IS,'(I1)',1)
 1200 CONTINUE
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,14.8)
      CALL TEXT('N-20 =',6)
      DO 1210 IS=1,MIN(ISMAX,4)
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PN(IS),'(F8.3)',8)
 1210 CONTINUE
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,14.3)
      CALL TEXT('T-PP =',6)
      DO 1220 IS=1,MIN(ISMAX,4)
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PTPP(IS),'(F8.3)',8)
 1220 CONTINUE
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,13.8)
      CALL TEXT('T-PR =',6)
      DO 1230 IS=1,MIN(ISMAX,4)
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PTPR(IS),'(F8.3)',8)
 1230 CONTINUE
C
      IF(NZP.EQ.1.AND.NZ.EQ.0) RETURN
C
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,13.3)
      CALL TEXT('P/TOT=',6)
      DO 1240 IS=1,MIN(ISMAX,4)
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PABSXZ(IS)*RNORM2,'(F8.3)',8)
 1240 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(14.,12.7)
      CALL TEXT('PTOT =',6)
      CALL NUMBD(PABSTT*RNORM2,'(F9.4)',9)
      CALL TEXT('   JTOT =',9)
      CALL NUMBD(AJCDT*RNORM2,'(F9.4)',9)
C
      RETURN
      END
C
C     ****** 2-D GRAPHIC ROUTINE ******
C
      SUBROUTINE W1GR2D(NGRAPH)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PWR1/ PABSX(NXPM,ISM),FLUXX(NXTM),PABSXZ(ISM),PABSTT,
     &                RANT1(IAM),RANT2(IAM),XANT1(IAM),XANT2(IAM),
     &                PANT1,PANT2,PANT,PWALL1,PWALL2,PWALL,
     &                PIBW1,PIBW2,PIBW,PERR
      COMMON /W1PWR2/ PAKT(NZPM,3),PANTK(NZPM),PAK(NZPM,ISM)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      PARAMETER (NZPMP1=NZPM+1)
      REAL*4 GDATA1,GDATA2,GDATA3,GX,GXM,GZ,GDATAZ
      COMMON /W1GDAT/ GDATA1(NXTM),GDATA2(NXTM),GDATA3(NXTM),
     &                GX(NXTM),GXM(NXTM),GZ(NZPMP1),GDATAZ(NZPMP1)
      COMMON /W1WORK/ TEMP(NXTM,NZPM),NXPRNT(NXTM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,ICDTYP
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
C
      REAL*4 GMIN,GMAX,SCAL,GZMIN,GZMAX,GZSCL,GAMIN,GAMAX
      REAL*4 PGMIN,PGMAX,PSCAL,SGAMAX,PGAMIN,PGAMAX,GA,GB
C
      GA=RA
      GB=RB
      CALL PAGES
      CALL SETCHS(0.3,0.)
      CALL SETLIN(0,0,7)
C
      CALL MOVE(1.1,17.0)
      CALL TEXT(' FREQ=',6)
      CALL NUMBD(RF,'(F8.3)',8)
      CALL TEXT('     BB=',8)
      CALL NUMBD(BB,'(F8.3)',8)
      CALL TEXT('     RR=',8)
      CALL NUMBD(RR,'(F8.3)',8)
      CALL TEXT('     RZ=',8)
      CALL NUMBD(RZ,'(F8.3)',8)
      CALL TEXT('  WALLR=',8)
      CALL NUMBD(WALLR,'(1PE8.1)',8)
C
      CALL MOVE(1.1,16.5)
      CALL TEXT('  NXP=',6)
      CALL NUMBI(NXP,'(I8)',8)
      CALL TEXT('    NZP=',8)
      CALL NUMBI(NZP,'(I8)',8)
      CALL TEXT('     RA=',8)
      CALL NUMBD(RA,'(F8.3)',8)
      CALL TEXT('     RD=',8)
      CALL NUMBD(RD,'(F8.3)',8)
      CALL TEXT('     RB=',8)
      CALL NUMBD(RB,'(F8.3)',8)
C
      CALL MOVE(1.1,16.0)
      CALL TEXT('              ',14)
      CALL TEXT('                ',16)
      CALL TEXT('        ',8)
      DO 10 IS=1,ISMAX
         ISS=IS
         CALL SETLIN(0,0,7-IS)
         CALL TEXT('    IS-',7)
         CALL NUMBI(ISS,'(I1)',1)
   10 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,15.5)
      CALL TEXT('  J-H=',6)
      CALL NUMBD(AJYH(1),'(F8.3)',8)
      CALL TEXT('    J-L=',8)
      CALL NUMBD(AJYL(1),'(F8.3)',8)
      CALL TEXT('  N-20 :',8)
      DO 20 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PN(IS),'(F8.3)',8)
   20 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,15.0)
      CALL TEXT('  R-H=',6)
      CALL NUMBD(RANT1,'(F8.3)',8)
      CALL TEXT('    R-L=',8)
      CALL NUMBD(RANT2,'(F8.3)',8)
      CALL TEXT('  T-PR :',8)
      DO 30 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PTPR(IS),'(F8.3)',8)
   30 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,14.5)
      CALL TEXT('  X-H=',6)
      CALL NUMBD(XANT1,'(F8.3)',8)
      CALL TEXT('    X-L=',8)
      CALL NUMBD(XANT2,'(F8.3)',8)
      CALL TEXT('  T-PP :',8)
      DO 40 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PTPP(IS),'(F8.3)',8)
   40 CONTINUE
C
      RNORM2=1.D0/PANT
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,14.0)
      CALL TEXT('PANTH=',6)
      CALL NUMBD(PANT1*RNORM2,'(F8.3)',8)
      CALL TEXT('  PANTL=',8)
      CALL NUMBD(PANT2*RNORM2,'(F8.3)',8)
      CALL TEXT('  N-S  :',8)
      DO 50 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PNS(IS),'(F8.3)',8)
   50 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,13.5)
      CALL TEXT('PWALH=',6)
      CALL NUMBD(PWALL1*RNORM2,'(F8.3)',8)
      CALL TEXT('  PWALL=',8)
      CALL NUMBD(PWALL2*RNORM2,'(F8.3)',8)
      CALL TEXT('  T-S  :',8)
      DO 60 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PTS(IS),'(F8.3)',8)
   60 CONTINUE
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,13.0)
      CALL TEXT('PABST=',6)
      CALL NUMBD(PABSTT*RNORM2,'(F8.3)',8)
      CALL TEXT('  AJCDT=',8)
      CALL NUMBD(AJCDT*RNORM2,'(F8.3)',8)
      CALL TEXT('  PABS :',8)
      DO 70 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         CALL NUMBD(PABSXZ(IS)*RNORM2,'(F8.3)',8)
   70 CONTINUE
C
      DO 1005 NZ=1,NZP+1
         IF(NZ.LE.NZP/2) THEN
            NZZ = NZ + NZP/2
         ELSE
            NZZ = NZ - NZP/2
         ENDIF
         GZ(NZ)=AKZ(NZZ)
 1005 CONTINUE     
      GZ(1    )=-AKZ(NZP/2+1)
      CALL GQSCAL(GZ(1),GZ(NZP+1),GZMIN,GZMAX,GZSCL)
C
      DO 1006 NZ=1,NZP
         GDATAZ(NZ)=PANTK(NZ)*RNORM2
 1006 CONTINUE
      CALL GMNMX1(GDATAZ,1,NZP,1,GAMIN,GAMAX)
      CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
C
      CALL SETLIN(0,0,4)
      IF(NGRAPH.EQ.3) THEN
         CALL GDEFIN(2.5,12.5,1.0,12.0,GZ(1),GZ(NZP+1),-0.1*GMAX,GMAX)
      ELSE
         CALL GDEFIN(2.5,12.5,1.0,6.5,GZ(1),GZ(NZP+1),-0.1*GMAX,GMAX)
      ENDIF
      CALL GFRAME
      CALL GSCALE(0.,GZSCL,0.,   SCAL,0.1,9)
      CALL GSCALE(0.,0.,0.,2.*GMAX,0.0,0)
      CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
      CALL GVALUE(0.,2*GZSCL,0.,0.,     0)
      CALL SETLIN(0,0,7)
      DO 2003 NZ=1,NZP+1
         IF(NZ.LE.NZP/2) THEN
            NZZ = NZ + NZP/2
         ELSE
            NZZ = NZ - NZP/2
         ENDIF
         GDATAZ(NZ)=PANTK(NZZ)*RNORM2
 2003 CONTINUE
      CALL GPLOTP(GZ,GDATAZ,1,NZP+1,1,0,0,0)
      DO 2005 NZ=1,NZP+1
         GDATAZ(NZ)=0.0
 2005 CONTINUE
      DO 2010 IS=1,ISMAX
         DO 2009 NZ=1,NZP+1
            IF(NZ.LE.NZP/2) THEN
               NZZ = NZ + NZP/2
            ELSE
               NZZ = NZ - NZP/2
            ENDIF
            GDATAZ(NZ)=GDATAZ(NZ)+PAK(NZZ,IS)*RNORM2
 2009    CONTINUE
         CALL SETLIN(0,0,7-IS)
         CALL GPLOTP(GZ,GDATAZ,1,NZP+1,1,-IS,10,0)
 2010 CONTINUE
C
      IF(NGRAPH.NE.2.AND.NGRAPH.NE.3) THEN
         DO 2020 NZ=1,NZP+1
            IF(NZ.LE.NZP/2) THEN
               NZZ = NZ + NZP/2
            ELSE
               NZZ = NZ - NZP/2
            ENDIF
            GDATAZ(NZ)=AJCDK(NZZ)*RNORM2
 2020    CONTINUE
         CALL GMNMX1(GDATAZ,1,NZP,1,GAMIN,GAMAX)
         CALL SETLIN(0,0,4)
         CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
         CALL GDEFIN(2.5,12.5,6.5,12.0,GZ(1),GZ(NZP+1),GMIN,GMAX)
         CALL GFRAME
         CALL GSCALE(0.,  GZSCL,0.,  SCAL,0.1,9)
         CALL GSCALE(0.,2*GZSCL,0.,2*SCAL,0.2,9)
         CALL GSCALE(0.,0.,0.,2.*MAX(ABS(GMAX),ABS(GMIN)),0.0,0)
         CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
         CALL SETLIN(0,0,7)
         CALL GPLOTP(GZ,GDATAZ,1,NZP+1,1,0,0,0)
      ENDIF
C
      DO 1001 NX=1,NXT
         NN=NXPRNT(NX)
         GX(NX)=XAM(NN)
         GXM(NX)=XAM(NX)
 1001 CONTINUE
C
      PGAMIN=0.0
      PGAMAX=0.0
      DO 1029 IS=1,ISMAX
         DO 1028 NX=1,NXP
            GDATA1(NX)=PABSX(NX,IS)*RNORM2
 1028    CONTINUE
         CALL GMNMX1(GDATA1,1,NXP,1,GAMIN,GAMAX)
         PGAMIN=MIN(PGAMIN,GAMIN)
         PGAMAX=MAX(PGAMAX,GAMAX)
 1029 CONTINUE
      PGAMAX=MAX(ABS(PGAMAX),ABS(PGAMIN))
      CALL GQSCAL(0.,PGAMAX,PGMIN,PGMAX,PSCAL)
C
      IF(NGRAPH.NE.2.AND.NGRAPH.NE.3) THEN
         DO 1030 NX=1,NXP
            GDATA1(NX)=AJCDX(NX)*RNORM2
 1030    CONTINUE
         CALL GMNMX1(GDATA1,1,NXP,1,GAMIN,GAMAX)
         IF(ABS(GAMAX).GE.ABS(GAMIN)) THEN
            SGAMAX=GAMAX
         ELSE
            SGAMAX=GAMIN
         ENDIF
C      
         CALL GQSCAL(GAMIN,GAMAX,GMIN,GMAX,SCAL)
         CALL GDEFIN(15.0,25.0,6.5,12.0,-GB,GB,GMIN,GMAX)
         CALL SETLIN(0,0,4)
         CALL GFRAME
         CALL GSCALE(0.,0.1,0.,0.,0.1,9)
         CALL GSCALE(0.,0.,0.,SCAL,0.1,9)
         CALL GSCALE(0.,100.,0.,0.,0.2,9)
         CALL GSCALE(-GA,2.*GA,0.,20.*SCAL,0.1,0)
         CALL GVALUE(0.,0.,0.,4*SCAL,NGVLEN(4*SCAL))
         CALL SETLIN(0,0,7)
         CALL GPLOTP(GXM,GDATA1,1,NXP,1,0,0,0)
      ENDIF
      CALL SETLIN(0,0,4)
C
      IF(NGRAPH.EQ.3) THEN
         CALL GDEFIN(15.0,25.0,1.0,12.0,-GB,GB,-0.1*PGMAX,PGMAX)
      ELSE
         CALL GDEFIN(15.0,25.0,1.0,6.5,-GB,GB,-0.1*PGMAX,PGMAX)
      ENDIF
      CALL GFRAME
      CALL GSCALE(0.,0.1,0.,0.,0.1,9)
      CALL GSCALE(0.,0.,0.,PSCAL,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,9)
      CALL GSCALE(-GA,2.*GA,0.,20.*PSCAL,0.1,0)
      CALL GVALUE(0.,0.,0.,4*PSCAL,NGVLEN(4*PSCAL))
      CALL GVALUE(0.,REAL(RA),0.,0.,2)
      DO 1040 IS=1,ISMAX
         CALL SETLIN(0,0,7-IS)
         DO 1039 NX=1,NXP
            GDATA1(NX)=PABSX(NX,IS)*RNORM2
 1039    CONTINUE
         CALL GPLOTP(GXM,GDATA1,1,NXP,1,-IS,10,0)
 1040 CONTINUE
C
      IF(NMODEL.EQ.5.OR.NMODEL.EQ.3.OR.NMODEL.EQ.1) THEN
         DO 1130 NX=1,NXT
            NN        =NXPRNT(NX)
            GDATA1(NX)=FLUXX(NN)*RNORM2
 1130    CONTINUE
         CALL GMNMX1(GDATA1,1,NXT,1,GAMIN,GAMAX)
         IF(ABS(GAMIN).GE.ABS(GAMAX)) THEN
            DO 1131 NX=1,NXT
               GDATA1(NX)=-GDATA1(NX)
 1131       CONTINUE
            GAMAX=-GAMIN
         ENDIF
         CALL GQSCAL(0.,GAMAX*1.02,GMIN,GMAX,SCAL)
         IF(NGRAPH.EQ.3) THEN
            CALL GDEFIN(15.0,25.0,1.0,12.0,-GB,GB,-0.1*GMAX,GMAX)
         ELSE
            CALL GDEFIN(15.0,25.0,1.0,6.5,-GB,GB,-0.1*GMAX,GMAX)
         ENDIF
         CALL SETLIN(0,0,7)
         CALL GPLOTP(GX,GDATA1,1,NXT,1,0,0,0)
      ENDIF
C
      CALL SETLIN(0,0,7)
      CALL MOVE(1.1,12.5)
      CALL TEXT('PGAMAX=',6)
      CALL NUMBR(PGAMAX,'(F8.3)',8)
      CALL TEXT('  SGAMAX=',8)
      CALL NUMBR(SGAMAX,'(F8.3)',8)
C
      CALL PAGEE
      RETURN
      END
C
C     ****** DRAW DISPERSION RELATION ******
C
      SUBROUTINE W1GDSP1(PKXMIN,PKXMAX)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1EPOL/ CSKX(NXPM*3),CSPX(NXPM*3),CSPZ(NXPM*3)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      REAL*4 SX(NXPM),SKR1(NXPM),SKR2(NXPM),SKR3(NXPM),
     &       SKI1(NXPM),SKI2(NXPM),SKI3(NXPM),SQK2R,SQK2I,S1,S2,
     &       SXMIN,SXMAX,SKMIN,SKMAX,SCALX,SCALK,SXORG,SKORG,SCALV
C
      IF(2.0*XAM(1)-XAM(2).LE.-RA.AND.
     &   2.0*XAM(NXP)-XAM(NXP-1).GE.RA) THEN
         SXMIN=-RB
         SXMAX= RB
         SXORG=0.0
         SCALX=0.1
         SCALV= RA
      ELSE
         SXMIN= 1.5*XAM(1)  -0.5*XAM(2)
         SXMAX= 1.5*XAM(NXP)-0.5*XAM(NXP-1)
         CALL GQSCAL(SXMIN,SXMAX,S1,S2,SCALX)
         SXORG=SXMIN
         IF(SXMIN*SXMAX.LE.0.0) SXORG=0.0
         SCALV= 2.*SCALX
      ENDIF
      SKMIN= PKXMIN
      SKMAX= PKXMAX
C
      DO 1100 NX=1,NXP
         IF(NMODEL.LE.3) THEN
            KK=(NX-1)*2
         ELSE
            KK=(NX-1)*3
         ENDIF
         SX(NX)=XAM(NX)
         SKR1(NX)=SQK2R(CSKX(KK+1))
         SKI1(NX)=SQK2I(CSKX(KK+1))
         SKR2(NX)=SQK2R(CSKX(KK+2))
         SKI2(NX)=SQK2I(CSKX(KK+2))
         IF(NMODEL.GT.3) THEN
            SKR3(NX)=SQK2R(CSKX(KK+3))
            SKI3(NX)=SQK2I(CSKX(KK+3))
         ENDIF
 1100 CONTINUE
C
      CALL PAGES
      CALL SETLIN(0,0,4)
      CALL SETCHS(0.3,0.)
      CALL SETMKS(0,0.1)
      CALL GQSCAL(SKMIN,SKMAX,S1,S2,SCALK)
      SKORG=SKMIN
      IF(SKMIN*SKMAX.LE.0.0) SKORG=0.0
      CALL GDEFIN(2.5,12.5,1.,17.5,SXMIN,SXMAX,SKMIN,SKMAX)
      CALL GFRAME
      CALL GSCALE(SXORG,SCALX,SKORG,SCALK,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,1)
      CALL GSCALE(-REAL(RA),2.*REAL(RA),0.,13.*SCALK,0.1,0)
      CALL GVALUE(SXORG,SCALV,0.,0.,2)
      CALL GVALUE(0.,0.,SKORG,2*SCALK,NGVLEN(2*SCALK))
      CALL SETLIN(0,0,6)
      CALL GPLOTP(SX,SKR1,1,NXP,1,7,1,0)
      CALL SETLIN(0,0,5)
      CALL GPLOTP(SX,SKI1,1,NXP,1,6,1,0)
      CALL SETLIN(0,0,6)
      CALL GPLOTP(SX,SKR2,1,NXP,1,8,1,0)
      CALL SETLIN(0,0,5)
      CALL GPLOTP(SX,SKI2,1,NXP,1,3,1,0)
      IF(NMODEL.GT.3) THEN
         CALL SETLIN(0,0,6)
         CALL GPLOTP(SX,SKR3,1,NXP,1,4,1,0)
         CALL SETLIN(0,0,5)
         CALL GPLOTP(SX,SKI3,1,NXP,1,2,1,0)
      ENDIF
C
      CALL W1GPRM(0,1)
C
      CALL PAGEE
C
      RETURN
      END
C
C     ****** DRAW DISPERSION RELATION ******
C
      SUBROUTINE W1GDSP2(PKXMIN,PKXMAX)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1EPOL/ CSKX(NXPM*3),CSPX(NXPM*3),CSPZ(NXPM*3)
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      REAL*4 SX(NXPM),SKR1(NXPM),SKR2(NXPM),SKR3(NXPM),
     &       SKI1(NXPM),SKI2(NXPM),SKI3(NXPM),SQK2R,SQK2I,S1,S2,
     &       SXMIN,SXMAX,SKMIN,SKMAX,SCALX,SCALK,SXORG,SKORG,SCALV
C
      IF(2.0*XAM(1)-XAM(2).LE.-RA.AND.
     &   2.0*XAM(NXP)-XAM(NXP-1).GE.RA) THEN
         SXMIN=-RB
         SXMAX= RB
         SXORG=0.0
         SCALX=0.1
         SCALV= RA
      ELSE
         SXMIN= 1.5*XAM(1)  -0.5*XAM(2)
         SXMAX= 1.5*XAM(NXP)-0.5*XAM(NXP-1)
         CALL GQSCAL(SXMIN,SXMAX,S1,S2,SCALX)
         SXORG=SXMIN
         IF(SXMIN*SXMAX.LE.0.0) SXORG=0.0
         SCALV= 2.*SCALX
      ENDIF
      SKMIN= PKXMIN
      SKMAX= PKXMAX
C
      DO 1100 NX=1,NXP
         IF(NMODEL.LE.3) THEN
            KK=(NX-1)*2
         ELSE
            KK=(NX-1)*3
         ENDIF
         SX(NX)=XAM(NX)
         SKR1(NX)=SQK2R(CSKX(KK+1))
         SKI1(NX)=SQK2I(CSKX(KK+1))
         SKR2(NX)=SQK2R(CSKX(KK+2))
         SKI2(NX)=SQK2I(CSKX(KK+2))
         IF(NMODEL.GT.3) THEN
            SKR3(NX)=SQK2R(CSKX(KK+3))
            SKI3(NX)=SQK2I(CSKX(KK+3))
         ENDIF
 1100 CONTINUE
C
      CALL PAGES
      CALL SETLIN(0,0,4)
      CALL SETCHS(0.3,0.)
      CALL SETMKS(0,0.1)
      CALL GQSCAL(SKMIN,SKMAX,S1,S2,SCALK)
      SKORG=SKMIN
      IF(SKMIN*SKMAX.LE.0.0) SKORG=0.0
      CALL GDEFIN(2.5,12.5,1.,17.5,SXMIN,SXMAX,SKMIN,SKMAX)
      CALL GFRAME
      CALL GSCALE(SXORG,SCALX,SKORG,SCALK,0.1,9)
      CALL GSCALE(0.,100.,0.,0.,0.2,1)
      CALL GSCALE(-REAL(RA),2.*REAL(RA),0.,13.*SCALK,0.1,0)
      CALL GVALUE(SXORG,SCALV,0.,0.,2)
      CALL GVALUE(0.,0.,SKORG,2*SCALK,NGVLEN(2*SCALK))
      CALL SETLIN(0,0,6)
      CALL GPLOTP(SX,SKR1,1,NXP,1,7,1,0)
      CALL SETLIN(0,0,5)
      CALL GPLOTP(SX,SKI1,1,NXP,1,6,1,0)
      CALL SETLIN(0,0,6)
      CALL GPLOTP(SX,SKR2,1,NXP,1,8,1,0)
      CALL SETLIN(0,0,5)
      CALL GPLOTP(SX,SKI2,1,NXP,1,3,1,0)
      IF(NMODEL.GT.3) THEN
         CALL SETLIN(0,0,6)
         CALL GPLOTP(SX,SKR3,1,NXP,1,4,1,0)
         CALL SETLIN(0,0,5)
         CALL GPLOTP(SX,SKI3,1,NXP,1,2,1,0)
      ENDIF
C
      CALL W1GPRM(0,1)
C
      CALL PAGEE
C
      RETURN
      END
C         
      FUNCTION SQK2R(CK)
C
      COMPLEX*16 CK
      R=REAL(CK)
      A=IMAG(CK)
      S=R*R-A*A
      IF(S.GE.0.) THEN
         SQK2R=SQRT(S)
      ELSE
         SQK2R=-SQRT(-S)
      ENDIF
      RETURN
      END
C
      FUNCTION SQK2I(CK)
C
      COMPLEX*16 CK
      S=2.*REAL(CK)*IMAG(CK)
      IF(S.GE.0.) THEN
         SQK2I=SQRT(S)
      ELSE
         SQK2I=-SQRT(-S)
      ENDIF
      RETURN
      END
