C
C     ************************* TASK.W1 *************************
C
C     ICRF WAVE PROPAGATION AND ABSORPTION
C
C          DIFFERENTIAL OR INTEGRO-DIFFERENTIAL ANALYSIS
C          SLAB PLASMA MODEL
C          MULTIPLE LAYER OR FINITE ELEMENT METHOD
C
C     PROGRAMED BY
C
C          A. FUKUYAMA, S. NISHIYAMA, T. MATSUISHI AND k. HAMAMATSU(*)
C
C          DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING
C          FACULTY OF ENGINEERING
C          OKAYAMA UNIVERSITY
C          OKAYA 700, JAPAN
C
C      (*) DEPARTMENT OF LARGE TOKAMAK RESEARCH
C          NAKA FUSION RESEARCH ESTABLISHMENT
C          JAPAN ATOMIC ENERGY RESEARCH INSTITUTE
C          NAKA, IBARAKI 311-01, JAPAN
C
C     PROGRAM VERSION
C
C          V1.68 : 90/02/17
C          V1.70 : 90/03/14
C          V1.71 : 90/06/08 : ICDTYP ADDED
C          V1.72 : 90/06/16 : WVYSIZ ADDED
C          V1.73 : 90/06/18 : W1CLCD CORRECTED, WVYSIZ CORRECTED
C          V2.00 : 90/09/08 : B, A, HELICITY, ABSORBED BOUNDARY ADDED
C          V2.01 : 90/09/12 : HELICITY CURRENT ADDED
C          V2.02 : 90/09/14 : CORRECTION
C          V2.03 : 90/09/20 : TALPHA,TAU CORRECTED
C          V2.04 : 90/09/22 : NEW GRAPH, QH RECORRECTED
C          V2.05 : 90/10/16 : TRAPPED PARTICLE EFFECTS
C          V2.06 : 91/03/29 : NONRESONANT FORCE MODIFIED
C          V2.10 : 91/06/18 : UNDERFLOW ADJUSTMENT FOR SX
C          V2.11 : 92/03/18 : WORKING ON HP WS
C          V2.12 : 94/01/12 : SPLIT SOURCE FILES, INCLUDE FILE, ERF
C          V2.98 : 17/06/19 : UPDATE INTERFACE
C
C     *************************************************************
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
C
      INCLUDE 'w1comm.f'
      INTEGER IERR
C
      WRITE(6,600)
      WRITE(6,601) 'TASK/W1 --- V2.12 : 94/01/12',
     &             NXPM,NXVM,NZPM,ISM,IAM,MATLM,NHARMM,NDM
      CALL GSOPEN
      OPEN(7,STATUS='SCRATCH',FORM='FORMATTED')
C
      CALL W1INIT
      CALL W1PARM(1,'w1parm',IERR)
C
      CALL W1MENU
C
      CLOSE(7)
      CALL GSCLOS
      STOP
C
  600 FORMAT(1H1)
  601 FORMAT(1H ,'## ',A28,' ',
     &           '## NXPM,NXVM,NZPM,ISM,IAM,MATLM,NHARMM,NDM ##'/
     &       1H ,35X,I4,',',I4,',',I4,',',I3,',',I3,',',
     &               I5,',',I6,',',I3)
      END
