C
C ***** TASK/W1 PARAMETER INTERFACE *****
C
C     ****** INPUT PARAMETERS ******
C
      SUBROUTINE W1PARM(MODE,KIN,IERR)
C
C     MODE=0 : standard namelist input
C     MODE=1 : namelist file input
C     MODE=2 : namelist line input
C
C     IERR=0 : normal end
C     IERR=1 : namelist standard input error
C     IERR=2 : namelist file does not exist
C     IERR=3 : namelist file open error
C     IERR=4 : namelist file read error
C     IERR=5 : namelist file abormal end of file
C     IERR=6 : namelist line input error
C     IERR=7 : unknown MODE
C     IERR=10X : input parameter out of range
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INTEGER MODE,IERR
      CHARACTER KIN*(*)
      EXTERNAL W1NLIN,W1PLST
C
    1 CALL TASK_PARM(MODE,'W1',KIN,W1NLIN,W1PLST,IERR)
      IF(IERR.NE.0) RETURN
C
      CALL W1CHEK(IERR)
      IF(MODE.EQ.0.AND.IERR.NE.0) GOTO 1
      IF(IERR.NE.0) IERR=IERR+100
C
      RETURN
      END
C
C     ****** INPUT NAMELIST ******
C
      SUBROUTINE W1NLIN(NID,IST,IERR)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PRM6/ IELEC(ISM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1BND1/ CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1PRM5/ EPSH
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,NCDTYP
C
      INTEGER NID,IST,IERR
C
C     ************************************************************
C
      NAMELIST /W1/ BB,RR,RZ,RA,RD,RB,RF,WALLR,APRFPN,APRFTR,APRFTP,
     &              RKZ,DRF,DRKZ,DXFACT,DXWDTH,
     &              AJYH,ALYH,APYH,AJYL,ALYL,APYL,AJZH,AJZL,IAMAX,
     &              PA,PZ,PN,PTPP,PTPR,PU,PNS,PTS,PZCL,ISMAX,
     &              NXP,NXV,NZP,NPRINT,NFILE,NGRAPH,NLOOP,NSYM,
     &              NMODEL,NALPHA,NDMAX,XDMAX,IHARM,NSYS,NDISP,
     &              EPSH,ZEFF,WVYSIZ,NCDTYP,NXABS,IELEC
C
      READ(NID,W1,IOSTAT=IST,ERR=9800,END=9900)
C
      IF(MOD(NXV,2).NE.0) NXV=NXV+1
      IF(ABS(RZ).LE.1.D-8) RZ=2.D0*PI*RR
      IF(NDMAX.GT.NDM-1) NDMAX=NDM-1
      NHARM=0
      IF(NMODEL.EQ.6) THEN
         DO 11 IS=1,ISMAX
            IF(ABS(IHARM(IS)).GT.NHARMM) IHARM(IS)=NHARMM
            IF(ABS(IHARM(IS)).GT.NHARM)  NHARM=IHARM(IS)
   11    CONTINUE
         DXD=XDMAX/NDMAX
         CALL W1QTBL(NDMAX,XDMAX,NHARM)
      ENDIF
      IERR=0
      RETURN
C
 9800 IERR=8
      WRITE(6,*) 'XX READ W1PARM ERROR: IST=',IST
      RETURN
 9900 IERR=9
      RETURN
      END
C
C     ***** INPUT PARAMETER LIST *****
C
      SUBROUTINE W1PLST
C
      WRITE(6,601)
      RETURN
C
  601 FORMAT(' ','# &W1 : BB,RR,RZ,RA,RD,RB,RF,WALLR,'/
     &       9X,'         APRFPN,APRFTR,APRFTP,'/
     &       9X,'         RKZ,DRF,DRKZ,DXFACT,DXWDTH,'/
     &       9X,'       AJYH,ALYH,APYH,AJYL,ALYL,APYL,AJZH,AJZL,IAMAX,'/
     &       9X,'       PA,PZ,PN,PTPP,PTPR,PU,PNS,PTS,PZCL,ISMAX,'/
     &       9X,'       NXP,NXV,NZP,NPRINT,NFILE,NGRAPH,NLOOP,NSYM,'/
     &       9X,'       NMODEL,NALPHA,NDMAX,XDMAX,IHARM,NSYS,NDISP,'/
     &       9X,'       EPSH,ZEFF,WVYSIZ,NCDTYP,NXABS,IELEC')
      END
C
C     ***** CHECK INPUT PARAMETERS *****
C
      SUBROUTINE W1CHEK(IERR)
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PRM6/ IELEC(ISM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1BND1/ CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1PRM5/ EPSH
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,NCDTYP
C
      IERR=0
C
      RETURN
      END
C
C     ****** SHOW PARAMETERS ******
C
      SUBROUTINE w1VIEW
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-H,O-Z)
      INCLUDE 'w1comm.f'
      PARAMETER (NZPM=2**NZLM)
      PARAMETER (NXTM=NXPM+2*NXVM,NXM=NXPM*6+10,NXQ=NXPM+1)
      PARAMETER (NHM=2*NHARMM+1,NHM1=NHARMM+1)
      COMMON /W1CNST/ AEE,AME,AMM,VC,EPS0,AMYU0,PI
      COMMON /W1PRM1/ NXP,NXV,NXT,ISMAX,IAMAX
      COMMON /W1PRM2/ RF,RKZ,BB,RR,RA,RD,RB,WALLR
      COMMON /W1PRM3/ PA(ISM),PZ(ISM),PN(ISM),PTPP(ISM),PTPR(ISM),
     &                PNS(ISM),PTS(ISM),PU(ISM),PZCL(ISM)
      COMMON /W1PRM4/ RZ,DZ,NZP
      COMMON /W1PRM6/ IELEC(ISM)
      COMMON /W1ANT1/ AJYL(IAM),AJYH(IAM),AJZL(IAM),AJZH(IAM),
     &                ALYL(IAM),ALYH(IAM),APYL(IAM),APYH(IAM)
      COMMON /W1BND1/ CGIN(3,5),CGOT(3,5),CFJY1,CFJY2,CFJZ1,CFJZ2
      COMMON /W1EF2D/ CE2DA(NZPM,NXTM,3)
      COMMON /W1ZDAT/ CJ1(NZPM),CJ2(NZPM),CJ3(NZPM),CJ4(NZPM),
     &                ZA(NZPM),AKZ(NZPM),NZANT1(IAM),NZANT2(IAM),NANT
      COMMON /W1CTRL/ DRF,DRKZ,DXFACT,DXWDTH,APRFPN,APRFTR,APRFTP,
     &                NPRINT,NFILE,NGRAPH,NLOOP,NSYM,NFLR,NALPHA,
     &                NSYS,NDISP,NXABS
      COMMON /W1QCTL/ XDMAX,DXD,NDMAX,NHARM,IHARM(ISM),MATL,NMODEL
      COMMON /W1PRM5/ EPSH
      COMMON /W1XDAT/ XA(NXQ),XAM(NXTM)
      COMMON /W1CDDT/ AJCDX(NXPM),AJCDK(NZPM),AJCDT,ZEFF,WVYSIZ,NCDTYP
C
      WRITE(6,609) BB,RR,RZ,RA,RD,RB
      WRITE(6,610) RF,RKZ,WALLR,ZEFF,WVYSIZ,NCDTYP,DXFACT,DXWDTH,EPSH
      WRITE(6,623) APRFPN,APRFTR,APRFTP
      WRITE(6,611) NXP,NXV,NZP,NSYM,NPRINT,NFILE,NGRAPH,NLOOP,
     &             NMODEL,NALPHA,NSYS,NXABS
      WRITE(6,620)
      DO 20 IA = 1 , IAMAX
         WRITE(6,621) IA,AJYH(IA),AJZH(IA),ALYH(IA),APYH(IA)
   20 CONTINUE
      WRITE(6,622)
      DO 30 IA = 1 , IAMAX
         WRITE(6,621) IA,AJYL(IA),AJZL(IA),ALYL(IA),APYL(IA)
   30 CONTINUE
      WRITE(6,612)
      DO 10 IS=1,ISMAX
         WRITE(6,613) IS,PA(IS),PZ(IS),PN(IS),PTPP(IS),PTPR(IS),PU(IS)
   10 CONTINUE
      WRITE(6,614)
      DO 12 IS=1,ISMAX
         WRITE(6,615) PNS(IS),PTS(IS),PZCL(IS),IHARM(IS),IELEC(IS)
   12 CONTINUE
C
      RETURN
  609 FORMAT(1H ,'BB    =',1PD12.4,' (T)   ',
     &           'RR    =',  D12.4,' (M)   ',
     &           'RZ    =',  D12.4,' (M)'/
     &       1H ,'RA    =',1PD12.4,' (M)   ',
     &           'RD    =',  D12.4,' (M)   ',
     &           'RB    =',  D12.4,' (M)')
  610 FORMAT(1H ,'RF    =',1PD12.4,' (MHZ) ',
     &           'RKZ   =',1PD12.4,' (/M)  ',
     &           'WALLR =',1PD12.4,'(OHM M)'/
     &       1H ,'ZEFF  =',1PD12.4,'       ',
     &           'WVYSIZ=',1PD12.4,' (M)   ',
     &           'NCDTYP=',I6,6X,  '       '/
     &       1H ,'DXFACT=',1PD12.4,'       ',
     &           'DXWDTH=',1PD12.4,' (M)   ',
     &           'EPSH  =',1PD12.4,'       ')
  620 FORMAT(1H ,'HFS  ANTY(KA)  ANTZ(KA)  POS(DEG)  PHA(DEG)     ')
  621 FORMAT(1H ,I3,4(F10.4))
  622 FORMAT(1H ,'LHS  ANTY(KA)  ANTZ(KA)  POS(DEG)  PHA(DEG)     ')
  623 FORMAT(1H ,'APRFPN=',1PD12.4,'       ',
     &           'APRFTR=',1PD12.4,'       ',
     &           'APRFTP=',1PD12.4,'       ')
  611 FORMAT(1H ,'NXP   =',I6,6X,'NXV   =',I6,
     &        6X,'NZP   =',I6,6X,'NSYM  =',I6/
     &       1H ,'NPRINT=',I6,6X,'NFILE =',I6,
     &        6X,'NGRAPH=',I6,6X,'NLOOP =',I6/
     &       1H ,'NMODEL=',I6,6X,'NALPHA=',I6,
     &        6X,'NSYS  =',I6,6X,'NXABS =',I6)
  612 FORMAT(1H ,'IS',2X,'PA(MASS)    PZ(CHARGE)  PN(E20/M3)  ',
     &                   'PTPP(KEV)   PTPR(KEV)   PU(KEV)     ')
  613 FORMAT(1H ,I2,1P6D12.4)
  614 FORMAT(1H ,    28X,'PNS(E20/M3) PTS(KEV)    PZCL    IHARM',
     &                   '   IELEC')
  615 FORMAT(1H ,26X,1P3D12.4,I3,5X,I3)
      END
