C     $Id$
C
      SUBROUTINE MTXSET(NPROCS1,MYRANK1,NBSIZ,NBMAX)
C
      COMMON /MPIVR1/ NPROCS,MYRANK
      COMMON /MPIVR2/ ISTA,IEND
      COMMON /MPIVR3/ NBST,NBED
C
      NPROCS=NPROCS1
      MYRANK=MYRANK1
C
      NFRAC=(NBMAX-1)/NPROCS+1
      NBST=MYRANK*NFRAC+1
      NBED=NBST+NFRAC-1
      IF(MYRANK.EQ.NPROCS-1) NBED=NBMAX
C
      ISTA=NBSIZ*(NBST-1)+1
      IEND=NBSIZ*NBED
C
      RETURN
      END
