!     $Id$

MODULE libgrf

  PRIVATE
  PUBLIC GRF1D, GRD1D
  PUBLIC GRF2D, GRD2D
  PUBLIC GRFUT1, GRFUT2, GRFUT3, GRFUT4
  PUBLIC GRF2DA, GRF2DAX, GRF2DB, GRF2DBX, GRF2DC, GRF2DCX, GDD2D

  TYPE grf_attr_type
     REAL(4):: GPXMIN,GPXMAX,GPYMIN,GPYMAX ! page size
     REAL(4):: XMIN,XMAX,XORG    ! X axis range, orgin of scale and value
     REAL(4):: YMIN,YMAX,YORG    ! Y axis range, orgin of scale and value
     REAL(4):: FMIN,FMAX,FORG    ! Z axis range, orgin of scale and value
     REAL(4):: XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR ! Axis rage reduction
     INTEGER:: NXMIN,NYMIN   ! Top of plot data
     INTEGER:: NXSTEP,NYSTEP ! Interval of plot data
     INTEGER:: NLMAX         ! Number of line attribute
     INTEGER:: NPMAX         ! Number of paint attribute
     REAL(4),DIMENSION(:),ALLOCATABLE:: LINE_VALUE   ! Line value (NLMAX)
     REAL(4),DIMENSION(:,:),ALLOCATABLE :: LINE_RGB  ! Line color array (NLMAX)
     REAL(4),DIMENSION(:),ALLOCATABLE:: LINE_THICKNESS ! Line thickness (NLMAX)
     INTEGER,DIMENSION(:),ALLOCATABLE:: LINE_PAT       ! Line pattern (NLMAX)
     INTEGER,DIMENSION(:),ALLOCATABLE:: LINE_MARK      ! Mark type (NLMAX)
     INTEGER,DIMENSION(:),ALLOCATABLE:: LINE_MARK_STEP ! Mark interval (NLMAX)
     REAL(4),DIMENSION(:),ALLOCATABLE:: LINE_MARK_SIZE ! Mark size (NLMAX)
     REAL(4),DIMENSION(:),ALLOCATABLE:: PAINT_VALUE ! Paint value (NPMAX)
     REAL(4),DIMENSION(:,:),ALLOCATABLE :: PAINT_RGB! Paint color array (NPMAX)
     REAL(4):: BEV_XORG     ! Bird's eye view : x pos of origin 
     REAL(4):: BEV_YORG     ! Bird's eye view : y pos of origin 
     REAL(4):: BEV_ZORG     ! Bird's eye view : z pos of origin 
     REAL(4):: BEV_PHI      ! Bird's eye view : angle in xy plane
     REAL(4):: BEV_CHI      ! Bird's eye view : angle from xy plane
     REAL(4):: BEV_DISTANCE ! Bird's eye view : distance from origin
     CHARACTER(LEN=80):: TITLE,XTITLE,YTITLE       ! Title contents
     INTEGER:: TITLE_LEN,XTITLE_LEN,YTITLE_LEN     ! Number of chars in title
     REAL(4):: TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE       ! Title font size
     INTEGER:: TITLE_FONT,XTITLE_FONT,YTITLE_FONT       ! Title font type
     REAL(4):: TITLE_RGB(3),XTITLE_RGB(3),YTITLE_RGB(3) ! Title font color
     REAL(4):: TITLE_SEP,XTITLE_SEP,YTITLE_SEP  ! Title separation from graph
     INTEGER:: TITLE_POS ! Title horizontal position
!                           0 : Flush left (default)
!                           1 : Centering
!                           2 : Flush right
!                           Always centering for X/Y/Z titles
     REAL(4):: FRAME_RGB(3)     ! Frame and scale color
     REAL(4):: FRAME_THICKNESS  ! Frame thickness
     INTEGER:: MODE_LS   ! Scale type
!                           0 : X:LINEAR  Y:LINEAR
!                           1 : X:LOG     Y:LINEAR
!                           2 : X:LINEAR  Y:LOG
!                           3 : X:LOG     Y:LOG
     REAL(4):: SCALE_RGB(3)          ! Scalse color
     REAL(4):: SCALE_Zero_RGB(3)     ! Zero scale color
     REAL(4):: SCALE_THICKNESS       ! Scale thickness
     REAL(4):: SCALE_ZERO_THICKNESS  ! Zero Scale thickness
     REAL(4):: XSCALE_STEP,YSCALE_STEP,FSCALE_STEP ! Scale step size
     REAL(4):: XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE ! Scale length or grid pat.
     INTEGER:: XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE ! Scale type (0 for grid)
     INTEGER:: XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE ! Scale type for log plot
     INTEGER:: XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO ! /= for origin grid
     INTEGER:: XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT ! org grid pat
     INTEGER:: VALUE_FONT   ! Value font type
     REAL(4):: VALUE_SIZE   ! Value font size
     REAL(4):: VALUE_RGB(3) ! Value font color
     INTEGER:: XVALUE_STEP,YVALUE_STEP,FVALUE_STEP ! Value step size
     INTEGER:: XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE ! Value type
     INTEGER:: XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE ! Value type for log plot
     INTEGER:: MODE_2D   ! Graph tupe
!                           0 : 1D plot (multi lines)  GRF1D
!                           1 : 2D contour lines       GRF2DA
!                           2 : 2D equi-value paint    GRF2DB
!                           3 : 2D contour lines and equi-value paint
!                          11 : Bird's eye view contour lines    GRF2DC
!                          12 : Bird's eye view equi-value paint GRF2DD
!                          13 : Bird's eye view contour and paint
!                          14 : Bird's eye view contour on Z=0 plane
!                          15 : Bird's eye view contour on X=0 plane
!                          16 : Bird's eye view contour on Y=0 plane
!                          17 : Bird's eye view X mesh
!                          18 : Bird's eye view Y mesh
!                          19 : Bird's eye view X and Y mesh
     INTEGER:: MODE_XY   ! Coordinate tupe
!                           0 : Rectangular coordinates
!                           1 : Circular coordinate
!                           2 : Fan type coordinate
     INTEGER:: MODE_PRD  ! Periodicity mode
!                           0 : no periodicity
!                           1 : periodic in X
!                           2 : periodic in Y
!                           3 : periodic in both X and Y
     INTEGER:: FRAME_TYPE   ! Frame type
!                           0 : Rectangular frame (Default)
!                           1 : XY axis only
     INTEGER:: NOTITLE                      ! /= 0 for no title
     INTEGER:: NOFRAME                      ! /= 0 for no frame
     INTEGER:: NOXSCALE,NOYSCALE,NOFSCALE   ! /= 0 for no scale
     INTEGER:: NOXVALUE,NOYVALUE,NOFVALUE   ! /= 0 for no value
  END TYPE grf_attr_type

  INTERFACE
     SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
       REAL(4),INTENT(IN):: VALUE
       REAL(4),DIMENSION(3),INTENT(OUT)::RGB
     END SUBROUTINE LINE_RGB_SUB
     SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
       REAL(4),INTENT(IN):: VALUE
       REAL(4),DIMENSION(3),INTENT(OUT):: RGB
     END SUBROUTINE PAINT_RGB_SUB
  END INTERFACE

CONTAINS

! ***** DRAW 1D GRAPH: REAL(4) interface *****

  SUBROUTINE GRF1D(NGP,GX,GF,NXM,NXMAX,NGMAX, &   ! indispensable arguments
                   TITLE,MODE_LS, &               ! optional positional args
                   GPXMIN,GPXMAX,GPYMIN,GPYMAX, & ! top of optional args
                   XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                   XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                   NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                   LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                   LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                   PAINT_VALUE,PAINT_RGB, &
                   BEV_XORG,BEV_YORG,BEV_ZORG, &
                   BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                   XTITLE,YTITLE, &
                   TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                   TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                   TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                   TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                   TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                   FRAME_RGB,FRAME_THICKNESS, &
                   SCALE_RGB,SCALE_ZERO_RGB, &
                   SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                   XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                   XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                   XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                   XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                   XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                   XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                   VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                   XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                   XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                   XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                   MODE_2D,MODE_XY,MODE_PRD,FRAME_TYPE, &
                   NOTITLE,NOFRAME, &
                   NOXSCALE,NOYSCALE,NOFSCALE, &
                   NOXVALUE,NOYVALUE,NOFVALUE, &
                   LINE_RGB_SUB,PAINT_RGB_SUB)

    IMPLICIT NONE

    INTEGER,INTENT(IN):: NGP                       ! Graph size and postion ID
    REAL(4),INTENT(IN):: GX(NXMAX),GF(NXM,NGMAX)   ! 1D data
    INTEGER,INTENT(IN):: NXM,NXMAX,NGMAX           ! Number of data

    REAL(4),INTENT(IN),OPTIONAL:: GPXMIN,GPXMAX,GPYMIN,GPYMAX
    REAL(4),INTENT(IN),OPTIONAL:: XMIN,XMAX,XORG
    REAL(4),INTENT(IN),OPTIONAL:: YMIN,YMAX,YORG
    REAL(4),INTENT(IN),OPTIONAL:: FMIN,FMAX,FORG
    REAL(4),INTENT(IN),OPTIONAL:: XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR
    INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NYMIN,NXSTEP,NYSTEP

    INTEGER,INTENT(IN),OPTIONAL:: NLMAX,NPMAX
    REAL(4),INTENT(IN),OPTIONAL:: LINE_VALUE(*),LINE_RGB(3,*)
    REAL(4),INTENT(IN),OPTIONAL:: LINE_THICKNESS(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_PAT(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_MARK(*),LINE_MARK_STEP(*)
    REAL(4),INTENT(IN),OPTIONAL:: LINE_MARK_SIZE(*)
    REAL(4),INTENT(IN),OPTIONAL:: PAINT_VALUE(*),PAINT_RGB(3,*)
    REAL(4),INTENT(IN),OPTIONAL:: BEV_XORG,BEV_YORG,BEV_ZORG
    REAL(4),INTENT(IN),OPTIONAL:: BEV_PHI,BEV_CHI,BEV_DISTANCE

    CHARACTER(LEN=*),INTENT(IN),OPTIONAL:: TITLE,XTITLE,YTITLE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_LEN,XTITLE_LEN,YTITLE_LEN
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_FONT,XTITLE_FONT,YTITLE_FONT
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_RGB(3),XTITLE_RGB(3),YTITLE_RGB(3)
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_SEP,XTITLE_SEP,YTITLE_SEP
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_POS

    REAL(4),INTENT(IN),OPTIONAL:: FRAME_RGB(3),FRAME_THICKNESS

    REAL(4),INTENT(IN),OPTIONAL:: SCALE_RGB(3),SCALE_Zero_RGB(3)
    REAL(4),INTENT(IN),OPTIONAL:: SCALE_THICKNESS,SCALE_ZERO_THICKNESS
    REAL(4),INTENT(IN),OPTIONAL:: XSCALE_STEP,YSCALE_STEP,FSCALE_STEP
    REAL(4),INTENT(IN),OPTIONAL:: XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO_PAT,YSCALE_ZERO_PAT, &
                                  FSCALE_ZERO_PAT

    INTEGER,INTENT(IN),OPTIONAL:: VALUE_FONT
    REAL(4),INTENT(IN),OPTIONAL:: VALUE_SIZE,VALUE_RGB(3)
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_STEP,YVALUE_STEP,FVALUE_STEP
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE

    INTEGER,INTENT(IN),OPTIONAL:: MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: NOTITLE,NOFRAME
    INTEGER,INTENT(IN),OPTIONAL:: NOXSCALE,NOYSCALE,NOFSCALE
    INTEGER,INTENT(IN),OPTIONAL:: NOXVALUE,NOYVALUE,NOFVALUE

    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE PAINT_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,PAINT_RGB_SUB

    TYPE(grf_attr_type):: A
    INTEGER:: NX,NG
    REAL(4):: GY(NGMAX)

    IF(PRESENT(MODE_2D)) THEN
       A%MODE_2D=MODE_2D
    ELSE
       A%MODE_2D=0
    ENDIF
    DO NG=1,NGMAX
       GY(1:NGMAX)=REAL(NG)
    END DO
    CALL GRF_CONVERT(NGP,GX,GY,GF,NXM,NXMAX,NGMAX, &
                     GPXMIN,GPXMAX,GPYMIN,GPYMAX, &
                     XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                     XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                     NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                     LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                     LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                     PAINT_VALUE,PAINT_RGB, &
                     BEV_XORG,BEV_YORG,BEV_ZORG, &
                     BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                     TITLE,XTITLE,YTITLE, &
                     TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                     TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                     TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                     TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                     TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                     FRAME_RGB,FRAME_THICKNESS, &
                     SCALE_RGB,SCALE_ZERO_RGB, &
                     SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                     XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                     XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                     XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                     XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                     XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                     XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                     VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                     XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                     XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                     XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                     MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE, &
                     NOTITLE,NOFRAME, &
                     NOXSCALE,NOYSCALE,NOFSCALE, &
                     NOXVALUE,NOYVALUE,NOFVALUE, &
                     LINE_RGB_SUB,PAINT_RGB_SUB,A)

    IF(A%MODE_2D.EQ.0) THEN
       CALL GRF1D_EXEC(GX,GF,NXM,NXMAX,NGMAX,A)
    ELSE
       CALL GRF2D_EXEC(GX,GY,GF,NXM,NXMAX,NGMAX,A)
    ENDIF

    DEALLOCATE(A%LINE_RGB)
    DEALLOCATE(A%LINE_PAT)
    DEALLOCATE(A%LINE_MARK)
    DEALLOCATE(A%LINE_MARK_STEP)
    DEALLOCATE(A%LINE_THICKNESS)
    RETURN
  END SUBROUTINE GRF1D

! ***** DRAW 1D GRAPH: REAL(8) interface *****

  SUBROUTINE GRD1D(NGP,FX,FF,NXM,NXMAX,NGMAX, &   ! indispensable arguments
                   TITLE,MODE_LS, &               ! optional positional args
                   GPXMIN,GPXMAX,GPYMIN,GPYMAX, & ! top of optional args
                   XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                   XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                   NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                   LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                   LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                   PAINT_VALUE,PAINT_RGB, &
                   BEV_XORG,BEV_YORG,BEV_ZORG, &
                   BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                   XTITLE,YTITLE, &
                   TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                   TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                   TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                   TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                   TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                   FRAME_RGB,FRAME_THICKNESS, &
                   SCALE_RGB,SCALE_ZERO_RGB, &
                   SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                   XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                   XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                   XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                   XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                   XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                   XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                   VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                   XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                   XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                   XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                   MODE_2D,MODE_XY,MODE_PRD,FRAME_TYPE, &
                   NOTITLE,NOFRAME, &
                   NOXSCALE,NOYSCALE,NOFSCALE, &
                   NOXVALUE,NOYVALUE,NOFVALUE, &
                   LINE_RGB_SUB,PAINT_RGB_SUB)

    IMPLICIT NONE

    INTEGER,INTENT(IN):: NGP                       ! Graph size and postion ID
    REAL(8),INTENT(IN):: FX(NXMAX),FF(NXM,NGMAX)   ! 1D data
    INTEGER,INTENT(IN):: NXM,NXMAX,NGMAX           ! Number of data

    REAL(8),INTENT(IN),OPTIONAL:: GPXMIN,GPXMAX,GPYMIN,GPYMAX
    REAL(8),INTENT(IN),OPTIONAL:: XMIN,XMAX,XORG
    REAL(8),INTENT(IN),OPTIONAL:: YMIN,YMAX,YORG
    REAL(8),INTENT(IN),OPTIONAL:: FMIN,FMAX,FORG
    REAL(8),INTENT(IN),OPTIONAL:: XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR
    INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NYMIN,NXSTEP,NYSTEP

    INTEGER,INTENT(IN),OPTIONAL:: NLMAX,NPMAX
    REAL(8),INTENT(IN),OPTIONAL:: LINE_VALUE(*),LINE_RGB(3,*)
    REAL(8),INTENT(IN),OPTIONAL:: LINE_THICKNESS(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_PAT(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_MARK(*),LINE_MARK_STEP(*)
    REAL(8),INTENT(IN),OPTIONAL:: LINE_MARK_SIZE(*)
    REAL(8),INTENT(IN),OPTIONAL:: PAINT_VALUE(*),PAINT_RGB(3,*)
    REAL(8),INTENT(IN),OPTIONAL:: BEV_XORG,BEV_YORG,BEV_ZORG
    REAL(8),INTENT(IN),OPTIONAL:: BEV_PHI,BEV_CHI,BEV_DISTANCE

    CHARACTER(LEN=*),INTENT(IN),OPTIONAL:: TITLE,XTITLE,YTITLE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_LEN,XTITLE_LEN,YTITLE_LEN
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_FONT,XTITLE_FONT,YTITLE_FONT
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_RGB(3),XTITLE_RGB(3),YTITLE_RGB(3)
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_SEP,XTITLE_SEP,YTITLE_SEP
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_POS

    REAL(8),INTENT(IN),OPTIONAL:: FRAME_RGB(3),FRAME_THICKNESS

    REAL(8),INTENT(IN),OPTIONAL:: SCALE_RGB(3),SCALE_Zero_RGB(3)
    REAL(8),INTENT(IN),OPTIONAL:: SCALE_THICKNESS,SCALE_ZERO_THICKNESS
    REAL(8),INTENT(IN),OPTIONAL:: XSCALE_STEP,YSCALE_STEP,FSCALE_STEP
    REAL(8),INTENT(IN),OPTIONAL:: XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO_PAT,YSCALE_ZERO_PAT, &
                                  FSCALE_ZERO_PAT

    INTEGER,INTENT(IN),OPTIONAL:: VALUE_FONT
    REAL(8),INTENT(IN),OPTIONAL:: VALUE_SIZE,VALUE_RGB(3)
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_STEP,YVALUE_STEP,FVALUE_STEP
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE

    INTEGER,INTENT(IN),OPTIONAL:: MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: NOTITLE,NOFRAME
    INTEGER,INTENT(IN),OPTIONAL:: NOXSCALE,NOYSCALE,NOFSCALE
    INTEGER,INTENT(IN),OPTIONAL:: NOXVALUE,NOYVALUE,NOFVALUE

    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE PAINT_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,PAINT_RGB_SUB

    TYPE(grf_attr_type):: A

    INTEGER:: NX,NG
    REAL(4):: GX(NXMAX),GY(NGMAX),GF(NXM,NGMAX)
    REAL(4):: GUCLIP

    IF(PRESENT(MODE_2D)) THEN
       A%MODE_2D=MODE_2D
    ELSE
       A%MODE_2D=0
    ENDIF

    DO NX=1,NXMAX
       GX(NX)=GUCLIP(FX(NX))
    ENDDO
    DO NG=1,NGMAX
       GY(NG)=1.0*(NG-1)
       DO NX=1,NXMAX
          GF(NX,NG)=GUCLIP(FF(NX,NG))
       ENDDO
    ENDDO

    CALL GRD_CONVERT(NGP,GX,GY,GF,NXM,NXMAX,NGMAX, &
                     GPXMIN,GPXMAX,GPYMIN,GPYMAX, &
                     XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                     XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                     NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                     LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                     LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                     PAINT_VALUE,PAINT_RGB, &
                     BEV_XORG,BEV_YORG,BEV_ZORG, &
                     BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                     TITLE,XTITLE,YTITLE, &
                     TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                     TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                     TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                     TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                     TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                     FRAME_RGB,FRAME_THICKNESS, &
                     SCALE_RGB,SCALE_ZERO_RGB, &
                     SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                     XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                     XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                     XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                     XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                     XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                     XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                     VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                     XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                     XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                     XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                     MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE, &
                     NOTITLE,NOFRAME, &
                     NOXSCALE,NOYSCALE,NOFSCALE, &
                     NOXVALUE,NOYVALUE,NOFVALUE, &
                     LINE_RGB_SUB,PAINT_RGB_SUB,A)

    IF(A%MODE_2D.EQ.0) THEN
       CALL GRF1D_EXEC(GX,GF,NXM,NXMAX,NGMAX,A)
    ELSE
       CALL GRF2D_EXEC(GX,GY,GF,NXM,NXMAX,NGMAX,A)
    ENDIF

    DEALLOCATE(A%LINE_RGB)
    DEALLOCATE(A%LINE_PAT)
    DEALLOCATE(A%LINE_MARK)
    DEALLOCATE(A%LINE_MARK_STEP)
    DEALLOCATE(A%LINE_THICKNESS)
    RETURN
  END SUBROUTINE GRD1D

! ***** Convert input parameters to A: REAL(4) *****

  SUBROUTINE GRF_CONVERT(NGP,GX,GY,GF,NXM,NXMAX,NYMAX, &
                         GPXMIN,GPXMAX,GPYMIN,GPYMAX, &
                         XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                         XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                         NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                         LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                         LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                         PAINT_VALUE,PAINT_RGB, &
                         BEV_XORG,BEV_YORG,BEV_ZORG, &
                         BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                         TITLE,XTITLE,YTITLE, &
                         TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                         TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                         TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                         TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                         TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                         FRAME_RGB,FRAME_THICKNESS, &
                         SCALE_RGB,SCALE_ZERO_RGB, &
                         SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                         XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                         XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                         XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                         XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                         XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                         XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                         VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                         XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                         XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                         XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                         MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE, &
                         NOTITLE,NOFRAME, &
                         NOXSCALE,NOYSCALE,NOFSCALE, &
                         NOXVALUE,NOYVALUE,NOFVALUE, &
                         LINE_RGB_SUB,PAINT_RGB_SUB,A)

    IMPLICIT NONE

    INTEGER,INTENT(IN):: NGP
    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX

    REAL(4),INTENT(IN),OPTIONAL:: GPXMIN,GPXMAX,GPYMIN,GPYMAX
    REAL(4),INTENT(IN),OPTIONAL:: XMIN,XMAX,XORG
    REAL(4),INTENT(IN),OPTIONAL:: YMIN,YMAX,YORG
    REAL(4),INTENT(IN),OPTIONAL:: FMIN,FMAX,FORG
    REAL(4),INTENT(IN),OPTIONAL:: XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR
    INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NYMIN,NXSTEP,NYSTEP

    INTEGER,INTENT(IN),OPTIONAL:: NLMAX,NPMAX
    REAL(4),INTENT(IN),OPTIONAL:: LINE_VALUE(*),LINE_RGB(3,*)
    REAL(4),INTENT(IN),OPTIONAL:: LINE_THICKNESS(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_PAT(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_MARK(*),LINE_MARK_STEP(*)
    REAL(4),INTENT(IN),OPTIONAL:: LINE_MARK_SIZE(*)
    REAL(4),INTENT(IN),OPTIONAL:: PAINT_VALUE(*),PAINT_RGB(3,*)
    REAL(4),INTENT(IN),OPTIONAL:: BEV_XORG,BEV_YORG,BEV_ZORG
    REAL(4),INTENT(IN),OPTIONAL:: BEV_PHI,BEV_CHI,BEV_DISTANCE

    CHARACTER(LEN=*),INTENT(IN),OPTIONAL:: TITLE,XTITLE,YTITLE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_LEN,XTITLE_LEN,YTITLE_LEN
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_FONT,XTITLE_FONT,YTITLE_FONT
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_RGB(3),XTITLE_RGB(3),YTITLE_RGB(3)
    REAL(4),INTENT(IN),OPTIONAL:: TITLE_SEP,XTITLE_SEP,YTITLE_SEP
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_POS

    REAL(4),INTENT(IN),OPTIONAL:: FRAME_RGB(3),FRAME_THICKNESS

    REAL(4),INTENT(IN),OPTIONAL:: SCALE_RGB(3),SCALE_Zero_RGB(3)
    REAL(4),INTENT(IN),OPTIONAL:: SCALE_THICKNESS,SCALE_ZERO_THICKNESS
    REAL(4),INTENT(IN),OPTIONAL:: XSCALE_STEP,YSCALE_STEP,FSCALE_STEP
    REAL(4),INTENT(IN),OPTIONAL:: XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO_PAT,YSCALE_ZERO_PAT, &
                                  FSCALE_ZERO_PAT

    INTEGER,INTENT(IN),OPTIONAL:: VALUE_FONT
    REAL(4),INTENT(IN),OPTIONAL:: VALUE_SIZE,VALUE_RGB(3)
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_STEP,YVALUE_STEP,FVALUE_STEP
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE

    INTEGER,INTENT(IN),OPTIONAL:: MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: NOTITLE,NOFRAME
    INTEGER,INTENT(IN),OPTIONAL:: NOXSCALE,NOYSCALE,NOFSCALE
    INTEGER,INTENT(IN),OPTIONAL:: NOXVALUE,NOYVALUE,NOFVALUE

    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE PAINT_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,PAINT_RGB_SUB

    TYPE(grf_attr_type):: A

    INTEGER,PARAMETER:: NLM=5
    REAL(4):: GP(4),GL,GFACTOR
    REAL(4):: GXMINL,GXMAXL,GYMINL,GYMAXL,GFMINL,GFMAXL
    REAL(4):: GXMIN,GXMAX,GXSTEP,GXORG
    REAL(4):: GYMIN,GYMAX,GYSTEP,GYORG
    REAL(4):: GFMIN,GFMAX,GFSTEP,GFORG
    REAL(4):: GRGB(3,NLM)
    INTEGER:: NL,NCH,NGULEN
    INTEGER:: IPAT(NLM)
    CHARACTER(LEN=80):: KTITLE
    CHARACTER(LEN=1):: KDL

    DATA IPAT/0,2,3,4,6/
    DATA GRGB/0.0,0.0,0.0, 1.0,0.0,0.0, 0.0,0.0,1.0, &
              0.0,1.0,0.0, 1.0,0.0,1.0/

    IF(NGP.LT.0.OR.NGP.GT.29) THEN
       WRITE(6,*) 'XX GRF_CONVERT: INVALID NGP'
       RETURN
    ENDIF

    IF(PRESENT(MODE_XY)) THEN
       A%MODE_XY=MODE_XY
    ELSE
       A%MODE_XY=0
    ENDIF
    IF(PRESENT(MODE_PRD)) THEN
       A%MODE_PRD=MODE_PRD
    ELSE
       A%MODE_PRD=0
    ENDIF
    IF(PRESENT(MODE_LS)) THEN
       A%MODE_LS=MODE_LS
    ELSE
       A%MODE_LS=0
    ENDIF

    IF(PRESENT(MODE_2D)) THEN
       A%MODE_2D=MODE_2D
    ELSE
       A%MODE_2D=0
    ENDIF

!     ----- define graph position -----

    CALL GRFUT4(NGP,GP) ! assign predefined graph position to GP
    IF(PRESENT(GPXMIN)) THEN
       A%GPXMIN=GPXMIN
    ELSE
       A%GPXMIN=GP(1)
    ENDIF
    IF(PRESENT(GPXMAX)) THEN
       A%GPXMAX=GPXMAX
    ELSE
       A%GPXMAX=GP(2)
    ENDIF
    IF(PRESENT(GPYMIN)) THEN
       A%GPYMIN=GPYMIN
    ELSE
       A%GPYMIN=GP(3)
    ENDIF
    IF(PRESENT(GPYMAX)) THEN
       A%GPYMAX=GPYMAX
    ELSE
       A%GPYMAX=GP(4)
    ENDIF

!     ----- define graph size scaling factor -----

    GL=MIN(ABS(A%GPXMAX-A%GPXMIN),ABS(A%GPYMAX-A%GPYMIN))
    GFACTOR=GL/15.0

!     ----- SCALE ADJUSTMENT SECTION -----

    IF(PRESENT(XSPACE_FACTOR)) THEN
       A%XSPACE_FACTOR=XSPACE_FACTOR
    ELSE
       A%XSPACE_FACTOR=0.0
    END IF
    IF(PRESENT(YSPACE_FACTOR)) THEN
       A%YSPACE_FACTOR=YSPACE_FACTOR
    ELSE
       A%YSPACE_FACTOR=0.0
    END IF

!     ----- DATA SECTION -----

    IF(PRESENT(NXMIN)) THEN
       A%NXMIN=NXMIN
    ELSE
       A%NXMIN=1
    END IF
    IF(PRESENT(NXSTEP)) THEN
       A%NXSTEP=NXSTEP
    ELSE
       A%NXSTEP=1
    END IF

    IF(PRESENT(NYMIN)) THEN
       A%NYMIN=NYMIN
    ELSE
       A%NYMIN=1
    END IF
    IF(PRESENT(NYSTEP)) THEN
       A%NYSTEP=NYSTEP
    ELSE
       A%NYSTEP=1
    END IF

    IF(A%MODE_2D.EQ.0) THEN
       CALL GRFUT1(GX,NXMAX,GXMINL,GXMAXL,NXMIN=A%NXMIN,NXSTEP=A%NXSTEP)
       CALL GRFUT2(GF,NXM,NXMAX,NYMAX,GFMINL,GFMAXL, &
                   NXMIN=A%NXMIN,NXSTEP=A%NXSTEP,NYMIN=A%NYMIN,NYSTEP=A%NYSTEP)
       GYMINL=0.0
       GYMAXL=0.0
    ELSE
       CALL GRFUT1(GX,NXMAX,GXMINL,GXMAXL,NXMIN=A%NXMIN,NXSTEP=A%NXSTEP)
       CALL GRFUT1(GY,NYMAX,GYMINL,GYMAXL,NXMIN=A%NYMIN,NXSTEP=A%NYSTEP)
       CALL GRFUT2(GF,NXM,NXMAX,NYMAX,GFMINL,GFMAXL, &
                   NXMIN=A%NXMIN,NXSTEP=A%NXSTEP,NYMIN=A%NYMIN,NYSTEP=A%NYSTEP)
    ENDIF

    IF(PRESENT(XMIN)) GXMINL=XMIN
    IF(PRESENT(XMAX)) GXMAXL=XMAX
    IF(PRESENT(YMIN)) GYMINL=YMIN
    IF(PRESENT(YMAX)) GYMAXL=YMAX
    IF(PRESENT(FMIN)) GFMINL=FMIN
    IF(PRESENT(FMAX)) GFMAXL=FMAX

    CALL GRFUT3(GXMINL,GXMAXL,GXMIN,GXMAX,GXSTEP,GXORG)
    CALL GRFUT3(GYMINL,GYMAXL,GYMIN,GYMAX,GYSTEP,GYORG)
    CALL GRFUT3(GFMINL,GFMAXL,GFMIN,GFMAX,GFSTEP,GFORG)

    IF(PRESENT(XMIN)) THEN
       A%XMIN=XMIN
    ELSE
       A%XMIN=GXMIN
    ENDIF
    IF(PRESENT(XMAX)) THEN
       A%XMAX=XMAX
    ELSE
       A%XMAX=GXMAX
    ENDIF
    IF(PRESENT(XSCALE_STEP)) THEN
       A%XSCALE_STEP=XSCALE_STEP
    ELSE
       A%XSCALE_STEP=GXSTEP
    ENDIF
    IF(PRESENT(XORG)) THEN
       A%XORG=XORG
    ELSE
       A%XORG=GXORG
    ENDIF

    IF(PRESENT(YMIN)) THEN
       A%YMIN=YMIN
    ELSE
       A%YMIN=GYMIN
    ENDIF
    IF(PRESENT(YMAX)) THEN
       A%YMAX=YMAX
    ELSE
       A%YMAX=GYMAXL
    ENDIF
    IF(PRESENT(YSCALE_STEP)) THEN
       A%YSCALE_STEP=YSCALE_STEP
    ELSE
       A%YSCALE_STEP=GYSTEP
    ENDIF
    IF(PRESENT(YORG)) THEN
       A%YORG=YORG
    ELSE
       A%YORG=GYORG
    ENDIF

    IF(PRESENT(FMIN)) THEN
       A%FMIN=FMIN
    ELSE
       A%FMIN=GFMIN
    ENDIF
    IF(PRESENT(FMAX)) THEN
       A%FMAX=FMAX
    ELSE
       A%FMAX=GFMAXL
    ENDIF
    IF(PRESENT(FSCALE_STEP)) THEN
       A%FSCALE_STEP=FSCALE_STEP
    ELSE
       A%FSCALE_STEP=GFSTEP
    ENDIF
    IF(PRESENT(FORG)) THEN
       A%FORG=FORG
    ELSE
       A%FORG=GFORG
    ENDIF

!     ----- Adjust min max according to space factor at both ends-----

    GL=A%XMAX-A%XMIN
    A%XMAX=A%XMAX+0.5*GL*A%XSPACE_FACTOR
    A%XMIN=A%XMIN-0.5*GL*A%XSPACE_FACTOR
    GL=A%YMAX-A%YMIN
    A%YMAX=A%YMAX+0.5*GL*A%YSPACE_FACTOR
    A%YMIN=A%YMIN-0.5*GL*A%YSPACE_FACTOR
    GL=A%FMAX-A%FMIN
    A%FMAX=A%FMAX+0.5*GL*A%FSPACE_FACTOR
    A%FMIN=A%FMIN-0.5*GL*A%FSPACE_FACTOR

!     ----- LINE SECTION -----

    IF(A%MODE_2D.EQ.0) THEN  ! 1D data
       IF(PRESENT(NLMAX)) THEN
          A%NLMAX=NLMAX
       ELSE
          A%NLMAX=NLM
       ENDIF
       ALLOCATE(A%LINE_RGB(3,A%NLMAX))
       ALLOCATE(A%LINE_THICKNESS(A%NLMAX))
       ALLOCATE(A%LINE_PAT(A%NLMAX))
       ALLOCATE(A%LINE_MARK(A%NLMAX))
       ALLOCATE(A%LINE_MARK_STEP(A%NLMAX))
       ALLOCATE(A%LINE_MARK_SIZE(A%NLMAX))

       IF(PRESENT(LINE_RGB)) THEN
          A%LINE_RGB(1:3,1:A%NLMAX)=LINE_RGB(1:3,1:A%NLMAX)
       ELSE
          DO NL=1,A%NLMAX
             A%LINE_RGB(1:3,NL)=GRGB(1:3,MOD(NL-1,NLM)+1)
          ENDDO
       END IF
       IF(PRESENT(LINE_THICKNESS)) THEN
          A%LINE_THICKNESS(1:A%NLMAX)=LINE_THICKNESS(1:A%NLMAX)*GFACTOR
       ELSE
          A%LINE_THICKNESS(1:A%NLMAX)=0.07*GFACTOR
       ENDIF
       IF(PRESENT(LINE_PAT)) THEN
          A%LINE_PAT(1:A%NLMAX)=LINE_PAT(1:A%NLMAX)
       ELSE
          DO NL=1,A%NLMAX
             A%LINE_PAT(NL)=IPAT(MOD(NL-1,NLM)+1)
          END DO
       ENDIF
       IF(PRESENT(LINE_MARK)) THEN
          A%LINE_MARK(1:A%NLMAX)=LINE_MARK(1:A%NLMAX)
       ELSE
          A%LINE_MARK(1:A%NLMAX)=0
       ENDIF
       IF(PRESENT(LINE_MARK_STEP)) THEN
          A%LINE_MARK_STEP(1:A%NLMAX)=LINE_MARK_STEP(1:A%NLMAX)
       ELSE
          A%LINE_MARK_STEP(1:A%NLMAX)=0
       ENDIF
       IF(PRESENT(LINE_MARK_SIZE)) THEN
          A%LINE_MARK_SIZE(1:A%NLMAX)=LINE_MARK_SIZE(1:A%NLMAX)*GFACTOR
       ELSE
          A%LINE_MARK_SIZE(1:A%NLMAX)=0.3*GFACTOR
       ENDIF

    END IF

!     ----- PAINT SECTION -----

    IF(PRESENT(NPMAX)) THEN
       A%NPMAX=NPMAX
    ELSE
       A%NPMAX=0
    END IF
    IF(A%NPMAX.GT.0) THEN
       ALLOCATE(A%PAINT_VALUE(A%NPMAX))
       ALLOCATE(A%PAINT_RGB(3,A%NPMAX))
       IF(PRESENT(PAINT_VALUE)) THEN
          A%PAINT_VALUE(1:A%NLMAX)=PAINT_VALUE(1:A%NLMAX)
       END IF
       IF(PRESENT(PAINT_RGB)) THEN
          A%PAINT_RGB(1:3,1:A%NLMAX)=PAINT_RGB(1:3,1:A%NLMAX)
       ELSE
          A%PAINT_RGB(1:3,1:A%NLMAX)=GRGB(1:3,1:A%NLMAX)
       END IF
    END IF

!     ----- TITLE SECTION -----

    IF(PRESENT(TITLE)) THEN
       KDL=TITLE(1:1)
       NCH=2
1      IF(TITLE(NCH:NCH).EQ.KDL.OR.NCH.EQ.LEN(TITLE)) GOTO 2
       KTITLE(NCH-1:NCH-1)=TITLE(NCH:NCH)
       NCH=NCH+1
       GOTO 1
2      CONTINUE
       A%TITLE=KTITLE
       A%TITLE_LEN=NCH-2
    ELSE
       A%TITLE_LEN=0
    ENDIF
       
    IF(PRESENT(TITLE_SIZE)) THEN
       A%TITLE_SIZE=TITLE_SIZE*GFACTOR
    ELSE
       A%TITLE_SIZE=0.6*GFACTOR
    END IF

    IF(PRESENT(TITLE_FONT)) THEN
       A%TITLE_FONT=TITLE_FONT
    ELSE
       A%TITLE_FONT=32
    END IF

    IF(PRESENT(TITLE_RGB)) THEN
       A%TITLE_RGB(1:3)=TITLE_RGB(1:3)
    ELSE
       A%TITLE_RGB(1:3)=0.0
    END IF

    IF(PRESENT(TITLE_SEP)) THEN
       A%TITLE_SEP=TITLE_SEP*GFACTOR
    ELSE
       A%TITLE_SEP=0.3*GFACTOR
    END IF

    IF(PRESENT(TITLE_POS)) THEN
       A%TITLE_POS=TITLE_POS
    ELSE
       A%TITLE_POS=0
    END IF
      
    IF(PRESENT(XTITLE)) THEN
       KDL=XTITLE(1:1)
       NCH=2
3      IF(XTITLE(NCH:NCH).EQ.KDL.OR.NCH.EQ.LEN(XTITLE)) GOTO 4
       KTITLE(NCH-1:NCH-1)=XTITLE(NCH:NCH)
       NCH=NCH+1
       GOTO 3
4      CONTINUE
       A%XTITLE=KTITLE
       A%XTITLE_LEN=NCH-2
    ELSE
       A%XTITLE_LEN=0
    ENDIF
       
    IF(PRESENT(XTITLE_SIZE)) THEN
       A%XTITLE_SIZE=XTITLE_SIZE*GFACTOR
    ELSE
       A%XTITLE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(XTITLE_FONT)) THEN
       A%XTITLE_FONT=XTITLE_FONT
    ELSE
       A%XTITLE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(XTITLE_RGB)) THEN
       A%XTITLE_RGB(1:3)=XTITlE_RGB(1:3)
    ELSE
       A%XTITLE_RGB(1:3)=A%TITlE_RGB(1:3)
    END IF

    IF(PRESENT(XTITLE_SEP)) THEN
       A%XTITLE_SEP=XTITLE_SEP*GFACTOR
    ELSE
       A%XTITLE_SEP=A%TITLE_SIZE*3.0+A%TITLE_SEP
    END IF

    IF(PRESENT(YTITLE)) THEN
       KDL=YTITLE(1:1)
       NCH=2
5      IF(YTITLE(NCH:NCH).EQ.KDL.OR.NCH.EQ.LEN(YTITLE)) GOTO 6
       KTITLE(NCH-1:NCH-1)=YTITLE(NCH:NCH)
       NCH=NCH+1
       GOTO 6
6      CONTINUE
       A%YTITLE=KTITLE
       A%YTITLE_LEN=NCH-2
    ELSE
       A%YTITLE_LEN=0
    ENDIF
       
    IF(PRESENT(YTITLE_SIZE)) THEN
       A%YTITLE_SIZE=YTITLE_SIZE*GFACTOR
    ELSE
       A%YTITLE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(YTITLE_FONT)) THEN
       A%YTITLE_FONT=YTITLE_FONT
    ELSE
       A%YTITLE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(YTITLE_RGB)) THEN
       A%YTITLE_RGB(1:3)=YTITlE_RGB(1:3)
    ELSE
       A%YTITLE_RGB(1:3)=A%TITlE_RGB(1:3)
    END IF

    IF(PRESENT(YTITLE_SEP)) THEN
       A%YTITLE_SEP=YTITLE_SEP*GFACTOR
    ELSE
       A%YTITLE_SEP=A%YTITLE_SIZE*3.0+A%TITLE_SEP
    END IF

!     ----- FRAME SECTION -----

    IF(PRESENT(FRAME_RGB)) THEN
       A%FRAME_RGB(1:3)=FRAME_RGB(1:3)
    ELSE
       A%FRAME_RGB(1:3)=0.0
    END IF

    IF(PRESENT(FRAME_THICKNESS)) THEN
       A%FRAME_THICKNESS=FRAME_THICKNESS*GFACTOR
    ELSE
       A%FRAME_THICKNESS=0.07*GFACTOR
    END IF

    IF(PRESENT(SCALE_THICKNESS)) THEN
       A%SCALE_THICKNESS=SCALE_THICKNESS*GFACTOR
    ELSE
       A%SCALE_THICKNESS=A%FRAME_THICKNESS
    END IF

!     ----- SCALE SECTION -----

    IF(PRESENT(SCALE_RGB)) THEN
       A%SCALE_RGB(1:3)=SCALE_RGB(1:3)
    ELSE
       A%SCALE_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

    IF(PRESENT(SCALE_ZERO_RGB)) THEN
       A%SCALE_ZERO_RGB(1:3)=SCALE_ZERO_RGB(1:3)
    ELSE
       A%SCALE_ZERO_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

    IF(PRESENT(SCALE_THICKNESS)) THEN
       A%SCALE_THICKNESS=SCALE_THICKNESS*GFACTOR
    ELSE
       A%SCALE_THICKNESS=A%FRAME_THICKNESS
    END IF

    IF(PRESENT(SCALE_ZERO_THICKNESS)) THEN
       A%SCALE_ZERO_THICKNESS=SCALE_ZERO_THICKNESS*GFACTOR
    ELSE
       A%SCALE_ZERO_THICKNESS=A%FRAME_THICKNESS
    END IF

    IF(PRESENT(VALUE_FONT)) THEN
       A%VALUE_FONT=VALUE_FONT
    ELSE
       A%VALUE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(VALUE_SIZE)) THEN
       A%VALUE_SIZE=VALUE_SIZE*GFACTOR
    ELSE
       A%VALUE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(VALUE_RGB)) THEN
       A%VALUE_RGB(1:3)=VALUE_RGB(1:3)
    ELSE
       A%VALUE_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

!     ----- XSCALE SECTION -----

    IF(PRESENT(XSCALE_SIZE)) THEN
       A%XSCALE_SIZE=XSCALE_SIZE*GFACTOR
    ELSE
       A%XSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(XSCALE_TYPE)) THEN
       A%XSCALE_TYPE=XSCALE_TYPE
    ELSE
       A%XSCALE_TYPE=9
    END IF

    IF(PRESENT(XSCALE_LTYPE)) THEN
       A%XSCALE_LTYPE=XSCALE_LTYPE
    ELSE
       A%XSCALE_LTYPE=9
    END IF

    IF(PRESENT(XSCALE_ZERO)) THEN
       A%XSCALE_ZERO=XSCALE_ZERO
    ELSE
       A%XSCALE_ZERO=1
    END IF

    IF(PRESENT(XSCALE_ZERO_PAT)) THEN
       A%XSCALE_ZERO_PAT=XSCALE_ZERO_PAT
    ELSE
       A%XSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(XVALUE_STEP)) THEN
       A%XVALUE_STEP=XVALUE_STEP
    ELSE
       A%XVALUE_STEP=2
    END IF

    IF(PRESENT(XVALUE_TYPE)) THEN
       A%XVALUE_TYPE=XVALUE_TYPE
    ELSE
       A%XVALUE_TYPE=NGULEN(2*GXSTEP)
    END IF

    IF(PRESENT(XVALUE_LTYPE)) THEN
       A%XVALUE_LTYPE=XVALUE_LTYPE
    ELSE
       A%XVALUE_LTYPE=1
    END IF

!     ----- YSCALE SECTION -----

    IF(PRESENT(YSCALE_SIZE)) THEN
       A%YSCALE_SIZE=YSCALE_SIZE*GFACTOR
    ELSE
       A%YSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(YSCALE_TYPE)) THEN
       A%YSCALE_TYPE=YSCALE_TYPE
    ELSE
       A%YSCALE_TYPE=9
    END IF

    IF(PRESENT(YSCALE_LTYPE)) THEN
       A%YSCALE_LTYPE=YSCALE_LTYPE
    ELSE
       A%YSCALE_LTYPE=9
    END IF

    IF(PRESENT(YSCALE_ZERO)) THEN
       A%YSCALE_ZERO=YSCALE_ZERO
    ELSE
       A%YSCALE_ZERO=1
    END IF

    IF(PRESENT(YSCALE_ZERO_PAT)) THEN
       A%YSCALE_ZERO_PAT=YSCALE_ZERO_PAT
    ELSE
       A%YSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(YVALUE_STEP)) THEN
       A%YVALUE_STEP=YVALUE_STEP
    ELSE
       A%YVALUE_STEP=2
    END IF

    IF(PRESENT(YVALUE_TYPE)) THEN
       A%YVALUE_TYPE=YVALUE_TYPE
    ELSE
       A%YVALUE_TYPE=NGULEN(2*GYSTEP)
    END IF

    IF(PRESENT(YVALUE_LTYPE)) THEN
       A%YVALUE_LTYPE=YVALUE_LTYPE
    ELSE
       A%YVALUE_LTYPE=1
    END IF

!     ----- FSCALE SECTION -----

    IF(PRESENT(FSCALE_SIZE)) THEN
       A%FSCALE_SIZE=FSCALE_SIZE*GFACTOR
    ELSE
       A%FSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(FSCALE_TYPE)) THEN
       A%FSCALE_TYPE=FSCALE_TYPE
    ELSE
       A%FSCALE_TYPE=9
    END IF

    IF(PRESENT(FSCALE_LTYPE)) THEN
       A%FSCALE_LTYPE=FSCALE_LTYPE
    ELSE
       A%FSCALE_LTYPE=9
    END IF

    IF(PRESENT(FSCALE_ZERO)) THEN
       A%FSCALE_ZERO=FSCALE_ZERO
    ELSE
       A%FSCALE_ZERO=1
    END IF

    IF(PRESENT(FSCALE_ZERO_PAT)) THEN
       A%FSCALE_ZERO_PAT=FSCALE_ZERO_PAT
    ELSE
       A%FSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(FVALUE_STEP)) THEN
       A%FVALUE_STEP=FVALUE_STEP
    ELSE
       A%FVALUE_STEP=2
    END IF

    IF(PRESENT(FVALUE_TYPE)) THEN
       A%FVALUE_TYPE=FVALUE_TYPE
    ELSE
       A%FVALUE_TYPE=NGULEN(2*GFSTEP)
    END IF

    IF(PRESENT(FVALUE_LTYPE)) THEN
       A%FVALUE_LTYPE=FVALUE_LTYPE
    ELSE
       A%FVALUE_LTYPE=1
    END IF

!   --- draw selection section ---

    IF(PRESENT(NOTITLE)) THEN
       A%NOTITLE=NOTITLE
    ELSE
       A%NOTITLE=0
    ENDIF

    IF(PRESENT(NOFRAME)) THEN
       A%NOFRAME=NOFRAME
    ELSE
       A%NOFRAME=0
    ENDIF

    RETURN
  END SUBROUTINE GRF_CONVERT

! ***** Convert input parameters to A: REAL(4) *****

  SUBROUTINE GRD_CONVERT(NGP,GX,GY,GF,NXM,NXMAX,NYMAX, &
                         GPXMIN,GPXMAX,GPYMIN,GPYMAX, &
                         XMIN,XMAX,XORG,YMIN,YMAX,YORG,FMIN,FMAX,FORG, &
                         XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR, &
                         NXMIN,NYMIN,NXSTEP,NYSTEP,NLMAX,NPMAX, &
                         LINE_VALUE,LINE_RGB,LINE_THICKNESS,LINE_PAT, &
                         LINE_MARK,LINE_MARK_STEP,LINE_MARK_SIZE, &
                         PAINT_VALUE,PAINT_RGB, &
                         BEV_XORG,BEV_YORG,BEV_ZORG, &
                         BEV_PHI,BEV_CHI,BEV_DISTANCE, &
                         TITLE,XTITLE,YTITLE, &
                         TITLE_LEN,XTITLE_LEN,YTITLE_LEN, &
                         TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE, &
                         TITLE_FONT,XTITLE_FONT,YTITLE_FONT, &
                         TITLE_RGB,XTITLE_RGB,YTITLE_RGB, &
                         TITLE_SEP,XTITLE_SEP,YTITLE_SEP,TITLE_POS, &
                         FRAME_RGB,FRAME_THICKNESS, &
                         SCALE_RGB,SCALE_ZERO_RGB, &
                         SCALE_THICKNESS,SCALE_ZERO_THICKNESS, &
                         XSCALE_STEP,YSCALE_STEP,FSCALE_STEP, &
                         XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE, &
                         XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE, &
                         XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE, &
                         XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO, &
                         XSCALE_ZERO_PAT,YSCALE_ZERO_PAT,FSCALE_ZERO_PAT, &
                         VALUE_FONT,VALUE_SIZE,VALUE_RGB, &
                         XVALUE_STEP,YVALUE_STEP,FVALUE_STEP, &
                         XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE, &
                         XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE, &
                         MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE, &
                         NOTITLE,NOFRAME, &
                         NOXSCALE,NOYSCALE,NOFSCALE, &
                         NOXVALUE,NOYVALUE,NOFVALUE, &
                         LINE_RGB_SUB,PAINT_RGB_SUB,A)

    IMPLICIT NONE

    INTEGER,INTENT(IN):: NGP
    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX

    REAL(8),INTENT(IN),OPTIONAL:: GPXMIN,GPXMAX,GPYMIN,GPYMAX
    REAL(8),INTENT(IN),OPTIONAL:: XMIN,XMAX,XORG
    REAL(8),INTENT(IN),OPTIONAL:: YMIN,YMAX,YORG
    REAL(8),INTENT(IN),OPTIONAL:: FMIN,FMAX,FORG
    REAL(8),INTENT(IN),OPTIONAL:: XSPACE_FACTOR,YSPACE_FACTOR,FSPACE_FACTOR
    INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NYMIN,NXSTEP,NYSTEP

    INTEGER,INTENT(IN),OPTIONAL:: NLMAX,NPMAX
    REAL(8),INTENT(IN),OPTIONAL:: LINE_VALUE(*),LINE_RGB(3,*)
    REAL(8),INTENT(IN),OPTIONAL:: LINE_THICKNESS(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_PAT(*)
    INTEGER,INTENT(IN),OPTIONAL:: LINE_MARK(*),LINE_MARK_STEP(*)
    REAL(8),INTENT(IN),OPTIONAL:: LINE_MARK_SIZE(*)
    REAL(8),INTENT(IN),OPTIONAL:: PAINT_VALUE(*),PAINT_RGB(3,*)
    REAL(8),INTENT(IN),OPTIONAL:: BEV_XORG,BEV_YORG,BEV_ZORG
    REAL(8),INTENT(IN),OPTIONAL:: BEV_PHI,BEV_CHI,BEV_DISTANCE

    CHARACTER(LEN=*),INTENT(IN),OPTIONAL:: TITLE,XTITLE,YTITLE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_LEN,XTITLE_LEN,YTITLE_LEN
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_SIZE,XTITLE_SIZE,YTITLE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_FONT,XTITLE_FONT,YTITLE_FONT
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_RGB(3),XTITLE_RGB(3),YTITLE_RGB(3)
    REAL(8),INTENT(IN),OPTIONAL:: TITLE_SEP,XTITLE_SEP,YTITLE_SEP
    INTEGER,INTENT(IN),OPTIONAL:: TITLE_POS

    REAL(8),INTENT(IN),OPTIONAL:: FRAME_RGB(3),FRAME_THICKNESS

    REAL(8),INTENT(IN),OPTIONAL:: SCALE_RGB(3),SCALE_Zero_RGB(3)
    REAL(8),INTENT(IN),OPTIONAL:: SCALE_THICKNESS,SCALE_ZERO_THICKNESS
    REAL(8),INTENT(IN),OPTIONAL:: XSCALE_STEP,YSCALE_STEP,FSCALE_STEP
    REAL(8),INTENT(IN),OPTIONAL:: XSCALE_SIZE,YSCALE_SIZE,FSCALE_SIZE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_TYPE,YSCALE_TYPE,FSCALE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_LTYPE,YSCALE_LTYPE,FSCALE_LTYPE
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO,YSCALE_ZERO,FSCALE_ZERO
    INTEGER,INTENT(IN),OPTIONAL:: XSCALE_ZERO_PAT,YSCALE_ZERO_PAT, &
                                  FSCALE_ZERO_PAT

    INTEGER,INTENT(IN),OPTIONAL:: VALUE_FONT
    REAL(8),INTENT(IN),OPTIONAL:: VALUE_SIZE,VALUE_RGB(3)
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_STEP,YVALUE_STEP,FVALUE_STEP
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_TYPE,YVALUE_TYPE,FVALUE_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: XVALUE_LTYPE,YVALUE_LTYPE,FVALUE_LTYPE

    INTEGER,INTENT(IN),OPTIONAL:: MODE_2D,MODE_XY,MODE_PRD,MODE_LS,FRAME_TYPE
    INTEGER,INTENT(IN),OPTIONAL:: NOTITLE,NOFRAME
    INTEGER,INTENT(IN),OPTIONAL:: NOXSCALE,NOYSCALE,NOFSCALE
    INTEGER,INTENT(IN),OPTIONAL:: NOXVALUE,NOYVALUE,NOFVALUE

    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE PAINT_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,PAINT_RGB_SUB

    TYPE(grf_attr_type):: A

    INTEGER,PARAMETER:: NLM=5
    REAL(4):: GP(4),GL,GFACTOR,GRGB(3,5)
    REAL(4):: GXMINL,GXMAXL,GYMINL,GYMAXL,GFMINL,GFMAXL
    REAL(4):: GXMIN,GXMAX,GYMIN,GYMAX,GFMIN,GFMAX
    REAL(4):: GXSTEP,GXORG,GYSTEP,GYORG,GFSTEP,GFORG
    INTEGER:: I,NGULEN,IPAT(5),NC,NL
    CHARACTER(LEN=80):: KTITLE
    CHARACTER(LEN=1):: KDL*1
    REAL(4):: GUCLIP

    DATA IPAT/0,2,3,4,6/
    DATA GRGB/0.0,0.0,0.0, 1.0,0.0,0.0, 0.0,0.0,1.0, &
              0.0,1.0,0.0, 1.0,0.0,1.0/

    IF(NGP.LT.0.OR.NGP.GT.29) THEN
       WRITE(6,*) 'XX GRF1D: INVALID NGP'
       RETURN
    ENDIF

    IF(PRESENT(MODE_XY)) THEN
       A%MODE_XY=MODE_XY
    ELSE
       A%MODE_XY=0
    ENDIF
    IF(PRESENT(MODE_PRD)) THEN
       A%MODE_PRD=MODE_PRD
    ELSE
       A%MODE_PRD=0
    ENDIF
    IF(PRESENT(MODE_LS)) THEN
       A%MODE_LS=MODE_LS
    ELSE
       A%MODE_LS=0
    ENDIF

    IF(PRESENT(MODE_2D)) THEN
       A%MODE_2D=MODE_2D
    ELSE
       A%MODE_2D=0
    ENDIF

    CALL GRFUT4(NGP,GP)
    IF(PRESENT(GPXMIN)) THEN
       A%GPXMIN=GUCLIP(GPXMIN)
    ELSE
       A%GPXMIN=GP(1)
    ENDIF
    IF(PRESENT(GPXMAX)) THEN
       A%GPXMAX=GUCLIP(GPXMAX)
    ELSE
       A%GPXMAX=GP(2)
    ENDIF
    IF(PRESENT(GPYMIN)) THEN
       A%GPYMIN=GUCLIP(GPYMIN)
    ELSE
       A%GPYMIN=GP(3)
    ENDIF
    IF(PRESENT(GPYMAX)) THEN
       A%GPYMAX=GUCLIP(GPYMAX)
    ELSE
       A%GPYMAX=GP(4)
    ENDIF

    GL=MIN(ABS(A%GPXMAX-A%GPXMIN),ABS(A%GPYMAX-A%GPYMIN))
    GFACTOR=GL/15.0

!     ----- SCALE ADJUSTMENT SECTION -----

    IF(PRESENT(XSPACE_FACTOR)) THEN
       A%XSPACE_FACTOR=GUCLIP(XSPACE_FACTOR)
    ELSE
       A%XSPACE_FACTOR=0.0
    END IF
    IF(PRESENT(YSPACE_FACTOR)) THEN
       A%YSPACE_FACTOR=GUCLIP(YSPACE_FACTOR)
    ELSE
       A%YSPACE_FACTOR=0.0
    END IF

!     ----- DATA SECTION -----

    IF(PRESENT(NXMIN)) THEN
       A%NXMIN=NXMIN
    ELSE
       A%NXMIN=1
    END IF
    IF(PRESENT(NXSTEP)) THEN
       A%NXSTEP=NXSTEP
    ELSE
       A%NXSTEP=1
    END IF

    IF(PRESENT(NYMIN)) THEN
       A%NYMIN=NYMIN
    ELSE
       A%NYMIN=1
    END IF
    IF(PRESENT(NYSTEP)) THEN
       A%NYSTEP=NYSTEP
    ELSE
       A%NYSTEP=1
    END IF

    IF(A%MODE_2D.EQ.0) THEN
       CALL GRFUT1(GX,NXMAX,GXMINL,GXMAXL,NXMIN=A%NXMIN,NXSTEP=A%NXSTEP)
       CALL GRFUT2(GF,NXM,NXMAX,NYMAX,GFMINL,GFMAXL, &
                   NXMIN=A%NXMIN,NXSTEP=A%NXSTEP,NYMIN=A%NYMIN,NYSTEP=A%NYSTEP)
       GYMINL=0.0
       GYMAXL=0.0
    ELSE
       CALL GRFUT1(GX,NXMAX,GXMINL,GXMAXL,NXMIN=A%NXMIN,NXSTEP=A%NXSTEP)
       CALL GRFUT1(GY,NYMAX,GYMINL,GYMAXL,NXMIN=A%NYMIN,NXSTEP=A%NYSTEP)
       CALL GRFUT2(GF,NXM,NXMAX,NYMAX,GFMINL,GFMAXL, &
                   NXMIN=A%NXMIN,NXSTEP=A%NXSTEP,NYMIN=A%NYMIN,NYSTEP=A%NYSTEP)
    ENDIF

    IF(PRESENT(XMIN)) GXMINL=GUCLIP(XMIN)
    IF(PRESENT(XMAX)) GXMAXL=GUCLIP(XMAX)
    IF(PRESENT(YMIN)) GYMINL=YMIN
    IF(PRESENT(YMAX)) GYMAXL=YMAX
    IF(PRESENT(FMIN)) GFMINL=GUCLIP(FMIN)
    IF(PRESENT(FMAX)) GFMAXL=GUCLIP(FMAX)

    CALL GRFUT3(GXMINL,GXMAXL,GXMIN,GXMAX,GXSTEP,GXORG)
    CALL GRFUT3(GYMINL,GYMAXL,GYMIN,GYMAX,GYSTEP,GYORG)
    CALL GRFUT3(GFMINL,GFMAXL,GFMIN,GFMAX,GFSTEP,GFORG)

    IF(PRESENT(XMIN)) THEN
       A%XMIN=GUCLIP(XMIN)
    ELSE
       A%XMIN=GXMIN
    ENDIF
    IF(PRESENT(XMAX)) THEN
       A%XMAX=GUCLIP(XMAX)
    ELSE
       A%XMAX=GXMAX
    ENDIF
    IF(PRESENT(XSCALE_STEP)) THEN
       A%XSCALE_STEP=GUCLIP(XSCALE_STEP)
    ELSE
       A%XSCALE_STEP=GXSTEP
    ENDIF
    IF(PRESENT(XORG)) THEN
       A%XORG=GUCLIP(XORG)
    ELSE
       A%XORG=GXORG
    ENDIF

    IF(PRESENT(YMIN)) THEN
       A%YMIN=GUCLIP(YMIN)
    ELSE
       A%YMIN=GYMIN
    ENDIF
    IF(PRESENT(YMAX)) THEN
       A%YMAX=GUCLIP(YMAX)
    ELSE
       A%YMAX=GYMAXL
    ENDIF
    IF(PRESENT(YSCALE_STEP)) THEN
       A%YSCALE_STEP=GUCLIP(YSCALE_STEP)
    ELSE
       A%YSCALE_STEP=GYSTEP
    ENDIF
    IF(PRESENT(YORG)) THEN
       A%YORG=GUCLIP(YORG)
    ELSE
       A%YORG=GYORG
    ENDIF

    IF(PRESENT(FMIN)) THEN
       A%FMIN=GUCLIP(FMIN)
    ELSE
       A%FMIN=GFMIN
    ENDIF
    IF(PRESENT(FMAX)) THEN
       A%FMAX=GUCLIP(FMAX)
    ELSE
       A%FMAX=GFMAXL
    ENDIF
    IF(PRESENT(FSCALE_STEP)) THEN
       A%FSCALE_STEP=GUCLIP(FSCALE_STEP)
    ELSE
       A%FSCALE_STEP=GFSTEP
    ENDIF
    IF(PRESENT(YORG)) THEN
       A%FORG=GUCLIP(FORG)
    ELSE
       A%FORG=GFORG
    ENDIF

!     ----- Adjust min max -----

    GL=A%XMAX-A%XMIN
    A%XMAX=A%XMAX+0.5*GL*A%XSPACE_FACTOR
    A%XMIN=A%XMIN-0.5*GL*A%XSPACE_FACTOR
    GL=A%YMAX-A%YMIN
    A%YMAX=A%YMAX+0.5*GL*A%YSPACE_FACTOR
    A%YMIN=A%YMIN-0.5*GL*A%YSPACE_FACTOR

!     ----- LINE SECTION -----

    IF(A%MODE_2D.EQ.0) THEN  ! 1D data
       IF(PRESENT(NLMAX)) THEN
          A%NLMAX=NLMAX
       ELSE
          A%NLMAX=NLM
       ENDIF
       ALLOCATE(A%LINE_RGB(3,A%NLMAX))
       ALLOCATE(A%LINE_THICKNESS(A%NLMAX))
       ALLOCATE(A%LINE_PAT(A%NLMAX))
       ALLOCATE(A%LINE_MARK(A%NLMAX))
       ALLOCATE(A%LINE_MARK_STEP(A%NLMAX))
       ALLOCATE(A%LINE_MARK_SIZE(A%NLMAX))

       IF(PRESENT(LINE_RGB)) THEN
          A%LINE_RGB(1:3,1:A%NLMAX)=LINE_RGB(1:3,1:A%NLMAX)
       ELSE
          A%LINE_RGB(1:3,1:A%NLMAX)=GRGB(1:3,1:A%NLMAX)
       END IF
       IF(PRESENT(LINE_THICKNESS)) THEN
          A%LINE_THICKNESS(1:A%NLMAX)=LINE_THICKNESS(1:A%NLMAX)*GFACTOR
       ELSE
          A%LINE_THICKNESS(1:A%NLMAX)=0.07*GFACTOR
       ENDIF
       IF(PRESENT(LINE_PAT)) THEN
          A%LINE_PAT(1:A%NLMAX)=LINE_PAT(1:A%NLMAX)
       ELSE
          A%LINE_PAT(1:A%NLMAX)=IPAT(1:A%NLMAX)
       ENDIF
       IF(PRESENT(LINE_MARK)) THEN
          A%LINE_MARK(1:A%NLMAX)=LINE_MARK(1:A%NLMAX)
       ELSE
          A%LINE_MARK(1:A%NLMAX)=0
       ENDIF
       IF(PRESENT(LINE_MARK_STEP)) THEN
          A%LINE_MARK_STEP(1:A%NLMAX)=LINE_MARK_STEP(1:A%NLMAX)
       ELSE
          A%LINE_MARK_STEP(1:A%NLMAX)=0
       ENDIF
       IF(PRESENT(LINE_MARK_SIZE)) THEN
          DO NL=1,A%NLMAX
             A%LINE_MARK_SIZE(NL)=GUCLIP(LINE_MARK_SIZE(NL)*GFACTOR)
          END DO
       ELSE
          A%LINE_MARK_SIZE(1:A%NLMAX)=0.3*GFACTOR
       ENDIF
    END IF

    IF(PRESENT(NXSTEP)) THEN
       A%NXSTEP=NXSTEP
    ELSE
       A%NXSTEP=1
    END IF

!     ----- TITLE SECTION -----

    IF(PRESENT(TITLE)) THEN
       KDL=TITLE(1:1)
       I=2
1      IF(TITLE(I:I).EQ.KDL.OR.I.EQ.LEN(TITLE)) GOTO 2
       KTITLE(I-1:I-1)=TITLE(I:I)
       I=I+1
       GOTO 1
2      CONTINUE
       A%TITLE=KTITLE
       A%TITLE_LEN=I-2
    ELSE
       A%TITLE_LEN=0
    ENDIF
       
    IF(PRESENT(TITLE_SIZE)) THEN
       A%TITLE_SIZE=GUCLIP(TITLE_SIZE)*GFACTOR
    ELSE
       A%TITLE_SIZE=0.6*GFACTOR
    END IF

    IF(PRESENT(TITLE_FONT)) THEN
       A%TITLE_FONT=TITLE_FONT
    ELSE
       A%TITLE_FONT=32
    END IF

    IF(PRESENT(TITLE_RGB)) THEN
       A%TITLE_RGB(1:3)=GUCLIP(TITLE_RGB(1:3))
    ELSE
       A%TITLE_RGB(1:3)=0.0
    END IF

    IF(PRESENT(TITLE_SEP)) THEN
       A%TITLE_SEP=GUCLIP(TITLE_SEP)*GFACTOR
    ELSE
       A%TITLE_SEP=0.3*GFACTOR
    END IF

    IF(PRESENT(TITLE_POS)) THEN
       A%TITLE_POS=TITLE_POS
    ELSE
       A%TITLE_POS=0
    END IF
      
    IF(PRESENT(XTITLE)) THEN
       KDL=XTITLE(1:1)
       I=2
3      IF(XTITLE(I:I).EQ.KDL.OR.I.EQ.LEN(XTITLE)) GOTO 4
       KTITLE(I-1:I-1)=XTITLE(I:I)
       I=I+1
       GOTO 3
4      CONTINUE
       A%XTITLE=KTITLE
       A%XTITLE_LEN=I-2
    ELSE
       A%XTITLE_LEN=0
    ENDIF
       
    IF(PRESENT(XTITLE_SIZE)) THEN
       A%XTITLE_SIZE=GUCLIP(XTITLE_SIZE)*GFACTOR
    ELSE
       A%XTITLE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(XTITLE_FONT)) THEN
       A%XTITLE_FONT=XTITLE_FONT
    ELSE
       A%XTITLE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(XTITLE_RGB)) THEN
       DO NC=1,3
          A%XTITLE_RGB(NC)=GUCLIP(XTITlE_RGB(NC))
       END DO
    ELSE
       A%XTITLE_RGB(1:3)=A%TITlE_RGB(1:3)
    END IF

    IF(PRESENT(XTITLE_SEP)) THEN
       A%XTITLE_SEP=GUCLIP(XTITLE_SEP)*GFACTOR
    ELSE
       A%XTITLE_SEP=A%TITLE_SIZE*3.0+A%TITLE_SEP
    END IF

    IF(PRESENT(YTITLE)) THEN
       KDL=YTITLE(1:1)
       I=2
5      IF(YTITLE(I:I).EQ.KDL.OR.I.EQ.LEN(YTITLE)) GOTO 6
       KTITLE(I-1:I-1)=YTITLE(I:I)
       I=I+1
       GOTO 5
6      CONTINUE
       A%YTITLE=KTITLE
       A%YTITLE_LEN=I-2
    ELSE
       A%YTITLE_LEN=0
    ENDIF
       
    IF(PRESENT(YTITLE_SIZE)) THEN
       A%YTITLE_SIZE=GUCLIP(YTITLE_SIZE)*GFACTOR
    ELSE
       A%YTITLE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(YTITLE_FONT)) THEN
       A%YTITLE_FONT=YTITLE_FONT
    ELSE
       A%YTITLE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(YTITLE_RGB)) THEN
       DO NC=1,3
          A%YTITLE_RGB(NC)=GUCLIP(YTITlE_RGB(NC))
       end DO
    ELSE
       A%YTITLE_RGB(1:3)=A%TITlE_RGB(1:3)
    END IF

    IF(PRESENT(YTITLE_SEP)) THEN
       A%YTITLE_SEP=GUCLIP(YTITLE_SEP)*GFACTOR
    ELSE
       A%YTITLE_SEP=A%YTITLE_SIZE*3.0+A%TITLE_SEP
    END IF

!     ----- FRAME SECTION -----

    IF(PRESENT(FRAME_RGB)) THEN
       DO NC=1,3
          A%FRAME_RGB(NC)=GUCLIP(FRAME_RGB(NC))
       END DO
    ELSE
       A%FRAME_RGB(1:3)=0.0
    END IF

    IF(PRESENT(FRAME_THICKNESS)) THEN
       A%FRAME_THICKNESS=GUCLIP(FRAME_THICKNESS)*GFACTOR
    ELSE
       A%FRAME_THICKNESS=0.07*GFACTOR
    END IF

!     ----- SCALE SECTION -----

    IF(PRESENT(SCALE_RGB)) THEN
       DO NC=1,3
          A%SCALE_RGB(NC)=GUCLIP(SCALE_RGB(NC))
       END DO
    ELSE
       A%SCALE_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

    IF(PRESENT(SCALE_ZERO_RGB)) THEN
       DO NC=1,3
          A%SCALE_ZERO_RGB(NC)=GUCLIP(SCALE_ZERO_RGB(NC))
       END DO
    ELSE
       A%SCALE_ZERO_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

    IF(PRESENT(SCALE_THICKNESS)) THEN
       A%SCALE_THICKNESS=GUCLIP(SCALE_THICKNESS)*GFACTOR
    ELSE
       A%SCALE_THICKNESS=A%FRAME_THICKNESS
    END IF

    IF(PRESENT(SCALE_ZERO_THICKNESS)) THEN
       A%SCALE_ZERO_THICKNESS=GUCLIP(SCALE_ZERO_THICKNESS)*GFACTOR
    ELSE
       A%SCALE_ZERO_THICKNESS=A%FRAME_THICKNESS
    END IF

    IF(PRESENT(VALUE_FONT)) THEN
       A%VALUE_FONT=VALUE_FONT
    ELSE
       A%VALUE_FONT=A%TITLE_FONT
    END IF

    IF(PRESENT(VALUE_SIZE)) THEN
       A%VALUE_SIZE=GUCLIP(VALUE_SIZE)*GFACTOR
    ELSE
       A%VALUE_SIZE=A%TITLE_SIZE
    END IF

    IF(PRESENT(VALUE_RGB)) THEN
       DO NC=1,3
          A%VALUE_RGB(NC)=GUCLIP(VALUE_RGB(NC))
       END DO
    ELSE
       A%VALUE_RGB(1:3)=A%FRAME_RGB(1:3)
    END IF

!     ----- XSCALE SECTION -----

    IF(PRESENT(XSCALE_SIZE)) THEN
       A%XSCALE_SIZE=GUCLIP(XSCALE_SIZE)*GFACTOR
    ELSE
       A%XSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(XSCALE_TYPE)) THEN
       A%XSCALE_TYPE=XSCALE_TYPE
    ELSE
       A%XSCALE_TYPE=9
    END IF

    IF(PRESENT(XSCALE_LTYPE)) THEN
       A%XSCALE_LTYPE=XSCALE_LTYPE
    ELSE
       A%XSCALE_LTYPE=9
    END IF

    IF(PRESENT(XSCALE_ZERO)) THEN
       A%XSCALE_ZERO=XSCALE_ZERO
    ELSE
       A%XSCALE_ZERO=1
    END IF

    IF(PRESENT(XSCALE_ZERO_PAT)) THEN
       A%XSCALE_ZERO_PAT=XSCALE_ZERO_PAT
    ELSE
       A%XSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(XVALUE_STEP)) THEN
       A%XVALUE_STEP=XVALUE_STEP
    ELSE
       A%XVALUE_STEP=2
    END IF

    IF(PRESENT(XVALUE_TYPE)) THEN
       A%XVALUE_TYPE=GUCLIP(XVALUE_TYPE)
    ELSE
       A%XVALUE_TYPE=NGULEN(2*GXSTEP)
    END IF

    IF(PRESENT(XVALUE_LTYPE)) THEN
       A%XVALUE_LTYPE=XVALUE_LTYPE
    ELSE
       A%XVALUE_LTYPE=1
    END IF

!     ----- YSCALE SECTION -----

    IF(PRESENT(YSCALE_SIZE)) THEN
       A%YSCALE_SIZE=GUCLIP(YSCALE_SIZE)*GFACTOR
    ELSE
       A%YSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(YSCALE_TYPE)) THEN
       A%YSCALE_TYPE=YSCALE_TYPE
    ELSE
       A%YSCALE_TYPE=9
    END IF

    IF(PRESENT(YSCALE_LTYPE)) THEN
       A%YSCALE_LTYPE=YSCALE_LTYPE
    ELSE
       A%YSCALE_LTYPE=9
    END IF

    IF(PRESENT(YSCALE_ZERO)) THEN
       A%YSCALE_ZERO=YSCALE_ZERO
    ELSE
       A%YSCALE_ZERO=1
    END IF

    IF(PRESENT(YSCALE_ZERO_PAT)) THEN
       A%YSCALE_ZERO_PAT=YSCALE_ZERO_PAT
    ELSE
       A%YSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(YVALUE_STEP)) THEN
       A%YVALUE_STEP=YVALUE_STEP
    ELSE
       A%YVALUE_STEP=2
    END IF

    IF(PRESENT(YVALUE_TYPE)) THEN
       A%YVALUE_TYPE=YVALUE_TYPE
    ELSE
       A%YVALUE_TYPE=NGULEN(2*GYSTEP)
    END IF

    IF(PRESENT(YVALUE_LTYPE)) THEN
       A%YVALUE_LTYPE=YVALUE_LTYPE
    ELSE
       A%YVALUE_LTYPE=1
    END IF

!     ----- FSCALE SECTION -----

    IF(PRESENT(FSCALE_SIZE)) THEN
       A%FSCALE_SIZE=GUCLIP(FSCALE_SIZE)*GFACTOR
    ELSE
       A%FSCALE_SIZE=0.2*GFACTOR
    END IF

    IF(PRESENT(FSCALE_TYPE)) THEN
       A%FSCALE_TYPE=FSCALE_TYPE
    ELSE
       A%FSCALE_TYPE=9
    END IF

    IF(PRESENT(FSCALE_LTYPE)) THEN
       A%FSCALE_LTYPE=FSCALE_LTYPE
    ELSE
       A%FSCALE_LTYPE=9
    END IF

    IF(PRESENT(FSCALE_ZERO)) THEN
       A%FSCALE_ZERO=FSCALE_ZERO
    ELSE
       A%FSCALE_ZERO=1
    END IF

    IF(PRESENT(FSCALE_ZERO_PAT)) THEN
       A%FSCALE_ZERO_PAT=FSCALE_ZERO_PAT
    ELSE
       A%FSCALE_ZERO_PAT=0
    END IF

    IF(PRESENT(FVALUE_STEP)) THEN
       A%FVALUE_STEP=FVALUE_STEP
    ELSE
       A%FVALUE_STEP=2
    END IF

    IF(PRESENT(FVALUE_TYPE)) THEN
       A%FVALUE_TYPE=FVALUE_TYPE
    ELSE
       A%FVALUE_TYPE=NGULEN(2*GFSTEP)
    END IF

    IF(PRESENT(FVALUE_LTYPE)) THEN
       A%FVALUE_LTYPE=FVALUE_LTYPE
    ELSE
       A%FVALUE_LTYPE=1
    END IF

!   --- draw selection section ---

    IF(PRESENT(NOTITLE)) THEN
       A%NOTITLE=NOTITLE
    ELSE
       A%NOTITLE=0
    ENDIF

    IF(PRESENT(NOFRAME)) THEN
       A%NOFRAME=NOFRAME
    ELSE
       A%NOFRAME=0
    ENDIF

    RETURN
  END SUBROUTINE GRD_CONVERT

!     ***** DRAW GRAPH TITLES *****

  SUBROUTINE GRF_TITLE(A)

    IMPLICIT NONE

    TYPE(grf_attr_type),INTENT(IN):: A
    REAL(4):: SIZE
    INTEGER:: NG,NL

    IF(A%TITLE_LEN.GT.0) THEN
       CALL SETCHS(A%TITLE_SIZE,0.0)
       CALL SETFNT(A%TITLE_FONT)
       CALL SETRGBA(A%TITLE_RGB(1:3))
       CALL INQTSZ(A%TITLE,A%TITLE_LEN,SIZE)
       SELECT CASE(A%TITLE_POS)
       CASE(0)
          CALL MOVE(A%GPXMIN,A%GPYMAX+A%TITLE_SEP)
       CASE(1)
          CALL MOVE(0.5*(A%GPXMIN+A%GPXMAX)-0.5*SIZE,A%GPYMAX+A%TITLE_SEP)
       CASE(2)
          CALL MOVE(A%GPXMAX-SIZE,A%GPYMAX+A%TITLE_SEP)
       CASE DEFAULT
          CALL MOVE(A%GPXMIN,A%GPYMAX+A%TITLE_SEP)
       END SELECT
       CALL TEXT(A%TITLE,A%TITLE_LEN)
    ENDIF

    IF(A%XTITLE_LEN.GT.0) THEN
       CALL SETCHS(A%XTITLE_SIZE,0.0)
       CALL SETFNT(A%XTITLE_FONT)
       CALL SETRGBA(A%XTITLE_RGB(1:3))
       CALL INQTSZ(A%XTITLE,A%XTITLE_LEN,SIZE)
       CALL MOVE(0.5*(A%GPXMIN+A%GPXMAX)-0.5*SIZE,A%GPYMIN-A%XTITLE_SEP)
       CALL TEXT(A%XTITLE,A%XTITLE_LEN)
    ENDIF

    IF(A%YTITLE_LEN.GT.0) THEN
       CALL SETCHS(A%YTITLE_SIZE,90.0)
       CALL SETFNT(A%YTITLE_FONT)
       CALL SETRGBA(A%YTITLE_RGB(1:3))
       CALL INQTSZ(A%YTITLE,A%YTITLE_LEN,SIZE)
       CALL MOVE(A%GPXMIN-A%YTITLE_SEP,0.5*(A%GPYMIN+A%GPYMAX)-0.5*SIZE)
       CALL TEXT(A%YTITLE,A%YTITLE_LEN)
    ENDIF

    RETURN
  END SUBROUTINE GRF_TITLE

!     ***** DRAW GRAPH FRAME AND SCALES *****

  SUBROUTINE GRF_FRAME(A)

    IMPLICIT NONE

    TYPE(grf_attr_type),INTENT(IN):: A
    REAL(4):: SIZE
    INTEGER:: NG,NL

    CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                A%XMIN,A%XMAX,A%FMIN,A%FMAX)

    CALL SETRGBA(A%FRAME_RGB(1:3))
    CALL SETLNW(A%FRAME_THICKNESS)
    CALL GFRAME

    CALL SETRGBA(A%SCALE_RGB(1:3))
    CALL SETLNW(A%SCALE_THICKNESS)
    CALL SETCHS(A%VALUE_SIZE,0.0)
    CALL SETFNT(A%VALUE_FONT)

    IF(A%MODE_LS.EQ.0.OR.A%MODE_LS.EQ.2) THEN
       IF(A%XSCALE_ZERO.NE.0) &
            CALL GSCALE(0.0,2*(A%XMAX-A%XMIN),0.0,0.0, &
                        FLOAT(A%XSCALE_ZERO_PAT),0)
       CALL GSCALE(A%XORG,A%XSCALE_STEP,0.0,0.0,A%XSCALE_SIZE,A%XSCALE_TYPE)
       CALL SETRGBA(A%VALUE_RGB(1:3))
       CALL GVALUE(A%XORG,A%XVALUE_STEP*A%XSCALE_STEP,0.0,0.0,A%XVALUE_TYPE)
    ELSE
       CALL GSCALL(A%XORG,A%XSCALE_LTYPE,0.0,0,A%XSCALE_SIZE,A%XSCALE_TYPE)
       CALL SETRGBA(A%VALUE_RGB(1:3))
       CALL GVALUL(A%XORG,A%XVALUE_LTYPE,0.0,0,A%XVALUE_TYPE)
    ENDIF

    IF(A%MODE_LS.EQ.0.OR.A%MODE_LS.EQ.1) THEN
       IF(A%FSCALE_ZERO.NE.0) &
            CALL GSCALE(0.0,0.0,0.0,2*(A%FMAX-A%FMIN), &
                        FLOAT(A%FSCALE_ZERO_PAT),0)
       CALL GSCALE(0.0,0.0,A%FORG,A%FSCALE_STEP,A%FSCALE_SIZE,A%FSCALE_TYPE)
       CALL SETRGBA(A%VALUE_RGB(1:3))
       CALL GVALUE(0.0,0.0,A%FORG,A%FVALUE_STEP*A%FSCALE_STEP,A%FVALUE_TYPE)
    ELSE
       CALL GSCALL(0.0,0,A%FORG,A%FSCALE_LTYPE,A%FSCALE_SIZE,A%FSCALE_TYPE)
       CALL SETRGBA(A%VALUE_RGB(1:3))
       CALL GVALUL(0.0,0,A%FORG,A%FVALUE_LTYPE,A%FVALUE_TYPE)
    ENDIF

  END SUBROUTINE GRF_FRAME


!     ***** DRAW 1D GRAPH *****

  SUBROUTINE GRF1D_EXEC(GX,GF,NXM,NXMAX,NYMAX,A)

    IMPLICIT NONE

    REAL(4),INTENT(IN):: GX(NXMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX
    TYPE(grf_attr_type),INTENT(IN):: A
    INTEGER:: NY,NL,nx

    CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                A%XMIN,A%XMAX,A%FMIN,A%FMAX)
    DO NY=1,NYMAX
       NL=MOD(NY-1,A%NLMAX)+1
       CALL SETLNW(A%LINE_THICKNESS(NL))
       CALL SETMKS(0,A%LINE_MARK_SIZE(NL))
       CALL SETRGBA(A%LINE_RGB(1:3,NL))
       CALL GPLOTP(GX,GF(1:NXMAX,NY),A%NXMIN,NXMAX,A%NXSTEP, &
                   A%LINE_MARK(NL),A%LINE_MARK_STEP(NL),A%LINE_PAT(NL))
    ENDDO
    CALL SETRGB(0.0,0.0,0.0)

    IF(A%NOFRAME.EQ.0) CALL GRF_FRAME(A)
    IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)
    CALL SETRGB(0.0,0.0,0.0)

    RETURN
  END SUBROUTINE GRF1D_EXEC

!     ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2D_EXEC(GX,GY,GF,NXM,NXMAX,NYMAX,A)

    IMPLICIT NONE

    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX
    TYPE(grf_attr_type),INTENT(IN):: A

    CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                A%XMIN,A%XMAX,A%YMIN,A%YMAX)

    CALL SETLNW(A%LINE_THICKNESS(1))
    CALL CONTF2(GF,GX,GY,NXM,NXMAX,NYMAX, &
                A%LINE_VALUE,A%LINE_RGB,A%NLMAX,A%MODE_PRD)

    IF(A%NOFRAME.EQ.0) CALL GRF_FRAME(A)
    IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)

    CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2D_EXEC

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GDD2D(NGP,FX,FY,FZ,NXM,NXMAX,NYMAX,STR,MODE_LS,IPRD,IG2D)

!     +++++ MODE_LS=0 X:LINEAR  Y:LINEAR
!     +++++ MODE_LS=1 X:LOG     Y:LINEAR
!     +++++ MODE_LS=2 X:LINEAR  Y:LOG
!     +++++ MODE_LS=3 X:LOG     Y:LOG

!     +++++ IG2D=0 Contour plot
!     +++++ IG2D=1 Bird's eye view
!     +++++ IG2D=2 Contour plot

      IMPLICIT NONE
      INTEGER NGP,NXM,NXMAX,NYMAX,MODE_LS,IPRD,IG2D
      REAL*8 FX(NXMAX),FY(NYMAX),FZ(NXM,NYMAX)
      CHARACTER STR*(*)
      REAL*4 GX(NXMAX),GY(NYMAX),GZ(NXMAX,NYMAX)
      INTEGER NX,NY
      REAL*4 GUCLIP

      DO NX=1,NXMAX
         GX(NX)=GUCLIP(FX(NX))
      ENDDO
      DO NY=1,NYMAX
         GY(NY)=GUCLIP(FY(NY))
      ENDDO
      DO NY=1,NYMAX
         DO NX=1,NXMAX
            GZ(NX,NY)=GUCLIP(FZ(NX,NY))
         ENDDO
      ENDDO

      IF(IG2D.EQ.0) THEN
         CALL GRF2DA(NGP,GX,GY,GZ,NXMAX,NXMAX,NYMAX,STR,MODE_LS,IPRD)
      ELSEIF(IG2D.EQ.1) THEN
         CALL GRF2DB(NGP,GX,GY,GZ,NXMAX,NXMAX,NYMAX,STR)
      ELSEIF(IG2D.EQ.2) THEN
         CALL GRF2DC(NGP,GX,GY,GZ,NXMAX,NXMAX,NYMAX,STR,MODE_LS)
      ELSE
         WRITE(6,*) 'XX GRD2D: INVALID IG2D'
      ENDIF
      RETURN
    END SUBROUTINE GDD2D

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DA(NGP,GX,GY,GZ,NXM,NXMAX,NYMAX,STR,MODE_LS,IPRD)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      CHARACTER STR*(*)

      IF(NGP.LT.0.OR.NGP.GT.29) THEN
         WRITE(6,*) 'XX GRF2DC: INVALID NGP'
         RETURN
      ENDIF
      CALL GRFUT4(NGP,GP)

      CALL GRFUT1(GX,NXMAX,GXMIN,GXMAX)
      CALL GRFUT1(GY,NYMAX,GYMIN,GYMAX)
      CALL GRFUT2(GZ,NXM,NXMAX,NYMAX,GFMIN,GFMAX)

      CALL GRFUT3(GXMIN,GXMAX,GSXMIN,GSXMAX,GXSTEP,GXORG)
      CALL GRFUT3(GYMIN,GYMAX,GSYMIN,GSYMAX,GYSTEP,GYORG)
      CALL GRFUT3(GFMIN,GFMAX,GSFMIN,GSFMAX,GFSTEP,GFORG)
      GFSTEP=0.5*GFSTEP

      CALL GRF2DAX(GP, &
                   GXMIN,GXMAX,GXSTEP,GXORG, &
                   GYMIN,GYMAX,GYSTEP,GYORG, &
                   GFMIN,GFMAX,GFSTEP,GFORG, &
                   GX,GY,GZ,NXM,NXMAX,NYMAX,STR,MODE_LS,IPRD)

      RETURN
    END SUBROUTINE GRF2DA

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DAX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,MODE_LS,IPRD)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      CHARACTER STR*(*),KT*80,KDL*1
      DIMENSION GZL(101),GRGB(3,101)

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      CALL GDEFIN(GP(1),GP(2),GP(3),GP(4), &
                  GXMIN,GXMAX,GYMIN,GYMAX)

      NSTEP=NINT(ABS((GFMAX-GFMIN)/GFSTEP))+1
      IF(NSTEP.GT.101) NSTEP=101
      GFSTEPL=(GFMAX-GFMIN)/(NSTEP-1)
      DO I=1,NSTEP
         GZL(I)=GFMIN+GFSTEPL*(I-1)
      ENDDO

      IF(GFMIN*GFMAX.GE.0.D0) THEN
         IF(GFORG.GE.0.D0) THEN
            DO I=1,NSTEP
               GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
               CALL R2Y2W(GFACTOR,GRGB(1,I))
            ENDDO
            CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRGB,NSTEP,IPRD)
         ELSE
            DO I=1,NSTEP
               GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
               CALL W2G2B(GFACTOR,GRGB(1,I))
            ENDDO
            CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRBG,NSTEP,IPRD)
         ENDIF
      ELSE
         DO I=1,NSTEP
            GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
            CALL R2W2B(GFACTOR,GRGB(1,I))
         ENDDO
         CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRGB,NSTEP,IPRD)
      ENDIF

      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.2) THEN
         CALL GSCALE(0.0,2*(GXMAX-GXMIN),0.0,0.0,0.0,0)
         CALL GSCALE(GXORG,GXSTEP,0.0,0.0,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      ELSE
         CALL GSCALL(GXORG,9,0.0,0,0.1,9)
         CALL GVALUL(GXORG,1,0.0,0,NGULEN(2*GXSTEP))
      ENDIF
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.1) THEN
         CALL GSCALE(0.0,0.0,0.0,2*(GYMAX-GYMIN),0.0,0)
         CALL GSCALE(0.0,0.0,GYORG,GYSTEP,0.1,9)
         CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALL(0.0,0,GYORG,9,0.1,9)
         CALL GVALUL(0.0,0,GYORG,1,NGULEN(2*GYSTEP))
      ENDIF

      CALL MOVE(0.5*(GP(1)+GP(2))-0.2*32*GFACTOR,GP(3)-1.5*GFACTOR)
      CALL TEXT('MIN  =',6)
      CALL NUMBR(GFMIN ,'(1PE12.4)',12)
      CALL TEXT('     MAX  =',11)
      CALL NUMBR(GFMAX ,'(1PE12.4)',12)
      CALL TEXT('     STEP =',11)
      CALL NUMBR(GFSTEP,'(1PE12.4)',12)

      CALL SETRGB(0.0,0.0,0.0)
      RETURN
    END SUBROUTINE GRF2DAX

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DB(NGP,GX,GY,GZ,NXM,NXMAX,NYMAX,STR)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION GP3D(6)
      CHARACTER STR*(*)

      IF(NGP.LT.0.OR.NGP.GT.29) THEN
         WRITE(6,*) 'XX GRF2DB: INVALID NGP'
         RETURN
      ENDIF
      CALL GRFUT4(NGP,GP)

      GP3D(1)=10.0*1.5
      GP3D(2)=20.0*1.5
      GP3D(3)=10.0*1.5
      GP3D(4)=-60.0
      GP3D(5)=65.0
      GP3D(6)=100.0

      CALL GRFUT1(GX,NXMAX,GXMIN,GXMAX)
      CALL GRFUT1(GY,NYMAX,GYMIN,GYMAX)
      CALL GRFUT2(GZ,NXM,NXMAX,NYMAX,GFMIN,GFMAX)

      CALL GRFUT3(GXMIN,GXMAX,GSXMIN,GSXMAX,GXSTEP,GXORG)
      CALL GRFUT3(GYMIN,GYMAX,GSYMIN,GSYMAX,GYSTEP,GYORG)
      CALL GRFUT3(GFMIN,GFMAX,GSFMIN,GSFMAX,GFSTEP,GFORG)

      CALL GRF2DBX(GP, &
                   GXMIN,GXMAX,GXSTEP,GXORG, &
                   GYMIN,GYMAX,GYSTEP,GYORG, &
                   GFMIN,GFMAX,GFSTEP,GFORG, &
                   GX,GY,GZ,NXM,NXMAX,NYMAX, &
                   STR,GP3D)
      RETURN
    END SUBROUTINE GRF2DB

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DBX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,GP3D)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION GP3D(6)
      CHARACTER STR*(*),KT*80,KDL*1
      EXTERNAL R2W2B,W2G2B,R2Y2W

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      GXL    =GP3D(1)
      GYL    =GP3D(2)
      GZL    =GP3D(3)
      GPHI   =GP3D(4)
      GTHETA =GP3D(5)
      GRADIUS=GP3D(6)
      GOX=0.5*(GXMIN+GXMAX)
      GOY=0.5*(GYMIN+GYMAX)
      GOZ=0.5*(GFMIN+GFMAX)

      CALL GDEFIN3D(GP(1),GP(2),GP(3),GP(4),GXL,GYL,GZL)
      CALL GVIEW3D(GPHI,GTHETA,GRADIUS,1.0,1,GOX,GOY,GOZ)
      CALL GDATA3D1(GZ,NXM,NXMAX,NYMAX, &
                    GXMIN,GXMAX,GYMIN,GYMAX,GFMIN,GFMAX)

      CALL SETCHS(0.2,0.0)
      CALL SETLIN(0,0,7)

      IF(NXMAX.GT.100.OR.NYMAX.GT.100) THEN
         ID=4
      ELSE
         ID=7
      ENDIF

      IF(GFMIN*GFMAX.LT.0.0) THEN
         CALL CPLOT3D1(ID,R2W2B)
      ELSEIF(GFMIN.LT.0.0) THEN
         CALL CPLOT3D1(ID,W2G2B)
      ELSE
         CALL CPLOT3D1(ID,R2Y2W)
      ENDIF
      CALL GAXIS3D(0)

      CALL SETLIN(0,0,7)
      CALL GSCALE3DX(GXORG,GXSTEP,0.3,0)
      CALL GSCALE3DY(GYORG,GYSTEP,0.3,0)
      CALL GSCALE3DZ(GFORG,GFSTEP,0.3,0)
      CALL GVALUE3DX(GXORG,2*GXSTEP,1,NGULEN(2*GXSTEP))
      CALL GVALUE3DY(GYORG,2*GYSTEP,1,NGULEN(2*GYSTEP))
      CALL GVALUE3DZ(GFORG,2*GFSTEP,2,NGULEN(2*GFSTEP))
      RETURN
    END SUBROUTINE GRF2DBX

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DC(NGP,GX,GY,GZ,NXM,NXMAX,NYMAX,STR,MODE_LS)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      CHARACTER STR*(*)

      IF(NGP.LT.0.OR.NGP.GT.29) THEN
         WRITE(6,*) 'XX GRF2DC: INVALID NGP'
         RETURN
      ENDIF
      CALL GRFUT4(NGP,GP)

      CALL GRFUT1(GX,NXMAX,GXMIN,GXMAX)
      CALL GRFUT1(GY,NYMAX,GYMIN,GYMAX)
      CALL GRFUT2(GZ,NXM,NXMAX,NYMAX,GFMIN,GFMAX)

      CALL GRFUT3(GXMIN,GXMAX,GSXMIN,GSXMAX,GXSTEP,GXORG)
      CALL GRFUT3(GYMIN,GYMAX,GSYMIN,GSYMAX,GYSTEP,GYORG)
      CALL GRFUT3(GFMIN,GFMAX,GSFMIN,GSFMAX,GFSTEP,GFORG)
      GFSTEP=0.2*GFSTEP

      CALL GRF2DCX(GP, &
                   GXMIN,GXMAX,GXSTEP,GXORG, &
                   GYMIN,GYMAX,GYSTEP,GYORG, &
                   GFMIN,GFMAX,GFSTEP,GFORG, &
                   GX,GY,GZ,NXM,NXMAX,NYMAX, &
                   STR,MODE_LS)

      RETURN
    END SUBROUTINE GRF2DC

!     ***** DRAW 2D GRAPH *****

      SUBROUTINE GRF2DCX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,MODE_LS)

      IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION KA(8,NXM,NYMAX)
      CHARACTER STR*(*),KT*80,KDL*1

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      CALL GDEFIN(GP(1),GP(2),GP(3),GP(4), &
                  GXMIN,GXMAX,GYMIN,GYMAX)

      IF(GFMIN*GFMAX.GE.0.D0) THEN
         NSTEP=NINT(ABS((GFMAX-GFMIN)/GFSTEP))+1
         IF(GFORG.GE.0.D0) THEN
            CALL SETRGB(1.0,0.0,0.0)
            CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                        GFORG,GFSTEP,NSTEP,0,0,KA)
         ELSE
            CALL SETRGB(0.0,0.0,1.0)
            CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                        GFORG,GFSTEP,NSTEP,0,3,KA)
         ENDIF
      ELSE
         CALL SETRGB(1.0,0.0,0.0)
         NSTEP=NINT(ABS(GFMAX/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     GFSTEP,GFSTEP,NSTEP,0,0,KA)
         CALL SETRGB(0.0,1.0,0.0)
         NSTEP=NINT(ABS(GFMAX/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     0.0,GFSTEP,1,0,0,KA)
         CALL SETRGB(0.0,0.0,1.0)
         NSTEP=NINT(ABS(GFMIN/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     -GFSTEP,-GFSTEP,NSTEP,0,3,KA)
      ENDIF

      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME

      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.2) THEN
         CALL GSCALE(0.0,2*(GXMAX-GXMIN),0.0,0.0,0.0,0)
         CALL GSCALE(GXORG,GXSTEP,0.0,0.0,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      ELSE
         CALL GSCALL(GXORG,9,0.0,0,0.1,9)
         CALL GVALUL(GXORG,1,0.0,0,NGULEN(2*GXSTEP))
      ENDIF
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.1) THEN
         CALL GSCALE(0.0,0.0,0.0,2*(GYMAX-GYMIN),0.0,0)
         CALL GSCALE(0.0,0.0,GYORG,GYSTEP,0.1,9)
         CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALL(0.0,0,GYORG,9,0.1,9)
         CALL GVALUL(0.0,0,GYORG,1,NGULEN(2*GYSTEP))
      ENDIF

      CALL MOVE(0.5*(GP(1)+GP(2))-0.2*32*GFACTOR,GP(3)-1.5*GFACTOR)
      CALL TEXT('MIN  =',6)
      CALL NUMBR(GFMIN ,'(1PE12.4)',12)
      CALL TEXT('     MAX  =',11)
      CALL NUMBR(GFMAX ,'(1PE12.4)',12)
      CALL TEXT('     STEP =',11)
      CALL NUMBR(GFSTEP,'(1PE12.4)',12)

      CALL SETRGB(0.0,0.0,0.0)
      RETURN
    END SUBROUTINE GRF2DCX

!     ***** EVALUATE GXMIN,GXMAX,GYMIN,GYMAX *****

      SUBROUTINE GRFUT1(GX,NXMAX,GXMIN,GXMAX,NXMIN,NXSTEP)

      IMPLICIT NONE

      REAL(4),INTENT(IN):: GX(NXMAX)
      INTEGER,INTENT(IN):: NXMAX
      REAL(4),INTENT(OUT):: GXMIN,GXMAX
      INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NXSTEP
      INTEGER:: NXMINL,NXSTEPL

      IF(PRESENT(NXMIN)) THEN
         NXMINL=NXMIN
      ELSE
         NXMINL=1
      ENDIF
      IF(PRESENT(NXSTEP)) THEN
         NXSTEPL=NXSTEP
      ELSE
         NXSTEPL=1
      ENDIF

      CALL GMNMX1(GX,NXMINL,NXMAX,NXSTEPL,GXMIN,GXMAX)
      IF(ABS(GXMAX-GXMIN).LT.1.D-6) THEN
         GXMIN=GXMIN-0.999E-6
         GXMAX=GXMAX+1.000E-6
      ENDIF

      RETURN
    END SUBROUTINE GRFUT1

!     ***** EVALUATE GXMIN,GXMAX,GYMIN,GYMAX *****

      SUBROUTINE GRFUT2(GY,NXM,NXMAX,NYMAX,GYMIN,GYMAX, &
                        NXMIN,NXSTEP,NYMIN,NYSTEP)

      IMPLICIT NONE

      REAL(4),INTENT(IN):: GY(NXM,NYMAX)
      INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX
      REAL(4),INTENT(OUT):: GYMIN,GYMAX
      INTEGER,INTENT(IN),OPTIONAL:: NXMIN,NXSTEP,NYMIN,NYSTEP
      INTEGER:: NXMINL,NXSTEPL,NYMINL,NYSTEPL
      REAL(4):: GYNORM

      IF(PRESENT(NXMIN)) THEN
         NXMINL=NXMIN
      ELSE
         NXMINL=1
      ENDIF
      IF(PRESENT(NXSTEP)) THEN
         NXSTEPL=NXSTEP
      ELSE
         NXSTEPL=1
      ENDIF
      IF(PRESENT(NYMIN)) THEN
         NYMINL=NYMIN
      ELSE
         NYMINL=1
      ENDIF
      IF(PRESENT(NYSTEP)) THEN
         NYSTEPL=NYSTEP
      ELSE
         NYSTEPL=1
      ENDIF

      CALL GMNMX2(GY,NXM,NXMINL,NXMAX,NXSTEPL,NYMINL,NYMAX,NYSTEPL,GYMIN,GYMAX)
      GYNORM=ABS(GYMIN)+ABS(GYMAX)
      IF(ABS(GYMAX-GYMIN).LT.1.D-6*GYNORM) THEN
         GYMIN=GYMIN-0.999E-6*GYNORM
         GYMAX=GYMAX+1.000E-6*GYNORM
      ENDIF

      RETURN
    END SUBROUTINE GRFUT2

!     ***** EVALUATE GSMIN,GSMAX,GSTEP,GORG *****

      SUBROUTINE GRFUT3(GMIN,GMAX,GSMIN,GSMAX,GSTEP,GORG)

      IMPLICIT NONE
      REAL(4),INTENT(IN):: GMIN,GMAX
      REAL(4),INTENT(OUT):: GSMIN,GSMAX,GSTEP,GORG

      CALL GQSCAL(GMIN,GMAX,GSMIN,GSMAX,GSTEP)

      IF(GMIN*GMAX.LE.0.0) THEN
         GORG=0.0
      ELSE
         GORG=(NINT(GSMIN/(2*GSTEP))+1)*2*GSTEP
      ENDIF
      RETURN
    END SUBROUTINE GRFUT3

!     ***** SET GP FOR NGP *****

      SUBROUTINE GRFUT4(NGP,GP)

      IMPLICIT NONE

      INTEGER NGP
      REAL*4 GP(4)
      INTEGER IX,IY
      REAL*4 X0,XL,Y0,YL

      IF(NGP.EQ.0) THEN
         GP(1)= 3.0
         GP(2)=23.0
         GP(3)= 2.0
         GP(4)=17.0
      ELSE
         IF(NGP.LE.4) THEN
            X0= 3.0
            XL=12.0
            Y0= 1.75
            YL= 8.5
            IX=MOD(NGP-1,2)
            IY=1-(NGP-1)/2
         ELSEIF(NGP.LE.13) THEN
            X0= 3.0*0.666
            XL=12.0*0.666
            Y0= 1.75*0.666
            YL= 8.5*0.666
            IX=MOD(NGP-5,3)
            IY=2-(NGP-5)/3
         ELSEIF(NGP.LE.29) THEN
            X0= 3.0*0.5
            XL=12.0*0.5
            Y0= 1.75*0.5
            YL= 8.5*0.5
            IX=MOD(NGP-14,4)
            IY=3-(NGP-14)/4
         ENDIF
         GP(1)=IX*XL+X0
         GP(2)=IX*XL+XL
         GP(3)=IY*YL+Y0
         GP(4)=IY*YL+YL
      ENDIF
      RETURN
    END SUBROUTINE GRFUT4

!     ***** SET RGB BY ARRAY *****

      SUBROUTINE SETRGBA(RGB)

        IMPLICIT NONE
        REAL(4),DIMENSION(3),INTENT(IN):: RGB

        CALL SETRGB(RGB(1),RGB(2),RGB(3))
        RETURN
      END SUBROUTINE SETRGBA
END MODULE libgrf
