      IMPLICIT NONE
      INTEGER NBM
      PARAMETER (NBM=101)
      REAL*8 X,ALPHA
      REAL*8 BESJN,BESYN,BESIN,BESKN,BESEIN,BESEKN
      REAL*8 BJ(NBM),BY(NBM),BI(NBM),BK(NBM)
      INTEGER NB,NCALC,N
      ALPHA=0.D0
C
    1 WRITE(6,*) '## input N, X:'
      READ(5,*,END=9000,ERR=1) N,X
C
C      NB=N+1
C      CALL DJBESL(X, ALPHA, NB, BJ, NCALC)
C      IF(NCALC.LT.NB) WRITE(6,*) 'XX DJBESL: NCALC = ',NCALC
C      NB=N+1
C      CALL DYBESL(X, ALPHA, NB, BY, NCALC)
C      IF(NCALC.LT.NB) WRITE(6,*) 'XX DYBESL: NCALC = ',NCALC
C      NB=N+1
C      CALL DIBESL(X, ALPHA, NB, 1, BI, NCALC)
C      IF(NCALC.LT.NB) WRITE(6,*) 'XX DIBESL: NCALC = ',NCALC
C      NB=N+1
C      CALL DKBESL(X, ALPHA, NB, 1, BK, NCALC)
C      IF(NCALC.LT.NB) WRITE(6,*) 'XX DKBESL: NCALC = ',NCALC
C
C      WRITE(6,'(I5,1P5E12.4)') N,X,BJ(N+1),BY(N+1),BI(N+1),BK(N+1)
      WRITE(6,'(I3,1PE12.4,1P4E15.7)') N,X,
     &     BESJN(N,X),BESYN(N,X),BESEIN(N,X),BESEKN(N,X)
      GOTO 1
C
 9000 STOP
      END
