! dpcomm.f90

MODULE dpcomm_parm

  USE plcomm_parm
  USE commpi
  IMPLICIT NONE

  PUBLIC

! --- input paramters ---

  INTEGER:: MODELP(NSM),MODELV(NSM),NCMIN(NSM),NCMAX(NSM)
  REAL(rkind):: RF0,RFI0,RKX0,RKY0,RKZ0,RX0,RY0,RZ0,RK0,RKANG0
  REAL(rkind):: EPSRT
  INTEGER:: LMAXRT,MDL

  INTEGER:: NS_NSA(NSM)
  REAL(rkind):: PMAX(NSM),EMAX(NSM),RHON_MIN(NSM),RHON_MAX(NSM)
  INTEGER:: NPMAX_DP,NTHMAX_DP,NRMAX_DP,NSAMAX_DP

END MODULE dpcomm_parm

MODULE dpcomm_parm_local     ! only for DP program, not for DP library

  USE dpcomm_parm
  IMPLICIT NONE

  REAL(rkind):: RF1,RFI1,RKX1,RKY1,RKZ1,RX1,RY1,RZ1,RK1
  REAL(rkind):: RF2,RFI2,RKX2,RKY2,RKZ2,RX2,RY2,RZ2,RK2
  INTEGER:: NGXMAX,NGYMAX,NGPMAX
  REAL(rkind):: EPSDP,EPSRF
  INTEGER:: NORMF,NORMK
  INTEGER:: NFLOUT

END MODULE dpcomm_parm_local

MODULE dpcomm
  USE dpcomm_parm
  IMPLICIT NONE

  PUBLIC

  COMPLEX(rkind):: CRF0,CKX0,CKY0,CKZ0
  REAL(rkind):: XPOS0,YPOS0,ZPOS0
  INTEGER:: ILIST

  INTEGER:: NSDP(NSM)

  REAL(rkind):: DELTH,DELR
  REAL(rkind):: FPDATA(2)
  INTEGER:: NFPDATA(3)

  REAL(rkind),ALLOCATABLE:: FP(:,:,:) ! FP(NTHMAX_DP,NPMAX_DP,NRMAX_DPP)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       FM,DFP,DFT ! (NPMAX_DP,NTHMAX_DP)

  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       AEFP,AMFP,RNFP0,RTFP0,DELP ! (NSAMAX_DP)
  REAL(rkind),DIMENSION(:,:,:,:),ALLOCATABLE:: &
       FNS ! (NTHMAX_DP,NPMAX_DP,NRMAX_DP,NSAMAX_DP)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       THM,THG,TSNM,TSNG,TCSM,TCSG,TTNM,TTNG ! (NTHMAX_DP)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       PM,PG ! (NPMAX_DP,NSAMAX_DP)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       RGMM,RGMG ! (NPMAX_DP)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       RM ! (NRMAX_DP)
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &
       DGP1,DGP2,DGT1,DGT2 ! (NPM,NTHM)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       RFP ! (NRM+2)
  REAL(rkind),DIMENSION(:,:,:,:),ALLOCATABLE:: &
       URFP ! (4,NRM+2,NPM,NTHM)
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
       FPDATAS ! (NSAM)
!  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &
!       CHI,CCHI,SCHI ! (NCHMAX)

CONTAINS

  SUBROUTINE dp_allocate
    RETURN
  END SUBROUTINE dp_allocate

  SUBROUTINE dp_deallocate
    RETURN
  END SUBROUTINE dp_deallocate

  SUBROUTINE dpfp_allocate
    IMPLICIT NONE
    INTEGER,SAVE:: init=0
    INTEGER,SAVE:: NTHMAX_DP_SAVE=0
    INTEGER,SAVE:: NPMAX_DP_SAVE=0
    INTEGER,SAVE:: NRMAX_DP_SAVE=0
    INTEGER,SAVE:: NSAMAX_DP_SAVE=0

    IF(init.EQ.0) THEN
       init=1
    ELSE
       IF((NTHMAX_DP.EQ.NTHMAX_DP_SAVE).AND. &
          (NPMAX_DP.EQ.NPMAX_DP_SAVE).AND. &
          (NRMAX_DP.EQ.NRMAX_DP_SAVE).AND. &
          (NSAMAX_DP.EQ.NSAMAX_DP_SAVE)) RETURN
       CALL dpfp_deallocate
    ENDIF

    ALLOCATE(AEFP(NSAMAX_DP),AMFP(NSAMAX_DP),RNFP0(NSAMAX_DP),RTFP0(NSAMAX_DP))
    ALLOCATE(DELP(NSMAX))
    ALLOCATE(FNS(NTHMAX_DP,NPMAX_DP,NRMAX_DP,NSAMAX_DP))
    ALLOCATE(FP(NTHMAX_DP,NPMAX_DP,NRMAX_DP))
    ALLOCATE(FM(NPMAX_DP,NTHMAX_DP))
    ALLOCATE(DFP(NPMAX_DP,NTHMAX_DP),DFT(NPMAX_DP,NTHMAX_DP))
    ALLOCATE(THM(NTHMAX_DP),THG(NTHMAX_DP),TSNM(NTHMAX_DP),TSNG(NTHMAX_DP))
    ALLOCATE(TCSM(NTHMAX_DP),TCSG(NTHMAX_DP),TTNM(NTHMAX_DP),TTNG(NTHMAX_DP))
    ALLOCATE(PM(NPMAX_DP,NSAMAX_DP),PG(NPMAX_DP,NSAMAX_DP))
    ALLOCATE(RGMM(NPMAX_DP,NSAMAX_DP),RGMG(NPMAX_DP,NSAMAX_DP))
    ALLOCATE(RM(NRMAX_DP))
    ALLOCATE(DGP1(NPMAX_DP,NTHMAX_DP),DGP2(NPMAX_DP,NTHMAX_DP))
    ALLOCATE(DGT1(NPMAX_DP,NTHMAX_DP),DGT2(NPMAX_DP,NTHMAX_DP))
    ALLOCATE(RFP(NRMAX_DP+2),URFP(4,NRMAX_DP+2,NPMAX_DP,NTHMAX_DP))
    ALLOCATE(FPDATAS(NSAMAX_DP))
!    ALLOCATE(CHI(NCHMAX),CCHI(NCHMAX),SCHI(NCHMAX))
    RETURN
  END SUBROUTINE dpfp_allocate

  SUBROUTINE dpfp_deallocate
    DEALLOCATE(AEFP,AMFP,RNFP0,RTFP0,DELP)
    DEALLOCATE(FNS)
    DEALLOCATE(FP)
    DEALLOCATE(FM,DFP,DFT)
    DEALLOCATE(THM,THG,TSNM,TSNG,TCSM,TCSG,TTNM,TTNG)
    DEALLOCATE(PM,PG)
    DEALLOCATE(RGMM,RGMG)
    DEALLOCATE(RM)
    DEALLOCATE(DGP1,DGP2,DGT1,DGT2)
    DEALLOCATE(RFP,URFP,FPDATAS)
!    DEALLOCATE(CHI,CCHI,SCHI)
    RETURN
  END SUBROUTINE dpfp_deallocate

END MODULE dpcomm

MODULE dpcomm_local

  USE dpcomm
  USE dpcomm_parm_local

END MODULE dpcomm_local

