MODULE DPROOT

  PRIVATE
  PUBLIC dpgrp0,dpgrp1,dp_root

CONTAINS

!     *************************
!           CALC POINT DISP
!     *************************

  SUBROUTINE DPGRP0

    USE dpcomm_local
    USE dpdisp
    USE dpfpin,ONLY: dpldfm
    IMPLICIT NONE
    COMPLEX(rkind):: CRF,CKX,CKY,CKZ,CD0,CD1,CD2,CD3,CD4,CD5,CD6
    REAL(rkind):: RF0_SAVE
    INTEGER:: MODELP_SAVE(NSMAX),MODELV_SAVE(NSMAX),NS,IERR

1   WRITE(6,'(A)')          '## INPUT: RF0,RFI0,RKX0,RKY0,RKZ0,RX0,RY0,RZ0='
    WRITE(6,'(A,1P2E12.4)') '##   ',RF0,RFI0
    WRITE(6,'(A,1P6E12.4)') '##   ',RKX0,RKY0,RKZ0,RX0,RY0,RZ0
    RF0_SAVE=RF0
    READ(5,*,ERR=1,END=9000) RF0,RFI0,RKX0,RKY0,RKZ0,RX0,RY0,RZ0
    IF(ABS(RF0).LE.1.D-8) THEN
       RF0=RF0_SAVE
       GOTO 9000
    END IF

    CRF=DCMPLX(RF1,RFI0)
    CKX=RKX0
    CKY=RKY0
    CKZ=RKZ0
    DO ns=1,nsmax
       MODELP_SAVE(ns)=MODELP(ns)
       MODELV_SAVE(ns)=MODELV(ns)
    END DO
    DO ns=1,nsmax
       MODELP(ns)=0
       MODELV(ns)=0
    END DO
    CD0=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELP=0: (',CD0,')' 
    DO ns=1,nsmax
       MODELP(ns)=1
       MODELV(ns)=0
    END DO
    CD1=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELP=1: (',CD1,')' 
    DO ns=1,nsmax
       MODELP(ns)=4
       MODELV(ns)=0
    END DO
    CD4=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELP=4: (',CD4,')' 
    DO ns=1,nsmax
       MODELP(ns)=5
       MODELV(ns)=0
    END DO
    CD5=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELP=5: (',CD5,')' 
    DO ns=1,nsmax
       MODELP(ns)=6
       MODELV(ns)=0
    END DO
    CD6=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELP=6: (',CD6,')' 
    MODELV(1)=1
    DO ns=2,nsmax
       MODELP(ns)=6
       MODELV(ns)=0
    END DO
    CALL DPLDFM(1,0,IERR)
    CD2=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELV=1: (',CD2,')' 
    MODELV(1)=3
    DO ns=2,nsmax
       MODELP(ns)=6
       MODELV(ns)=0
    END DO
    CALL DPLDFM(1,1,IERR)
    CD3=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
    WRITE(6,'(A,1P2E16.8,A)') 'MODELV=3: (',CD3,')' 

    GOTO 1

9000 RETURN
  END SUBROUTINE DPGRP0

!     *************************
!           PLOT 1D GRAPH      
!     *************************

  SUBROUTINE DPGRP1

    USE dpcomm_local
    USE dpdisp
    IMPLICIT NONE
    REAL(4),DIMENSION(:),ALLOCATABLE:: GX,GY
    INTEGER:: ISW,NX
    REAL(rkind):: DRF
    COMPLEX(rkind):: CRF,CKX,CKY,CKZ,CD
    REAL(4):: GXMIN,GXMAX,GXSMN,GXSMX,GSCALX
    REAL(4):: GYMIN,GYMAX,GYSMN,GYSMX,GSCALY
    REAL(4):: GUCLIP
    REAL(rkind):: DRFI,RNPHII,DKX,DKY,DKZ

1   WRITE(6,*)'## SELECT : (1)RF (2)RFI (3)KX (4)KY (5)KZ (0)END'
    READ(5,*,ERR=1,END=9000) ISW
    IF(ISW.EQ.0) GOTO 9000

100 CONTINUE

    IF(ISW.EQ.1) THEN
2      WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RF1,RF2,NGXMAX: ',RF1,RF2,NGXMAX
       READ(5,*,ERR=2,END=1) RF1,RF2,NGXMAX
       IF(NGXMAX.LE.0) GOTO 1
       ALLOCATE(GX(NGXMAX),GY(NGXMAX))
       DRF=(RF2-RF1)/NGXMAX
       DO NX=1,NGXMAX
          CRF=DCMPLX(RF1,RFI0)+DRF*(NX-1)
          CKX=RKX0
          CKY=RKY0
          CKZ=RKZ0
          CD=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
          GX(NX)=GUCLIP(DBLE(CRF))
          GY(NX)=GUCLIP(LOG10(ABS(CD)))
       END DO
    ELSEIF(ISW.EQ.2) THEN
102    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RFI1,RFI2,NGXMAX: ',RFI1,RFI2,NGXMAX
       READ(5,*,ERR=102,END=1) RFI1,RFI2,NGXMAX
       IF(NGXMAX.LE.0) GOTO 1
       ALLOCATE(GX(NGXMAX),GY(NGXMAX))
       DRFI=(RFI2-RFI1)/NGXMAX
       DO NX=1,NGXMAX
          CRF=DCMPLX(RF0,RFI1)+DCMPLX(0.D0,DRFI)*(NX-1)
          CKX=RKX0
          CKY=RKY0
          CKZ=RKZ0
          CD=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
          GX(NX)=GUCLIP(DIMAG(CRF))
          GY(NX)=GUCLIP(LOG10(ABS(CD)))
       END DO
    ELSEIF(ISW.EQ.3) THEN
202    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKX1,RKX2,NGXMAX: ',RKX1,RKX2,NGXMAX, &
            '         RF0,RX0,RNPHII:   ',RF0,RX0,RNPHII
       READ(5,*,ERR=202,END=1) RKX1,RKX2,NGXMAX,RF0,RX0,RNPHII
       IF(NGXMAX.LE.0) GOTO 1
       ALLOCATE(GX(NGXMAX),GY(NGXMAX))
       DKX=(RKX2-RKX1)/NGXMAX
       DO NX=1,NGXMAX
          CRF=DCMPLX(RF0,RFI0)
          CKX=RKX1+DKX*(NX-1)
          RKY0=2.D6*PI*RF0*RNPHII/VC
          CKY=RKY0
          CKZ=RKZ0
          CD=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
          GX(NX)=GUCLIP(DBLE(CKX))
          GY(NX)=GUCLIP(LOG10(ABS(CD)))
       END DO
    ELSEIF(ISW.EQ.4) THEN
302    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKY1,RKY2,NGXMAX: ',RKY1,RKY2,NGXMAX
       READ(5,*,ERR=302,END=1) RKY1,RKY2,NGXMAX
       IF(NGXMAX.LE.0) GOTO 1
       ALLOCATE(GX(NGXMAX),GY(NGXMAX))
       DKY=(RKY2-RKY1)/NGXMAX
       DO NX=1,NGXMAX
          CRF=DCMPLX(RF0,RFI0)
          CKX=RKX0
          CKY=RKY1+DKY*(NX-1)
          CKZ=RKZ0
          CD=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
          GX(NX)=GUCLIP(DBLE(CKY))
          GY(NX)=GUCLIP(LOG10(ABS(CD)))
       END DO
    ELSEIF(ISW.EQ.5) THEN
402    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKZ1,RKZ2,NGXMAX: ',RKZ1,RKZ2,NGXMAX
       READ(5,*,ERR=402,END=1) RKZ1,RKZ2,NGXMAX
       IF(NGXMAX.LE.0) GOTO 1
       ALLOCATE(GX(NGXMAX),GY(NGXMAX))
       DKZ=(RKZ2-RKZ1)/NGXMAX
       DO NX=1,NGXMAX
          CRF=DCMPLX(RF0,RFI0)
          CKX=RKX0
          CKY=RKY0
          CKZ=RKZ1+DKZ*(NX-1)
          CD=CFDISP(CRF,CKX,CKY,CKZ,RX0,RY0,RZ0)
          GX(NX)=GUCLIP(DBLE(CKZ))
          GY(NX)=GUCLIP(LOG10(ABS(CD)))
       END DO
    ELSE
       GOTO 1
    ENDIF
    CALL PAGES
      CALL SETLIN(0,0,7)
      CALL SETCHS(0.3,0.)
      CALL GMNMX1(GX,1,NGXMAX,1,GXMIN,GXMAX)
      CALL GMNMX1(GY,1,NGXMAX,1,GYMIN,GYMAX)
      CALL GQSCAL(GXMIN,GXMAX,GXSMN,GXSMX,GSCALX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMN,GYSMX,GSCALY)
      CALL GDEFIN(3.,18.,2.,17.,GXSMN,GXSMX,GYSMN,GYSMX)
      CALL GFRAME
      CALL GSCALE(GXSMN,GSCALX,0.0,0.0,0.2,9)
      CALL GSCALL(0.0,0,GYSMN,2,0.2,9)
      CALL GVALUE(GXSMN,2*GSCALX,0.0,0.0,-2)
      CALL GVALUL(0.0,0,GYSMN,1,0)
      CALL GPLOTP(GX,GY,1,NGXMAX,1,0,0,0)

      CALL MOVE(9.0,18.0)
      IF (ISW.EQ.1) THEN
       CALL TEXT (' RF ',4)
      ELSEIF (ISW.EQ.2) THEN
       CALL TEXT (' RFI',4) 
      ELSEIF (ISW.EQ.3) THEN
       CALL TEXT (' KPP',4) 
      ELSEIF (ISW.EQ.4) THEN
       CALL TEXT (' KPR',4) 
      ENDIF
      CALL MOVE(20.0,16.5)
      CALL TEXT('RF  =',5)
      CALL NUMBD(RF0,  '(1PE11.3)',11)
      CALL MOVE(20.0,16.0)
      CALL TEXT('RFI0=',5)
      CALL NUMBD(RFI0, '(1PE11.3)',11)
      CALL MOVE(20.0,15.5)
      CALL TEXT('KX  =',5)
      CALL NUMBD(RKX0,'(1PE11.3)',11)
      CALL MOVE(20.0,15.0)
      CALL TEXT('KY  =',5)
      CALL NUMBD(RKY0,'(1PE11.3)',11)
      CALL MOVE(20.0,14.5)
      CALL TEXT('KZ  =',5)
      CALL NUMBD(RKZ0,'(1PE11.3)',11)
    CALL PAGEE
    DEALLOCATE(GX,GY)
    GOTO 100

9000 RETURN
  END SUBROUTINE DPGRP1

!     *************************
!             FIND ROOT
!     *************************

  SUBROUTINE DP_ROOT

    USE dpcomm_local
    IMPLICIT NONE
    REAL(4),DIMENSION(:),ALLOCATABLE::  GX,GY,GY2
    REAL(4),DIMENSION(:,:),ALLOCATABLE:: GXA,GYA,GY2A
    INTEGER,DIMENSION(:),ALLOCATABLE::  NGXMAXA
    REAL(rkind):: RFX,RFIX,DKX,DKY,DKZ,DXPOS,RKXX,RKXIX
    COMPLEX(rkind):: CRF,CKX
    REAL(4):: GUCLIP
    INTEGER:: NX,ISW,I,IGMAX

    IGMAX=100

1   WRITE(6,*)'## SELECT : CRF : (1)ROOT (2)KX (3)KY (4)KZ (5) X'
    WRITE(6,*)'  (0) END : CKX : (6)ROOT (7)X1 (8)X2'
    READ(5,*,ERR=1,END=9000) ISW
    IF(ISW.EQ.0) GOTO 9000
    RFX=RF0
    RFIX=RFI0

    IF(ISW.EQ.1) THEN
2      WRITE(6,'(A,1P2E12.4)') ' INPUT : RFX,RFIX: ',RFX,RFIX
       READ(5,*,ERR=2,END=1) RFX,RFIX
       ILIST=1
       CKX0=RKX0
       CKY0=RKY0
       CKZ0=RKZ0
       XPOS0=RX0
       YPOS0=RY0
       ZPOS0=RZ0
       CRF=DCMPLX(RFX,RFIX)
       CALL DPBRENT1(CRF)
       WRITE(6,*) CRF
       GOTO 2
    ELSEIF(ISW.EQ.2) THEN
202    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKX1,RKX2,NGXMAX: ',RKX1,RKX2,NGXMAX
       READ(5,*,ERR=202,END=1) RKX1,RKX2,NGXMAX
       ALLOCATE(GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX))
       DKX=(RKX2-RKX1)/(NGXMAX-1)
       CRF=DCMPLX(RF0,RFI0)
       CKY0=RKY0
       CKZ0=RKZ0
       XPOS0=RX0
       YPOS0=RY0
       ZPOS0=RZ0
       DO NX=1,NGXMAX
          ILIST=0
          CKX0=RKX1+DKX*(NX-1)
          WRITE(6,*) CRF
          CALL DPBRENT1(CRF)
          GX(NX)=GUCLIP(DBLE(CKX0))
          GY(NX)=GUCLIP(DBLE(CRF))
          GY2(NX)=GUCLIP(DIMAG(-CRF))
       END DO
       CALL DPGR1A(GX,GY,GY2,NGXMAX,ISW)
    ELSEIF(ISW.EQ.3) THEN
302    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKY1,RKY2,NGXMAX: ',RKY1,RKY2,NGXMAX
       READ(5,*,ERR=302,END=1) RKY1,RKY2,NGXMAX
       ALLOCATE(GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX))
       DKY=(RKY2-RKY1)/(NGXMAX-1)
       CRF=DCMPLX(RF0,RFI0)
       CKX0=RKX0
       CKZ0=RKZ0
       XPOS0=RX0
       YPOS0=RY0
       ZPOS0=RZ0
       DO NX=1,NGXMAX
          ILIST=0
          CKY0=RKY1+DKY*(NX-1)
          CALL DPBRENT1(CRF)
          WRITE(6,*) CRF
          GX(NX)=GUCLIP(DBLE(CKY0))
          GY(NX)=GUCLIP(DBLE(CRF))
          GY2(NX)=GUCLIP(DIMAG(-CRF))
       END DO
       CALL DPGR1A(GX,GY,GY2,NGXMAX,ISW)
       DEALLOCATE(GX,GY,GY2)
    ELSEIF(ISW.EQ.4) THEN
402    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RKZ1,RKZ2,NGXMAX: ',RKZ1,RKZ2,NGXMAX
       READ(5,*,ERR=402,END=1) RKZ1,RKZ2,NGXMAX
       ALLOCATE(GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX))
       DKZ=(RKZ2-RKZ1)/(NGXMAX-1)
       CRF=DCMPLX(RF0,RFI0)
       CKX0=RKX0
       CKY0=RKY0
       XPOS0=RX0
       YPOS0=RY0
       ZPOS0=RZ0
       DO NX=1,NGXMAX
          ILIST=0
          CKZ0=RKZ1+DKZ*(NX-1)
          CALL DPBRENT1(CRF)
          WRITE(6,*) CRF
          GX(NX)=GUCLIP(DBLE(CKZ0))
          GY(NX)=GUCLIP(DBLE(CRF))
          GY2(NX)=GUCLIP(DIMAG(-CRF))
       END DO
       CALL DPGR1A(GX,GY,GY2,NGXMAX,ISW)
       DEALLOCATE(GX,GY,GY2)
    ELSEIF(ISW.EQ.5) THEN
502    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RX1,RX2,NGXMAX: ',RX1,RX2,NGXMAX
       READ(5,*,ERR=502,END=1) RX1,RX2,NGXMAX
       ALLOCATE(GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX))
       DXPOS=(RX2-RX1)/(NGXMAX-1)
       CRF=DCMPLX(RF0,RFI0)
       CKX0=RKX0
       CKY0=RKY0
       CKZ0=RKZ0
       YPOS0=RY0
       ZPOS0=RZ0
       DO NX=1,NGXMAX
          ILIST=0
          XPOS0=RX1+DXPOS*(NX-1)
          CALL DPBRENT1(CRF)
          WRITE(6,*) CRF
          GX(NX)=GUCLIP(XPOS0)
          GY(NX)=GUCLIP(DBLE(CRF))
          GY2(NX)=GUCLIP(DIMAG(-CRF))
       END DO
       CALL DPGR1A(GX,GY,GY2,NGXMAX,ISW)
       DEALLOCATE(GX,GY,GY2)
    ELSEIF(ISW.EQ.6) THEN
602    WRITE(6,'(A,1P2E12.4)') ' INPUT : RKX,RKXI: ',RKXX,RKXIX
       READ(5,*,ERR=602,END=1) RKXX,RKXIX
       ILIST=1
       CRF0=DCMPLX(RF0,0.D0)
       CKY0=RKY0
       CKZ0=RKZ0
       XPOS0=RX0
       YPOS0=RY0
       ZPOS0=RZ0
       CKX=DCMPLX(RKXX,RKXIX)
       CALL DPBRENT2(CKX)
       WRITE(6,*) CKX
       GOTO 602
    ELSEIF(ISW.EQ.7) THEN
702    WRITE(6,'(A,1P2E12.4,I5)') &
            ' INPUT : RX1,RX2,NGXMAX: ',RX1,RX2,NGXMAX
       READ(5,*,ERR=702,END=1) RX1,RX2,NGXMAX
       ALLOCATE(GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX))
       DXPOS=(RX2-RX1)/(NGXMAX-1)
       CRF0=DCMPLX(RF0,0.D0)
       CKX0=RKX0
       CKY0=RKY0
       CKZ0=RKZ0
       YPOS0=RY0
       ZPOS0=RZ0
       DO NX=1,NGXMAX
          ILIST=0
          XPOS0=RX1+DXPOS*(NX-1)
          CALL DPBRENT2(CKX)
          GX(NX)=GUCLIP(DBLE(XPOS0))
          GY(NX)=GUCLIP(DBLE(CKX**2))
          GY2(NX)=GUCLIP(DIMAG(CKX**2))
          WRITE(6,*) CKX
       END DO
       CALL DPGR1A(GX,GY,GY2,NGXMAX,ISW)
    ELSEIF(ISW.EQ.8) THEN
801    WRITE(6,'(A,2I5)') &
            ' INPUT : NGXMAX,IGMAX: ',NGXMAX,IGMAX
       READ(5,*,ERR=801,END=8000) NGXMAX,IGMAX
       IF(NGXMAX.EQ.0) GOTO 8000
       ALLOCATE(GXA(NGXMAX,IGMAX),GYA(NGXMAX,IGMAX),GY2A(NGXMAX,IGMAX))
       ALLOCATE(NGXMAXA(IGMAX))
       I=0
802    WRITE(6,'(A,1P2E12.4,I5,1PE12.4)') &
            ' INPUT : RX1,RX2,NGXMAX,RKX0: ',RX1,RX2,NGXMAX,RKX0
       READ(5,*,ERR=802,END=8000) RX1,RX2,NGXMAX,RKX0
       IF(RX1.EQ.RX2)   GO TO 8000
       I=I+1
       DXPOS=(RX2-RX1)/(NGXMAX-1)
       CRF0=DCMPLX(RF0,0.D0)
       CKX=DCMPLX(RKX0,0.D0)
       CKY0=RKY0
       CKZ0=RKZ0
       YPOS0=RY0
       ZPOS0=RZ0
       NGXMAXA(I)=NGXMAX
       DO NX=1,NGXMAX
          ILIST=0
          XPOS0=RX1+DXPOS*(NX-1)
          CALL DPBRENT2(CKX)
          GXA(NX,I)=GUCLIP(XPOS0)
          IF(DBLE(CKX**2).GT.0) THEN
             GYA(NX,I)=GUCLIP(SQRT(DBLE(CKX**2)))
          ELSEIF(DBLE(CKX**2).LT.0) THEN         
             GYA(NX,I)=GUCLIP(-SQRT(-DBLE(CKX**2)))
          ENDIF
          IF(DIMAG(CKX**2).GT.0) THEN
             GY2A(NX,I)=GUCLIP(SQRT(DIMAG(CKX**2)))
          ELSEIF(DIMAG(CKX**2).LT.0) THEN         
             GY2A(NX,I)=GUCLIP(-SQRT(DIMAG(CKX**2)))
          ENDIF
          WRITE(6,*) CKX
       END DO
       CALL DPGR1A(GXA(1,I),GYA(1,I),GY2A(1,I),NGXMAX,ISW)
       IF(I.LT.IGMAX) GOTO 802
8000   CONTINUE
       CALL DPGR1B(GXA,GYA,GY2A,NGXMAX,NGXMAXA,I,ISW)
       DEALLOCATE(GXA,GYA,GY2A,NGXMAXA)
    ENDIF

   GOTO 1

9000 RETURN
 END SUBROUTINE DP_ROOT

!     *************************
!           BRENT METHOD 1
!     *************************

  SUBROUTINE DPBRENT1(CX)

    USE dpcomm_local
    IMPLICIT NONE
    COMPLEX(rkind),INTENT(INOUT):: CX
    REAL(rkind),DIMENSION(:),ALLOCATABLE:: X,F,WA
    INTEGER:: M,NBRMAX,INFO,LWA

    M = LMAXRT
    NBRMAX = 2
    LWA=NBRMAX*(NBRMAX+3)
    ALLOCATE(X(NBRMAX),F(NBRMAX),WA(LWA))
    X(1)=DBLE(CX)
    X(2)=DIMAG(CX)

    CALL FBRENTN(DPFUNC1,NBRMAX,X,F,EPSRT,INFO,WA,LWA)
    IF(INFO.GE.1.AND.INFO.LE.3) THEN
       X(1)=RF0
       X(2)=RFI0
    ENDIF

    CX=DCMPLX(X(1),X(2))
    DEALLOCATE(X,F,WA)
    RETURN
 END SUBROUTINE DPBRENT1

!     *******************************
!           Determinant Function
!     *******************************

  SUBROUTINE DPFUNC1(N,X,F,ID)

    USE dpcomm_local
    USE dpdisp
    IMPLICIT NONE
    INTEGER,INTENT(IN):: N,ID
    REAL(rkind),INTENT(IN):: X(N)
    REAL(rkind),INTENT(INOUT):: F(N)
    COMPLEX(rkind):: CRF,CFUNC

    CRF=DCMPLX(X(1),X(2))
    CFUNC=CFDISP(CRF,CKX0,CKY0,CKZ0,XPOS0,YPOS0,ZPOS0)
    IF(ID.EQ.1)THEN
       F(1)=DBLE(CFUNC)
    ELSE
       F(2)=DIMAG(CFUNC)
    END IF
    IF(ILIST.NE.0) WRITE(6,'(1P3E12.4,I5)') X(1),X(2),F(ID),ID
    RETURN
  END SUBROUTINE DPFUNC1

!     *******************************
!           BRENT METHOD 2
!     *******************************

  SUBROUTINE DPBRENT2(CX)

    USE dpcomm_local
    IMPLICIT NONE
    COMPLEX(rkind),INTENT(INOUT):: CX
    REAL(rkind),DIMENSION(:),ALLOCATABLE:: X,F,WA
    INTEGER:: M,NBRMAX,LWA,INFO
    REAL(rkind):: EPS

    EPS  = 1.D2
    M = 100
    NBRMAX=2
    LWA=NBRMAX*(NBRMAX+3)
    ALLOCATE(X(NBRMAX),F(NBRMAX),WA(LWA))

    X(1)=DBLE(CX)
    X(2)=DIMAG(CX)

    CALL FBRENTN(DPFUNC2,NBRMAX,X,F,EPS,INFO,WA,LWA)
    IF(INFO.GE.1.AND.INFO.LE.3) THEN
       X(1)=RKX0
       X(2)=0.D0
    ENDIF

    CX=DCMPLX(X(1),X(2))
    DEALLOCATE(X,F,WA)
    RETURN
  END SUBROUTINE DPBRENT2

!     *******************************
!           Determinant Function
!     *******************************

  SUBROUTINE DPFUNC2(N,X,F,I)

    USE dpcomm_local
    USE dpdisp
    IMPLICIT NONE

    INTEGER,INTENT(IN):: N,I
    REAL(rkind),INTENT(IN):: X(N)
    REAL(rkind),INTENT(OUT):: F(N)
    COMPLEX(rkind):: CKX,CFUNC2

    CKX=DCMPLX(X(1),X(2))
    CFUNC2=CFDISP(CRF0,CKX,CKY0,CKZ0,XPOS0,YPOS0,ZPOS0)
    IF(I.EQ.1)THEN
       F(1)=DBLE(CFUNC2)
    ELSE
       F(2)=DIMAG(CFUNC2)
    END IF
    IF(ILIST.NE.0) WRITE(6,'(1P3E12.4,I5)') X(1),X(2),F(I),I
    RETURN
  END SUBROUTINE DPFUNC2

!     *******************************
!           BRENT METHOD 3
!     *******************************
!
!  SUBROUTINE DPBRENT3(CX)
!
!    USE dpcomm_local
!    IMPLICIT NONE
!    COMPLEX(rkind),INTENT(INOUT):: CX
!    REAL(rkind),DIMENSION(:),ALLOCATABLE:: X,F,WA
!    INTEGER:: M,NBRMAX,INFO,LWA
!    REAL(rkind):: EPS
!
!    EPS  = 1.D2
!    M = 100
!    NBRMAX=2
!    LWA=NBRMAX*(NBRMAX+3)
!    ALLOCATE(X(NBRMAX),F(NBRMAX),WA(LWA))
!
!    X(1)=DBLE(SQRT(CX))
!    X(2)=DIMAG(SQRT(CX))
!
!    CALL FBRENTN(DPFUNC3,NBRMAX,X,F,EPS,INFO,WA,LWA)
!    IF(INFO.GE.1.AND.INFO.LE.3) THEN
!       X(1)=RKX0**2
!       X(2)=0.D0
!    ENDIF
!
!    CX=DCMPLX(X(1),X(2))**2
!    DEALLOCATE(X,F,WA)
!    RETURN
!  END SUBROUTINE DPBRENT3

!     *******************************
!           Determinant Function
!     *******************************
!
!  SUBROUTINE DPFUNC3(N,X,F,I)
!
!    USE dpcomm_local
!    USE dpdisp
!    IMPLICIT NONE
!
!    INTEGER,INTENT(IN):: N,I
!    REAL(rkind),INTENT(IN):: X(N)
!    REAL(rkind),INTENT(OUT):: F(N)
!    COMPLEX(rkind):: CKX,CFUNC3
!
!    CKX=DCMPLX(X(1),X(2))
!    CFUNC3=CFDISP(CRF0,CKX,CKY0,CKZ0,XPOS0,YPOS0,ZPOS0)
!    IF(I.EQ.1)THEN
!       F(1)=DBLE(CFUNC3)
!    ELSE
!       F(2)=DIMAG(CFUNC3)
!    END IF
!    IF(ILIST.NE.0) WRITE(6,'(1P3E12.4,I5)') X(1),X(2),F(I),I
!    RETURN
!  END SUBROUTINE DPFUNC3

!     *******************************
!           1D plot
!     *******************************

  SUBROUTINE DPGR1A(GX,GY,GY2,NGXMAX,ISW)

      DIMENSION GX(NGXMAX),GY(NGXMAX),GY2(NGXMAX)

      CALL PAGES
      CALL SETLIN(0,0,7)
      CALL SETCHS(0.3,0.)
      CALL GMNMX1(GX,1,NGXMAX,1,GXMIN,GXMAX)
      CALL GMNMX1(GY,1,NGXMAX,1,GYMIN,GYMAX)
      CALL GQSCAL(GXMIN,GXMAX,GXSMN,GXSMX,GSCALX)
      CALL SETLIN(0,0,5)
      CALL GQSCAL(GYMIN,GYMAX,GYSMN,GYSMX,GSCALY)
      IF(GXMIN*GXMAX.LT.0.0) THEN
         GXORG=0.0
      ELSE
         GXORG=GXSMN
      ENDIF
      IF(GYMIN*GYMAX.LT.0.0) THEN
         GYORG=0.0
      ELSE
         GYORG=GYSMN
      ENDIF
      CALL GDEFIN(4.,17.,2.,17.,GXSMN,GXSMX,GYSMN,GYSMX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(GXORG,GSCALX,0.0,0.0,0.2,9)
      CALL SETLIN(0,0,5)
      CALL GSCALE(0.0,0.0,GYORG,GSCALY,0.2,1)
      CALL GSCALE(0.0,0.0,0.0,10*(GYMAX-GYMIN),0.0,0)
      CALL SETLIN(0,0,7)
      CALL GVALUE(GXORG,2*GSCALX,0.0,0.0,2)
      CALL SETLIN(0,0,5)
      CALL GVALUE(0.0,0.0,GYORG,2*GSCALY,-2)
      CALL GPLOTP(GX,GY,1,NGXMAX,1,0,0,0)

      CALL SETLIN(0,0,2)
      CALL GMNMX1(GY2,1,NGXMAX,1,GYMIN,GYMAX)
      IF(GYMAX-GYMIN.GT.1.D-15) THEN
         CALL GQSCAL(GYMIN,GYMAX,GYSMN,GYSMX,GSCALY)
         IF(GYMIN*GYMAX.LT.0.0) THEN
            GYORG=0.0
         ELSE
            GYORG=GYSMN
         ENDIF
         CALL GDEFIN(4.,17.,2.,17.,GXSMN,GXSMX,GYSMN,GYSMX)
         CALL GSCALE(0.0,0.0,GYORG,GSCALY,0.2,5)
         CALL GVALUE(0.0,0.0,GYORG,2*GSCALY,-402)
         CALL GVALUE(0.0,0.0,GYORG,2*GSCALY,-402)
         CALL GPLOTP(GX,GY2,1,NGXMAX,1,0,0,2)
      ENDIF

      CALL DPGPRM(ISW)
      CALL PAGEE
      RETURN
  END SUBROUTINE DPGR1A

!     *******************************
!           1D plot
!     *******************************

  SUBROUTINE DPGR1B(GXA,GYA,GY2A,NXM,NGXMAXA,IGMAX,ISW)

      DIMENSION GXA(NXM,IGMAX),GYA(NXM,IGMAX),GY2A(NXM,IGMAX)
      DIMENSION NGXMAXA(IGMAX)

      CALL PAGES
      CALL SETLIN(0,0,7)
      CALL SETCHS(0.3,0.)
      GXMIN  = 1.E20
      GXMAX  =-1.E20
      GYMIN  = 1.E20
      GYMAX  =-1.E20
      GYMIN3 = 1.E20
      GYMAX3 =-1.E20
      DO IG=1,IGMAX
         CALL GMNMX1(GXA(1,IG),1,NGXMAXA(IG),1,GXMIN1,GXMAX1)
         CALL GMNMX1(GYA(1,IG),1,NGXMAXA(IG),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GY2A(1,IG),1,NGXMAXA(IG),1,GYMIN2,GYMAX2)
         GXMIN  = MIN(GXMIN,GXMIN1)
         GXMAX  = MAX(GXMAX,GXMAX1)
         GYMIN  = MIN(GYMIN,GYMIN1)
         GYMAX  = MAX(GYMAX,GYMAX1)
         GYMIN3 = MIN(GYMIN3,GYMIN2)
         GYMAX3 = MAX(GYMAX3,GYMAX2)
      END DO
      GYMIN  = MIN(GYMIN,GYMIN3)
      GYMAX  = MAX(GYMAX,GYMAX3)
      CALL GQSCAL(GXMIN,GXMAX,GXSMN,GXSMX,GSCALX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMN,GYSMX,GSCALY)
      IF(GXMIN*GXMAX.LT.0.0) THEN
         GXORG=0.0
      ELSE
         GXORG=GXSMN
      ENDIF
      IF(GYMIN*GYMAX.LT.0.0) THEN
         GYORG=0.0
      ELSE
         GYORG=GYSMN
      ENDIF
      CALL GDEFIN(4.,17.,2.,17.,GXSMN,GXSMX,GYSMN,GYSMX)
      CALL GFRAME
      CALL GSCALE(GXORG,GSCALX,0.0,0.0,0.2,9)
      CALL GSCALE(0.0,0.0,GYORG,GSCALY,0.2,9)
      CALL GSCALE(0.0,0.0,0.0,10*(GYMAX-GYMIN),0.0,0)
      CALL GVALUE(GXORG,2*GSCALX,0.0,0.0,2)
      CALL GVALUE(0.0,0.0,GYORG,2*GSCALY,-2)
      DO IG=1,IGMAX
         CALL SETLIN(0,0,4)
         CALL GPLOTP(GXA(1,IG),GYA(1,IG),1,NGXMAXA(IG),1,0,0,0)
         CALL SETLIN(0,0,6)
         CALL GPLOTP(GXA(1,IG),GY2A(1,IG),1,NGXMAXA(IG),1,0,0,1)
      END DO

      CALL DPGPRM(ISW)
      CALL PAGEE
      RETURN
  END SUBROUTINE DPGR1B

!     *******************************
!           DRAW PARAMETERS
!     *******************************

  SUBROUTINE DPGPRM(ISW)

    USE dpcomm_local
    IMPLICIT NONE
    INTEGER,INTENT(IN):: ISW

    CALL SETLIN(0,0,7)
    IF (ISW.EQ.1) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' RF ',4)
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' RFI ',4)
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.2) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' KX ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' RF ',4) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.3) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' KY ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' RF ',4) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.4) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' KZ ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' RF ',4) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.5) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' X  ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' RF ',4) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.6) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' KX ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' KXI ',4) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.7) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' X  ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' KX*KX ',7) 
       CALL SETCHS(0.3,0.0)
    ELSEIF (ISW.EQ.8) THEN
       CALL MOVE(10.0,0.5)
       CALL TEXT (' X  ',4) 
       CALL MOVE(0.5,9.0)
       CALL SETCHS(0.3,90.0)
       CALL TEXT (' KX*KX ',7) 
       CALL SETCHS(0.3,0.0)
    ENDIF

    CALL MOVE(20.5,16.5)
    CALL TEXT('RF  =',5)
    CALL NUMBD(RF0,  '(1PE11.3)',11)
    CALL MOVE(20.5,16.0)
    CALL TEXT('RFI0=',5)
    CALL NUMBD(RFI0, '(1PE11.3)',11)
    CALL MOVE(20.5,15.5)
    CALL TEXT('KX  =',5)
    CALL NUMBD(RKX0,'(1PE11.3)',11)
    CALL MOVE(20.5,15.0)
    CALL TEXT('KY  =',5)
    CALL NUMBD(RKY0,'(1PE11.3)',11)
    CALL MOVE(20.5,14.5)
    CALL TEXT('KZ  =',5)
    CALL NUMBD(RKZ0,'(1PE11.3)',11)
    CALL MOVE(20.5,14.0)
    CALL TEXT('BB  =',5)
    CALL NUMBD(BB,'(1PE11.3)',11)
    CALL MOVE(20.5,13.5)
    CALL TEXT('RR  =',5)
    CALL NUMBD(RR,'(1PE11.3)',11)
    CALL MOVE(20.5,13.0)
    CALL TEXT('RA  =',5)
    CALL NUMBD(RA,'(1PE11.3)',11)
    CALL MOVE(20.5,12.5)
    CALL TEXT('PA1 =',5)
    CALL NUMBD(PA(1),'(1PE11.3)',11)
    CALL MOVE(20.5,12.0)
    CALL TEXT('PA2 =',5)
    CALL NUMBD(PA(2),'(1PE11.3)',11)
    CALL MOVE(20.5,11.5)
    CALL TEXT('PA3 =',5)
    CALL NUMBD(PA(3),'(1PE11.3)',11)
    CALL MOVE(20.5,11.0)
    CALL TEXT('PZ1 =',5)
    CALL NUMBD(PZ(1),'(1PE11.3)',11)
    CALL MOVE(20.5,10.5)
    CALL TEXT('PZ2 =',5)
    CALL NUMBD(PZ(2),'(1PE11.3)',11)
    CALL MOVE(20.5,10.0)
    CALL TEXT('PZ3 =',5)
    CALL NUMBD(PZ(3),'(1PE11.3)',11)
    CALL MOVE(20.5,9.5)
    CALL TEXT('PN1 =',5)
    CALL NUMBD(PN(1),'(1PE11.3)',11)
    CALL MOVE(20.5,9.0)
    CALL TEXT('PN2 =',5)
    CALL NUMBD(PN(2),'(1PE11.3)',11)
    CALL MOVE(20.5,8.5)
    CALL TEXT('PN3 =',5)
    CALL NUMBD(PN(3),'(1PE11.3)',11)
    CALL MOVE(20.5,8.0)
    CALL TEXT('PNS1=',5)
    CALL NUMBD(PNS(1),'(1PE11.3)',11)
    CALL MOVE(20.5,7.5)
    CALL TEXT('PNS2=',5)
    CALL NUMBD(PNS(2),'(1PE11.3)',11)
    CALL MOVE(20.5,7.0)
    CALL TEXT('PNS3=',5)
    CALL NUMBD(PNS(3),'(1PE11.3)',11)
    CALL MOVE(20.5,6.5)
    CALL TEXT('PTPR(e)=',8)
    CALL NUMBD(PTPR(1),'(1PE9.3)',9)
    CALL MOVE(20.5,6.0)
    CALL TEXT('PTPP(e)=',8)
    CALL NUMBD(PTPP(1),'(1PE9.3)',9)
    CALL MOVE(20.5,5.5)
    CALL TEXT('PTPR(i)=',8)
    CALL NUMBD(PTPR(2),'(1PE9.3)',9)
    CALL MOVE(20.5,5.0)
    CALL TEXT('PTPP(i)=',8)
    CALL NUMBD(PTPP(2),'(1PE9.3)',9)
    CALL MOVE(20.5,4.5)
    CALL TEXT('PTS    =',8)
    CALL NUMBD(PTS(1),'(1PE9.3)',9)
    CALL MOVE(20.5,3.5)
    CALL TEXT('MODELP =',8)
    CALL NUMBI(MODELP(1),'(I1)',1)

    RETURN
  END SUBROUTINE DPGPRM
END MODULE DPROOT
