C     $Id$
C
C     INCLUDE 'wmcomm.h'
C
      IMPLICIT COMPLEX*16(C),REAL*8(A-B,D-F,H,O-Z)
C
      PARAMETER (NCPUMIN=1)
      PARAMETER (NCPUMAX=32)
      PARAMETER (NRM=201)
      PARAMETER (NDPM=0)
      PARAMETER (MDPM=5)
      PARAMETER (NSM=3)
      PARAMETER (NAM=4)
      PARAMETER (NSUM=2049)
      PARAMETER (NGZM=401)
      PARAMETER (NTHGM=64)
C
      PARAMETER (NDM=2**NDPM)
      PARAMETER (MDM=2**MDPM)
      PARAMETER (NDMX=3*NDM/2)
      PARAMETER (MDMX=3*MDM/2)
      PARAMETER (NPHM=NDM)
      PARAMETER (NTHM=MDM)
      PARAMETER (LFFTM=MDM*MDPM)
      PARAMETER (MSIZM=3*NRM*MDM*NDM,MBNDM=12*MDM*NDM)
      PARAMETER (NRMD=NRM/NCPUMIN+1)
      PARAMETER (MSIZD=3*NRMD*MDM*NDM+1)
      PARAMETER (MSIZP=MSIZD+MBNDM)
      PARAMETER (NRGM=NRM+1)
C
      COMMON /WMCNS1/ CI,PI,AEE,AME,AMP,VC,RMU0,EPS0
      COMMON /WMPRM1/ BB,RR,RA,RB,Q0,QA,RKAP,RDEL
      COMMON /WMPRM2/ PA(NSM),PZ(NSM),PN(NSM),PNS(NSM),NSMAX
      COMMON /WMPRM3/ PZCL(NSM),PTPR(NSM),PTPP(NSM),PTS(NSM),ZEFF
      COMMON /WMPRM4/ PROFN1,PROFN2,PROFT1,PROFT2
      COMMON /WMPRM5/ PNA,PNAL,PTA
      COMMON /WMPRM6/ NRMAX,NTHMAX,NPHMAX
      COMMON /WMPRM7/ NTH0,NPH0,NHC
      COMMON /WMPRM8/ NPRINT,NGRAPH,MODELN
      COMMON /WMPRM9/ MODELG,MODELJ,MODELP,MODELA,MODELK,MODELM,MODELW
      COMMON /WMPRX1/ RHOMIN,QMIN
      COMMON /WMPRX2/ RHOITB,PNITB(NSM),PTITB(NSM),PUITB(NSM)
      COMMON /WMPRX3/ PU(NSM),PUS(NSM),PROFU1,PROFU2
      COMMON /WMPRX4/ PRFIN
C
      COMMON /WMANT1/ CRF,RD,BETAJ
      COMMON /WMANT2/ AJ(NAM),APH(NAM),NAMAX
      COMMON /WMANT3/ THJ1(NAM),THJ2(NAM),PHJ1(NAM),PHJ2(NAM)
C
      COMMON /WMNOD1/ XR(NRM),XRHO(NRM)
      COMMON /WMNOD2/ MDSIZ,MDMIN,MDMAX,LDSIZ,LDMIN,LDMAX,MDSIZX
      COMMON /WMNOD3/ NDSIZ,NDMIN,NDMAX,KDSIZ,KDMIN,KDMAX,NDSIZX
      COMMON /WMNOD4/ CJANT(3,MDM,NDM)
C
      COMMON /WMMTX1/ CEM(MBNDM,MSIZP),CFV(MSIZP)
      COMMON /WMMTX2/ MSIZ,MBND
      COMMON /WMMTX3/ CFVG(MSIZM)
C
      COMMON /WMTNS1/ CTNSR(3,3,-MDMX:MDMX,-NDMX:NDMX,MDM,NDM)
      COMMON /WMTNS2/ CGD(3,3,MDM,MDM,NDM,NDM,3)
C
      COMMON /WMEQG1/ RG11(MDM,NDM,NRM),RG12(MDM,NDM,NRM)
      COMMON /WMEQG2/ RG13(MDM,NDM,NRM),RG22(MDM,NDM,NRM)
      COMMON /WMEQG3/ RG23(MDM,NDM,NRM),RG33(MDM,NDM,NRM)
      COMMON /WMEQG4/ RJ(MDM,NDM,NRM)
      COMMON /WMEQG5/ CGF11(MDM,NDM,3),CGF12(MDM,NDM,3)
      COMMON /WMEQG6/ CGF13(MDM,NDM,3),CGF22(MDM,NDM,3)
      COMMON /WMEQG7/ CGF23(MDM,NDM,3),CGF33(MDM,NDM,3)
C
      COMMON /WMFLD1/ CEFLD(3,MDM,NDM,NRM),CEFLDK(3,MDM,NDM,NRM)
      COMMON /WMFLD2/ CBFLD(3,MDM,NDM,NRM),CBFLDK(3,MDM,NDM,NRM)
      COMMON /WMFLD3/ CEN(3,MDM,NDM,NRM),CEP(3,MDM,NDM,NRM)
C
      COMMON /WMPWR1/ PABS(MDM,NDM,NRM,NSM),PABSK(MDM,NDM,NRM,NSM)
      COMMON /WMPWR2/ PABSR(NRM,NSM),PABSKT(MDM,NDM,NSM)
      COMMON /WMPWR3/ CFLX(MDM,NDM,NRM),CFLXK(MDM,NDM,NRM),CFLXR(NRM)
      COMMON /WMPWR4/ CRADK(MDM,NDM,NAM),CRADKT(MDM,NDM)
      COMMON /WMPWR5/ CRADT(NAM),CRADTT,PABST(NSM),PABSTT
      COMMON /WMPWR6/ PCUR(MDM,NDM,NRM),PCURR(NRM),PCURT
      COMMON /WMPWR7/ CPABS(MDM,MDM,NDM,NDM,NSM,NRM)
      COMMON /WMPWR8/ PTABS(MDM,NDM,NRM,NSM)
C
      COMMON /WMEQX1/ RPST(NTHM,NPHM,NRM),ZPST(NTHM,NPHM,NRM)
      COMMON /WMEQX2/ BFLD(2:3,NTHM,NPHM,NRM)
      COMMON /WMEQX3/ BR(MDM,NDM,NRM),BICF
      COMMON /WMEQX4/ RGMIN,RGMAX,ZGMIN,ZGMAX
      COMMON /WMEQX5/ RSU(NSUM,NDM),ZSU(NSUM,NDM),NSUMAX
      COMMON /WMEQX6/ RSW(NSUM,NDM),ZSW(NSUM,NDM),NSWMAX
C
      COMMON /WMEQU2/ PSIPS(NRM),RPS(NTHM,NRM),ZPS(NTHM,NRM),PSIA
      COMMON /WMEQU4/ DRPSI(NTHM,NRM),DZPSI(NTHM,NRM)
      COMMON /WMEQU5/ DRCHI(NTHM,NRM),DZCHI(NTHM,NRM)
      COMMON /WMEQU6/ PPS(NRM),QPS(NRM),RBPS(NRM),VPS(NRM),RLEN(NRM)
C
C      COMMON /EQPRM4/ BTV,TTCU,TTPR,BETS,BETA,BETJ
C      COMMON /EQPRM5/ SAXIS,RAXIS,ZAXIS,ELL,TRG
C
      COMMON /WMFFT1/ CT(MDM),CFFT(LFFTM,2),LFFT(LFFTM)
C
      COMMON /WMEGN1/ FRMIN,FRMAX,FIMIN,FIMAX,FI0
      COMMON /WMEGN2/ FRINI,FIINI
      COMMON /WMEGN3/ NGFMAX,NGXMAX,NGYMAX
      COMMON /WMEGN4/ SCMIN,SCMAX,NSCMAX
      COMMON /WMEGN5/ LISTEG
      COMMON /WMEGN6/ DLTNW,EPSNW,LMAXNW,LISTNW,MODENW
C
      COMMON /WMTAE1/ WAEMIN,WAEMAX
C
      COMMON /WMPRF1/ RNPRF(NRM,NSM),RTPRF(NRM,NSM)
C
      COMMON /WMEGP1/ MODEEG
C
      COMMON /WMGRA1/ KACONT(8,NRGM,NTHGM)
      COMMON /WMGRA2/ RPSG(NTHGM,NRM),ZPSG(NTHGM,NRM)
C
      COMMON /WMMPI1/ NPROCS,MYRANK
      COMMON /WMMPI2/ NBST,NBED
C
      COMMON /WMKNM1/ KNAMEQ,KNAMPF
      CHARACTER KNAMEQ*80,KNAMPF*80
