C     $Id$
C
C     ****** CALCULATE LOCAL COEFFICIENT MATRIX ******
C
      SUBROUTINE WMSETM(CA,CB,IGD,LA,NRP)
C
      INCLUDE 'wmcomm.inc'
C
      DIMENSION CA(LA)
C
      IF(MDLWMX.EQ.0) THEN
         CALL WMSETM0(CA,CB,IGD,LA,NRP)
      ELSEIF(MDLWMX.EQ.1) THEN
         CALL WMSETM1(CA,CB,IGD,LA,NRP)
      ELSE
         WRITE(6,*) 'XX Unknow MDLWMX:',MDLWMX
      ENDIF
      RETURN
      END
