! MODULE ticomm_parm,ticomm

MODULE ticomm_parm

  USE plcomm,pm=>pa
  USE commpi

!     NSM=100 ! imported from plcomm

! IMPORTED FROM plcomm
!     RR,RA,RKAP,RDLT,BB,RIP,
!     NSM,NSMAX,
!     PM(NSM),PZ(NSM),PN(NSM),PNS(NSM),PTPR(NSM),PTPP(NSM),PTS(NSM),
!     PU(NSM),PUS(NSM),ID_NS(NSM),KID_NS(NSM)
!     PROFN1,PROFN2,PROFT1,PROFT2,PROFU1,PROFU2
!     MODELG,MODELN,MODELQ,MODEL_NPROF
!     KNAMEQ,KNAMEQ2,KNAMTR
!     MODEFR,MODEFW,IDEBUG
!     RHOA,Q0,QA (not an input parameter for tr)

  INTEGER:: NZMIN_NS(NSM),NZMAX_NS(NSM),NZINI_NS(NSM)
  INTEGER:: NRMAX,NTMAX,NTSTEP,NGTSTEP,NGRSTEP
  INTEGER:: ngt_allocate_step,ngr_allocate_step
  INTEGER:: MAXLOOP,MATTYPE
  INTEGER:: MODEL_EQB,MODEL_EQN,MODEL_EQT,MODEL_EQU
  INTEGER:: MODEL_KAI,MODEL_DRR,MODEL_VR,MODEL_NC
  INTEGER:: MODEL_NF,MODEL_NB,MODEL_EC,MODEL_LH,MODEL_IC
  INTEGER:: MODEL_CD,MODEL_SYNC
  INTEGER:: MODEL_PEL,MODEL_PSC

  REAL(rkind):: PT(NSM)
  REAL(rkind):: PROFJ1,PROFJ2
  REAL(rkind):: DT
  REAL(rkind):: EPSLOOP
  REAL(rkind):: EPSMAT

  REAL(rkind):: AK0,AD0,AV0,DK0,DKS
  REAL(rkind):: PNBIN,PNBR0,PNBRW,PNBENG,PNBRTG
  REAL(rkind):: PECIN,PECR0,PECRW,PECTOE,PECNPR
  REAL(rkind):: PLHIN,PLHR0,PLHRW,PLHTOE,PLHNPR
  REAL(rkind):: PICIN,PICR0,PICRW,PICTOE,PICNPR
  REAL(rkind):: PNBCD,PECCD,PLHCD,PICCD,PBSCD
  REAL(rkind):: PELIN,PELR0,PELRW,PELPAT(NSM)
  REAL(rkind):: PELTS,PELDT,PELTE,PELRAD,PELVEL
  REAL(rkind):: PSCIN,PSCR0,PSCRW,PSCPAT(NSM)
  REAL(rkind):: SYNC_WALL,SYNC_CONV

  CHARACTER(LEN=80):: KNAMLOG

END MODULE ticomm_parm

MODULE ticomm
  
  USE ticomm_parm
  USE commpi
  IMPLICIT NONE

  REAL(rkind),PARAMETER:: RKEV = AEE*1.D3

  INTEGER:: NR_START,NR_END
  INTEGER:: istart,iend,imax,jwidth

  REAL(rkind):: T
  INTEGER,DIMENSION(:),ALLOCATABLE:: &  !nsa_max
       ID_NSA,NSA_UP,NSA_DN,NS_NSA
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !nsa_max
       PMA,PZA
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: &  !nsa_max,NRMAX
       RNA,RTA,RUA
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !NRMAX
       RBP,RQP,RJP
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &  !nsa_max,NRMAX
       rnatot,rnuatot,rntatot,rnaave,ruaave,rtaave
  
  INTEGER:: NEQMAX,NGTMAX,NGRMAX

!     ****** CONTROL VARIABLES ******

  INTEGER:: NT
  INTEGER:: icount_loop,icount_mat
  INTEGER:: icount_loop_max,icount_mat_max
  REAL(rkind):: residual_loop,residual_loop_max

!     ****** GRID VARIBALES ******

  REAL(rkind):: DR
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: RM,RG

!     ****** MATRIX VARIBALES ******

  INTEGER:: nsa_max
  INTEGER, DIMENSION(:),ALLOCATABLE:: NSA_NEQ,NV_NEQ
  INTEGER, DIMENSION(:,:),ALLOCATABLE:: NEQ_NVNSA
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE :: MAT_LOCAL
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: VEC_LOCAL,VEC_GLOBAL
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: SOL_BASE,SOL_PREV,SOL_NEW
  REAL(rkind),DIMENSION(:),ALLOCATABLE :: VAL_EDGE

!     ****** PROFILE VARIBALES ******

  REAL(rkind),DIMENSION(:),ALLOCATABLE :: ZEFF,BETA,BETAP

!     ****** COEF VARIABLSE *****

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: AKTB,ADTB,AVTB
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: AKNC,ADNC,AVNC

!     ****** SOURCE VARIABLES ******

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       PNB,SNB,AJNB,PEC,AJEC,PLH,AJLH,PIC,AJIC, &
       PNF,SNF,SPEL,SPSC,POH,PRB,PRC,PRL, &
       PCX,PIE,SCX,SIE,AJBS
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (NRMAX)
       AJR,AJOHR,EZOHR,QPR,AJCDR,AJBSR
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (NRMAX)
       PNBR,SNBR,AJNBR,PECR,AJECR,PLHR,AJLHR,PICR,AJICR, &
       PNFR,SNFR,SPELR,SPSCR,POHR,PRBR,PRCR,PRLR, &
       PCXR,PIER,SCXR,SIER
  REAL(rkind),DIMENSION(:),ALLOCATABLE:: &! (nsa_max)
       PNBS,SNBS,AJNBS,PECS,AJECS,PLHS,AJLHS,PICS,AJICS, &
       PNFS,SNFS,SPELS,SPSCS,POHS,PRBS,PRCS,PRLS, &
       PCXS,PIES,SCXS,SIES,AJBSS
  REAL(rkind):: &
       AJTOT,AJOHTOT,EZOHTOT,QPTOT,AJCDTOT,AJBSTOT
  REAL(rkind):: &
       PNBTOT,SNBTOT,AJNBTOT,PECTOT,AJECTOT,PLHTOT,AJLHTOT,PICTOT,AJICTOT, &
       PNFTOT,SNFTOT,SPELTOT,SPSCTOT,POHTOT,PRBTOT,PRCTOT,PRLTOT, &
       PCXTOT,PIETOT,SCXTOT,SIETOT

!     ****** MATRIX VARIABLES ******

  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       SSIN,VSIN,PSIN,AJIN
  REAL(rkind),DIMENSION(:,:),ALLOCATABLE:: & ! (nsa_max,NRMAX)
       DD,VV
  REAL(rkind),DIMENSION(:,:,:),ALLOCATABLE:: & ! (nsa_max,nsa_max,NRMAX)
       CC

!     ****** EQUILIBRIUM INTERFACE VARIABLES ******

  REAL(rkind):: voltot,DVRHOS
  REAL(rkind)                 :: BPSEQ,RIPEQ
  REAL(rkind), DIMENSION(:),ALLOCATABLE :: &  ! (NRM)
       RHOTR, PRHO, HJRHO, VTRHO, TRHO, TTRHO, DVRHO, RKPRHO, ABRHO, ABVRHO, &
       ARRHO, AR1RHO, AR2RHO,  RJCB, EPSRHO, BPRHO, RMJRHO, RMNRHO, &
       TTRHOG, DVRHOG, RKPRHOG, ABRHOG, ABVRHOG, ARRHOG, AR1RHOG, AR2RHOG, &
       ABB2RHOG, AIB2RHOG, ARHBRHOG, RMJRHOG, RMNRHOG, RDPVRHOG, &
       PSITRHO, PSIPRHO, PPPRHO, PIQRHO, PIRHO, FACTQ, &
       PVOLRHOG, PSURRHOG, ABB1RHO

!     ****** NCLASS ******
! TRNCL
  INTEGER:: NSCLMAX
  INTEGER,DIMENSION(:),ALLOCATABLE:: NSCL_NSA,NSA_NSCL
  REAL(rkind), DIMENSION(:)    ,ALLOCATABLE :: & !  (NRM)
       AJBSNC, ETANC, AJEXNC
  REAL(rkind), DIMENSION(:,:)  ,ALLOCATABLE :: & !  (NRM,NSM)
       CJBSP, CJBST, ADNCG, AVNCG
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,NSM,NSM)
       AKNCP, AKNCT, ADNCP, ADNCT, AKLP, AKLD, ADLP, ADLD
  REAL(rkind), DIMENSION(:,:,:),ALLOCATABLE :: & !  (NRM,5,NSM)
       RGFLS,   RQFLS


  INTEGER,SAVE:: nrmax_save=0
  INTEGER,SAVE:: nsa_max_save=0
  INTEGER,SAVE:: nrmax_save2=0
  INTEGER,SAVE:: neqmax_save=0

CONTAINS

  SUBROUTINE allocate_ticomm(ierr)

    IMPLICIT NONE
    INTEGER,INTENT(OUT):: ierr
    ierr = 0

    IF(nrmax_save==nrmax .AND. &
       nsa_max_save==nsa_max) RETURN

    IF(ALLOCATED(ID_NSA)) CALL deallocate_ticomm

    ALLOCATE(ID_NSA(nsa_max),NS_NSA(nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(NSA_UP(nsa_max),NSA_DN(nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(PMA(nsa_max),PZA(nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(RNA(nsa_max,NRMAX),RTA(nsa_max,NRMAX),RUA(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(RBP(NRMAX),RQP(NRMAX),RJP(NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(rnatot(nsa_max),rnuatot(nsa_max),rntatot(nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(rnaave(nsa_max),ruaave(nsa_max),rtaave(nsa_max))
             IF(IERR.NE.0) GOTO 900

    ALLOCATE(RM(NRMAX),RG(0:NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(ZEFF(NRMAX),BETA(NRMAX),BETAP(NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(AKTB(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(ADTB(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(AVTB(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(AKNC(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(ADNC(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(AVNC(nsa_max,NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900

!     ****** SOURCE VARIABLES ******

    ALLOCATE(PNB(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNB(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNB(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PEC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJEC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLH(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLH(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJIC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNF(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNF(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPEL(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(POH(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRB(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRC(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRL(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCX(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIE(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCX(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIE(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBS(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900

    ALLOCATE(AJR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJOHR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(EZOHR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(QPR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJCDR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBSR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900

    ALLOCATE(PNBR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNBR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNBR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PECR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJECR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLHR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLHR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PICR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJICR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNFR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNFR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPELR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSCR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(POHR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRBR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRCR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRLR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCXR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIER(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCXR(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIER(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900

    ALLOCATE(PNBS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNBS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJNBS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PECS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJECS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PLHS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJLHS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PICS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJICS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PNFS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SNFS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPELS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SPSCS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(POHS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRBS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRCS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PRLS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PCXS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PIES(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SCXS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(SIES(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJBSS(nsa_max),STAT=IERR); IF(IERR.NE.0) GOTO 900

    ALLOCATE(SSIN(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(VSIN(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(PSIN(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(AJIN(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(DD(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(VV(nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900
    ALLOCATE(CC(nsa_max,nsa_max,NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900

    ALLOCATE(DVRHO(NRMAX),STAT=IERR); IF(IERR.NE.0) GOTO 900

    nrmax_save = nrmax
    nsa_max_save = nsa_max
    RETURN

 900 CONTINUE
    WRITE(6,*) "XX  TICOMM ALLOCATION ERROR IERR=",ierr
    CALL deallocate_ticomm
    RETURN

  END SUBROUTINE allocate_ticomm


  SUBROUTINE deallocate_ticomm
    IMPLICIT NONE

    IF(ALLOCATED(ID_NSA   ))     DEALLOCATE(ID_NSA   )
    IF(ALLOCATED(NSA_UP   ))     DEALLOCATE(NSA_UP   )
    IF(ALLOCATED(PMA      ))     DEALLOCATE(PMA      )
    IF(ALLOCATED(PZA      ))     DEALLOCATE(PZA      )
    IF(ALLOCATED(RNA      ))     DEALLOCATE(RNA      )
    IF(ALLOCATED(RTA      ))     DEALLOCATE(RTA      )
    IF(ALLOCATED(RUA      ))     DEALLOCATE(RUA      )
    IF(ALLOCATED(RBP      ))     DEALLOCATE(RBP      )
    IF(ALLOCATED(RQP      ))     DEALLOCATE(RQP      )
    IF(ALLOCATED(RJP      ))     DEALLOCATE(RJP      )

    IF(ALLOCATED(RM       ))     DEALLOCATE(RM       )
    IF(ALLOCATED(RG       ))     DEALLOCATE(RG       )

    IF(ALLOCATED(ZEFF     ))     DEALLOCATE(ZEFF     )
    IF(ALLOCATED(BETA     ))     DEALLOCATE(BETA     )
    IF(ALLOCATED(BETAP    ))     DEALLOCATE(BETAP    )

    IF(ALLOCATED(AKTB     ))     DEALLOCATE(AKTB     )
    IF(ALLOCATED(ADTB     ))     DEALLOCATE(ADTB     )
    IF(ALLOCATED(AVTB     ))     DEALLOCATE(AVTB     )
    IF(ALLOCATED(AKNC     ))     DEALLOCATE(AKNC     )
    IF(ALLOCATED(ADNC     ))     DEALLOCATE(ADNC     )
    IF(ALLOCATED(AVNC     ))     DEALLOCATE(AVNC     )

    IF(ALLOCATED(PNB      ))     DEALLOCATE(PNB      )
    IF(ALLOCATED(SNB      ))     DEALLOCATE(SNB      )
    IF(ALLOCATED(AJNB     ))     DEALLOCATE(AJNB     )
    IF(ALLOCATED(PEC      ))     DEALLOCATE(PEC      )
    IF(ALLOCATED(AJEC     ))     DEALLOCATE(AJEC     )
    IF(ALLOCATED(PLH      ))     DEALLOCATE(PLH      )
    IF(ALLOCATED(AJLH     ))     DEALLOCATE(AJLH     )
    IF(ALLOCATED(PIC      ))     DEALLOCATE(PIC      )
    IF(ALLOCATED(AJIC     ))     DEALLOCATE(AJIC     )
    IF(ALLOCATED(PNF      ))     DEALLOCATE(PNF      )
    IF(ALLOCATED(SNF      ))     DEALLOCATE(SNF      )
    IF(ALLOCATED(SPEL     ))     DEALLOCATE(SPEL     )
    IF(ALLOCATED(SPSC     ))     DEALLOCATE(SPSC     )
    IF(ALLOCATED(POH      ))     DEALLOCATE(POH      )
    IF(ALLOCATED(PRB      ))     DEALLOCATE(PRB      )
    IF(ALLOCATED(PRC      ))     DEALLOCATE(PRC      )
    IF(ALLOCATED(PRL      ))     DEALLOCATE(PRL      )
    IF(ALLOCATED(PCX      ))     DEALLOCATE(PCX      )
    IF(ALLOCATED(PIE      ))     DEALLOCATE(PIE      )
    IF(ALLOCATED(SCX      ))     DEALLOCATE(SCX      )
    IF(ALLOCATED(SIE      ))     DEALLOCATE(SIE      )
    IF(ALLOCATED(AJBS     ))     DEALLOCATE(AJBS     )

    IF(ALLOCATED(AJR      ))     DEALLOCATE(AJR      )
    IF(ALLOCATED(AJOHR    ))     DEALLOCATE(AJOHR    )
    IF(ALLOCATED(EZOHR    ))     DEALLOCATE(EZOHR    )
    IF(ALLOCATED(QPR      ))     DEALLOCATE(QPR      )
    IF(ALLOCATED(AJCDR    ))     DEALLOCATE(AJCDR    )
    IF(ALLOCATED(AJBSR    ))     DEALLOCATE(AJBSR    )

    IF(ALLOCATED(PNBR     ))     DEALLOCATE(PNBR     )
    IF(ALLOCATED(SNBR     ))     DEALLOCATE(SNBR     )
    IF(ALLOCATED(AJNBR    ))     DEALLOCATE(AJNBR    )
    IF(ALLOCATED(PECR     ))     DEALLOCATE(PECR     )
    IF(ALLOCATED(AJECR    ))     DEALLOCATE(AJECR    )
    IF(ALLOCATED(PLHR     ))     DEALLOCATE(PLHR     )
    IF(ALLOCATED(AJLHR    ))     DEALLOCATE(AJLHR    )
    IF(ALLOCATED(PICR     ))     DEALLOCATE(PICR     )
    IF(ALLOCATED(AJICR    ))     DEALLOCATE(AJICR    )
    IF(ALLOCATED(PNFR     ))     DEALLOCATE(PNFR     )
    IF(ALLOCATED(SNFR     ))     DEALLOCATE(SNFR     )
    IF(ALLOCATED(SPELR    ))     DEALLOCATE(SPELR    )
    IF(ALLOCATED(SPSCR    ))     DEALLOCATE(SPSCR    )
    IF(ALLOCATED(POHR     ))     DEALLOCATE(POHR     )
    IF(ALLOCATED(PRBR     ))     DEALLOCATE(PRBR     )
    IF(ALLOCATED(PRCR     ))     DEALLOCATE(PRCR     )
    IF(ALLOCATED(PRLR     ))     DEALLOCATE(PRLR     )
    IF(ALLOCATED(PCXR     ))     DEALLOCATE(PCXR     )
    IF(ALLOCATED(PIER     ))     DEALLOCATE(PIER     )
    IF(ALLOCATED(SCXR     ))     DEALLOCATE(SCXR     )
    IF(ALLOCATED(SIER     ))     DEALLOCATE(SIER     )

    IF(ALLOCATED(PNBS     ))     DEALLOCATE(PNBS     )
    IF(ALLOCATED(SNBS     ))     DEALLOCATE(SNBS     )
    IF(ALLOCATED(AJNBS    ))     DEALLOCATE(AJNBS    )
    IF(ALLOCATED(PECS     ))     DEALLOCATE(PECS     )
    IF(ALLOCATED(AJECS    ))     DEALLOCATE(AJECS    )
    IF(ALLOCATED(PLHS     ))     DEALLOCATE(PLHS     )
    IF(ALLOCATED(AJLHS    ))     DEALLOCATE(AJLHS    )
    IF(ALLOCATED(PICS     ))     DEALLOCATE(PICS     )
    IF(ALLOCATED(AJICS    ))     DEALLOCATE(AJICS    )
    IF(ALLOCATED(PNFS     ))     DEALLOCATE(PNFS     )
    IF(ALLOCATED(SNFS     ))     DEALLOCATE(SNFS     )
    IF(ALLOCATED(SPELS    ))     DEALLOCATE(SPELS    )
    IF(ALLOCATED(SPSCS    ))     DEALLOCATE(SPSCS    )
    IF(ALLOCATED(POHS     ))     DEALLOCATE(POHS     )
    IF(ALLOCATED(PRBS     ))     DEALLOCATE(PRBS     )
    IF(ALLOCATED(PRCS     ))     DEALLOCATE(PRCS     )
    IF(ALLOCATED(PRLS     ))     DEALLOCATE(PRLS     )
    IF(ALLOCATED(PCXS     ))     DEALLOCATE(PCXS     )
    IF(ALLOCATED(PIES     ))     DEALLOCATE(PIES     )
    IF(ALLOCATED(SCXS     ))     DEALLOCATE(SCXS     )
    IF(ALLOCATED(SIES     ))     DEALLOCATE(SIES     )
    IF(ALLOCATED(AJBSS    ))     DEALLOCATE(AJBSS    )

    IF(ALLOCATED(SSIN     ))     DEALLOCATE(SSIN     )
    IF(ALLOCATED(VSIN     ))     DEALLOCATE(VSIN     )
    IF(ALLOCATED(PSIN     ))     DEALLOCATE(PSIN     )
    IF(ALLOCATED(AJIN     ))     DEALLOCATE(AJIN     )
    IF(ALLOCATED(DD       ))     DEALLOCATE(DD       )
    IF(ALLOCATED(VV       ))     DEALLOCATE(VV       )

    nrmax_save=0
    nsa_max_save=0
    RETURN

  END SUBROUTINE deallocate_ticomm

  SUBROUTINE allocate_neqmax(ierr)

    IMPLICIT NONE
    INTEGER,INTENT(OUT):: ierr
    ierr = 0

    IF(nrmax_save2==nrmax .AND. &
       neqmax_save==neqmax) RETURN

    IF(ALLOCATED(MAT_LOCAL)) CALL deallocate_neqmax

    ALLOCATE(NSA_NEQ(NEQMAX),NV_NEQ(NEQMAX),NEQ_NVNSA(3,0:nsa_max),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(MAT_LOCAL(NEQMAX,3*NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VEC_LOCAL(NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VEC_GLOBAL(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_BASE(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_PREV(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(SOL_NEW(NEQMAX*NRMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900
    ALLOCATE(VAL_EDGE(NEQMAX),STAT=IERR)
             IF(IERR.NE.0) GOTO 900

    nrmax_save2 = nrmax
    neqmax_save = neqmax

    RETURN
             
 900 CONTINUE
    WRITE(6,*) "XX  TICOMM NEQMAX ALLOCATION ERROR IERR=",ierr
    CALL deallocate_neqmax
    RETURN
  END SUBROUTINE allocate_neqmax

  SUBROUTINE deallocate_neqmax

    IMPLICIT NONE

    DEALLOCATE(NSA_NEQ,NV_NEQ,NEQ_NVNSA)
    DEALLOCATE(MAT_LOCAL,VEC_LOCAL,VEC_GLOBAL,SOL_BASE,SOL_PREV,SOL_NEW)
    DEALLOCATE(VAL_EDGE)

    RETURN
  END SUBROUTINE deallocate_neqmax

END MODULE ticomm
