MODULE TRCOM0
  IMPLICIT NONE

! TRCOM0
  INTEGER(4)  :: NEQMAXM, NVM, MWM, MLM, NRMP, NGLF, NRMU, LDAB
  INTEGER(4)  :: NRMAX, NSMAX, NSZMAX, NSNMAX
  INTEGER(4)  :: NRMAX_OLD=0, NSMAX_OLD=0, NSZMAX_OLD=0, NSNMAX_OLD=0
  INTEGER(4)  :: NRM=80, NSM=4, NSZM=2, NSNM=2
  INTEGER(4), PARAMETER :: NTM =10001, NGM=1001, NFM=2
  INTEGER(4), PARAMETER :: NCGM=23, NCTM=107, NSTM=8, NEQM=3*NSTM+1
  INTEGER(4), PARAMETER :: NLM =1001, NTUM=1001

END MODULE TRCOM0