MODULE TRCOM0
  IMPLICIT NONE

! TRCOM0
  INTEGER(4)  :: NEQMAXM, NVM, MWM, MLM, NRMP, NGLF, LDAB
  INTEGER(4)  :: NRMAX, NSMAX, NSZMAX, NSNMAX
  INTEGER(4)  :: NRMAX_OLD=0, NSMAX_OLD=0, NSZMAX_OLD=0, NSNMAX_OLD=0
  INTEGER(4), PARAMETER :: NSMM=100 ! Max number of species for namelist input
  INTEGER(4), PARAMETER :: NSM=4, NSZM=2, NSNM=2
  INTEGER(4), PARAMETER :: NTM =10001, NGM=1001, NFM=2
  INTEGER(4), PARAMETER :: NCGM=23, NCTM=110, NCRTM=67, NSTM=8
  INTEGER(4), PARAMETER :: NEQM=3*NSTM+1
  INTEGER(4), PARAMETER :: NLM =1001
  INTEGER(4), PARAMETER :: NTUM=1001, NRUM=102   ! Size of ufile data

END MODULE TRCOM0
