MODULE grf2dexec

  PRIVATE
  PUBLIC grf2d_exec

CONTAINS

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2D_EXEC(GX,GY,GF,NXM,NXMAX,NYMAX,A)

    USE grftype, ONLY: grf_attr_type
    USE grfutils, ONLY: grf_title, grf_frame
    IMPLICIT NONE

    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX
    TYPE(grf_attr_type),INTENT(IN):: A

    CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                A%XMIN,A%XMAX,A%YMIN,A%YMAX)

    CALL SETLNW(A%LINE_THICKNESS(1))
    CALL CONTF2(GF,GX,GY,NXM,NXMAX,NYMAX, &
                A%LINE_VALUE,A%LINE_RGB,A%NLMAX,A%MODE_PRD)

    IF(A%NOFRAME.EQ.0) CALL GRF_FRAME(A)
    IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)

    CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2D_EXEC

END MODULE grf2dexec
