MODULE grf2dexec

  PRIVATE
  PUBLIC grf2d_exec

CONTAINS

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2D_EXEC(GX,GY,GF,NXM,NXMAX,NYMAX,A)

    USE grftype, ONLY: grf_attr_type
    USE grfutils, ONLY: grf_title, grf_frame
    IMPLICIT NONE

    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX),GF(NXM,NYMAX)
    INTEGER,INTENT(IN):: NXM,NXMAX,NYMAX
    TYPE(grf_attr_type),INTENT(IN):: A

    CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                A%XMIN,A%XMAX,A%YMIN,A%YMAX)

    CALL SETLNW(A%LINE_THICKNESS(1))
    CALL CONTF2(GF,GX,GY,NXM,NXMAX,NYMAX, &
                A%LINE_VALUE,A%LINE_RGB,A%NLMAX,A%MODE_PRD)

    IF(A%NOFRAME.EQ.0) CALL GRF_FRAME(A)
    IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)

    CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2D_EXEC

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DAX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,MODE_LS,IPRD)

    IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      CHARACTER STR*(*),KT*80,KDL*1
      DIMENSION GZL(101),GRGB(3,101)

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      CALL GDEFIN(GP(1),GP(2),GP(3),GP(4), &
                  GXMIN,GXMAX,GYMIN,GYMAX)

      NSTEP=NINT(ABS((GFMAX-GFMIN)/GFSTEP))+1
      IF(NSTEP.GT.101) NSTEP=101
      GFSTEPL=(GFMAX-GFMIN)/(NSTEP-1)
      DO I=1,NSTEP
         GZL(I)=GFMIN+GFSTEPL*(I-1)
      ENDDO

      IF(GFMIN*GFMAX.GE.0.D0) THEN
         IF(GFORG.GE.0.D0) THEN
            DO I=1,NSTEP
               GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
               CALL R2Y2W(GFACTOR,GRGB(1,I))
            ENDDO
            CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRGB,NSTEP,IPRD)
         ELSE
            DO I=1,NSTEP
               GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
               CALL W2G2B(GFACTOR,GRGB(1,I))
            ENDDO
            CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRBG,NSTEP,IPRD)
         ENDIF
      ELSE
         DO I=1,NSTEP
            GFACTOR=FLOAT(I-1)/FLOAT(NSTEP-1)
            CALL R2W2B(GFACTOR,GRGB(1,I))
         ENDDO
         CALL CONTF2(GZ,GX,GY,NXM,NXMAX,NYMAX,GZL,GRGB,NSTEP,IPRD)
      ENDIF

      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.2) THEN
         CALL GSCALE(0.0,2*(GXMAX-GXMIN),0.0,0.0,0.0,0)
         CALL GSCALE(GXORG,GXSTEP,0.0,0.0,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      ELSE
         CALL GSCALL(GXORG,9,0.0,0,0.1,9)
         CALL GVALUL(GXORG,1,0.0,0,NGULEN(2*GXSTEP))
      ENDIF
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.1) THEN
         CALL GSCALE(0.0,0.0,0.0,2*(GYMAX-GYMIN),0.0,0)
         CALL GSCALE(0.0,0.0,GYORG,GYSTEP,0.1,9)
         CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALL(0.0,0,GYORG,9,0.1,9)
         CALL GVALUL(0.0,0,GYORG,1,NGULEN(2*GYSTEP))
      ENDIF

      CALL MOVE(0.5*(GP(1)+GP(2))-0.2*32*GFACTOR,GP(3)-1.5*GFACTOR)
      CALL TEXT('MIN  =',6)
      CALL NUMBR(GFMIN ,'(1PE12.4)',12)
      CALL TEXT('     MAX  =',11)
      CALL NUMBR(GFMAX ,'(1PE12.4)',12)
      CALL TEXT('     STEP =',11)
      CALL NUMBR(GFSTEP,'(1PE12.4)',12)

      CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2DAX

!     ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DB(NGP,GX,GY,GZ,NXM,NXMAX,NYMAX,STR)

    USE grfutils,ONLY: grfut1,grfut2,grfut3,grfut4
    IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION GP3D(6)
      CHARACTER STR*(*)

      IF(NGP.LT.0.OR.NGP.GT.29) THEN
         WRITE(6,*) 'XX GRF2DB: INVALID NGP'
         RETURN
      ENDIF
      CALL GRFUT4(NGP,GP)

      GP3D(1)=10.0*1.5
      GP3D(2)=20.0*1.5
      GP3D(3)=10.0*1.5
      GP3D(4)=-60.0
      GP3D(5)=65.0
      GP3D(6)=100.0

      CALL GRFUT1(GX,NXMAX,GXMIN,GXMAX)
      CALL GRFUT1(GY,NYMAX,GYMIN,GYMAX)
      CALL GRFUT2(GZ,NXM,NXMAX,NYMAX,GFMIN,GFMAX)

      CALL GRFUT3(GXMIN,GXMAX,GSXMIN,GSXMAX,GXSTEP,GXORG)
      CALL GRFUT3(GYMIN,GYMAX,GSYMIN,GSYMAX,GYSTEP,GYORG)
      CALL GRFUT3(GFMIN,GFMAX,GSFMIN,GSFMAX,GFSTEP,GFORG)

      CALL GRF2DBX(GP, &
                   GXMIN,GXMAX,GXSTEP,GXORG, &
                   GYMIN,GYMAX,GYSTEP,GYORG, &
                   GFMIN,GFMAX,GFSTEP,GFORG, &
                   GX,GY,GZ,NXM,NXMAX,NYMAX, &
                   STR,GP3D)
    RETURN
  END SUBROUTINE GRF2DB

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DBX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,GP3D)

    IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION GP3D(6)
      CHARACTER STR*(*),KT*80,KDL*1
      EXTERNAL R2W2B,W2G2B,R2Y2W

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      GXL    =GP3D(1)
      GYL    =GP3D(2)
      GZL    =GP3D(3)
      GPHI   =GP3D(4)
      GTHETA =GP3D(5)
      GRADIUS=GP3D(6)
      GOX=0.5*(GXMIN+GXMAX)
      GOY=0.5*(GYMIN+GYMAX)
      GOZ=0.5*(GFMIN+GFMAX)

      CALL GDEFIN3D(GP(1),GP(2),GP(3),GP(4),GXL,GYL,GZL)
      CALL GVIEW3D(GPHI,GTHETA,GRADIUS,1.0,1,GOX,GOY,GOZ)
      CALL GDATA3D1(GZ,NXM,NXMAX,NYMAX, &
                    GXMIN,GXMAX,GYMIN,GYMAX,GFMIN,GFMAX)

      CALL SETCHS(0.2,0.0)
      CALL SETLIN(0,0,7)

      IF(NXMAX.GT.100.OR.NYMAX.GT.100) THEN
         ID=4
      ELSE
         ID=7
      ENDIF

      IF(GFMIN*GFMAX.LT.0.0) THEN
         CALL CPLOT3D1(ID,R2W2B)
      ELSEIF(GFMIN.LT.0.0) THEN
         CALL CPLOT3D1(ID,W2G2B)
      ELSE
         CALL CPLOT3D1(ID,R2Y2W)
      ENDIF
      CALL GAXIS3D(0)

      CALL SETLIN(0,0,7)
      CALL GSCALE3DX(GXORG,GXSTEP,0.3,0)
      CALL GSCALE3DY(GYORG,GYSTEP,0.3,0)
      CALL GSCALE3DZ(GFORG,GFSTEP,0.3,0)
      CALL GVALUE3DX(GXORG,2*GXSTEP,1,NGULEN(2*GXSTEP))
      CALL GVALUE3DY(GYORG,2*GYSTEP,1,NGULEN(2*GYSTEP))
      CALL GVALUE3DZ(GFORG,2*GFSTEP,2,NGULEN(2*GFSTEP))
    RETURN
  END SUBROUTINE GRF2DBX

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DC(NGP,GX,GY,GZ,NXM,NXMAX,NYMAX,STR,MODE_LS)

    USE grfutils,ONLY: grfut1,grfut2,grfut3,grfut4
    IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      CHARACTER STR*(*)

      IF(NGP.LT.0.OR.NGP.GT.29) THEN
         WRITE(6,*) 'XX GRF2DC: INVALID NGP'
         RETURN
      ENDIF
      CALL GRFUT4(NGP,GP)

      CALL GRFUT1(GX,NXMAX,GXMIN,GXMAX)
      CALL GRFUT1(GY,NYMAX,GYMIN,GYMAX)
      CALL GRFUT2(GZ,NXM,NXMAX,NYMAX,GFMIN,GFMAX)

      CALL GRFUT3(GXMIN,GXMAX,GSXMIN,GSXMAX,GXSTEP,GXORG)
      CALL GRFUT3(GYMIN,GYMAX,GSYMIN,GSYMAX,GYSTEP,GYORG)
      CALL GRFUT3(GFMIN,GFMAX,GSFMIN,GSFMAX,GFSTEP,GFORG)
      GFSTEP=0.2*GFSTEP

      CALL GRF2DCX(GP, &
                   GXMIN,GXMAX,GXSTEP,GXORG, &
                   GYMIN,GYMAX,GYSTEP,GYORG, &
                   GFMIN,GFMAX,GFSTEP,GFORG, &
                   GX,GY,GZ,NXM,NXMAX,NYMAX, &
                   STR,MODE_LS)

    RETURN
  END SUBROUTINE GRF2DC

! ***** DRAW 2D GRAPH *****

  SUBROUTINE GRF2DCX(GP, &
                         GXMIN,GXMAX,GXSTEP,GXORG, &
                         GYMIN,GYMAX,GYSTEP,GYORG, &
                         GFMIN,GFMAX,GFSTEP,GFORG, &
                         GX,GY,GZ,NXM,NXMAX,NYMAX, &
                         STR,MODE_LS)

    IMPLICIT REAL*8 (A-F,H,O-Z)

      DIMENSION GP(4),GX(NXMAX),GY(NYMAX),GZ(NXM,NYMAX)
      DIMENSION KA(8,NXM,NYMAX)
      CHARACTER STR*(*),KT*80,KDL*1

      GL=GP(2)-GP(1)
      IF(GL.GT.7.9) then
         GFACTOR=1.0
      ELSEIF(GL.GT.7.9*0.666) then
         GFACTOR=0.666
      ELSE
         GFACTOR=0.5
      ENDIF

      CALL SETCHS(0.3*GFACTOR,0.0)
      CALL SETFNT(32)
      CALL SETLNW(0.035*GFACTOR)
      CALL SETRGB(0.0,0.0,0.0)

      KDL=STR(1:1)
      I=2
    1 IF(STR(I:I).EQ.KDL.OR.I.EQ.LEN(STR)) GOTO 2
         KT(I-1:I-1)=STR(I:I)
         I=I+1
      GOTO 1

    2 CALL MOVE(GP(1),GP(4)+0.3)
      CALL TEXT(KT,I-2)

      CALL GDEFIN(GP(1),GP(2),GP(3),GP(4), &
                  GXMIN,GXMAX,GYMIN,GYMAX)

      IF(GFMIN*GFMAX.GE.0.D0) THEN
         NSTEP=NINT(ABS((GFMAX-GFMIN)/GFSTEP))+1
         IF(GFORG.GE.0.D0) THEN
            CALL SETRGB(1.0,0.0,0.0)
            CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                        GFORG,GFSTEP,NSTEP,0,0,KA)
         ELSE
            CALL SETRGB(0.0,0.0,1.0)
            CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                        GFORG,GFSTEP,NSTEP,0,3,KA)
         ENDIF
      ELSE
         CALL SETRGB(1.0,0.0,0.0)
         NSTEP=NINT(ABS(GFMAX/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     GFSTEP,GFSTEP,NSTEP,0,0,KA)
         CALL SETRGB(0.0,1.0,0.0)
         NSTEP=NINT(ABS(GFMAX/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     0.0,GFSTEP,1,0,0,KA)
         CALL SETRGB(0.0,0.0,1.0)
         NSTEP=NINT(ABS(GFMIN/GFSTEP))+1
         CALL CONTQ2(GZ,GX,GY,NXM,NXMAX,NYMAX, &
                     -GFSTEP,-GFSTEP,NSTEP,0,3,KA)
      ENDIF

      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME

      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.2) THEN
         CALL GSCALE(0.0,2*(GXMAX-GXMIN),0.0,0.0,0.0,0)
         CALL GSCALE(GXORG,GXSTEP,0.0,0.0,0.1,9)
         CALL GVALUE(GXORG,2*GXSTEP,0.0,0.0,NGULEN(2*GXSTEP))
      ELSE
         CALL GSCALL(GXORG,9,0.0,0,0.1,9)
         CALL GVALUL(GXORG,1,0.0,0,NGULEN(2*GXSTEP))
      ENDIF
      IF(MODE_LS.EQ.0.OR.MODE_LS.EQ.1) THEN
         CALL GSCALE(0.0,0.0,0.0,2*(GYMAX-GYMIN),0.0,0)
         CALL GSCALE(0.0,0.0,GYORG,GYSTEP,0.1,9)
         CALL GVALUE(0.0,0.0,GYORG,2*GYSTEP,NGULEN(2*GYSTEP))
      ELSE
         CALL GSCALL(0.0,0,GYORG,9,0.1,9)
         CALL GVALUL(0.0,0,GYORG,1,NGULEN(2*GYSTEP))
      ENDIF

      CALL MOVE(0.5*(GP(1)+GP(2))-0.2*32*GFACTOR,GP(3)-1.5*GFACTOR)
      CALL TEXT('MIN  =',6)
      CALL NUMBR(GFMIN ,'(1PE12.4)',12)
      CALL TEXT('     MAX  =',11)
      CALL NUMBR(GFMAX ,'(1PE12.4)',12)
      CALL TEXT('     STEP =',11)
      CALL NUMBR(GFSTEP,'(1PE12.4)',12)

      CALL SETRGB(0.0,0.0,0.0)
    RETURN
  END SUBROUTINE GRF2DCX
END MODULE grf2dexec
