MODULE grfxyexec

  PRIVATE
  PUBLIC grfxy_exec

CONTAINS

! ***** DRAW 2D trajectory *****

  SUBROUTINE GRFXY_EXEC(GX,GY,GD,NXMAX,NYMAX,NDIM,NTM,NTMAX,NDMAX,A, &
                        LINE_RGB_SUB,PAINT_RGB_SUB)

    USE grftype, ONLY: grf_attr_type
    USE grfutils, ONLY: grf_title, grf_frame2d, grf_frame3d ,grf_info,setrgba
    IMPLICIT NONE

    INTEGER,INTENT(IN):: NXMAX,NYMAX
    INTEGER,INTENT(IN):: NDIM,NTM,NDMAX,NTMAX(NDMAX)
    REAL(4),INTENT(IN):: GX(NXMAX),GY(NYMAX)
    REAL(4),INTENT(IN):: GD(NDIM,NTM,NDMAX)
    REAL(4):: line_width
    TYPE(grf_attr_type),INTENT(IN):: A
    INTERFACE
       SUBROUTINE LINE_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE LINE_RGB_SUB
       SUBROUTINE PAINT_RGB_SUB(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE PAINT_RGB_SUB
    END INTERFACE
    OPTIONAL LINE_RGB_SUB,PAINT_RGB_SUB

    INTEGER(4),DIMENSION(:,:),ALLOCATABLE:: KA
    REAL(4):: FSTEP
    INTEGER(4):: ND,NT,NL
    INTERFACE
       SUBROUTINE R2W2B(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT)::RGB
       END SUBROUTINE R2W2B
       SUBROUTINE W2G2B(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE W2G2B
       SUBROUTINE R2Y2W(VALUE,RGB)
         REAL(4),INTENT(IN):: VALUE
         REAL(4),DIMENSION(3),INTENT(OUT):: RGB
       END SUBROUTINE R2Y2W
    END INTERFACE

    CALL INQLNW(line_width)

    SELECT CASE(A%MODE_2D)
    CASE(21) ! 2D trajectory

       CALL GDEFIN(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX, &
                   A%XMIN,A%XMAX,A%YMIN,A%YMAX)
       CALL SETCLP(A%GPXMIN,A%GPXMAX,A%GPYMIN,A%GPYMAX)

       DO ND=1,NDMAX
          NL=MOD(ND-1,A%NLMAX)+1
          CALL SETRGB(A%LINE_RGB(1,NL),A%LINE_RGB(2,NL),A%LINE_RGB(3,NL))
          CALL SETLNW(A%LINE_THICKNESS(NL))
          CALL MOVE2D(GD(1,1,ND),GD(2,1,ND))
          DO NT=2,NTMAX(ND)
             CALL DRAW2D(GD(1,NT,ND),GD(2,NT,ND))
          END DO
       END DO
       CALL OFFCLP

       IF(A%NOFRAME.EQ.0) CALL GRF_FRAME2D(A)
       IF(A%NOTITLE.EQ.0) CALL GRF_TITLE(A)
       IF(A%NOINFO.EQ.0)  CALL GRF_INFO(A)

    END SELECT
    CALL SETRGB(0.0,0.0,0.0)
    CALL SETLNW(line_width)
    RETURN
  END SUBROUTINE GRFXY_EXEC

END MODULE grfxyexec
