C     $Id$

C*********************** GRAPHIC DATA ************************
C
      SUBROUTINE WRGOUT
C
      INCLUDE 'wrcomm.h'
C
      CHARACTER KID*1
C
    1 WRITE(6,*)'INPUT GRAPH TYPE : 1,2,3,4,5,6  X'
      READ(5,'(A1)',ERR=1,END=9000) KID
      CALL GUCPTL(KID)
C
      IF(KID.EQ.'1') CALL WRGRFA
      IF(KID.EQ.'2') CALL WRGRFB
      IF(KID.EQ.'3') CALL WRGRFC
      IF(KID.EQ.'4') CALL WRGRFD
      IF(KID.EQ.'5') CALL WRGRFE
      IF(KID.EQ.'6') CALL WRGRFF
      IF(KID.EQ.'X') GOTO 9000
C
      GOTO 1
C
 9000 RETURN
      END
C
C     ***** POLOIDAL TRAJECTORY AND POWER *****
C
      SUBROUTINE WRGRFA
C
      INCLUDE 'wrcomm.h'
C
      PARAMETER(NSUM=201)
      PARAMETER(NGXL=101,NGYL=101)
C
      DIMENSION RSU(NSUM),ZSU(NSUM)
      DIMENSION GRS(NSUM),GZS(NSUM)
      DIMENSION GX(NITM+1),GY(NITM+1)
      DIMENSION GUX(NITM+1),GUY(NITM+1)
      DIMENSION GPX(NITM+1),GPY(NITM+1,NRAYM)
      DIMENSION GCF(NGXL,NGYL),GCX(NGXL),GCY(NGYL)
      DIMENSION KA(2,NGXL,NGYL)
C
C     ----- PLASMA BOUNDARY -----
C
      CALL PLRZSU(RSU,ZSU,NSUM,NSUMAX)
      DO NSU=1,NSUMAX
         GRS(NSU)=GUCLIP(RSU(NSU))
         GZS(NSU)=GUCLIP(ZSU(NSU))
      ENDDO
C
      CALL GMNMX1(GRS,1,NSUMAX,1,GRSMIN,GRSMAX)
      CALL GMNMX1(GZS,1,NSUMAX,1,GZSMIN,GZSMAX)
      CALL GQSCAL(GRSMIN,GRSMAX,GRMIN,GRMAX,GRSTEP)
      CALL GQSCAL(GZSMIN,GZSMAX,GZMIN,GZMAX,GZSTEP)
      GRORG=GRMIN+GRSTEP
C
      GRLEN=GRMAX-GRMIN
      GZLEN=GZMAX-GZMIN
      IF(1.5*GRLEN.GT.GZLEN) THEN
         GZMID=0.5*(GZMIN+GZMAX)
         GZMIN=GZMID-0.75*GRLEN
         GZMAX=GZMID+0.75*GRLEN
C         CALL GDEFIN(1.5,11.5,1.0,16.0,
C     &               GRMIN,GRMAX,GZMID-0.75*GRLEN,GZMID+0.75*GRLEN)
         
      ELSE
         GRMID=0.5*(GRMIN+GRMAX)
         GRMIN=GRMID-0.333*GZLEN
         GRMAX=GRMID+0.333*GZLEN
C         CALL GDEFIN(1.5,11.5,1.0,16.0,
C     &               GRMID-0.333*GZLEN,GRMID+0.333*GZLEN,GZMIN,GZMAX)
      ENDIF
         CALL GDEFIN(1.5,11.5,1.0,16.0,GRMIN,GRMAX,GZMIN,GZMAX)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(GRORG,  GRSTEP,0.0,  GZSTEP,0.1,9)
      CALL GVALUE(GRORG,2*GRSTEP,0.0,2*GZSTEP,1)
      CALL SETLIN(0,0,4)
      CALL GPLOTP(GRS,GZS,1,NSUMAX,1,0,0,0)
C
      IF(MODELG.EQ.3) THEN
         DGX=DBLE(GRMAX-GRMIN)/(NGXL-1)
         DO NGX=1,NGXL
            GCX(NGX)=GRMIN+(NGX-1)*GUCLIP(DGX)
         ENDDO
         DGY=DBLE(GZMAX-GZMIN)/(NGYL-1)
         DO NGY=1,NGYL
            GCY(NGY)=GZMIN+(NGY-1)*GUCLIP(DGY)
         ENDDO
         DO NGY=1,NGYL
            ZL=DBLE(GCY(NGY))
            DO NGX=1,NGXL
               RL=DBLE(GCX(NGX))
               CALL PLMAG(RL,0.D0,ZL,PSIN)
               GCF(NGX,NGY)=GUCLIP(PSIN)
            ENDDO
         ENDDO
         CALL CONTP2(GCF,GCX,GCY,NGXL,NGXL,NGYL,
     &               0.1,0.1,9,0,1,KA)
      ENDIF
C
C     ----- RAY TRAJECTORY -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            RL=SQRT(RAYS(1,IT,NRAY)**2+RAYS(2,IT,NRAY)**2)
            GX(IT+1)=GUCLIP(RL)
            GY(IT+1)=GUCLIP(RAYS(3,IT,NRAY))
         ENDDO
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
C     ----- CALCULATE RADIAL DEPOSITION PROFILE -----
C
      DRHO=1.D0/NRZMAX
      DO NRZ=1,NRZMAX
         GPX(NRZ)=GUCLIP(NRZ*DRHO)
      ENDDO
      DO NRAY=1,NRAYMX
         DO NRZ=1,NRZMAX
            GPY(NRZ,NRAY)=0.0
         ENDDO
      ENDDO
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)-1
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN1)
            RHO1=SQRT(PSIN1)
	    NRS1=INT(RHO1/DRHO)+1
            XL=RAYS(1,IT+1,NRAY)
            YL=RAYS(2,IT+1,NRAY)
            ZL=RAYS(3,IT+1,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN2)
            RHO2=SQRT(PSIN2)
            NRS2=INT(RHO2/DRHO)+1
            NDR=ABS(NRS2-NRS1)
            IF(NDR.EQ.0) THEN
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)+GUCLIP(RAYS(8,IT+1,NRAY))
            ELSE IF(NRS1.LT.NRS2) THEN
               SDR=(RHO2-RHO1)/DRHO
               DELP=RAYS(8,IT+1,NRAY)/SDR
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)
     &                       +GUCLIP((DBLE(NRS1)-RHO1/DRHO)*DELP)
               DO NR=NRS1+1,NRS2-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELP)
               ENDDO
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY)
     &                       +GUCLIP((RHO2/DRHO-DBLE(NRS2-1))*DELP)
            ELSE
               SDR=(RHO1-RHO2)/DRHO
               DELP=RAYS(8,IT+1,NRAY)/SDR
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY)
     &                       +GUCLIP((DBLE(NRS2)-RHO2/DRHO)*DELP)
               DO NR=NRS2+1,NRS1-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELP)
               ENDDO
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)
     &                       +GUCLIP((RHO1/DRHO-DBLE(NRS1-1))*DELP)
            ENDIF
         ENDDO
C         WRITE(6,'(5(I3,1PE12.4))') (NRZ,GPY(NRZ,NRAY),NRZ=1,NRZMAX)
      ENDDO
C
      DO NRAY=1,NRAYMX
      DO NRZ=1,NRZMAX
         GPY(NRZ,NRAY)=GPY(NRZ,NRAY)
     &                 /GUCLIP(2*PI*(DBLE(NRZ)-0.5D0)*DRHO*DRHO)
      ENDDO
C         WRITE(6,'(5(I3,1PE12.4))') (NRZ,GPY(NRZ,NRAY),NRZ=1,NRZMAX)
      ENDDO
c
c     ----- draw deposition profile -----
c
      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
c
      CALL GMNMX2(GPY,NITM+1,1,NRZMAX,1,1,NRAYMX,1,GYMIN,GYMAX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMIN,GYSMAX1,GYSCAL1)
      GYSMIN=0.0
      GYSMAX2=0.1 
      GYSCAL2=2.E-2
      GYSMAX=MAX(GYSMAX1,GYSMAX2)
      GYSCAL=MAX(GYSCAL1,GYSCAL2)
C
      CALL MOVE(13.5,16.1)
      CALL TEXT('ABS POWER',10)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,GYSMIN,GYSMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYSMIN,GYSCAL,0.1,9)      
      CALL GVALUE(0.0,2*GXSTEP,GYSMIN,GYSCAL,2)
      CALL SETLIN(0,0,4)
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GPX,GPY(1,NRAY),1,NRZMAX,1,0,0,0)
      ENDDO
C
C     ----- DRAW POWER FLUX -----
C      
      GZSMIN=0.0
      GZSMAX=1.1
      GZSCAL=0.2
C
      CALL MOVE(13.5,8.1)
      CALL TEXT('POWER FLUX',10)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,GZSMIN,GZSMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GZSMIN,GZSCAL,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GZSMIN,GZSCAL,1)
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN)
            RHO=SQRT(PSIN)
	    GUX(IT+1)=GUCLIP(RHO)
            GUY(IT+1)=GUCLIP(RAYS(7,IT,NRAY))
         ENDDO
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GUX,GUY,1,NITMAX(NRAY)+1,1,0,0,0)      
      ENDDO
C
      CALL WRGPRM
      CALL PAGEE
      RETURN
      END
C
C     ***** RADIAL DEPENDENCE 1 *****
C
      SUBROUTINE WRGRFB
C
      INCLUDE 'wrcomm.h'
C
      PARAMETER(NSUM=101)
      DIMENSION GX(NITM+1),GY(NITM+1)
      DIMENSION GKX(NITM+1,NRAYM)
      DIMENSION GKY1(NITM+1,NRAYM),GKY2(NITM+1,NRAYM)
      DIMENSION GLCX(NSUM),GLCY(NSUM),GSCX(NSUM),GSCY(NSUM)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETLIN(0,0,7)
C
C     ----- TOLOIDAL CROSS SECTION -----
C
      NSUMAX=101
      RMAX=RR+RA
      RMIN=RR-RA
      DTH=2*PI/(NSUMAX-1)
      DO NSU=1,NSUMAX
         TH=DTH*(NSU-1)
         GLCX(NSU)=GUCLIP(RMAX*COS(TH))
         GLCY(NSU)=GUCLIP(RMAX*SIN(TH))
         GSCX(NSU)=GUCLIP(RMIN*COS(TH))
         GSCY(NSU)=GUCLIP(RMIN*SIN(TH))
      ENDDO
C      GRRMAX=GUCLIP(RMAX)
C      CALL GQSCAL(-GRRMAX,GRRMAX,GXMIN,GXMAX,GXSTEP)
C      CALL GQSCAL(-GRRMAX,GRRMAX,GYMIN,GYMAX,GYSTEP)
C
      CALL GQSCAL(GUCLIP(RR-RA),GUCLIP(RR+RA),GXMIN,GXMAX,GXSTEP)
      CALL GQSCAL(GUCLIP(  -RA),GUCLIP(   RA),GYMIN,GYMAX,GYSTEP)
C
      CALL GDEFIN(1.7,11.7,1.0,11.0,GXMIN,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
C      CALL GSCALE(0.0,GXSTEP,0.0,GYSTEP,0.1,9)
C      CALL GVALUE(0.0,2*GXSTEP,0.0,2*GYSTEP,1)
      CALL GSCALE(GXMIN,GXSTEP,0.0,GYSTEP,0.1,9)
      CALL GVALUE(GXMIN,2*GXSTEP,0.0,2*GYSTEP,1)
C
      CALL SETLIN(0,0,4)
      CALL GPLOTP(GLCX,GLCY,1,101,1,0,0,0)
      CALL GPLOTP(GSCX,GSCY,1,101,1,0,0,0)
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GX(IT+1)=GUCLIP(RAYS(1,IT,NRAY))
            GY(IT+1)=GUCLIP(RAYS(2,IT,NRAY))
         ENDDO
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GX,GY,1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
C     ----- WAVE NUMBER -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN)
            RHO=SQRT(PSIN)
            CALL WRCALK(IT,NRAY,RKPARA,RKPERP)
            GKX( IT+1,NRAY)=GUCLIP(RHO)
            GKY1(IT+1,NRAY)=GUCLIP(RKPARA)
            GKY2(IT+1,NRAY)=GUCLIP(RKPERP)
         ENDDO
      ENDDO
C
      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
      NRAY=1
         CALL GMNMX1(GKY1(1,NRAY),1,NITMAX(NRAY),1,GYMIN1,GYMAX1)
         CALL GMNMX1(GKY2(1,NRAY),1,NITMAX(NRAY),1,GYMIN2,GYMAX2)
      DO NRAY=2,NRAYMX
         CALL GMNMX1(GKY1(1,NRAY),1,NITMAX(NRAY),1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
         CALL GMNMX1(GKY2(1,NRAY),1,NITMAX(NRAY),1,GYMIN,GYMAX)
         GYMIN2=MIN(GYMIN2,GYMIN)
         GYMAX2=MAX(GYMAX2,GYMAX)
      ENDDO
C
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,16.1)
      CALL TEXT('k-para',6)
      CALL GDEFIN(13.7,23.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
C
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY1(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
      CALL GQSCAL(GYMIN2,GYMAX2,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.7,8.1)
      CALL TEXT('k-perp',6)
      CALL GDEFIN(13.7,23.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
C
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY2(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
      CALL WRGPRM
      CALL PAGEE
C
      RETURN
      END
C
C     ***** RADIAL DEPENDENCE 2 *****
C
      SUBROUTINE WRGRFC
C
      INCLUDE 'wrcomm.h'
C
      DIMENSION GKX(NITM+1,NRAYM)
      DIMENSION GKY(NITM+1,NRAYM)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETLIN(0,0,7)
C
C     ----- X AXIS -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN)
            RHO=SQRT(PSIN)
            GKX( IT+1,NRAY)=GUCLIP(RHO)
         ENDDO
      ENDDO
      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
C
C     ----- Fig.1 -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            RL=SQRT(RAYS(1,IT,NRAY)**2+RAYS(2,IT,NRAY)**2)
            RKR  =( RAYS(4,IT,NRAY)*RAYS(1,IT,NRAY)
     &             +RAYS(5,IT,NRAY)*RAYS(2,IT,NRAY))/RL
            GKY( IT+1,NRAY)=GUCLIP(RKR)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMX
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
C
      CALL MOVE(1.7,16.1)
      CALL TEXT('k-R',3)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
C     ----- Fig.2 -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            RKZ  =  RAYS(6,IT,NRAY)
            GKY( IT+1,NRAY)=GUCLIP(RKZ)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMX
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
C
      CALL MOVE(13.7,16.1)
      CALL TEXT('k-Z',3)
      CALL GDEFIN(13.7,23.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
C     ----- Fig.3 -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            RL=SQRT(RAYS(1,IT,NRAY)**2+RAYS(2,IT,NRAY)**2)
            RKPHI=(-RAYS(4,IT,NRAY)*RAYS(2,IT,NRAY)
     &             +RAYS(5,IT,NRAY)*RAYS(1,IT,NRAY))/RL
            GKY( IT+1,NRAY)=GUCLIP(RKPHI)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMX
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
C
      CALL MOVE(1.7,8.1)
      CALL TEXT('k-phi',5)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
C     ----- Fig.4 -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            RNPHI=(-RAYS(4,IT,NRAY)*RAYS(2,IT,NRAY)
     &             +RAYS(5,IT,NRAY)*RAYS(1,IT,NRAY))
            GKY( IT+1,NRAY)=GUCLIP(RNPHI)
         ENDDO
      ENDDO
      NRAY=1
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN1,GYMAX1)
      DO NRAY=2,NRAYMX
         CALL GMNMX1(GKY(1,NRAY),1,NITMAX(NRAY)+1,1,GYMIN,GYMAX)
         GYMIN1=MIN(GYMIN1,GYMIN)
         GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
C
      CALL MOVE(13.7,8.1)
      CALL TEXT('n-phi',5)
      CALL GDEFIN(13.7,23.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,2*GYSTEP,1)
      DO NRAY=1,NRAYMX
         CALL SETLIN(0,0,7-MOD(NRAY-1,5))
         CALL GPLOTP(GKX,GKY(1,NRAY),1,NITMAX(NRAY)+1,1,0,0,0)
      ENDDO
C
      CALL WRGPRM
      CALL PAGEE
      RETURN
      END
C
C     ***** BEAM AND POWER *****
C
      SUBROUTINE WRGRFD
C
      INCLUDE 'wrcomm.h'
C
      PARAMETER(NSUM=201)
C
      DIMENSION RSU(NSUM),ZSU(NSUM)
      DIMENSION GRS(NSUM),GZS(NSUM)
      DIMENSION GX(NITM+1),GY(NITM+1)
      DIMENSION GUX(NITM+1),GUY(NITM+1)
      DIMENSION GPX(NITM+1),GPY(NITM+1,NRAYM)
      DIMENSION GKX(NITM+1,2)
      DIMENSION GKY(NITM+1,2)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C     ----- X AXIS -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN)
            RHO=SQRT(PSIN)
C            WRITE(6,'(A,I5,1P5E12.4)') '!!',IT,XL,YL,ZL,PSIN,RHO
            GKX( IT+1,NRAY)=GUCLIP(RHO)
C            GKX( IT+1,NRAY)=GUCLIP(RAYB(0,IT))
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKX,1,NITMAX(1),1,GXMIN1,GXMAX1)
      CALL GQSCAL(0.0,GXMAX1,GXMIN,GXMAX,GXSTEP)
C
C     ----- Fig.1  R-CURV-----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKY( IT+1,1)=GUCLIP(RAYB(21,IT))
            GKY( IT+1,2)=GUCLIP(RAYB(22,IT))
         ENDDO
      ENDDO
C
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
      CALL MOVE(1.7,16.1)
      CALL TEXT('R-curv',6)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-6.0,6.0)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,2.0,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,2.0,1)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ----- Fig.3   R-BEAM-----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKY( IT+1,1)=GUCLIP(RAYB(23,IT))
            GKY( IT+1,2)=GUCLIP(RAYB(24,IT))
C           WRITE(6,*) GKY(IT+1,2),RAYB(24,IT)
         ENDDO
      ENDDO
C
      CALL MOVE(1.7,8.1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
      CALL TEXT('R-beam',6)
C      CALL GMNMX1(GKY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
C      CALL GMNMX1(GKY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C      GYMIN1=MIN(GYMINA,GYMINB)
C      GYMAX1=MAX(GYMAXA,GYMAXB)     
      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
C      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,0.0,0.06)
      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.01,0.1,9)
C      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
C      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,2)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ----- Fig.3  Beam-Rot -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKY( IT+1,1)=GUCLIP(RAYB(25,IT))
            GKY( IT+1,2)=GUCLIP(RAYB(26,IT))
         ENDDO
      ENDDO
C
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
      CALL MOVE(13.5,16.1)
      CALL TEXT('Beam-rot',8)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,0.0,180.0)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,0.0,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,0.0,0.0,1)
      CALL GSCALE(0.0,0.0,0.0,30.0,0.1,9)
      CALL GVALUE(0.0,0.0,0.0,30.0,0)
      CALL SETRGB(0.0,0.0,1.0)
      CALL GPLOTP(GKX,GKY(1,1),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GKX,GKY(1,2),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ----- CALCULATE RADIAL DEPOSITION PROFILE -----
C
      DRHO=1.D0/NRZMAX
      DO NRZ=1,NRZMAX
         GPX(NRZ)=GUCLIP(NRZ*DRHO)
      ENDDO
      DO NRAY=1,NRAYMX
         DO NRZ=1,NRZMAX
            GPY(NRZ,NRAY)=0.0
         ENDDO
      ENDDO
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)-1
            XL=RAYS(1,IT,NRAY)
            YL=RAYS(2,IT,NRAY)
            ZL=RAYS(3,IT,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN1)
            RHO1=SQRT(PSIN1)
	    NRS1=INT(RHO1/DRHO)+1
            XL=RAYS(1,IT+1,NRAY)
            YL=RAYS(2,IT+1,NRAY)
            ZL=RAYS(3,IT+1,NRAY)
            CALL PLMAG(XL,YL,ZL,PSIN2)
            RHO2=SQRT(PSIN2)
            NRS2=INT(RHO2/DRHO)+1
            NDR=ABS(NRS2-NRS1)
            IF(NDR.EQ.0) THEN
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)+GUCLIP(RAYS(8,IT+1,NRAY))
            ELSE IF(NRS1.LT.NRS2) THEN
               SDR=(RHO2-RHO1)/DRHO
               DELP=RAYS(8,IT+1,NRAY)/SDR
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)
     &                       +GUCLIP((DBLE(NRS1)-RHO1/DRHO)*DELP)
               DO NR=NRS1+1,NRS2-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELP)
               ENDDO
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY)
     &                       +GUCLIP((RHO2/DRHO-DBLE(NRS2-1))*DELP)
            ELSE
               SDR=(RHO1-RHO2)/DRHO
               DELP=RAYS(8,IT+1,NRAY)/SDR
               GPY(NRS2,NRAY)=GPY(NRS2,NRAY)
     &                       +GUCLIP((DBLE(NRS2)-RHO2/DRHO)*DELP)
               DO NR=NRS2+1,NRS1-1
                  GPY(NR,NRAY)=GPY(NR,NRAY)+GUCLIP(DELP)
               ENDDO
               GPY(NRS1,NRAY)=GPY(NRS1,NRAY)
     &                       +GUCLIP((RHO1/DRHO-DBLE(NRS1-1))*DELP)
            ENDIF
         ENDDO
C         WRITE(6,'(5(I3,1PE12.4))') (NRZ,GPY(NRZ,NRAY),NRZ=1,NRZMAX)
      ENDDO
C
      DO NRAY=1,NRAYMX
      DO NRZ=1,NRZMAX
         GPY(NRZ,NRAY)=GPY(NRZ,NRAY)
     &                 /GUCLIP(2*PI*(DBLE(NRZ)-0.5D0)*DRHO*DRHO)
      ENDDO
C         WRITE(6,'(5(I3,1PE12.4))') (NRZ,GPY(NRZ,NRAY),NRZ=1,NRZMAX)
      ENDDO
c
c     ----- draw deposition profile -----
c
      CALL GQSCAL(0.0,1.0,GXMIN,GXMAX,GXSTEP)
c
      CALL GMNMX2(GPY,NITM+1,1,NRZMAX,1,1,NRAYMX,1,GYMIN,GYMAX)
      CALL GQSCAL(GYMIN,GYMAX,GYSMIN,GYSMAX1,GYSCAL1)
      GYSMIN=0.0
      GYSMAX2=0.1 
      GYSCAL2=2.E-2
      GYSMAX=MAX(GYSMAX1,GYSMAX2)
      GYSCAL=MAX(GYSCAL1,GYSCAL2)
C
      CALL MOVE(13.5,8.1)
      CALL TEXT('ABS POWER',10)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,GYSMIN,GYSMAX)
      CALL SETRGB(0.0,0.0,0.0)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYSMIN,GYSCAL,0.1,9)      
      CALL GVALUE(0.0,2*GXSTEP,GYSMIN,GYSCAL,2)
      CALL SETLIN(0,0,4)
      CALL SETRGB(1.0,0.0,0.0)
      CALL GPLOTP(GPX,GPY(1,1),1,NRZMAX,1,0,0,0)
      CALL SETRGB(0.0,0.0,0.0)
C
      CALL WRGPRM
      CALL PAGEE
      RETURN
      END
C
C
C
C
C
C
C
C
C     ***** ANGLE AND WS(I,J) *****
C
      SUBROUTINE WRGRFE
C
      INCLUDE 'wrcomm.h'
C
      PARAMETER(NSUM=201)
C
      DIMENSION RSU(NSUM),ZSU(NSUM)
      DIMENSION GRS(NSUM),GZS(NSUM)
      DIMENSION GX(NITM+1),GY(NITM+1)
      DIMENSION GUX(NITM+1),GUY(NITM+1)
      DIMENSION GPX(NITM+1),GPY(NITM+1,NRAYM)
      DIMENSION GKX(NITM+1,1),GKY(NITM+1,2)
      DIMENSION GKSY(NITM+1,6),GKPY(NITM+1,6)
      DIMENSION GTHY(NITM+1,1)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C     ----- X AXIS -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
C            XL=RAYS(1,IT,NRAY)
C            YL=RAYS(2,IT,NRAY)
C            ZL=RAYS(3,IT,NRAY)
C            CALL PLMAG(XL,YL,ZL,PSIN)
C            RHO=SQRT(PSIN)
            GKX( IT+1,NRAY)=GUCLIP(RAYB(0,IT))
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKX,1,NITMAX(1),1,GXMIN1,GXMAX1)
      CALL GQSCAL(GKMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP) 
C
C     ----- Fig.1  WS-----
C
      DO NRAY=1,NRAYMX         
         DO IT=0,NITMAX(NRAY)
            DO N=1,6
            GKSY(IT+1,N)=GUCLIP(RAYB(25+N,IT))
            ENDDO
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKSY(1,1),1,NITMAX(1),1,GYMIN1,GYMAX1)
C
      DO N=2,6
       CALL GMNMX1(GKSY(1,N),1,NITMAX(1),1,GYMIN,GYMAX)
       GYMIN1=MIN(GYMIN1,GYMIN)
       GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
C
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(1.7,16.1)
      CALL TEXT('X-WS',6)
C      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-40.0,40.0)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,GYMIN,GYMAX)
      CALL GFRAME
C      CALL GSCALE(0.0,GXSTEP,0.0,5.0,0.1,9)
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
      CALL SETRGB(0.0,0.0,1.0)
C
      DO N=1,6
      CALL GPLOTP(GKX,GKSY(1,N),1,NITMAX(1)+1,1,0,0,0)
      CALL SETLIN(0,0,N)
      ENDDO
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C    
C     
C     
C      
C
C
C     ------Fig2  WP-------
C   
C    
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            DO N=1,6
            GKPY( IT+1,N)=GUCLIP(RAYB(31+N,IT))
            ENDDO
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKPY(1,1),1,NITMAX(1),1,GYMIN1,GYMAX1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
      DO N=2,6
       CALL GMNMX1(GKPY(1,N),1,NITMAX(1),1,GYMIN,GYMAX)
       GYMIN1=MIN(GYMIN1,GYMIN)
       GYMAX1=MAX(GYMAX1,GYMAX)
      ENDDO
C
      CALL MOVE(1.7,8.1)
      CALL TEXT('X-WP',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C      
      DO N=1,6
      CALL GPLOTP(GKX,GKPY(1,N),1,NITMAX(1)+1,1,0,0,0)
      CALL SETLIN(0,0,N)
      ENDDO
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ----- Fig.3   Angle-----
C
      DO NRAY=1,NRAYMX         
         DO IT=0,NITMAX(NRAY)
            GTHY( IT+1,1)=GUCLIP(RAYB(25,IT))
         ENDDO
      ENDDO
C
C      CALL GMNMX1(GTHY(1,1),1,NITMAX(1),1,GYMIN1,GYMAX1)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C      CALL GQSCAL (GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL MOVE(13.5,16.1)
      CALL TEXT('Angle',6)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,-40.0,40.0)
C      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,GYMIN1,GYMAX1)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,0.0,5.0,0.1,9)
C      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
C      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
       CALL GVALUE(0.0,2*GXSTEP,0.0,10.0,1)
      CALL SETRGB(0.0,0.0,1.0)
C
      CALL GPLOTP(GKX,GTHY(1,1),1,NITMAX(1)+1,1,0,0,0)
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C    
C     
C     
C      
C
C
C
C     -------fig4  LAMDA------------------------
C
            DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKY( IT+1,1)=GUCLIP(RAYB(47,IT))
            GKY( IT+1,2)=GUCLIP(RAYB(48,IT))
C           WRITE(6,*) GKY(IT+1,5),RAYB(30,IT)
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
      CALL GMNMX1(GKY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C
      GYMIN1=MIN(GYMINA,GYMINB)
      GYMAX1=MAX(GYMAXA,GYMAXB)
      CALL MOVE(13.5,8.1)
      CALL TEXT('LAMDA',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,GYMIN,GYMAX)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C      
      CALL GPLOTP(GKX,GKY(1,1),1,NITMAX(1)+1,1,0,0,0)
      CALL GPLOTP(GKX,GKY(1,2),1,NITMAX(1)+1,1,0,0,0)
      CALL SETLIN(0,0,7)
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
      CALL WRGPRM
      CALL PAGEE
      RETURN
      END

C     ***** K,(K*B),K*(K*B),VG *****
C
      SUBROUTINE WRGRFF
C
      INCLUDE 'wrcomm.h'
C
      PARAMETER(NSUM=201)
C
      DIMENSION GX(NITM+1),GY(NITM+1)
      DIMENSION GUX(NITM+1),GUY(NITM+1)
      DIMENSION GPX(NITM+1),GPY(NITM+1,NRAYM)
      DIMENSION GKX(NITM+1,1)
      DIMENSION GKY(NITM+1,3),GKBY(NITM+1,3),GKKBY(NITM+1,3)
      DIMENSION GVGY(NITM+1,3)
C
      CALL PAGES
      CALL SETCHS(0.2,0.)
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C     ----- X AXIS -----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKX( IT+1,NRAY)=GUCLIP(RAYB(0,IT))
         ENDDO
      ENDDO
C
      CALL GMNMX1(GKX,1,NITMAX(1),1,GXMIN1,GXMAX1)
      CALL GQSCAL(GKMIN1,GXMAX1,GXMIN,GXMAX,GXSTEP) 
C
C     ------fig 1  K----------
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKY( IT+1,1)=GUCLIP(RAYB(38,IT))
            GKY( IT+1,2)=GUCLIP(RAYB(39,IT))
            GKY( IT+1,3)=GUCLIP(RAYB(40,IT))
         ENDDO
      ENDDO
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C      CALL GMNMX1(GKY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
C      CALL GMNMX1(GKY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C      CALL GMNMX1(GKY(1,3),1,NITMAX(1),1,GYMINC,GYMAXC)
C
C      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
C      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(1.7,16.1)
      CALL TEXT('K',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,9.0,16.0,0.0,GXMAX,-1.2,1.2)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C
      DO N=1,3
        CALL GPLOTP(GKX,GKY(1,N),1,NITMAX(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ------fig 2 K*B---------
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKBY( IT+1,1)=GUCLIP(RAYB(41,IT))
            GKBY( IT+1,2)=GUCLIP(RAYB(42,IT))
            GKBY( IT+1,3)=GUCLIP(RAYB(43,IT))
         ENDDO
      ENDDO
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C      CALL GMNMX1(GKBY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
C      CALL GMNMX1(GKBY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C      CALL GMNMX1(GKBY(1,3),1,NITMAX(1),1,GYMINC,GYMAXC)
C
C      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
C      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(1.7,8.1)
      CALL TEXT('K*B',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-1.2,1.2)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C
      DO N=1,3
        CALL GPLOTP(GKX,GKBY(1,N),1,NITMAX(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ------fig 3 K*(K*B)-----
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GKKBY( IT+1,1)=GUCLIP(RAYB(44,IT))
            GKKBY( IT+1,2)=GUCLIP(RAYB(45,IT))
            GKKBY( IT+1,3)=GUCLIP(RAYB(46,IT))
         ENDDO
      ENDDO
C
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C
C      CALL GMNMX1(GKKBY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
C      CALL GMNMX1(GKKBY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C      CALL GMNMX1(GKKBY(1,3),1,NITMAX(1),1,GYMINC,GYMAXC)
C
C      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
C      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(13.5,16.1)
      CALL TEXT('K*(K*B)',6)
      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(13.5,23.5,9.0,16.0,0.0,GXMAX,-1.2,1.2)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C
      DO N=1,3
        CALL GPLOTP(GKX,GKKBY(1,N),1,NITMAX(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
C
C     ------fig 4 VG ---------
C
      DO NRAY=1,NRAYMX
         DO IT=0,NITMAX(NRAY)
            GVGY( IT+1,1)=GUCLIP(RAYB(49,IT))
            GVGY( IT+1,2)=GUCLIP(RAYB(50,IT))
            GVGY( IT+1,3)=GUCLIP(RAYB(51,IT))
         ENDDO
      ENDDO
C
      CALL SETRGB(0.0,0.0,0.0)
      CALL SETLNW(0.035)
C      CALL GMNMX1(GVGY(1,1),1,NITMAX(1),1,GYMINA,GYMAXA)
C      CALL GMNMX1(GVGY(1,2),1,NITMAX(1),1,GYMINB,GYMAXB)
C      CALL GMNMX1(GVGY(1,3),1,NITMAX(1),1,GYMINC,GYMAXC)
C
C      GYMIN1=MIN(GYMINA,GYMINB,GYMINC)
C      GYMAX1=MAX(GYMAXA,GYMAXB,GYMAXC)
      CALL MOVE(13.5,8.1)
      CALL TEXT('VG',6)
C      CALL GQSCAL(GYMIN1,GYMAX1,GYMIN,GYMAX,GYSTEP)
      CALL GDEFIN(13.5,23.5,1.0,8.0,0.0,GXMAX,-1.2,1.2)
C       CALL GDEFIN(1.7,11.7,1.0,8.0,0.0,GXMAX,-50.0,50.0)
C      CALL SETLIN(0,0,7)
      CALL GFRAME
      CALL GSCALE(0.0,GXSTEP,GYMIN,GYSTEP,0.1,9)
      CALL GVALUE(0.0,2*GXSTEP,GYMIN,GYSTEP,1)
C      CALL GVALUE(0.0,0.0,0.0,0.01,2)
      CALL SETRGB(0.0,0.0,1.0)
C
      DO N=1,3
        CALL GPLOTP(GKX,GVGY(1,N),1,NITMAX(1)+1,1,0,0,0)      
        CALL SETLIN(0,0,N+2)
      ENDDO  
C
      CALL SETRGB(1.0,0.0,0.0)
      CALL SETRGB(0.0,0.0,0.0)
      CALL WRGPRM
      CALL PAGEE 
      RETURN
      END

C     ***** DRAW PARAMETERS *****
C
      SUBROUTINE WRGPRM
C
      INCLUDE 'wrcomm.h'
C
C     ----- DRAW PARAMETERS -----
C
      CALL SETLIN(0,0,7)
      CALL WRPRMT(1.0,18.0, 'BB   =',6, BB  ,'(F8.3)',8)
      CALL WRPRMT(1.0,17.6, 'RR   =',6, RR  ,'(F8.3)',8)
      CALL WRPRMT(1.0,17.2, 'RA   =',6, RA  ,'(F8.3)',8)
      CALL WRPRMT(1.0,16.8, 'RKAP =',6, RKAP,'(F8.3)',8)
      CALL WRPRMT(5.0,18.0, 'Q0   =',6, Q0  ,'(F8.3)',8)
      CALL WRPRMT(5.0,17.6, 'QA   =',6, QA  ,'(F8.3)',8)
      CALL WRPRMT(5.0,17.2, 'RF =',  4, RF  ,'(1PE10.3)',10)
      CALL WRPRMT(5.0,16.8, 'NPHII=',6,RNPHII,'(F8.4)',8)
      CALL WRPRMT(9.0,18.0, 'PA(1)  =',8,PA(1),'(F8.4)',8)
      CALL WRPRMT(9.0,17.6, 'PZ(1)  =',8,PZ(1),'(F8.4)',8)
      CALL WRPRMT(9.0,17.2, 'PN(1)  =',8,PN(1),'(F8.4)',8)
      CALL WRPRMT(9.0,16.8, 'PNS(1) =',8,PNS(1),'(F8.4)',8)
      CALL WRPRMT(13.0,18.0,'PTPR(1)=',8,PTPR(1),'(F8.4)',8)
      CALL WRPRMT(13.0,17.6,'PTPP(1)=',8,PTPP(1),'(F8.4)',8)
      CALL WRPRMT(13.0,17.2,'PTS(1) =',8,PTS(1),'(F8.4)',8)
      CALL WRPRMT(13.0,16.8,'MODELP1=',8,DBLE(MODELP(1)),'(F4.0)',4)
      CALL WRPRMT(17.0,18.0,'PA(2)  =',8,PA(2),'(F8.4)',8)
      CALL WRPRMT(17.0,17.6,'PZ(2)  =',8,PZ(2),'(F8.4)',8)
      CALL WRPRMT(17.0,17.2,'PN(2)  =',8,PN(2),'(F8.4)',8)
      CALL WRPRMT(17.0,16.8,'PNS(2)= ',8,PNS(2),'(F8.4)',8)
      CALL WRPRMT(21.0,18.0,'PTPR(2)=',8,PTPR(2),'(F8.4)',8)
      CALL WRPRMT(21.0,17.6,'PTPP(2)=',8,PTPP(2),'(F8.4)',8)
      CALL WRPRMT(21.0,17.2,'PTS(2) =',8,PTS(2),'(F8.4)',8)
      CALL WRPRMT(21.0,16.8,'MODELP2=',8,DBLE(MODELP(2)),'(F4.0)',4)
      CALL PAGEE
      RETURN
      END
C
C***********************************************************************
C
      SUBROUTINE WRPRMT(X,Y,KTEXT,ITEXT,D,KFORM,IFORM)
C
      CHARACTER*(*) KTEXT,KFORM
      REAL*8 D
C
      CALL MOVE(X,Y)
      CALL TEXT(KTEXT,ITEXT)
      CALL NUMBD(D,KFORM,IFORM)
      RETURN
      END            
