C     $Id$
C
      module libchar_mod
      public
      contains
C
C     ***** FIND CHARACTER POSITION *****
C
      FUNCTION KKINDEX(KKLINEX,KID)
C
      PARAMETER(KSLEN=80)
      INTEGER KKINDEX
      CHARACTER KKLINEX*(*),KKLINE*80
      CHARACTER KID*1
C
      KKLINE=KKLINEX
      DO I=1,KSLEN
         IF(KKLINE(I:I).EQ.KID) GOTO 100
      ENDDO
      KKINDEX=0
      RETURN
C
  100 KKINDEX=I
      RETURN
      END FUNCTION KKINDEX
C
C     ***** SEPARATE STRING AT CHAR *****
C
      SUBROUTINE KSPLIT(KKLINEX,KID,KKLINE1,KKLINE2)
C
      PARAMETER(KSLEN=80)
      CHARACTER KKLINEX*(*),KKLINE*80
      CHARACTER KKLINE1*80,KKLINE2*80
      CHARACTER KID*1
C
      KKLINE=KKLINEX
      DO I=1,KSLEN
         IF(KKLINE(I:I).EQ.KID) GOTO 100
      ENDDO
      KKLINE1=KKLINE
      KKLINE2=' '
      GOTO 9000
C
  100 IF(I.EQ.1) THEN
         KKLINE1=' '
      ELSE
         KKLINE1=KKLINE(1:I-1)
      ENDIF
      KKLINE2=KKLINE(I+1:)
c
 9000 RETURN
      END SUBROUTINE KSPLIT
C
C     ***** TRIM STRING AND RETURN LENGTH *****
C
      SUBROUTINE KTRIM(KKLINEX,KL)
C
      PARAMETER(KSLEN=80)
      CHARACTER KKLINEX*(*),KKLINE*80
      CHARACTER KKLINE1*80
C
      KKLINE=KKLINEX
      DO I=1,KSLEN
         IF(KKLINE(I:I).NE.' ') GOTO 100
      ENDDO
  100 ITOP=I
C
      DO I=KSLEN,1,-1
         IF(KKLINE(I:I).NE.' ') GOTO 200
      ENDDO
  200 IBOTTOM=I
C
      IF(ITOP.GT.KSLEN) THEN
         KKLINE=' '
         KL=0
      ELSE IF(IBOTTOM.LT.1) THEN
         KKLINE=' '
         KL=0
      ELSE
         KKLINE1=KKLINE(ITOP:IBOTTOM)
         KKLINE=KKLINE1
         KL=IBOTTOM-ITOP+1
      ENDIF
      KKLINEX=KKLINE
      RETURN
      END SUBROUTINE KTRIM
C
C     ***** EXTRACT STRING FROM KSTRING *****
C
      SUBROUTINE KEXTR(KKLINEX)
C
      CHARACTER KKLINEX*(*),KKLINE*80
      CHARACTER KID*1
C
      KKLINE=KKLINEX
      KID=KKLINE(1:1)
      INCL=KKINDEX(KKLINE(2:),KID)
      IF(INCL.LE.1) THEN
         KKLINEX=KKLINE(2:)
      ELSE
         KKLINEX=KKLINE(2:INCL)
      ENDIF
      RETURN
      END SUBROUTINE KEXTR
C
C     ***** RETURN TRUE WHEN STRINGS MATCH *****
C
      LOGICAL FUNCTION KMATCH(KKLINE1X,KKLINE2X)
C
      PARAMETER(KSLEN=80)
      CHARACTER KKLINE1X*(*),KKLINE1*80
      CHARACTER KKLINE2X*(*),KKLINE2*80
C
      KKLINE1=KKLINE1X
      KKLINE2=KKLINE2X
      DO I=1,KSLEN
         IF(KKLINE1(I:I).NE.KKLINE2(I:I)) GO TO 100
      ENDDO
      KMATCH=.TRUE.
      RETURN
C
  100 KMATCH=.FALSE.
      RETURN
      END FUNCTION KMATCH
C
C     ***** CAPITALIZE *****
C
      SUBROUTINE GUCPTL(KID)
C
      CHARACTER KID*1
C
      ID=ICHAR(KID)
      IF(ID.GE.97.AND.ID.LE.122) THEN
         KID=CHAR(ID-32)
      ENDIF
      RETURN
      END SUBROUTINE GUCPTL
c
      end module libchar_mod
